### ISSUE TITLE
Restructure HTML Area tools config

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1007]
Current input config of HTML Area supports 2 fields (`include` and `exclude`) for enabling/disabling tools in the toolbar.
```XML
<config>
  <exclude>*</exclude>
  <include>AlignLeft AlignRight | Bold Italic</include>
</config>
```

Since we're going to use input config for [other settings](https://github.com/enonic/app-contentstudio/issues/985), we need to restructure these two fields like this:
```XML
<config>
  <tools>
    <disable>*</disable>
    <enable>AlignLeft AlignRight | Bold Italic</enable>
  </tools>
</config>
```

To avoid breaking things, support the two old fields until we release 3.0. Add deprecation note to [description of the fields](https://developer.enonic.com/docs/xp/stable/cms/input-types#htmlarea).

**Comment by alansemenov** [comment]
Seems like it's not possible to have more than one level depth in the input type config... :(
Alternative is to rename the two fields, but it's not really worth the change. Keeping it as it is for now.

**Comment by sigdestad** [comment]
Also, v3.0 of what??
