### ISSUE TITLE
Duplicate dialog -  Duplicate button is missing a number of items to duplicate

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1015]
1. Select several folders in the grid(in root) and click on Duplicate: 

![image](https://user-images.githubusercontent.com/3728712/65495082-c6161800-debe-11e9-8693-84af92c2ff0e.png)

2. Select a site (click on the checkbox)

![image](https://user-images.githubusercontent.com/3728712/65495131-de863280-debe-11e9-8f93-07c0430515e1.png)

BUG: Duplicate button does not contains a number of content to delete.

**Comment by sigdestad** [comment]
Assume you mean duplicate, not delete? ;)

**Comment by sgauruseu** [comment]
@sigdestad I updated this header immediately after the creating )
