### ISSUE TITLE
Implement support of custom part icons

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1029]
Implement support of part icons, similar to how we support icons for content types. Icons must be placed in the part folder and have the same name as the part. Supported formats: PNG and SVG.

In UI the part icon will be shown in Page Components view and inside the part descriptor dropdown. If there's not icon for the part, current standard icon (puzzle piece) will be used.

**Comment by pmi** [comment]
PRs:
lib-admin-ui: https://github.com/enonic/lib-admin-ui/pull/1110
content-studio: https://github.com/enonic/app-contentstudio/pull/1060
xp: https://github.com/enonic/xp/pull/7496
