### ISSUE TITLE
Image Wizard - Save button gets enabled after version rollback

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1040]
1. Upload the attached image.
2. Open the image in wizard.
3. Go to `Photo` step and select a date , save the content and close the wizard.
4. Reopen the image again , open Versions and rollback the previous version.

BUG:  Save button gets enabled after version rollback: 

![image](https://user-images.githubusercontent.com/3728712/65757795-85b5d480-e120-11e9-87d8-d7af8ff8c6b2.png)

**Comment by sgauruseu** [comment]
[nord.zip](https://github.com/enonic/app-contentstudio/files/3661954/nord.zip)

**Comment by vbradnitski** [comment]
can't reproduced, looks like was fixed by new rollback mechanism (creating new version for each rollback)
