### ISSUE TITLE
Component View - options are not shown after correct text has been typed in the filter options input 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1044]
1. Open Features site.
2. Open Page Component view and insert the layout component.
3. Type `3-col` text 

Actual: `No layouts available` this message appears

![image](https://user-images.githubusercontent.com/3728712/65768455-aa6a7600-e139-11e9-8562-ba0e36d19c9e.png)

But searching gets workable after  you clear the input and type the text again: 

![image](https://user-images.githubusercontent.com/3728712/65768490-c53cea80-e139-11e9-8d9f-ff0c5ba855a8.png)

**Comment by pmi** [comment]
Issue moved to [enonic/lib-admin-ui #1107](https://github.com/enonic/lib-admin-ui/issues/1107) via [**ZenHub**](https://www.zenhub.com/)
