### ISSUE TITLE
Content Wizard - Unsaved changes should be reverted after content is marked as deleted

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1066]
1. Open a content and publish it.
2. Update the content- select a language for example (Do not press the Save button)
3. Press `Delete` button, open Delete Content Dialog then click on  (Delete or Mark as Deleted).
4. The content gets `Marked for deletion`.
5. Try to close the browser tab with the folder.
**BUG**: 
       **1)** This content has unsaved changes - clicking on `close-tab` icon opens  alert with warning
         **2)**  Incorrect status(PUBLISHED) is displayed in Details Panel  .

![image](https://user-images.githubusercontent.com/3728712/66194558-63323700-e69d-11e9-80b7-00d0068718a3.png)

       

**Expected**: 
   - Unsaved changes should be reverted
  -  Marked for deletion status should be in Deatials Panel

**Comment by alansemenov** [comment]
No longer relevant since we're dropping pending delete
