### ISSUE TITLE
Inputs in Content Wizard should be disabled if content is pending deletion

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1067]
1. Open a published folder.
2. Click on Delete button and do Deleted this content .

**Issue** - content is `Deleted` now, `Save` button is not visible on the toolbar , so 
 Language, Schedule, Owner, Versions  should be disabled  as well:  

![image](https://user-images.githubusercontent.com/3728712/66195094-90331980-e69e-11e9-9bc8-88a48ca2f66d.png)

**Comment by alansemenov** [comment]
We should reuse [this method ](https://github.com/enonic/app-contentstudio/blob/efbd75b018c31c15d40c243640f7fc51ee2c8cd8/src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts#L2210) which applies certain styling to the Wizard Panel and Page Editor when user doesn't have Modify permissions. Should of course be refactored.

**Comment by alansemenov** [comment]
We no longer support pending delete
