### ISSUE TITLE
Comparison of content versions

### ISSUE THREAD

**Issue by pmi** [enonic/app-contentstudio#1110]

**Comment by pmi** [comment]
**Here is the draft of how version diff might look like:**

Clicking compare will open compare dialog with comparison of this version against the latest
![version list](https://user-images.githubusercontent.com/754221/67003532-d3ea4200-f0e6-11e9-8c0b-0db636d94837.png)

Here user can select versions he wants to compare against (by default there will be latest and the one whose compare button was clicked)
![diff dialog](https://user-images.githubusercontent.com/754221/67003543-d9e02300-f0e6-11e9-8b9b-816fea6f7861.png)

**Comment by sigdestad** [comment]
This is a nice, start. But we will need more details on the compare design especiallty. I.e.
* What is actually listed in the dropdown (should be based on history view content, maybe use standard exp Two lines XP design for lists?
* If this is a modal, does it maximize both height and width?
* What about "mobile"?
* Also, detail panel appears to have been resized. What does it look like without resizing (i.e. mobile size)

**Comment by pmi** [comment]
- All available versions are listed in both dropdowns
- Yes it's modal. I was thinking about 90% width/height
- Eh, good question :) Probably a full-screen patch variant comparison (everything on one pane) ? But that will require usage of the other library in addition to jsondiff
- Here what it looks like on mobile
![version-list](https://user-images.githubusercontent.com/754221/67371430-0c759a00-f585-11e9-89dc-213c1180415e.jpg)

**Comment by sigdestad** [comment]
Ok. I think the other diff library might be more relevant, as it will work on both views..

**Comment by sigdestad** [comment]
Also, missing a New design suggestion for the droodowns in views.

Think we should use 100% height like in editor fullscreen now

**Comment by pmi** [comment]
Yes, agree about using [jsondiffpatch](https://benjamine.github.io/jsondiffpatch/demo/index.html) in both mobile and desktop variants.

Yes, we can use a 2 line list item, to show modified time for instance in addition to version number
