### ISSUE TITLE
Incorrect layout inside Schedule form under mobile resolution

### ISSUE THREAD

**Issue by Slideshow776** [enonic/app-contentstudio#1119]
Elements are incorrectly wrapped when the editor pane is small.

![image](https://user-images.githubusercontent.com/4059636/67270580-3bbed500-f4b9-11e9-8610-b13b33aaaa02.png)

**Comment by ashklianko** [comment]
Checked locally in Chrome and FF, checked on BrowserStack with Chrome, FF and Safari - works fine.
@alansemenov do you have it reproduced?
