### ISSUE TITLE
Bold/Italic/Underline styling stopped working in the HTML Area

### ISSUE THREAD

**Issue by vot-enonic** [enonic/app-contentstudio#1123]
Until today I was able to copy and paste text from Google Docs into the text editor in Content Studio, with style formatting like italics and bold intact. Now the text is pasted without e.g. <i> tags where they should be.

**Comment by vot-enonic** [comment]
Actually, I can't find options for bold or italics in the text editor menu.
![Capture](https://user-images.githubusercontent.com/43465080/67371400-a08f3380-f57c-11e9-8380-82c1cd231dd2.PNG)

**Comment by vot-enonic** [comment]
I can't even manually write <i> in the HTML code! @alansemenov

**Comment by mortyeriksen** [comment]
Why did we remove the italic and bold buttons?

**Comment by sigdestad** [comment]
Use the fullscreen mode to get all buttons (i hope). There was too little space left.. And most user know shortcuts for these action.
