### ISSUE TITLE
Changes in the Page Editor don't reset workflow status to "In Progress"

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1127]
1. Deploy Superhero. Make sure the site is in "Ready" status. If not - mark it as ready.
2. Open the site in editor
3. Drag a new part onto the page. Status/icon changes from "Ready" to "In progress" - correct.
4. Now select a controller ("FAQ List") for the new part. Content gets saved and status/icon changes back to "Ready"...
5. Open the Inspect panel, change something in the config and hit "Apply" button. Content gets saved and status/icon is still "Ready"...

**Comment by alansemenov** [comment]
Possible duplicate of https://github.com/enonic/app-contentstudio/issues/1052

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/issues/1052 now seems to work
