### ISSUE TITLE
Incorrect behaviour when updating boolean properties in content-types

### ISSUE THREAD

**Issue by abdavid** [enonic/app-contentstudio#1131]
Version: 2.2.2

After looking around in resolved issues/open issues to find out if some one reported something similar to what I am experiencing I came across #683 which is more or less the same issue as @alansemenov describes, thought the problem resides inside a content-type declaration and not site.xml.

I have been trying to eliminate the issue by removing input types from my schema and ended up with this

```
<?xml version="1.0" encoding="UTF-8"?>
<content-type>
    <display-name>Fordel</display-name>
    <super-type>base:structured</super-type>
    <form>
        <field-set>
            <label>Star</label>
            <items>
                <input type="CheckBox" name="starred">
                    <label>Starred</label>
                    <default>unchecked</default>
                </input>
            </items>
        </field-set>
    </form>
</content-type>
```

This alone when seems to work consistently (not really sure, if that is coincidental), but I have not been able to isolate the scenario that causes this, but I have managed to get some screen shots of the update request with its payload. 

**Toggling the checkbox and saving by cmd+s** 
![Skjermbilde 2019-10-29 kl  12 30 58](https://user-images.githubusercontent.com/1027468/67763556-455fb400-fa48-11e9-8629-5790895b81e2.png)

**Marking the content as ready to publish**
![Skjermbilde 2019-10-29 kl  12 31 16](https://user-images.githubusercontent.com/1027468/67763594-5e686500-fa48-11e9-9ed7-9fcbd3c08226.png)

in this step notice that the update payload explicitly states that the Boolean value is null - this is somewhat hard to reproduce. Then what happens is exactly like what #683 describes with the data property on the node. 

**After publishing said content**
![Skjermbilde 2019-10-29 kl  12 32 05](https://user-images.githubusercontent.com/1027468/67763652-7cce6080-fa48-11e9-9fe0-78ce162c9d3a.png)

Also here for some reason displayName suddenly disappears.

**Comment by alansemenov** [comment]
```
<input type="CheckBox" name="starred">
  <label>Starred</label>
  <default>unchecked</default>
</input>
```

A bit confused about why you are using _unchecked_ as default value? You shouldn't specify anything, then the checkbox will not be checked off by default.

**Comment by abdavid** [comment]
I believe you can ignorere that. From my tests it doesnt really matter. It shouldnt have been included at all, but how you map default values *could* have been a source of the problem, hence why I tested it. Because from where I stand «unchecked» should resolve to «false» while «checked» to «true», and when I see «null» values being posted that was a natural thing to check.

- David
