### ISSUE TITLE
Versions Widget - incorrect tooltip in version items

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1140]
1. Select 'New' folder  and open Versions Widget
2. Move cursor to any version

BUG: `Published` status is in the tooltip: 

![image](https://user-images.githubusercontent.com/3728712/67931464-ee3a1a80-fbd2-11e9-9654-b87dceb529ca.png)

**Comment by alansemenov** [comment]
Fixed, duplicate of https://github.com/enonic/app-contentstudio/issues/1306
