### ISSUE TITLE
Mobile resolutions - date time picker is not fully shown in Publishing Wizard

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1143]
1. Change browser window size to a mobile resolution.
2. Select a content in the grid or open a content in wizard.
3. Open Publish Wizard and  click on `Add schedule` button.

Issue: 

![image](https://user-images.githubusercontent.com/3728712/67943287-c9ea3800-fbea-11e9-962f-637eba303031.png)

**Comment by edloidas** [comment]
Issue moved to [enonic/lib-admin-ui #1150](https://github.com/enonic/lib-admin-ui/issues/1150) via [**ZenHub**](https://www.zenhub.com/)
