### ISSUE TITLE
Error after selecting an option in Image Selector

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1146]
1. Select Features, open new ImageSelector wizard.
2. Type a text in the search input

Issue: error appears in the page: 

![image](https://user-images.githubusercontent.com/3728712/68111304-de3a7780-feff-11e9-9467-92854c5f197a.png)

**Comment by alansemenov** [comment]
Complaint on the same issue on Discuss: https://discuss.enonic.com/t/combobox-error-in-cs-followup/2010/7

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1136](https://github.com/enonic/lib-admin-ui/issues/1136) via [**ZenHub**](https://www.zenhub.com/)
