### ISSUE TITLE
Site Wizard - application dropdown  gets expanded after saving the site via  Keyboard Shortcut (Ctrl+S)

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1147]
1. Open new site wizard , type a name.
2. Expand app-selector then select 2 applications, click on Apply button.
3 Press `Ctrl+S` (Cmd+S)
**Issue :  dropdown  gets expanded :**

![image](https://user-images.githubusercontent.com/3728712/68113423-da5d2400-ff04-11e9-959f-d875bf5f5162.png)

**Comment by alansemenov** [comment]
The focus is still on the selector's input after Apply closes the dropdown. So when cmd-S is saved, the selector reacts to it as typeahead and opens the dropdown.

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1161](https://github.com/enonic/lib-admin-ui/issues/1161) via [**ZenHub**](https://www.zenhub.com/)
