### ISSUE TITLE
Selected item loses selection after grid refresh

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1148]
If selected item in the grid is not loaded within the first batch of items (lazy loaded on scroll) then it will not restore selection if the grid is refreshed.

To reproduce:
1. Install Features app which will create "Large tree" folder in the root
2. Expand "Large tree", then "Large tree node 2"
3. Scroll down to item "Large tree node 2-80" and select it
4. Refresh the grid with icon in the toolbar

Scroll down to the same item again. Note that the row is not marked as selected.

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1141](https://github.com/enonic/lib-admin-ui/issues/1141) via [**ZenHub**](https://www.zenhub.com/)
