### ISSUE TITLE
Upload button disappears after version rollback of content with attachments  

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1149]
1. Select Features and open new Attachments content: 
![image](https://user-images.githubusercontent.com/3728712/68195125-5881ff00-ffc7-11e9-9975-3efba07d80d9.png)
 
2. Upload 2 files.
3. Open Versions history and revert the second version from the bottom: 

![image](https://user-images.githubusercontent.com/3728712/68195376-cfb79300-ffc7-11e9-8511-ab20461acde7.png)

**Issue:   Upload button in the Single attachment is not visible**

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/4bee154cc3ec26b7668398a6a32507bb27a18576
