### ISSUE TITLE
Site Wizard - controller selector does not appear after selecting an application in the saved site

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1151]
1. Open new site wizard,type a name.
2. Press `Save` button.
3. Select Features in app-selector.

**Expected**: page descriptor dropdown should appear after selecting the applications

**Actual** :  Application is selected but  "No page controller found" is displayed in Page Editor

![image](https://user-images.githubusercontent.com/3728712/68214836-3ef4ad80-ffef-11e9-94f1-7ba996cbf38f.png)

 **Page descriptor dropdown  appears after clicking on  button Save**

**Comment by alansemenov** [comment]
Note: it works as it should if the content is not saved before selecting the app.
