### ISSUE TITLE
Selection highlighter is misplaced in the Page Editor after content save

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1161]
1. Install Superhero app
2. Open the site for edit
3. Select some of the component on the side, for example "Recent comments"

![Screenshot 2019-11-08 at 15 43 04](https://user-images.githubusercontent.com/11612490/68484945-9d639b00-023e-11ea-9759-d0479ff09c0e.png)

4. Change something in the Wizard form
5. Save content
 
The page is refreshed after save and when selection is restored the highlighter is misplaced .

![Screenshot 2019-11-08 at 15 43 22](https://user-images.githubusercontent.com/11612490/68484947-9dfc3180-023e-11ea-9b09-dcdc16a3322e.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1157](https://github.com/enonic/lib-admin-ui/issues/1157) via [**ZenHub**](https://www.zenhub.com/)
