### ISSUE TITLE
Add validators and sanitizers for user data

### ISSUE THREAD

**Issue by edloidas** [enonic/app-contentstudio#1172]
Add validators and sanitizers for user data and data, that are rendered on the page to fix the XSS vulnerabilities.

**Comment by alansemenov** [comment]
See use cases [here](https://github.com/enonic/app-contentstudio/issues/1455)

**Comment by ashklianko** [comment]
Notes: 
1. Selectors that  send content queries (ContentSelectorRequest.ts) spawn error on backend when using quotation marks `"` and apostrophe together in search string
2. Content wizard header allows all chars in content display name except slash and backslash, however if you gonna use chars like `&<>[]` then searching contents by those chars in content selectors won't find them
Probably more things to come

**Comment by alansemenov** [comment]
Fixed in other epic tasks
