### ISSUE TITLE
Image Wizard is not refreshed on version revert after binary is updated

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1180]
1. Open an image or upload an image then open it.
2. Click on Upload button in the wizard and select new image.
3. Open versions widget in the wizard and revert the previous version.

Issue: image is not updated after revert the  version.

![image](https://user-images.githubusercontent.com/3728712/68746636-0dd93600-060a-11ea-9d83-ae3e4209c242.png)

**Comment by alansemenov** [comment]
It's not just the binary that is not updated after version revert. If you for example change content name, then upload a new binary and then rollback the version, the name won't be updated either. 

Also, when trying to refresh the page there's a popup about unsaved changes. After refresh everything is correct, but it has to be correct after the rollback without having to refresh.
