### ISSUE TITLE
Error appears in Inspect Panel after applying changes in Site Configurator.

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1198]
1. Open new site-wizard, type a name and select Features.
2.  Select `main region` in controller-selector
3. Open Page Components View and insert image-component.
4. Go to Inspection Panel, type `spum` in the filter input, then select the filtered image.
5. Click on edit-icon and open Site Configurator dialog . Click on Red option.

**Issue: browser hangs for 10-15 seconds, then error appears in Inspect Panel**

![image](https://user-images.githubusercontent.com/3728712/68939929-e7a2ca00-07b2-11ea-8783-c1993eaa04f0.png)

The similar issue was opened recently:
https://github.com/enonic/app-contentstudio/issues/1176

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1154](https://github.com/enonic/lib-admin-ui/issues/1154) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1153](https://github.com/enonic/lib-admin-ui/issues/1153) via [**ZenHub**](https://www.zenhub.com/)
