### ISSUE TITLE
Incorrect layout in Edit Permissions dialog under mobile resolution

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1219]
Resolution - 2312 × 1080 px
Open a content, click on Edit Permissions button.

Issue : Checkbox gets checked after clicking on Apply button
![image](https://user-images.githubusercontent.com/3728712/69243839-e4de1580-0bb4-11ea-9435-4254d50700fb.png)

Landscape resolution :    Apply button and checkbox are not available

![image](https://user-images.githubusercontent.com/3728712/69243929-122ac380-0bb5-11ea-968e-01b8c0d044f2.png)

**Comment by alansemenov** [comment]
The checkbox should be over the buttons in this resolution
