### ISSUE TITLE
Translate missing language phrases to Portuguese

### ISSUE THREAD

**Issue by jsi** [enonic/app-contentstudio#1241]
The following keys are missing in 'phrases_pt.properties': 
 - action.newTask
 - dialog.compareVersions.comparingVersions
 - dialog.compareVersions.current
 - dialog.compareVersions.newerVersion
 - dialog.compareVersions.olderVersion
 - dialog.compareVersions.showUnchanged
 - dialog.compareVersions.versionsIdentical
 - dialog.delete.markDeleted
 - dialog.deleteNow
 - dialog.issue.filter.label
 - dialog.table.formitem.caption
 - field.createdByMe
 - field.hideComponent
 - field.tasks
 - field.version.compare
 - notify.revert.noChanges
 - tooltip.editor.pastemode.formatted
 - tooltip.editor.pastemode.plain
 - tooltip.widget.versions.compareWithCurrentVersion

**Comment by williamsrb** [comment]
```
action.newTask=Nova Tarefa
dialog.compareVersions.comparingVersions=Comparando versões de {0}
dialog.compareVersions.current=Versão atual
dialog.compareVersions.newerVersion=Versão Nova
dialog.compareVersions.olderVersion=Versão Antiga
dialog.compareVersions.showUnchanged=Mostrar conteudo inteiro
dialog.compareVersions.versionsIdentical=Versões são idênticas
dialog.delete.markDeleted=Marcar Como Excluído
dialog.deleteNow=Excluir Agora
dialog.issue.filter.label=Filtro
dialog.table.formitem.caption=Legenda
field.createdByMe=Criado por Mim
field.hideComponent=Esconder a Exibição de Componente
field.tasks=Tarefas
field.version.compare=Comparar
notify.revert.noChanges=Sem mudanças para reverter.
tooltip.editor.pastemode.formatted=Modo de colagem: texto formatado
tooltip.editor.pastemode.plain=Modo de colagem: texto plano
tooltip.widget.versions.compareWithCurrentVersion=Comparar com versão atual
```

**Comment by jsi** [comment]
Hi Williams!

Thank you so much for the work.  We do really appreciate your help!

Not sure how much you have looked into the whole set of phrases, but when I inserted your translations into the code, I noticed this:
```
field.issues=Tarefas
field.tasks=Tarefas
```
In English, these phrases are:
```
field.issues=Issues
field.tasks=Tasks
```

The difference is: "Tasks" are specific things to do.  "Issues" are more like problems to solve.  Do you have such a distinction in Portuguese?  I do notice that "Tarefa" have been used for both "issue" and "task" in previous translations as well, so this may very well be the best solution in Portuguese, but there is a distinction in English that would be good to have in the translation if possible.

Can you please verify this?

**Comment by williamsrb** [comment]
Hi Jørgen!
In Portuguese we have male and female words, and we use different definite
article <https://www.grammar-monster.com/glossary/definite_article.htm> vowels
before the nouns.
In English we use THE, and it's all good.
Since the related enonic translation keys use the article on the main
phrase and not on the noun, I was forced to choose a female word for the
translation.

We can safely use "Problemas" instead of "Tarefas", for plural.
And "Problema" instead of "Tarefa", for singular.

Em seg., 20 de jan. de 2020 às 09:31, Jørgen Sivesind <
notifications@github.com> escreveu:

**Comment by jsi** [comment]
Oh, so Tarefas is the only female word that can be used?  -  I see.

I will report this to the devs and see if they can do anything about it.  Thanks for the clarification, and again:  Thank you so much for helping out!
