### ISSUE TITLE
Comment fails to get deleted in the Task Details dialog

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1272]
1. Open a task (with a comment).
2, Go to comments tab, open the menu and click on Delete menu item:

![image](https://user-images.githubusercontent.com/3728712/70040231-3b434f00-15cc-11ea-923c-7c1905f8ade1.png)

3. Click on Yes button in the confirmation dialog.

Bug: confirmation dialog. is closed but the comment is not deleted

**Comment by pmi** [comment]
Issue moved to [enonic/lib-admin-ui #1166](https://github.com/enonic/lib-admin-ui/issues/1166) via [**ZenHub**](https://www.zenhub.com/)
