### ISSUE TITLE
Image Fragment Wizard - confirmation about unsaved changes appears but nothing was changed

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#128]
This issue reproduced in XP 6.15 as well
1.  Open a site , insert an image and save it as fragment (do close the wizard with fragment)
2. Go to grid and open the fragment in wizard.
3. Open Page Component View and click on the image 
4. Click on `close-browser` icon
Bug:

Confirmation appears, but the fragment was not changed 

![image](https://user-images.githubusercontent.com/3728712/51995562-377a0400-24b3-11e9-8ef0-546e3b1a8620.png)

**Comment by ashklianko** [comment]
That was fixed in https://github.com/enonic/app-contentstudio/issues/104, @sgauruseu please recheck.

@alansemenov , do we need PR for 6.15?

**Comment by alansemenov** [comment]
No

**Comment by sgauruseu** [comment]
I did not reproduce this bug in latest XP, so it is Done now
