### ISSUE TITLE
Changing content permissions triggers fetch of all modified child content items

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/app-contentstudio#1285]
Calls to resolveByIds should be batched (But check first it is really necessary to retrieve all of them).

Example: Change permissions on the parent of a lot of contents
ContentStudio will call "resolveByIds" with the list of all modified contents

<img width="910" alt="Screenshot 2019-12-04 at 16 14 34" src="https://user-images.githubusercontent.com/12030113/70154999-c21e2780-16b1-11ea-8fae-1eabf039b758.png">

Fix also in 2.2.4

Check for similar situations

**Comment by sigdestad** [comment]
We also need a circut breaker for this stuff in XP! Can never trust a client!

**Comment by GlennRicaud** [comment]
> We also need a circut breaker for this stuff in XP! Can never trust a client!

https://github.com/enonic/app-contentstudio/issues/1288

**Comment by GlennRicaud** [comment]
> We also need a circut breaker for this stuff in XP! Can never trust a client!

https://github.com/enonic/xp/issues/7693

**Comment by runarmyklebust** [comment]
This will be always be a problem if running with several content studios open and someone doing changes to a lot of content?

**Comment by ashklianko** [comment]
Considering UI part of task: I'll optimize those calls on UI so we won't fetch all ids, only needed ones
