### ISSUE TITLE
Tooltip in Version History always says "Published"

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1306]
Always says "Published" for every version.
![image](https://user-images.githubusercontent.com/11612490/70252970-94ed7a00-1782-11ea-9154-a3a87e65e09d.png)

**Comment by sgauruseu** [comment]
Verified : 
![image](https://user-images.githubusercontent.com/3728712/81273422-84a23980-9057-11ea-9590-2a4fc0c3c35b.png)
