### ISSUE TITLE
Notification about version revert is covered by Compare Version dialog

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1309]
1. Open a content.
2. Open Versions widget.
3. Click on Compare Versions button and open modal dialog
4. Click on Revert button in the  Compare Versions

Issue:  message should be over Compare Version dialog

![image](https://user-images.githubusercontent.com/3728712/70427951-b0a89700-1a86-11ea-96f5-3559884c905d.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1223](https://github.com/enonic/lib-admin-ui/issues/1223) via [**ZenHub**](https://www.zenhub.com/)
