### ISSUE TITLE
Implement toggle panel with menu items

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1317]
Burger icon should behave like the toggle button (same as in the Launcher panel) expanding/collapsing the sidebar menu on the left-hand side. The expanded menu should shift contents of ContentAppPanel to the right, then back again when it collapses. In expanded mode the burger icon will turn into "X" icon, like in the Launcher panel.

In desktop mode:
* Vertically positioned app name (what's now to the right of the tree icon) under the "X" icon
* Two icons (for now) in the menu: pencil (always selected for now) and cog
* Menu item names: "Content" and "Settings" (localise both)
* Tooltip with menu item name should show on icon hover
* "Content" menu item should open Content Studio in the new browser tab

In mobile mode: see https://github.com/enonic/app-contentstudio/issues/1318

![image](https://user-images.githubusercontent.com/11612490/70610305-a19b2380-1c03-11ea-817d-1571c0483c8c.png)

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/pull/1320
