### ISSUE TITLE
Different layout of the menu panel in mobile mode

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1318]
* Use the same width as the Launcher panel 
* App name should be shown to the right of the "X" icon
* Menu item titles should be shown next to the icons
* A tap anywhere outside of the menu should collapse it

![image](https://user-images.githubusercontent.com/11612490/70610834-8da3f180-1c04-11ea-8eea-3b39a36221d9.png)

**Comment by ashklianko** [comment]
Pushed to https://github.com/enonic/app-contentstudio/pull/1320
