### ISSUE TITLE
Widget panel is not refreshed after batch-selecting items in the Content Grid

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1323]
1. Open CS
2. Open the Widget panel, select some content-dependent widget, like "Details"
3. Click some item in the grid. The widget is updated
4. Using keyboard (Shift+Down arrow) select several items.

Bug: the widget is supposed to be updated with info of the last selected item, but it's still displaying the first one. It works correctly when items are selected with Shift+Up arrow.

**Comment by ashklianko** [comment]
Same when using checkboxes on the left - if you select item and start checking items above widget gets updated but not vice versa
