### ISSUE TITLE
Implement new /settings page

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1338]
Cog icon in the [new top level menu](https://github.com/enonic/app-contentstudio/issues/1319) will open a new page under Content Studio app, which will be used for the application management. "Content grid" part of the app will still be under `com.enonic.app.contentstudio/main#/browse`, and the new "Settings" page will have URL `com.enonic.app.contentstudio/main#/settings`. When this is set up, add the link to the Cog icon in the top-level menu.

This page's main container element will be `TabbedAppBar`, like in the Users app.

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/e63a130fc388a7af765b4f66432deadc69c6131a
