### ISSUE TITLE
Restrict access to the settings page

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1339]
To begin with, only users of roles `system.admin` and `cms.admin` will have access to this page. Later on we will also give access to users who have `owner` permission for at least one project in the list.

Since we cannot verify this in the backend's admin layer, we can run this check inside the app controller (`main.js`) via `authLib.hasRole()` and respond with 403 if permissions are insufficient.

After we implement permissions on the project level, we will get rid of `cms.cm.app` role

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/51a346eb9ce4aab60214f22817ccfc896806f61c
