### ISSUE TITLE
Implement SettingsTreeGrid

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1340]
`SettingsTreeGrid` will derive from `TreeGrid<SettingsTreeGridItem>` (https://github.com/enonic/app-contentstudio/issues/1347) and display configurations in tree structure. First level will be "static" folders, like "_Projects_", "_VHosts_", "_Roles_" etc. These names should be hardcoded and localised, like "_Users_", "_Groups_" etc in the Users app. In the first version we will only have "_Projects_" folder. Use standard folder icon for the top-level nodes.

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/ebbbc67b2f51135005e3e6feb14eba9ab2e4873e
