### ISSUE TITLE
Implement ProjectResourceRequest and ProjectItem

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1341]
Implement base class `ProjectResourceRequest` for requests to [Content Project API](https://github.com/enonic/xp/blob/epic-project/modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/ProjectResource.java). Similar to `ContentResourceRequest`. Add project entity class (`ProjectItem`) and required Json classes as needed.

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/5a978982cfb11e2f059ed34c72e9a8d875f75118
