### ISSUE TITLE
Bind SettingsTreeGrid with data fetched by ProjectListRequest

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1342]
When the Settings page of the app opens, make a request to fetch the list of projects via [ProjectListRequest](https://github.com/enonic/app-contentstudio/issues/1344), transform Json to array of `ProjectItem`, then feed to `SettingsTreeGrid` to display them under "Projects" folder.

Use [Content Tree icon](https://github.com/enonic/app-contentstudio/blob/master/src/main/resources/assets/icons/icon-black.svg) if project doesn't have its own.

![image](https://user-images.githubusercontent.com/11612490/71014310-0b2e9c80-20f2-11ea-872e-b282c6d5e051.png)

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/08b543def5b050259c3a8148c64f3c25cce98a96
