### ISSUE TITLE
Implement New Configuration dialog

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1343]
1. Add `New` action to the Grid toolbar
2. Implement NewConfigDialog where user will select type of the new configuration (like we select User or Group or Role or Id provider in the Users app). Initially there will only be "Project" in this dialog. Clicking on the "Project" will open the Project Wizard page.

Use [Content Tree icon](https://github.com/enonic/app-contentstudio/blob/master/src/main/resources/assets/icons/icon-black.svg) for the "Project" option.

Same title ("Create New") and button ("Cancel") as in the User app's New dialog.

![image](https://user-images.githubusercontent.com/11612490/71014777-c5be9f00-20f2-11ea-8c46-b80b916afd96.png)

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/ce3bc428229f5b8e24c116d4a8e615dc4d8fe4c5
