### ISSUE TITLE
Implement ProjectListRequest

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1344]
Implement class `ProjectListRequest` which will derive from [ProjectResourceRequest](https://github.com/enonic/app-contentstudio/issues/1341) and fetch data from [project list API](https://github.com/enonic/xp/blob/9cfbaaca5f9d3b6a073156d24a508f1d122ed471/modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/ProjectResource.java#L59)

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/5a978982cfb11e2f059ed34c72e9a8d875f75118
