### ISSUE TITLE
Implement ProjectGetRequest

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1345]
Implement class `ProjectGetRequest` which derives from [ProjectResourceRequest](https://github.com/enonic/app-contentstudio/issues/1341, gets project json by its `name` from [project get API](https://github.com/enonic/xp/blob/9cfbaaca5f9d3b6a073156d24a508f1d122ed471/modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/ProjectResource.java#L66) and transforms it to `ProjectItem`.

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/ac1f9d2eef270f2689d0397c21abd1251c92aedc
