### ISSUE TITLE
Implement ProjectWizardPanel

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1346]
Project Wizard page will open in a new tab, like in the Users app. 
When opened for an existing project the Wizard should fetch its details from the `get` [endpoint](https://github.com/enonic/app-contentstudio/issues/1345).

The Wizard will initially have the following fields/controls:

Header:
* Content Tree icon (will be a thumbnail control for uploading custom project icon)
* Display name

Step "Project": 
* Name
* Description

Toolbar buttons:
* [Save](https://github.com/enonic/app-contentstudio/issues/1352)
* [Delete](https://github.com/enonic/app-contentstudio/issues/1353)

![image](https://user-images.githubusercontent.com/11612490/71017439-d8d36e00-20f6-11ea-8967-3b2bf0501eb3.png)

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/e34e99c801ff59a3247de2deb952c8d409d7a3cf
https://github.com/enonic/app-contentstudio/commit/2d1669ae971932a6ef67abc960d3069d0509ae15
