### ISSUE TITLE
Implement SettingsItem and SettingsTreeGridItem classes

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1347]
The Settings page will initially only have project management. But in the future there will be other settings there, like Vhosts, Users etc. 

All of these will be shown in the same `TreeGrid` (kind of like we combine Id Providers with Principals in the User app's grid), so we need general classes with common properties (display name, description, icon) which will be used by the tree and which other, more specific classes (like `ProjectItem`) will derive from. Similar to `UserItem` and `UserTreeGridItem` in the Users app.

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/ebbbc67b2f51135005e3e6feb14eba9ab2e4873e
