### ISSUE TITLE
Implement ProjectCreateRequest

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1349]
Implement class `ProjectCreateRequest` which derives from [ProjectResourceRequest](https://github.com/enonic/app-contentstudio/issues/1341, posts project json to [project create API](https://github.com/enonic/xp/blob/9cfbaaca5f9d3b6a073156d24a508f1d122ed471/modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/ProjectResource.java#L36), gets created project json back and transforms it to `ProjectItem`.

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/d2b0fe54f91f016da9c5b024a8a85bb5bd5b8db2
