### ISSUE TITLE
Implement ProjectUpdateRequest

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1350]
Implement class `ProjectUpdateRequest ` which derives from [ProjectResourceRequest](https://github.com/enonic/app-contentstudio/issues/1341, posts project json to [project modify API](https://github.com/enonic/xp/blob/9cfbaaca5f9d3b6a073156d24a508f1d122ed471/modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/ProjectResource.java#L44), gets modified project json back and transforms it to `ProjectItem`.

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/816826c0aff915067335a67285b91ada4193f903
