### ISSUE TITLE
Implement ProjectDeleteRequest

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1351]
Implement class `ProjectDeleteRequest` which derives from [ProjectResourceRequest](https://github.com/enonic/app-contentstudio/issues/1341, posts project json to [project delete API](https://github.com/enonic/xp/blob/9cfbaaca5f9d3b6a073156d24a508f1d122ed471/modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/ProjectResource.java#L52), gets saved project json back and handles response.

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/1760691ee807b2c3e5ac2afee1dde16bfe0a86e5
