### ISSUE TITLE
Enable deleting project from the Wizard page

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1353]
_Delete_ button should only be enabled for saved/existing projects and will [delete the project ](https://github.com/enonic/app-contentstudio/issues/1351) with confirmation.

Upon successful deletion, close the wizard tab and show confirmation: "_Project "aaa" is deleted._"

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/71771436721e0c4497edef35570f05fa4b896b58
