### ISSUE TITLE
Sanitize project name from its display name

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1354]
When user enters display name for a new project in the wizard header, we should auto-generate the project name (first field in the wizard form), similar to how we do it for content path. Upper case should be lower cased, spaces and other special characters removed etc.

The result should match the regex used for project name [in the backend](https://github.com/enonic/xp/blob/3ce68097cdb0b645e0b033015dfd6bae4d0c997f/modules/core/core-api/src/main/java/com/enonic/xp/project/ProjectName.java#L13), other characters can be stripped away.

For existing projects the project name field should be read-only.

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/d6b5d6c5aef420f335354f9a917ff5ed38a3da67
