### ISSUE TITLE
Uploader won't check uploaded file type

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1358]
1. Open new wizard for a content with Image Selector 
2.  Drag'n'Drop  and upload a jar-file

BUG -  jdk-8u191-windows-x64.exe is uploaded in the Image-Selector

![image](https://user-images.githubusercontent.com/3728712/71086484-24dfea80-21ab-11ea-9674-604a56a79c42.png)

**Comment by alansemenov** [comment]
Will be fixed in https://github.com/enonic/xp/issues/8075
