### ISSUE TITLE
Inspection Panel - incorrect size of frame in expanded options of image-selector

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1359]
1. Open Super Hero, open Page Component View and insert new image-component (in left)
2. Click on Upload-icon and upload an image.
3. Insert one more image component do not select an image but save and close the wizard.  
4. Open Super Hero again , open Page Component View and click on the just added image component  - Inspection Panel is loaded (OK)
5. Click on dropdown handle in the Inspect Panel and expand options: 

Issue - incorrect styles are in the expanded options: 

![image](https://user-images.githubusercontent.com/3728712/71088609-db45ce80-21af-11ea-81cd-ea77adb84fc9.png)

Options gets normally displayed  after scrolling options.

**Comment by alansemenov** [comment]
Fixed in another issue
