### ISSUE TITLE
Set project context via URL

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1372]
Similar to [what we did](https://github.com/enonic/app-contentstudio/issues/739) for layers.

Project name should be passed via URL of the Content Studio app.

Now:
`/main#/browse` or `/main#/edit`

New version:
`/main#/<project>/browse` or `/main#/<project>/edit`

`<project>` should then be parsed out of the URL and be used to set correct context of the Content Studio.

If  `<project>` is missing in the URL, we should redirect to  the default URL which is `/main#/default/browse`.

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/681f98cc1a2101ac3b9b0a0474271590a9a0278d
