### ISSUE TITLE
Set URL and project context after switching a project

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1374]
After a project is switched via [project selector](https://github.com/enonic/app-contentstudio/issues/1373), we should switch project name in the URL which will lead to the [change of the context ](https://github.com/enonic/app-contentstudio/issues/1372) which will reload the page/data from [new API endpoints](https://github.com/enonic/app-contentstudio/issues/1376)

**Comment by ashklianko** [comment]
Depends on https://github.com/enonic/lib-admin-ui/commit/24cefba61eec98b0d1fc6a4775b80b842aed898d
