### ISSUE TITLE
Modify API endpoint for content resource

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1376]
Content API endpoint is now at `admin/rest/content`. This changes to `admin/rest/cms/<project>/base`, where `<project>` is project name from current context. It's of course crucial that context is correctly set before API endpoint is called. `base` part is hardcoded for now, later on this will be layer name inside the selected project.

See https://github.com/enonic/app-contentstudio/issues/684 where we did the same thing for layers.

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/049ea1699be84e8592ced853e934b4b9c9bc15f7
