### ISSUE TITLE
Duplicated content should always be created in state "In Progress"

### ISSUE THREAD

**Issue by Sneiwert** [enonic/app-contentstudio#1382]
When copying an event it shows "ready to publish", but nothing has been edited or approved.

**Comment by alansemenov** [comment]
Should most likely be fixed in admin API.

**Comment by ashklianko** [comment]
@alansemenov we only send ids to duplicate, result is fully created on backend, so I believe it is a backend task

**Comment by alansemenov** [comment]
Issue moved to [enonic/xp #8829](https://github.com/enonic/xp/issues/8829) via [**ZenHub**](https://www.zenhub.com/)
