### ISSUE TITLE
Code tag cannot be removed in HTML Editor

### ISSUE THREAD

**Issue by vot-enonic** [enonic/app-contentstudio#1383]
Working in htmlArea, if you mark text and apply "Code" as paragraph format, the formatting will not be replaced if you apply e.g. "Normal". You need to go into "Source" to remove the code tags. Shouldn't it be possible to remove these tags from the WYSIWYG editor by applying another paragraph format?

**Comment by alansemenov** [comment]
It's actually worse than that - after applying "Code" formatting the format dropdown won't display correct selection (see screenshot below where it says "Normal" even though the cursor is in the middle of `<code>` tag)

![image](https://user-images.githubusercontent.com/11612490/78251076-1961c680-74f1-11ea-889e-dd398775bbd6.png)
 
It seems to work fine in [CKE 4 demo](https://ckeditor.com/ckeditor-4/demo/)

**Comment by ashklianko** [comment]
The Format plugin we use is intended for block level elements, and code tag is inline so it doesn't work well.
I will add custom plugin with button on toolbar to wrap/unwrap selection into code tag

**Comment by alansemenov** [comment]
@ashklianko The thing is we don't want any additional buttons in the toolbar... Can you research why it works fine in CKE 4 demo? Select "Computer code" from the "Block styles" dropdown.

**Comment by ashklianko** [comment]
That is also a separate plugin called  "Styles Combo"  that can handle inline elements
