### ISSUE TITLE
Fragment Wizard - Preview button should be visible in the toolbar

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1384]
1. Open Features then insert an image or part or layout.
2. Open Page Component view and save the component as fragment

Expected:  "Preview" button should be present in the fragment-wizard

Actual: Preview is enabled in the browse panel (the fragment is selected) but it is not present in the wizard-tab:

![image](https://user-images.githubusercontent.com/3728712/72050982-70317880-32d3-11ea-9e5d-81a55b4081fb.png)

**Preview button gets visible after updating this fragment in the wizard or refreshing this page in browser**

**Comment by alansemenov** [comment]
Most likely caused by the fix of https://github.com/enonic/app-contentstudio/issues/1128.

Seems like the logic for disabling/enabling the Preview button is correct in the Grid, so we should use the same in the Wizard.
