### ISSUE TITLE
Site Wizard does not update after selecting a part ( layout) in Inspection Panel

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1385]
1. Open new site wizard , type a name and select Features.
2. select  default controller , open Page Component View and insert two components : image and part(layout).

![step1](https://user-images.githubusercontent.com/3728712/72054134-74f92b00-32d9-11ea-9212-587d7ebecf50.png)

3. Save the site.
4. Click on the image component and select an image in the Inspection Panel:  (Site is  updated automatically)
![step2](https://user-images.githubusercontent.com/3728712/72054206-94905380-32d9-11ea-884f-a6d7cadfa914.png)

5. Click on part(layout) component and select an option in Inspect Panel

Expected: new component should appear in the LiveEdit and this site should be saved automatically 

**Actual**: 
**1. The option is selected , but the page is not updated :**  
**2. Selected option in Inspect Panel disappears after clicking on Apply button.**

![image](https://user-images.githubusercontent.com/3728712/72054475-17b1a980-32da-11ea-8395-ec0a71de6355.png)

**Comment by ashklianko** [comment]
Discussed with @sgauruseu , issue is not reproduced anymore. Closing it
