### ISSUE TITLE
Content Studio dashboard - "my last edits"

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/app-contentstudio#1389]
Editors that work with contents a lot will often revisit the same contents a few times before moving on. XP/Content Studio have no way today to show you "These 10 items are the last ones you've worked on, get back in there?". In CMS we had this, many used to that really misses this feature in XP. How can we incorporate this in XP? It is indeed a very handy feature as XP has no easy way for you to go back to where you were last, unless you always keep those resource-hungry tabs open, or bookmark - neither solution are very good.

I've so far yet to hold a Content course were this is not requested. What is our plan for this? Use the empty space to the right when you open Content Studio? Or make Home Screen more useful? I'd prefer adding this to Content Studio since the contents are managed in there anyway. Another idea would be a Widget that we add to market that could display "my last edits" and similar shortcuts/lists of childContents for each content you click. Not very user friendly perhaps, but could do the job until we land the final thing.

TINE and Nav especially misses this functionality.

How it looked in CMS:
![screen shot 2018-04-17 at 14 34 09](https://user-images.githubusercontent.com/1465598/38869873-713e2116-424c-11e8-876a-f1ee6da2b8e5.png)

**Comment by alansemenov** [comment]
This is already added to the backlog
