### ISSUE TITLE
HTML Area - Configure available fonts

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1391]
http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-font_names

By default we will use standard set of fonts from CKEditor's default configuration:

![image](https://user-images.githubusercontent.com/11612490/27335777-f9152bdc-55cd-11e7-8238-6e6c3dba68f9.png)

But we need to implement override of the font set via HTML Area's schema (as with tools in the toolbar).

**Comment by sigdestad** [comment]
I'm closing this issue, as we don't want to support random fonts for now.
