### ISSUE TITLE
Content Studio: Get overview all contents with status "Pending Publish"

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/app-contentstudio#1395]
TINE editors requested during training the ability somehow to see what contents are set up for pending publication (or expiration date). It could be via the search-function. The point of the feature would be to get a quick overview over contents and their statuses, you could see "oh, Tine.no have these 3 articles going out in the coming weeks, then I won't need to write this fourth one".

If we had a dashboard/improved home screen, this could also be displayed there. But I guess that is further away.

Today getting overview of this is not possible, unless you expand every content in the grid and manually check all their statuses, something that is not feasible for sites with 100s or 1000s of contents.

**Comment by alansemenov** [comment]
Duplicate of https://github.com/enonic/app-contentstudio/issues/1231
