### ISSUE TITLE
Allow user to work in Content Studio in the context of a specific user group 

### ISSUE THREAD

**Issue by RF0** [enonic/app-contentstudio#1398]
When working in context of **one** site - lets say superhero.no - in Content Studio, the Search Panel / search results creates a lot of unnecessary noise by listing Content Types / content from all sites. It makes it harder to find stuff. Especially if there are lots of sites. 

Example screenshot with two sites: 
![screen shot 2018-08-22 at 14 50 33](https://user-images.githubusercontent.com/951293/44464456-2337fe00-a61b-11e8-9953-0a5cf8410583.png)

Therefore, a content editor should be able to work in the context of a certain group, lets say a "Superhero Editor", which shows only relevant Content Types and content in the Search Panel / search results.

Screenshot of what a content editor wants to see when working with the superhero site:
<img width="606" alt="screen shot 2018-08-22 at 14 50 12" src="https://user-images.githubusercontent.com/951293/44464457-2337fe00-a61b-11e8-8891-4912a2656d90.png">

Note: since the ldap-id-provider is in use, it is unpractical to have multiple users for each person to allow this, that would also encompass the need to remember multiple username / password combinations, which is bad. 

A "Work in context as a group" functionality would solve this. Also see [slack conversation](https://enonic.slack.com/archives/C1GAHTD0V/p1534928492000100) for discussion regarding this.

**Comment by alansemenov** [comment]
This will be solved by Content Projects
