### ISSUE TITLE
Rename widget interfaces

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#14]
To fetch the list of widgets we send API request to ``/widget/list/byinterfaces`` and send array of expected interfaces as a parameter. Currently we support two interfaces: *com.enonic.xp.content-manager.context-widget* (deprecated) and *contentstudio.detailpanel* (current).

Remove the deprecated one and rename the current one to *contentstudio.contextpanel*

**Comment by sigdestad** [comment]
Alan, a small important details - I am not sure how this is best done, but the context widget either needs to get the repo+branch injected always, even when a content has not been selected. This is in order to be future-proof when we support multiple repos

**Comment by alansemenov** [comment]
@sigdestad Not sure I understood this one... If no content is selected, what repo/branch will we send to the widget?

**Comment by sigdestad** [comment]
The one in context ofcourse. Initially, it can be hardcoded to the new default cms repo "com.enonic.cms.default" something. And the branch is always draft (at least for now).

**Comment by alansemenov** [comment]
Context can be received directly from inside the widget, no?
In any case this is not breaking. We can add this any time.

**Comment by sigdestad** [comment]
I am not sure? How can it? Then it will need a special contentStudio javascript API or something like that...
