### ISSUE TITLE
Switching between tabs is not working in the "Insert Link" dialog on mobile

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#140]
On iPhone 7 at least tapping on tabs in the "Insert Link" dialog doesn't do anything, the first tab always remains active. Works fine in the Inspect/Insert/Emulator panel.

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #921](https://github.com/enonic/lib-admin-ui/issues/921) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #922](https://github.com/enonic/lib-admin-ui/issues/922) via [**ZenHub**](https://www.zenhub.com/)
