### ISSUE TITLE
Misc improvements

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1408]
1. In the screenshot below the "name" field under display name is using a different sanitisation algorithm than the project name field in the form. We need some kind of separator to replace the space with, and "-" is allowed, so I suggest using the same algorithm. 

![image](https://user-images.githubusercontent.com/11612490/72252593-d84bcb80-35ff-11ea-8da7-f8e3217fd03a.png)

2. Remove the "name" field - it's not used

3. We need to dynamically update tab name ("<_Unnamed Project_>" below) whenever display name is changed - this works in the Users app and should work here as well. 

![image](https://user-images.githubusercontent.com/11612490/72252947-a129ea00-3600-11ea-9b3c-3dde8d22af07.png)

4. In the grid we should show description under display name (if it exists). I cannot test it now since save doesn't work, but if there's no description then we should not show anything, because "_<unnamed>_" is not correct.

5. Use the following layout for the Preview panel (similar to what we use for selected Id Provider in the Users app)

![image](https://user-images.githubusercontent.com/11612490/72254049-447bfe80-3603-11ea-8e40-df479f541326.png)

6. For a **new** project show the following hint under the "Project name" field (should be localised):

_NB! This field cannot be changed after the project is created!_

![image](https://user-images.githubusercontent.com/11612490/72254402-3f6b7f00-3604-11ea-9df6-303fd1005419.png)

7. For existing project make the Project name field look like text on the page, not like a readonly field. Right now project name looks like a placeholder inside a readonly field.

![image](https://user-images.githubusercontent.com/11612490/72254546-a4bf7000-3604-11ea-9989-82ab11130d5f.png)

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/81e590bcb93f78a4797f1c3e6411213501dea8fe
