### ISSUE TITLE
Shortcut wizard - error in console after saving a shortcut and parameter was deleted  before

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1418]
1. Open new shortcut wizard, type a name, select target , and add one parameter.

![image](https://user-images.githubusercontent.com/3728712/72518315-1d713700-3866-11ea-94e5-c8bd7fb4dab4.png)

2. Reopen the shortcut. (this step is required).
3. Remove the parameter. Click on Save button

Bug: error in console after saving the shortcut: 

error in console
![image](https://user-images.githubusercontent.com/3728712/72518885-4d6d0a00-3867-11ea-9eea-4baf05872fae.png)

**Comment by ashklianko** [comment]
Not reproduced neither by me nor by @sgauruseu
