### ISSUE TITLE
Error in console after closing several notification messages sequentially

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1424]
Case 1 
- Open Features site, update the description.
- Save the site then click on Mark As Ready menu-button and publish the site.
- Click on remove icon and close the first bottom notification message then remove the second bottom message.

BUG:  error in console after removing these messages:

![image](https://user-images.githubusercontent.com/3728712/72723667-48bf9300-3b92-11ea-8341-6bb8cd14a22e.png)

Case 2 :  
- Select Features and open Attachments  wizard, upload 4 files
- 3 messages appears (OK)
- remove the first bottom notification message then remove the second bottom message.

BUG:  error appears in the console 

![image](https://user-images.githubusercontent.com/3728712/72723907-eb781180-3b92-11ea-80c0-c23f304ad36a.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1225](https://github.com/enonic/lib-admin-ui/issues/1225) via [**ZenHub**](https://www.zenhub.com/)
