### ISSUE TITLE
Uploaded attachments are not correctly displayed in the Details widget

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1432]
**Case 1:**
- Select Features and open new wizard Attachments-content
- Type a name and upload 4 files in `Multiple attachments`
 **BUG** - 3 items appear in the widget after the uploading  (expected is 4)

![image](https://user-images.githubusercontent.com/3728712/72884486-40449500-3d17-11ea-9714-980a6e789258.png)

**Case 2** 
- Upload in `Single attachment` an image that was  uploaded in Multiple attachments:

![image](https://user-images.githubusercontent.com/3728712/72884773-bba64680-3d17-11ea-8aed-4e5d526fa88f.png)

- Remove the attachment item in Single Attachment.

**BUG -**    2 items remain in the widget, but expected is 4  

![image](https://user-images.githubusercontent.com/3728712/72885014-2788af00-3d18-11ea-9124-e83dbea6ba06.png)

**Comment by alansemenov** [comment]
See also https://github.com/enonic/app-contentstudio/issues/1423

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1227](https://github.com/enonic/lib-admin-ui/issues/1227) via [**ZenHub**](https://www.zenhub.com/)
