### ISSUE TITLE
Mark content type as obsolete

### ISSUE THREAD

**Issue by poi33** [enonic/app-contentstudio#1433]
I often find customers using old content types, that they no longer use and should not be used. 
Could we have some functionlaity to show its not supported anymore/ not in use? 
Maybe gray out or remove the content-type in the new content wizard?

**Comment by poi33** [comment]
Any update on this?

**Comment by alansemenov** [comment]
We will add a new property to content-type schema:

```
<content-type>
  <disabled>true</disabled>
</content-type>
```

**Comment by alansemenov** [comment]
Done in 3.3

**Comment by alansemenov** [comment]
Originally done in https://github.com/enonic/xp/issues/8720
