### ISSUE TITLE
Projects: Fix switching between content studio and settings

### ISSUE THREAD

**Issue by ashklianko** [enonic/app-contentstudio#1436]
Currently both cs and settings panels are present in DOM,  receive events, add/remove items in grids etc. 
-Remove from DOM or disable app that is not used
-Make sure events are not listened by inactive app
-Make sure shortcuts of inactive panel are not working in active one

**Comment by sigdestad** [comment]
This is interesting in many ways:
We do not want each "panel" (i.e. settings/content) to loose it's state (i.e what you expanded, or if you just did a search etc). I guess this is stuff that is normally handled by UI frameworks (i.e. like saving the state). Is this something we can do later when we have many different panels maybe? Or is this easy to handle with our current framework?

**Comment by ashklianko** [comment]
It is not only improvement, there's a bug with shortcuts from one panel working while other is active, so this is to be fixed first; In general, I am aiming to handle it with our framework

**Comment by ashklianko** [comment]
Part regarding "_Make sure shortcuts of inactive panel are not working in active one_" is done, the rest is  out of scope for now and to be done on demand later
