### ISSUE TITLE
Issues with mid-aligning images in html-area

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/app-contentstudio#1444]
Related to this issue #1289; i still get the problem both in CS 2.2.4 and 2.3.1
The style is assigned to the preview-window, but dissapears on save / mark as ready etc.
Aligning left or right works as expected

![Screenshot 2020-01-28 at 11 10 37](https://user-images.githubusercontent.com/356026/73256114-a6229800-41c1-11ea-9aa9-05eb2ba0b260.png)

After save

![Screenshot 2020-01-28 at 11 11 00](https://user-images.githubusercontent.com/356026/73256128-ad49a600-41c1-11ea-8b17-05f185799968.png)

**Comment by alansemenov** [comment]
@ashklianko  More details on this one. After I center-aligned an image and saved content, "Save" button blinked twice and eventually remained enabled (should be disabled after save). When I checked the saved content, it was actually saved correctly but was wrong in HTML Area source, which means it was tweaked after save (which explains why Save became enabled).

![image](https://user-images.githubusercontent.com/11612490/73853502-3fd8ed80-4831-11ea-9d21-fef7b98a85b9.png)

![image](https://user-images.githubusercontent.com/11612490/73853665-86c6e300-4831-11ea-9125-e1ce97e9e040.png)
