### ISSUE TITLE
Display current project name in the Content Wizard toolbar

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1448]
Only if more than 1 project exists, show current project name in the Wizard toolbar (top left corner). We already have hidden `app-name` span there, which can be used for that. 

Icon to the left of the project name should be project icon, not the app icon like now (fix height of the icon so that it's equal to the toolbar height). Remove on-hover animation for the span so that it doesn't look like a button. The project icon will still open the Content Grid in the new tab.
 
Right border color: @admin-bg-light-gray. 
Project name color: @admin-font-gray3

![image](https://user-images.githubusercontent.com/11612490/73346549-5659d480-4286-11ea-905c-3a18a7fefc84.png)

In mobile resolution, hide the project name and show only project icon:

![image](https://user-images.githubusercontent.com/11612490/73347107-54dcdc00-4287-11ea-932e-de0a9146c26f.png)

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/08955d167485fc041355fbae88e30444a8214080
