### ISSUE TITLE
Image Selector - filtering is not triggered when pasting string from buffer into the filter input

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1451]
1. Select Features and open new Image Selector content.
2. Copy 'Features' (Ctlc+c) and paste it in input filter (Ctrl-v) 

**Expected: Required options should be shown in the expanded selector** 

**Actual:** 

![image](https://user-images.githubusercontent.com/3728712/73351037-44d0f680-429f-11ea-9616-475c69afd79f.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1778](https://github.com/enonic/lib-admin-ui/issues/1778) via [**ZenHub**](https://www.zenhub.com/)
