### ISSUE TITLE
Customer request: user group permissions with different access to content types and parts

### ISSUE THREAD

**Issue by vot-enonic** [enonic/app-contentstudio#1460]
A customer has asked me to convey a feature request in Content Studio.

In Content Studio, administrators can decide what areas a given user group can publish content on, but all users have access to all content types and parts.

This particular customer will end up with a sizeable number of content types and parts, something which can be overwhelming and confusing for some user groups.

**Our customer thus requests the ability to manage what content types and parts a user group may have access to.**

A hypothetical example:
- Administrators and super users: access to all content
- Sub editors: access to level 2: approx. 80% of selected content types and parts
- Publishers: access to level 3: approx. 30% of selected content types and parts

Is this possible to implement?

**Comment by alansemenov** [comment]
We have implemented a new feature (in XP 7.7 / CS 3.3) of being able to specify what content can be created in a specific content-type. You can also hide "deprecated" content types and specify what components (parts and layouts) are enabled for which content-type. This should suffice.
