### ISSUE TITLE
Responsive/compact Component Viewer (revival)

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/app-contentstudio#1469]
This looks to be done and merged into old CS but I cannot find it in new CS (and actually never seen this feature in action). What happened to it?

https://github.com/enonic/app-contentstudio-old/issues/435

**Comment by alansemenov** [comment]
@Bellfalasch It was done a long time ago. The threshold for switching to compact mode is 960px. See below for how it looks for me when browser page width is < 960. Also, starting from the next version layouts will be by default collapsed in the component tree.

![image](https://user-images.githubusercontent.com/11612490/73850159-7449ab00-482b-11ea-9b9f-4c7a290a4343.png)

**Comment by Bellfalasch** [comment]
Oh sweet, it was triggered from view point, didn't know. Should've used Slack/Discuss first ... Well thanks for the information =)

**Comment by alansemenov** [comment]
Added a bug for the missing description thingie: https://github.com/enonic/app-contentstudio/issues/1474
