### ISSUE TITLE
Site wizard does not open after deleting a child fragment

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1472]
Case 1 :
1. Open Features , open Page Component View and create new fragment from existing text component. Close the wizard.
2. Expand Features and delete just created fragment.
3. Select Features and click on Edit button.
**Bug: Wizard page is not loaded, error in browser console.**

Case 2:
1. Open Features , open Page Component View and insert new image component
2. Upload an image and close the site
3. Expand Features and select just uploaded image.
4. Click on `Delete` button then click on `Delete now`.
![image](https://user-images.githubusercontent.com/3728712/73848985-31430400-483a-11ea-8198-7136821de7e7.png)

5. Select Features and click on Edit button.

**BUG:** 
-  Wizard page is not loaded, errors in console appear

![image](https://user-images.githubusercontent.com/3728712/73849261-b0383c80-483a-11ea-90bc-f5962fcf0c96.png)

- click on New button -  New content Dialog does not load and the same error in console .

**The same issue after deleting a fragment in the site.**

**Comment by ashklianko** [comment]
Issue moved to [enonic/xp #8080](https://github.com/enonic/xp/issues/8080) via [**ZenHub**](https://www.zenhub.com/)
