### ISSUE TITLE
Image Selector with deleted image is not properly validated

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1479]
1. Select `Features `, open new Image Selector wizard.
2. Type a name and select images in required selectors., close the wizard
3. Select the content and open `Dependencies widget`, click on `Show Outbound` button
4. Delete the image that was selected in 'One required'
4. Reopen the content.
**Expected: This content should not be valid, because image in 'One required'  is not  selected.**
**Actual - This content is valid and can be published**

![image](https://user-images.githubusercontent.com/3728712/73938317-0fa85200-48f8-11ea-951f-e9eaf58e8d84.png)

**Comment by alansemenov** [comment]
Not only that, but images that are selected but not deleted stop showing as well.
