### ISSUE TITLE
Page Components Dialog - custom icon is overwritten with the default icon

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1487]
There is the similar fixed issue:  https://github.com/enonic/app-contentstudio/issues/1102

But this bug is still reproducing in the next cases: 

Case 1:  
Custom icon is not shown when the part is included more than once
-  Open Features site. Insert the part twice: `Image filters test`
-  Close the wizard then reopen it again 
![image](https://user-images.githubusercontent.com/3728712/74027260-de438b00-49b8-11ea-9c1b-2c3fff36960c.png)

Case 2:
- open new site wizard, select Features,  select default controller.
- insert   `Image filters test` part
- click on this part in Page Component View and select Duplicate menu item
Bug : this part is duplicated and the site is automatically saved, but custom icon is overwritten: 

![image](https://user-images.githubusercontent.com/3728712/74027559-7772a180-49b9-11ea-86e3-ca7a5caedd53.png)

**Comment by alansemenov** [comment]
Could be related to https://github.com/enonic/app-contentstudio/issues/1474
