### ISSUE TITLE
Option-set inside part config is not shown in the Inspection panel

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1490]
1. Create a new part with XML scheme below

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<part xmlns="urn:enonic:xp:model:1.0">
  <display-name>Option Set</display-name>
  <form>
  <option-set name="radioOptionSet">
    <label>Lenke</label>
    <expanded>false</expanded>
    <occurrences minimum="1" maximum="1"/>
    <options minimum="1" maximum="1">
      <option name="optionLink">
        <label>URL</label>
        <default>true</default>
        <items>
          <input name="link" type="TextLine">
            <label>Lenke</label>
            <occurrences minimum="0" maximum="1"/>
            <default>/</default>
          </input>
        </items>
      </option>
      <option name="optionXPContent">
        <label>XP-innhold</label>
        <items>
          <input name="xpContent" type="ContentSelector">
            <label>Innhold i XP</label>
            <occurrences minimum="0" maximum="1"/>
            <config>
              <allowPath>${site}</allowPath>
            </config>
          </input>
        </items>
      </option>
    </options>
  </option-set>
  </form>
</part>

```

2. Open a site and add the part to the page. The site is saved, everything is looking good in the inspect panel:

![image](https://user-images.githubusercontent.com/11612490/74145949-4f28b400-4c00-11ea-92bb-1b2aa66c898d.png)

3. Refresh the browser page

4. Click the same part and open the Inspect panel. 

**Bug: Content of the option-set is not shown**

![image](https://user-images.githubusercontent.com/11612490/74146018-78494480-4c00-11ea-87f2-acddb7ce17f9.png)

5. Click another component on the page and then the same part again. Now everything is back to normal.

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1206](https://github.com/enonic/lib-admin-ui/issues/1206) via [**ZenHub**](https://www.zenhub.com/)
