### ISSUE TITLE
Missing documentation about the custom content types / schema 

### ISSUE THREAD

**Issue by mortyeriksen** [enonic/app-contentstudio#1505]
Content Studio seems very limited with just the built in oned. 

Maybe this should be built in content types:
https://developer.enonic.com/docs/content-studio/master/content-types

And we need new page for content types?

**Comment by alansemenov** [comment]
@mortyeriksen  We have description of content types in general under XP/CMS/Content Types: https://developer.enonic.com/docs/xp/stable/cms/content-types. Is it that what you think we are missing?
