### ISSUE TITLE
Context is not set correctly when user doesn't have access to Default project

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1508]
I have created a new project and a new user who has access only to this project, not to the Default one (**Test User** in the screenshot below):

![image](https://user-images.githubusercontent.com/11612490/74472739-b4033900-4ea2-11ea-8f7f-38cd5a1c245c.png)

In the Settings' grid everything looks correct and I see only this project when I log in as that user:

![image](https://user-images.githubusercontent.com/11612490/74472670-9c2bb500-4ea2-11ea-8b8c-58c9f5621de9.png)

However, in the Content Studio the context is not set correctly - I see content from the Default project in the grid and project name is missing in the header:

![image](https://user-images.githubusercontent.com/11612490/74472927-0a707780-4ea3-11ea-976e-ec5be5a09261.png)

**Comment by ashklianko** [comment]
Pushed into https://github.com/enonic/app-contentstudio/issues/1492 to have permissions working and testable
