### ISSUE TITLE
Fix context panel behaviour in edit mode

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-contentstudio#151]
ONLY APPLIES TO EDIT MODE:

The following things must be fixed, as they have changed from 6.x
Test with 6.x if you are unsure how things should work

* Context panel is not "floating" in front of preview for medium size screens/laptops, seems trigger size has changed.
* Context panel now opens by default, where it used to be closed before. 
Check behaviour from 6.x, it is OK to open by default for large screens.

Also, with the new context panel, we need to tune the panel a bit more in edit mode:
1. if preview is closed/unavailable - and screen is > than mobile - we should show context panel by default anyway. In these cases, it kind of replaces the preview panel.
2. Also, when preview is closed/unavailable, the "components" widget must be removed (or disabled?), as this is only relevant when there is a preview. Same goes for the emulator widget.

NOTE: Hmm.. maybe we should have a special interface name for widgets that are not relevant unless the page editor is active? Any comments on this @alansemenov ?

**Comment by alansemenov** [comment]
For the first two points we have https://github.com/enonic/app-contentstudio/issues/120 which I see is not started yet. 
Hiding the Components widget when there's no preview we also discussed, maybe it simply hasn't been done yet.
I'm reluctant about adding new interfaces for specific things we have in Content Studio, interfaces should be generic. Plus Components widget is our internal thing anyway so we can steer when to hide/show it.

**Comment by edloidas** [comment]
Components won't be displayed, if there is no preview. This should work. But the emulator widget is always visible. I can also make it disappear when there is no controller, just like the components.

**Comment by alansemenov** [comment]
Yes, we should hide the Emulator is well. If there's no preview panel then there's no point in showing the Emulator.

**Comment by sigdestad** [comment]
Ok, let's just hardcode these things for now. Forget about the "different" interface suggestion. Let me know when I can test an updated version!
