### ISSUE TITLE
Image Wizard - Save button is auto-enabled after opening a cropped image

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1515]
- Open existing image and click on Crop button, drag zoom button.
- Save the changes and close the wizard.
- Reopen the image again.

![image](https://user-images.githubusercontent.com/3728712/74742779-41160b80-5270-11ea-8ee7-b5a3671d32ae.png)

Bug-  `Save` button is enabled after the content is reopened

**Comment by ashklianko** [comment]
Was fixed in https://github.com/enonic/app-contentstudio/pull/1826
