### ISSUE TITLE
Upgrade CKEditor to version 4.17.2

### ISSUE THREAD

**Issue by poi33** [enonic/app-contentstudio#1518]
Lots of vulnerabilities fixes since 4.11.1 we are currently on.

Check that all UI tests are passing and that our custom plugins and changes to existing plugins are not ruined.

https://github.com/ckeditor/ckeditor4/tags

**Comment by alansemenov** [comment]
This should fix https://github.com/enonic/app-contentstudio/issues/1518

**Comment by alansemenov** [comment]
This upgrade must be done before the next feature release (4.1.0).
