### ISSUE TITLE
Upgrade to the latest version of PasteFromWord plugin

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1526]
Customer has a problem pasting text from the [attached document ](https://github.com/enonic/app-contentstudio/files/4244400/Nasjonale.faglige.anbefalinger.for.undersokelse.av.syn.i.helsestasjons-.og.skolehelsetjenesten.docx)into our editor (pasted text gets empty links and odd attributes). Seems like the same text pastes fine on the [demo page](https://ckeditor.com/docs/ckeditor4/latest/examples/pastefromword.html) of the PasteFromWord plugin. 

Implement the latest version of this plugin for our version of editor.

**Comment by ashklianko** [comment]
Done in #1518
