### ISSUE TITLE
Live Editor - image does not load after  inserting of a fragment with the image

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#153]
1. Open new site wizard, type a name , select Features, select `main region`
2. Insert a text - component (use page Component View) , type a text and insert an Image in the editor, 
3. Click on the component and  select `Save as Fragment`
4. Click on the 'main' in the Page  Component View and select  `Insert Fragment`
5. Select the just created fragment

**Expected** - 2 the same image should be loaded in the LiveEditor 
**Actual**  - error appears in console and only one image is loaded

![image](https://user-images.githubusercontent.com/3728712/52562337-42b42480-2e0f-11e9-91a4-a877cc3faf21.png)

The second image loads when the page is refreshed

**Comment by ashklianko** [comment]
@alansemenov please check https://github.com/enonic/app-contentstudio/issues/241 - it is an issue source, I've currently made a workaround for it to work but need to solve this problem in general
