### ISSUE TITLE
Implement "Guest" role for project permissions

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1531]
Implement a 4th project role called "_Guest_" in addition to current _Owner_, _Expert_ and _Contributor_.

User with this role will have the same rights as _Contributor_, but should have some limitations in the Content Studio UI, basically read-only access:

1. Disable all buttons (including Publish menu) in the Grid and Wizard toolbar except for Preview
2. Disable issues button in the header
3. Make sure that keyboard shortcuts assigned to actions are disabled as well
4. Don't show context menu on right-click in the grid
5. Access section in the Content Wizard and Details widget should be hidden
6. Double-click to open the Wizard from the Grid should work.

**Comment by sigdestad** [comment]
Maybe we should wait with this new Role, seems to be quite some work involved, and we need to consider the implications more before we continue! Can we move it to backlog?

**Comment by alansemenov** [comment]
Sure
