### ISSUE TITLE
Remove polyfills for deprecated HTML Imports

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1547]
3.0 will be breaking version and we should remove remains of HTML imports:

https://github.com/enonic/app-contentstudio/blob/1862683c689b9b45b28bc602c5edd37ed641a1fb/src/main/resources/admin/tools/main/main.html#L74
https://github.com/enonic/app-contentstudio/blob/1862683c689b9b45b28bc602c5edd37ed641a1fb/package.json#L16
https://github.com/enonic/app-contentstudio/blob/1862683c689b9b45b28bc602c5edd37ed641a1fb/webpack.config.js#L106

**Comment by sigdestad** [comment]
Breaking as in all other apps will need to be updated?

**Comment by alansemenov** [comment]
As in all widgets that rely on HTML Imports, like for example [Google Analytics](https://github.com/enonic/app-google-analytics/blob/master/src/main/resources/assets/js/google-analytics.js). I'll create tasks for specific widgets too.
