### ISSUE TITLE
Remove "This version is active" button from Version History Widget 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1552]
1. Add a folder and publish one.
2. Open Version Panel and click on latest(published) version

Expected : "This version is active"  - should not be present in the view

![image](https://user-images.githubusercontent.com/3728712/75546913-c2bd2480-5a3a-11ea-940a-e4a3599d4b61.png)

**Comment by alansemenov** [comment]
We decided to keep the button. Fixed to show it for any active version (not only for the published one as now).
