### ISSUE TITLE
Site Wizard - Error after reordering applications and saving

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#156]
1. Open new site wizard and type a name and select 2 any applications . save the site 
2. Do swap applications in the wizard and click on Save button 

Bug: error message appears after the site has been saved 

![image](https://user-images.githubusercontent.com/3728712/52565534-21a40180-2e18-11e9-9a7f-d645b8f2c59b.png)

**Comment by vbradnitski** [comment]
Issue moved to [enonic/lib-admin-ui #931](https://github.com/enonic/lib-admin-ui/issues/931) via [**ZenHub**](https://www.zenhub.com/)

**Comment by vbradnitski** [comment]
Issue moved to [enonic/lib-admin-ui #932](https://github.com/enonic/lib-admin-ui/issues/932) via [**ZenHub**](https://www.zenhub.com/)
