### ISSUE TITLE
Files from another project are visible in browse panel

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1566]
Case 1: 
 - Select London project , open Filter Panel , click on `shortcut` checkbox 
![step1](https://user-images.githubusercontent.com/3728712/75759996-8560db80-5d47-11ea-9a49-bbb49890373e.png)

-  Switch to Default project   - Filter Panel is opened and checkbox is selected.
![image](https://user-images.githubusercontent.com/3728712/75759955-767a2900-5d47-11ea-813b-531af829d2ea.png)

-  Uncheck the checkbox 

BUG- files from `London` project are loaded after uncheck 'shortcut' 

![image](https://user-images.githubusercontent.com/3728712/75760136-ceb12b00-5d47-11ea-95d3-6ed182e5cc9c.png)

**Comment by alansemenov** [comment]
This is the same as https://github.com/enonic/app-contentstudio/issues/1565
