### ISSUE TITLE
Projects: filter node server events from other projects/repos

### ISSUE THREAD

**Issue by ashklianko** [enonic/app-contentstudio#1578]
No need to handle content CRUD events from other repos

**Comment by sigdestad** [comment]
I assume this is being filtered in the back-end?

**Comment by alansemenov** [comment]
How? The server has no idea about current context on the client, it sends events for all repos. Should be filtered on the client, of course.

**Comment by sigdestad** [comment]
So content studio clients should get all events going on within xp and filter them in the browser?
