### ISSUE TITLE
Incorrect validation behaviour in Project Wizard

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1640]
1. Open new project wizard.
2. Type a display name .
3. Type 'my project'

![image](https://user-images.githubusercontent.com/3728712/77537002-6a007080-6eae-11ea-9c33-241b3547e8ae.png)

**Bug- incorrect validation message appears when the name contains not allowed symbols**

4. Click on close-icon, Save Before Dialog appears. Click on Yes button

BUG-  not clear `notification message` appears:

![image](https://user-images.githubusercontent.com/3728712/77537400-15a9c080-6eaf-11ea-8167-18a5f1605c72.png)

5. Remove white space in the project name.

**BUG: validation message remains after the correct name is typed:**

![image](https://user-images.githubusercontent.com/3728712/77537762-af716d80-6eaf-11ea-998a-1f93ad6f5c32.png)

** Save button gets enabled after click on Yes button in Confirmation Dialog and the name is not correct:**

![image](https://user-images.githubusercontent.com/3728712/77538242-738ad800-6eb0-11ea-9ea0-99fa99b840c9.png)

**Comment by ashklianko** [comment]
1. Grey text under name input is help text, hint for a user, and not a validation result text
2. Incorrect validation message comes from a backend, need to update it there
