### ISSUE TITLE
Selecting an animated GIF in the Insert Image dialog gives endless spinner

### ISSUE THREAD

**Issue by vot-enonic** [enonic/app-contentstudio#1664]
Sometimes it is impossible to insert an uploaded GIF into e.g. a blog post. A GIF has been uploaded and can be observed as fully functional in the Grid. But when I attempt to insert the GIF via the "Image" function in the Content Editor, the image just loads forever and I cannot press the "Insert" button. Can this please be fixed?

See attached GIF for reference.
![screenshot](https://user-images.githubusercontent.com/43465080/78109946-834b7480-73fa-11ea-9cb2-042b91281f07.gif)

**Comment by alansemenov** [comment]
@vot-enonic Can you attach the actual GIF that gave that error?

**Comment by vot-enonic** [comment]
![fragments](https://user-images.githubusercontent.com/43465080/78123147-088c5480-740e-11ea-84f3-e8d74b36161c.gif)

**Comment by sgauruseu** [comment]
![image](https://user-images.githubusercontent.com/3728712/78455421-f416b900-76a6-11ea-86b9-d3d40d26737c.png)

I got exception after upload the gif in Htmlarea
