### ISSUE TITLE
Project Wizard - Confirmation dialog about unsaved changes appears when there are none

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1673]
1. Open new project wizard.
2. Type all required data.
3. Click on Save button then click on close-icon.

BUG: Confirmation dialog is loaded but the project was saved:

![image](https://user-images.githubusercontent.com/3728712/78353348-90ab5f00-75b2-11ea-85df-96b34e65cfc0.png)

**Comment by alansemenov** [comment]
It's not only on new projects, it's on ANY project. Even if I don't make any changes at all.

**Comment by sgauruseu** [comment]
I suggest adding Shader mask when project is being saving

**Comment by ashklianko** [comment]
Discussed with @alansemenov: will postpone close until save/update is finished
