### ISSUE TITLE
limit macro and parts to spesific content types

### ISSUE THREAD

**Issue by Kristiandal** [enonic/app-contentstudio#1689]
We need to limit macro and parts to spesific content types.
https://discuss.enonic.com/t/filter-parts-in-content-studio/2047

**Comment by sigdestad** [comment]
Issues here should provide a detailed solution description or pull request, if this is a feature request use the following options instead:
A) Register a support issue (subscribing customer)
B) Post it on our forum: https://discuss.enonic.com
