### ISSUE TITLE
HTML Area fields are cleared on concurrent content update

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1692]
1. Open Content Wizard for a content that has an HTML Area field and some X-data fields
2. Fill in some text into the HTML Area field (don't save)
3. Open the same content in another browser tab
4. Change values in X-data fields and save the content
5. Switch back to the first tab - HTML Area is cleared

This doesn't happen for other input types - we mark form fields as "dirty" on change and keep their values on form refresh if the content was modified on the server. Should work for HTML Area as well.

**Comment by sgauruseu** [comment]
I noticed that ` Save` button in the first tab gets enabled

**Comment by sgauruseu** [comment]
Case 2:
1. Open  a site with x-data(html area) in the first browser. Enable the x-data and fill in some text into the HTML Area field . Click on `Save` button.
![image](https://user-images.githubusercontent.com/3728712/79107528-301fdd00-7d7d-11ea-8ab0-05335711f732.png)

2. Go to the second browser  open the site and disable the X-data. Do not save the site .
3. Go to the first tab and update the text in htmlarea and click on `Save`
![image](https://user-images.githubusercontent.com/3728712/79107613-5c3b5e00-7d7d-11ea-9642-16d1781164b9.png)

4. Switch back to the first tab - text in HTML Area  is not updated and `Save` button is enabled.

![image](https://user-images.githubusercontent.com/3728712/79107686-868d1b80-7d7d-11ea-887f-883f862f86bf.png)
