### ISSUE TITLE
Displayname-script active until publish

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/app-contentstudio#1696]
The displayname-script is used only until first save, which often is causing issues for editors using a temporary title; its 'easy' to forget to change the title before publishing which is the critical point of not url-return. Maybe the display-name should change the name and url until first time published instead?

**Comment by sigdestad** [comment]
I see your point, and will investigate.

**Comment by alansemenov** [comment]
It does stop working after save. But if you reload the browser page (after save) then it starts working again. So it's a bug.

**Comment by sigdestad** [comment]
Hmm.. Not a bug, problem is that renaming a content will also change the structure of sub-items. We'll discuss it!

**Comment by alansemenov** [comment]
What you are saying is a totally different issue with changing path (and will be solved when we implement locking path for published items). 

What Runar describes here is a bug. Display name script works until save, stops working after save but after page refresh starts working again. There should be no difference in form behaviour immediately after save and when the content was just opened. Just try it.

**Comment by alansemenov** [comment]
We already stop change of path when changing display name after content is published. So it's a clear bug here that display name stops being changed by the display name script after save. Should always work.

**Comment by ashklianko** [comment]
Appeared to be issue with form data in lib-admin-ui:
https://github.com/enonic/lib-admin-ui/pull/1336
