### ISSUE TITLE
Save is enabled when a project with selected Project Access has been reopened after deleting the user

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1697]
1. Create new User.
2. Go to Settings and open new Project wizard, type a name, select the just created User in Custom Read access. Close the wizard.
3. Go to users-app an delete the user.
4. Reopen the project.

**BUG:** 
1)  Save button is enabled, Confirmation Dialog appears after clicking on close icon.
2) Private radio should be selected.
**Bug does not reproduce after refreshing Settings in browser**

![image](https://user-images.githubusercontent.com/3728712/78875274-4e709a80-7a56-11ea-898e-636a31fb6513.png)

**Comment by alansemenov** [comment]
It's true that Save button should be disabled but not "_Private radio should be selected_". No changes were made to the project itself, so we can't automatically change read access mode because some user was deleted. The project should remain in "Custom" mode but with empty selector.

**Comment by sgauruseu** [comment]
But when we open any project with Private read access - Save is disabled: 

![image](https://user-images.githubusercontent.com/3728712/78979113-d53f7900-7b23-11ea-8507-0f9ba2dc6274.png)

**Comment by ashklianko** [comment]
Will work with https://github.com/enonic/app-contentstudio/pull/1737

Noticed that after deleting that user backend itself returns afftected project with Private read access
