### ISSUE TITLE
Settings browse panel - errors after opening several filtered projects

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1701]
Case 1:
1. Click on 2 checkboxes and select two projects
2. Click on 'Show selections' circle.
3. Click on `Edit` button two tabs are opened - OK
![image](https://user-images.githubusercontent.com/3728712/78914845-b2fe1a80-7a93-11ea-9f5a-faf23a9bc545.png)

4. Click on `Settings` button

BUG - errors appears in console.

![image](https://user-images.githubusercontent.com/3728712/78914795-9b269680-7a93-11ea-85db-fb297f85a9f3.png)

Case 2:
1. Click on 2 checkboxes and select two projects
2. Click on 'Show selections' circle.
3. Click on `Edit` button two tabs are opened - OK
4. Click on Close icon and try to close wizard-tabs
BUG - errors appears in console.

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1254](https://github.com/enonic/lib-admin-ui/issues/1254) via [**ZenHub**](https://www.zenhub.com/)
