### ISSUE TITLE
Selection checkbox in the Content Grid toolbar remains irresponsive after adding content in empty grid

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1717]
1. Create new Project.
2. Navigate to  the just created project .
3. Add 2 folders.
4. Try to click on Selection controller checkbox

BUG: The checkbox is irresponive.

![image](https://user-images.githubusercontent.com/3728712/79334738-8a5da100-7f29-11ea-901e-bf1e59953386.png)

**The Checkbox gets workable after refreshing the panel in browser**

**Comment by alansemenov** [comment]
@ashklianko check if this is still relevant after the latest fixes.

**Comment by ashklianko** [comment]
ok!

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1291](https://github.com/enonic/lib-admin-ui/issues/1291) via [**ZenHub**](https://www.zenhub.com/)
