### ISSUE TITLE
Projects folder gets selected after a project is created

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1727]
1. Open Settings, no selections in the grid.
2. Create new Project, close the wizard.

BUG: Projects gets checked after creating the project and closing the wizard: 

![image](https://user-images.githubusercontent.com/3728712/79561665-6083b600-80b2-11ea-8e63-ba875f6baac5.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1250](https://github.com/enonic/lib-admin-ui/issues/1250) via [**ZenHub**](https://www.zenhub.com/)
