### ISSUE TITLE
Browse toolbar is not updated after deleting content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1746]
1. Select two folders then delete .
![image](https://user-images.githubusercontent.com/3728712/80082171-a92cea80-855c-11ea-8d09-373dac9892d4.png)

**Bug: Folders are deleted but toolbar is not updated:**  Edit, Delete. Duplicate  buttons should be disabled, 

![image](https://user-images.githubusercontent.com/3728712/80082293-cfeb2100-855c-11ea-8de1-2a3e28edf616.png)

![image](https://user-images.githubusercontent.com/3728712/80081952-4f2c2500-855c-11ea-8858-a22cb8d07c77.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1260](https://github.com/enonic/lib-admin-ui/issues/1260) via [**ZenHub**](https://www.zenhub.com/)
