### ISSUE TITLE
ContextSplitPanel freezes after Context panel is resized in docked mode

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1750]
1. Open Content Studio
2. Open Context panel on the right side
3. Expand width of the browser window until the Context panel switches to docked mode
4. Now try resizing the Context panel

The panel stays in "masked mode" after panel resizer is let go.

![image](https://user-images.githubusercontent.com/11612490/80114582-0ab47f80-8584-11ea-944c-6343f7c4935a.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1262](https://github.com/enonic/lib-admin-ui/issues/1262) via [**ZenHub**](https://www.zenhub.com/)
