### ISSUE TITLE
Better feedback when applications used by a site get stopped or uninstalled

### ISSUE THREAD

**Issue by espen42** [enonic/app-contentstudio#1763]
If a site has an app missing/stopped/incompatible, in CS edit mode the missing app(s) are marked in red, indicating that they're missing. This is the only indication of why the preview fails.

The preview panel only says "Can't render the preview, check the logs", but there is no error message in neither server log nor browser console (at least in several cases lately, XP 7.2.0, CS 2.3.2).

And if editing a different page (i.e. not at the site root level), you only get the failed preview panel message, with no information anywhere.

**Comment by alansemenov** [comment]
We should not force preview to fail when at least one app is missing, like we do now. The missing apps might not be relevant for rendering of preview at all.

**Comment by alansemenov** [comment]
In the case of the missing/stopped apps, change the **second** part of the message in the preview panel to the following: _Some applications required for rendering are not available_

![image](https://user-images.githubusercontent.com/11612490/108051415-288b2d80-704b-11eb-9c00-97823b07f285.png)
