### ISSUE TITLE
Maximise modal dialogs on mobile resolution

### ISSUE THREAD

**Issue by ashklianko** [enonic/app-contentstudio#1770]
@alansemenov commented on [Wed Mar 04 2020](https://github.com/enonic/lib-admin-ui/issues/1213)

In mobile mode all modal dialogs should fill up the entire available height (width is already ok) with small padding top/bottom (equal to small padding on the sides).

Now:
![image](https://user-images.githubusercontent.com/11612490/80691414-85275700-8ad0-11ea-834d-f5a4b0c7c970.png)

Should be:
![image](https://user-images.githubusercontent.com/11612490/80692009-4645d100-8ad1-11ea-9266-d4d38153df59.png)

Please test all of the modal dialogs.

**Comment by sigdestad** [comment]
Ups. This is the first time i see this design. The idea is that it should full the entire screen. As in NO padding at all. Can we fix it?

**Comment by alansemenov** [comment]
When we discussed it in PAB you said you wanted small paddings on all sides like on zenhub... but ok, let's make it fullscreen.

**Comment by sigdestad** [comment]
Hmm. Lets test what we have before changing it then

**Comment by ashklianko** [comment]
Updated
