### ISSUE TITLE
Tooltip for Selection Controller checkbox is not fully shown when Filter Panel is opened

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1772]
1. Open Filter Panel and move mouse cursor   to the checkbox : 

![image](https://user-images.githubusercontent.com/3728712/80945835-6937f400-8df5-11ea-9db2-79fd64ca8036.png)

**Comment by ashklianko** [comment]
Doesn't seem to reproduce @sgauruseu ?

**Comment by sgauruseu** [comment]
I did not reproduce it on my machine and on nightly server
