### ISSUE TITLE
Page Component View - component disappears from the tree after DnD

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1774]
1. Open new site wizard, select Features in apps, select main region.
2. Open Page Component View and insert 2 images: 

![image](https://user-images.githubusercontent.com/3728712/80967162-96e56300-8e1e-11ea-8af0-0463a40c788c.png)

3. Swap two components.

**BUG**: One component-item gets not visible in Page Component View .
 **Expected** : two components should be in the modal dialog

![image](https://user-images.githubusercontent.com/3728712/80967426-06f3e900-8e1f-11ea-9452-9165a60aad49.png)

**Second component item appears after saving the site.**

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1276](https://github.com/enonic/lib-admin-ui/issues/1276) via [**ZenHub**](https://www.zenhub.com/)
