### ISSUE TITLE
Permissions are not updated in Edit Permissions Dialog and Access Widget after deleting an user

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1783]
1. Create a folder and create an user.
2. Select a folder , open Edit Permissions Dialog (Details Panel , access widget)
3. Add `Can Publish` permission for the user 

![image](https://user-images.githubusercontent.com/3728712/81188137-a4851f00-8fbd-11ea-925c-085b9f69eefa.png)

4. Go to Users-app and delete the user.
5. Go to Content Browse Panel and reopen Edit Permissions dialog

BUG:   Permissions are not updated in Edit Permissions Dialog and Access Widget - deleted user remains in dialog and widget

**Comment by ashklianko** [comment]
Principal events are not handled in CS now, need https://github.com/enonic/lib-admin-ui/issues/1221 to avoid code duplication
