### ISSUE TITLE
Browse Panel - toolbar is not updated after a content has been unhighlighted

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1813]
1. Click on a row - the content is highlighted (OK)
2. Click on the row again 

BUG - grid  toolbar is not updated:

![image](https://user-images.githubusercontent.com/3728712/81730770-b1f74900-9496-11ea-897b-1294fe3d9d1e.png)

**Comment by ashklianko** [comment]
Will be fixed in https://github.com/enonic/lib-admin-ui/pull/1283 for 3.0

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1285](https://github.com/enonic/lib-admin-ui/issues/1285) via [**ZenHub**](https://www.zenhub.com/)
