### ISSUE TITLE
Error after clicking on Hide selection button in filtered grid

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1815]
1. Open Filter Panel and click on City checkbox (Features content)
2. Select 2 cities: 

![image](https://user-images.githubusercontent.com/3728712/81800631-cc273a80-951b-11ea-88ea-497b2333e30a.png)

3. Click on `Show Selection`
4. Click on `Hide Selection`, Filter Panel closes (ok)
5. Click on `Select all rows` or `Show selection` 
BUG:  SelectionController checkbox is irresponsive  and error appears after clicking on `Show Selection`

![image](https://user-images.githubusercontent.com/3728712/81800533-a437d700-951b-11ea-9dd2-f3e755335dff.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1287](https://github.com/enonic/lib-admin-ui/issues/1287) via [**ZenHub**](https://www.zenhub.com/)
