### ISSUE TITLE
Error message appears after saving a fragment

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#183]
1. Open new site wizard, select Features, type a name 
2. Open Page Component View and insert a text-component.
3. select `Save as Fragment` menu item 

![image](https://user-images.githubusercontent.com/3728712/52938919-f2d7df00-3373-11e9-9cd8-99b0e05da2d3.png)

Bug: error notification message appears, live editor closes, impossible to `detach from fragment` the component .

![image](https://user-images.githubusercontent.com/3728712/52939055-421e0f80-3374-11e9-89d1-dda884980ae2.png)

**Comment by alansemenov** [comment]
Ok, I got the error now.

**Comment by alansemenov** [comment]
@sgauruseu please check if this one is still valid. I couldn't reproduce it.
