### ISSUE TITLE
Project grid is not refreshed after adding a project in the filtered grid

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1830]
1. Select Default project , click on Show Selection button
2. Click on New button and add new project
![image](https://user-images.githubusercontent.com/3728712/82323207-60901200-99e0-11ea-90ae-ba754db2a455.png)

3. Selection Controller is partially selected(OK)  uncheck the checbox:

BUG: New project is not present in the browse panel

![image](https://user-images.githubusercontent.com/3728712/82323525-dac09680-99e0-11ea-87a8-30fb55493772.png)

New project appears after clicking on the refresh icon

**Comment by alansemenov** [comment]
@ashklianko If it's too much work fixing this (and https://github.com/enonic/app-contentstudio/issues/1828) we might consider hiding Show Selection button in the Project grid. It's important in Content grid, but not here.
