### ISSUE TITLE
Project Wizard form scrolled down after icon upload

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#1886]
1. Open an existing project
2. Click the icon thumbnail and select an icon file
3. After the icon is uploaded, the form will be scrolled down

**Comment by ashklianko** [comment]
Couldn't reproduce neither locally on Chrome and FF, nor on Browserstack

**Comment by alansemenov** [comment]
@ashklianko It doesn't happen when the browser window is high enough, but in 1200x700 (WxH) it happens every time. Can you try with the same size?
