### ISSUE TITLE
Incorrect handling of  Enter key event in NewContentDialog and InstallAppDialog

### ISSUE THREAD

**Issue by jsi** [enonic/app-contentstudio#19]
@sgauruseu commented on [Mon Sep 17 2018](https://github.com/enonic/app-contentstudio-old/issues/425)

1. Do 'Log out' , then do 'log in'
2. Go to Content Studio
3. Press the New an open   NewContentDialog
4. press `Enter`

Bug: `Launcher panel`  appears, when `Enter` has been pressed
Press `Esc` key,  `Launcher panel` closes, but the modal dialog remains on the grid-page

![image](https://user-images.githubusercontent.com/3728712/45616572-88dfa480-ba78-11e8-8043-98075b5debf4.png)

---

@alansemenov commented on [Wed Sep 19 2018](https://github.com/enonic/app-contentstudio-old/issues/425#issuecomment-422718833)

@sgauruseu I cannot reproduce this

---

@ashklianko commented on [Wed Sep 19 2018](https://github.com/enonic/app-contentstudio-old/issues/425#issuecomment-422719009)

I'll try with @sgauruseu 

---

@sgauruseu commented on [Wed Sep 19 2018](https://github.com/enonic/app-contentstudio-old/issues/425#issuecomment-422840765)

This bug reproducing, when dialog is opened and  focus is not in the Search Input.
So, this bug does not always reproduce,.
I think, this issue similar to  
https://github.com/enonic/app-contentstudio/issues/427 

---

@sgauruseu commented on [Wed Sep 19 2018](https://github.com/enonic/app-contentstudio-old/issues/425#issuecomment-422841591)

focus is not in Search Input of the dialog, when content-grid was refreshed before,

**Comment by ashklianko** [comment]
I believe this will be fixed after https://github.com/enonic/app-contentstudio/issues/154 is done
