### ISSUE TITLE
Error appears after creating Request Publishing assigned to user that has no required permissions

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1919]
1. Create new user with `Admin Console Login` role.
2. Select `Features` and create  new `Request Publishing`. Assign  just created user to the request.
3. Select `Features` and click on `Publish Tree`
4. Unpublish Features. - Request Publishing... menu gets enabled now
5. Click on Request Publishing menu item again .
6. Fill in changes and click on Create 

BUG: Dialog does not close, error appears in console : 

![image](https://user-images.githubusercontent.com/3728712/83874372-057b5080-a73e-11ea-9832-37de15e45e0b.png)

**Comment by alansemenov** [comment]
@sgauruseu this should've been fixed, please check
