### ISSUE TITLE
User with author role - Last stage in publishing workflow for Project gives user option to "Publish Now"

### ISSUE THREAD

**Issue by jsi** [enonic/app-contentstudio#1920]
Logging in to a project with a user that has Author rights, means I can create and edit content, but not publish it.  So, when I have created a content, I need to ask for it to be published.  In the Wizard that appears, in the last stage, the box, has a button to "Publish Now", in the bottom right:

<img width="658" alt="Screenshot 2020-06-05 16 26 35" src="https://user-images.githubusercontent.com/477453/83888605-60b34000-a74a-11ea-96a6-9fe74ffc615c.png">

As I went from step 2 to 3, a message appeared at the bottom of the screen, saying the publish request had been created, so the button should just say something like "Ok", "Finish" or "Close":

<img width="912" alt="Screenshot 2020-06-05 16 32 02" src="https://user-images.githubusercontent.com/477453/83888816-a3751800-a74a-11ea-918b-9d3937b3ae0d.png">

If I do press the button, an error appears:

<img width="875" alt="Screenshot 2020-06-05 16 30 12" src="https://user-images.githubusercontent.com/477453/83888902-c1427d00-a74a-11ea-967e-1cb9f62c539e.png">

... so it is not possible for the user to do the publishing, but the button is wrong.

**Comment by sgauruseu** [comment]
the same issue with Scheduling: 

![image](https://user-images.githubusercontent.com/3728712/84015486-93e11380-a984-11ea-9c10-71feca664d6c.png)
