### ISSUE TITLE
Preview button and Show Component View remain visible after the site has been reset  in another browser window

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1927]
1. Open existing site(controller is selected) in FF.
2. Open the site in chrome, open Page Component View and click on Reset menu item  

![image](https://user-images.githubusercontent.com/3728712/84018427-b70dc200-a988-11ea-979f-9cc7dc8970bc.png)

3. Go to the first browser window.

Bug: the page is reset, but Show Page Component and Preview buttons remain visible:

![image](https://user-images.githubusercontent.com/3728712/84018313-8fb6f500-a988-11ea-8e00-bc9d48d60ad7.png)

**Comment by ashklianko** [comment]
Fixed in https://github.com/enonic/app-contentstudio/issues/3188
