### ISSUE TITLE
Compare Versions dialog - Revert button should be disabled for users with no modify permissions

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1934]
Case 1:
1. Create an user with `Admin Console login` role
2. Create a project , select the user as Contributor, 
3. Create a folder in the project, update a language (create several version)
4. Log in with user-contributor, select the folder open Versions
5. Click on 'compare versions' icon

BUG: 
**Expected:  Revert button should be disabled  in the modal dialog**
**Actual:     Revert button is enabled in the modal dialog**  : 

![image](https://user-images.githubusercontent.com/3728712/84037729-a751a600-a9a7-11ea-8c8b-e2a66a4d6fd4.png)

Case 2: 
- login with user that is Contributor .
- open existing folder.
- Open Versions Panel in the wizard
- expand a version and click on Revert button
**BUG:  Revert button should be disabled.**

Actual - the button is enabled, error appears after clicking on the button 
 
![image](https://user-images.githubusercontent.com/3728712/84042605-f569a800-a9ad-11ea-833c-e1e1b855362e.png)

**Comment by sigdestad** [comment]
No, compare versions should not be disabled - Contributors should have access to almost everything, except "create" content. And this is again controlled by permissions.

Revert a version should however be disabled if the user does not have write permissions, but this is not related to roles. Remember, default project is still suppose to work like it has always done (even without any roles present)
