### ISSUE TITLE
Updated project is not refreshed in filtered grid 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#1954]
1. Expand Projects and click on `Default` checkbox.
2. Click on `Show  Selection` button.

![image](https://user-images.githubusercontent.com/3728712/84511949-f5301c00-accf-11ea-89c0-222cba105d04.png)

3. Click on `Edit` button , open the project.
4. Fill in the description input, click on Save button and close the wizard.

![image](https://user-images.githubusercontent.com/3728712/84512347-843d3400-acd0-11ea-89f5-c4b6bc590ee1.png)

**BUG:** 
1. Notification message is appeared (project is modified), but description is not updated in the grid.
2.  Reopen this project again -  description input is empty

**Comment by ashklianko** [comment]
Fixed in https://github.com/enonic/app-contentstudio/pull/2419
