### ISSUE TITLE
Image Inspection Panel - Inputs are not displayed on the  panel

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#197]
Case 1
1. Open new site wizard (window-size=1920,1100)
2. Type a name, select features , select `main region`
3. Open Page Component View and insert an image

**Bug:  Image Inspect Panel is loaded , but `Caption` text area is not present** 

![image](https://user-images.githubusercontent.com/3728712/53077948-395c4380-3504-11e9-97b2-38fb4ea8690c.png)

Caption is present on the panel when browser page has been maximized, but the text area disappears when  you decrease the browser page 

Case 2:
 Open Features, insert a layout .
Bug: Inspection panel does not contains the new input

![image](https://user-images.githubusercontent.com/3728712/53333193-41522400-3906-11e9-8bdf-e105fa9040cf.png)

**Comment by ashklianko** [comment]
Will be fixed in https://github.com/enonic/app-contentstudio/pull/221

**Comment by ashklianko** [comment]
@sgauruseu please check now

**Comment by sgauruseu** [comment]
There are no problems with occurrences of inputs now
