### ISSUE TITLE
Backslash is allowed in project identifier field

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2009]
1. Open new project wizard, fill in the name input. Select Public access 
2. Add backslash in identifier input.
3. Click on Save button.

BUG: 

![image](https://user-images.githubusercontent.com/3728712/86122266-3140ea80-bae0-11ea-8937-535e6b3b811b.png)

**Comment by alansemenov** [comment]
It should not be allowed in this field
