### ISSUE TITLE
Version History is missing publish from/to dates

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2014]
1. If `modified` date is before `publishFrom` date,  show `publishFrom` instead of `modified` inside the "Published version" box.
2. Find out why last published version disappears after unpublishing content
3. Replace the icon for unpublished version
4. For expired publish content show when content expired (`publishTo`)

**Comment by alansemenov** [comment]
> Find out why last published version disappears after unpublishing content

https://github.com/enonic/xp/issues/8314

**Comment by alansemenov** [comment]
> 3. Replace the icon for unpublished version

This is not possible at the moment because there's no "unpublished version". We simply show current state of the item for the top version in the widget. This is wrong but we cannot do more until we start creating a version for "unpublishing" action (see proposal in enonic/xp#8314). 

In this screenshot the actual unpublishing happened in between the two versions but there's no way to figure this out based on data received from `getVersionsForView` API:

![image](https://user-images.githubusercontent.com/11612490/91715641-53adbd80-eb8e-11ea-88d2-769e7f6d6116.png)

**Comment by sigdestad** [comment]
What data do we plan to save in this version (and the following?) that indicates it was unpublished? Do we remove publish-from/to?

**Comment by alansemenov** [comment]
No idea - this is TBD in enonic/xp#8314. As of now, all the valuable data seems to disappear after the item is unpublished

**Comment by alansemenov** [comment]
1 and 4 are done
