### ISSUE TITLE
Console error on resize of HTML Area

### ISSUE THREAD

**Issue by runarmyklebust** [enonic/app-contentstudio#2015]
In content-studio 3.0.0, the resizing of html-area fails, staying small for large texts, making it unusable for editing. 

![Screenshot 2020-06-30 at 19 14 34](https://user-images.githubusercontent.com/356026/86156298-04073300-bb06-11ea-9d26-59c1d844d462.png)

This happens both in Chrome and IE, console yields this error:

![Screenshot 2020-06-30 at 19 01 39](https://user-images.githubusercontent.com/356026/86156174-d3bf9480-bb05-11ea-9a2b-a67910a5ba36.png)

Worked perfect again after rollback to 2.3.2

![image](https://user-images.githubusercontent.com/356026/86157279-71679380-bb07-11ea-9b9a-c46036b0db0e.png)

**Comment by runarmyklebust** [comment]
Any news on this, I expect this will affect all windows-users rendering v3.0.0 and v3.0.1 not usable?

**Comment by runarmyklebust** [comment]
ping

**Comment by alansemenov** [comment]
We are prioritising this for the next sprint and next release of CS

**Comment by alansemenov** [comment]
We are prioritising this for the next sprint and next release of CS

**Comment by alansemenov** [comment]
@runarmyklebust We only managed to reproduce this on IE (under windows). In Chrome it seems to work fine. What version of Chrome are you on?
