### ISSUE TITLE
Add ContentSummary.isInherited

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2022]
Add new boolean field `inherited` to `ContentSummaryJson`, `ContentSummary`, `ContentSummaryBuilder` and other classes managing ContentSummary. We are not receiving this field from the backend yet, so stub it with a random value. For a new content `inherited` will always be `false`.

**Comment by ashklianko** [comment]
I'd say that property name 'inherited' would be better since we going to use methods like 'isInherited()'

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1368](https://github.com/enonic/lib-admin-ui/issues/1368) via [**ZenHub**](https://www.zenhub.com/)
