### ISSUE TITLE
Toolbar actions for inherited content items

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2040]
When inherited item is selected in the grid, the only enabled actions in the toolbar should be: New, Edit, Duplicate and Preview. This of course should be on top of currently existing validation checks (like if current user only has read permissions for an item then Edit should also be disabled, or if the item doesn't support preview then Preview should be disabled etc.)

![image](https://user-images.githubusercontent.com/11612490/86468343-8dea1280-bd37-11ea-9027-5013cba4a20b.png)

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/commit/72d0daaacdde4ab86fe542a3c065e92101b94650
