### ISSUE TITLE
Switch Content Wizard to the readonly mode for inherited item

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2041]
For an inherited item the Content Wizard should open in the readonly mode (we already support it - see `ContentWizardPanel.setModifyPermissions()`).

The only difference to the regular read-only mode is the toolbar: only two actions should be available there, **Edit** and **Preview**. If user doesn't have write permissions for the item, then of course **Edit** will be disabled, and if there's no preview available then "**Preview**" will be disabled. 

![image](https://user-images.githubusercontent.com/11612490/86469350-80358c80-bd39-11ea-91a4-711c6f11fe6d.png)

**Comment by ashklianko** [comment]
Some updates after latest meeting with Layers team:

1. No readonly mode on opening when inherited content is open for edit, start modifying content in wizard immediately (if you have permissions)
2. Small diffs for when inherited content has or hasn't same language as current project:
 
A) If current project has same language as inherited content: 
1. Edit button in ContentTreeGrid in BrowsePanel is named ... 'Edit'!
2. After pressing Edit we open wizard for Edit, no readonly mode 
3. Create local copy only  after save
4. After save show notification 'Local copy was created'

B) Current project has language different from inherited content
1. Edit button in ContentTreeGrid in BrowsePanel is named 'Translate'
2. After pressing Edit we open wizard for Edit, no readonly mode 
3. Set language field in wizard to current project's language
4. Show notification 'Language was set to <language>'
5. Create local only after save
6. After save show notification 'Local copy was created'
