### ISSUE TITLE
Unlock inherited item on Edit

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2042]
When Edit is clicked in the Content Wizard's toolbar for an inherited item, do the following:
1. Switch the Content Wizard into "edit" mode, with regular actions in the toolbar, editable fields etc.
2. Set `inherited` property in the data model to _false_.
3. Set language of the content item to language of the current project (if it's set).

The changes should not be sent to the server until user clicks Save.

**Comment by ashklianko** [comment]
We can probably set inherited to 'false' implicitly on backend when updating for first time content that is inherited

**Comment by sigdestad** [comment]
Indeed, similar to how we set "in progress" when a user starts editing a "Ready" content i assume?

**Comment by ashklianko** [comment]
Not exactly: I meant we don't need to send 'inherited' param in content update request at all because backend is supposed to save updated content with inherited set to 'false' anyway. No need to do it same as with workflow state on frontend.

**Comment by sigdestad** [comment]
Ok, I thought it was done this way. But agreed - any inherited item getting modified locally -> inherited=false, and should be handled by Content API automatically.
