### ISSUE TITLE
In mobile resolution “Apply” button is covered by the action buttons

### ISSUE THREAD

**Issue by espen42** [enonic/app-contentstudio#2044]
When using a narrow browser window on desktop (working on a split screen can be nice), messages on the bottom of the screen such as "mark as ready" appear in front of the "Apply" button (in the config panel that'a usually on the right but now on entire screen). This makes it unclickable (or actually, clickable in a height of 1-2 pixels above the message...).

![image](https://user-images.githubusercontent.com/5279775/86472943-461bb900-bd40-11ea-85a8-b26a0d92c5e8.png)

OSX
CS 3
XP 7.3
Window width: ~610 px
Apply button

**Comment by alansemenov** [comment]
Let's place Apply above the status button in mobile resolution
