### ISSUE TITLE
Issue Details dialog blinks after items in an issue have been changed

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2063]
1. Open Task Details dialog or Request details dialog.
2. Add new item (remove an item)

BUG: Dialog blinks 4 times after the updating.

![image](https://user-images.githubusercontent.com/3728712/87401894-71659a00-c5c3-11ea-90d8-de5f5aeedce1.png)

**Comment by ashklianko** [comment]
ListIssuesRequest - is invoked up to 10 -14 times on adding/removing item!!!
