### ISSUE TITLE
Implement modal dialog with layer-specific item details in the Content Wizard

### ISSUE THREAD

**Issue by ashklianko** [enonic/app-contentstudio#2069]
Replace project name in content wizard toolbar with tree selector showing items with same id in other projects #2069

**Comment by alansemenov** [comment]
We decided to drop this for now since users might confuse it with the context switch. They should use the Layers widget for seeing item status in other layers. We might add a shortcut icon which will toggle the Layers widget on and off to make it more accessible, but this is a different task.
