### ISSUE TITLE
Subproject wizard - issues with 'Copy'  buttons

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2076]
Case 1: - copy language button remains enabled after copying roles from parent project

1. Select `Default` project , open wizard for  new subproject.
2. Fill in the name input, select Private access mode.
3. Select an item in Roles combobox   - `Copy from parent` gets enabled - OK. Save the subproject.
4. Click on `Copy roles from parent`

**BUGS:** 1 ) `Copy from parent` button is enabled.  2) `Save` button should be enabled after copying roles from parent
Expected - `Copy from parent` button should be disabled, Save button should be enabled.
 
![image](https://user-images.githubusercontent.com/3728712/87914912-1b3c9f00-ca7a-11ea-8c4b-6d6b0fd669aa.png)

Case 2: 
1. Select Default and  save new subproject(Public access mode). Close the wizard
2. Reopen the subproject and click on Copy access mode from parent

BUG: Confirmation dialog appears and notification about copied mode appears at the same time 

![image](https://user-images.githubusercontent.com/3728712/87777973-218d0a00-c833-11ea-88de-3411c6ff385d.png)

Case 3: 
1. Select Default open wizard for new subproject.
2. Select an item in roles selector.
3. Button `Copy roles from parent` gets enabled.
4. Click on `Copy roles from parent` - the role is removed 

![image](https://user-images.githubusercontent.com/3728712/88682868-d957cc80-d0fb-11ea-9ba7-45e2346929da.png)

**BUG**:  `Copy roles from parent` remains enabled
**Expected** - `Copy roles from parent` should be disabled.

**Comment by ashklianko** [comment]
Regarding case 3: not a bug, copying value of a parent, no matter if it has items or not
