### ISSUE TITLE
Project selector button should not be clickable if current user has access to only one project

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2089]
1. Create a project and add an user-contributor for this project.
2. Login with the user 
3. Click on  Project Viewer button 

BUG- Select project dialog should not appear after clicking on the button. 
Expected - this button should be disabled.

![image](https://user-images.githubusercontent.com/3728712/88540528-c968bb80-d01b-11ea-8d89-55b09fbdb853.png)

**Comment by alansemenov** [comment]
This is not about roles at all. Whether the button is clickable or not should be determined by whether current user can switch between projects. If he has access to just one project, then the button should be disabled.
