### ISSUE TITLE
Reset context after current project or layer is deleted

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2091]
Login with `su/password`

1. Add a subproject to existing project.
2. Switch to  content mode and select the subproject's context.
![image](https://user-images.githubusercontent.com/3728712/88552169-70edea00-d02c-11ea-9cc9-e57d626eb517.png)

3. Switch to settings mode and delete the subproject.
4. Switch to content mode.

![image](https://user-images.githubusercontent.com/3728712/88552319-a09cf200-d02c-11ea-82c9-7c348b39d3a4.png)

Expected : parent project's context should be loaded;
Actual :   `Default` context is loaded

**Comment by alansemenov** [comment]
The way it should work is that current context should be reset and user should get a "Select context" modal dialog, as if he just opened the Content Studio.
