### ISSUE TITLE
Selection Toggler remains visible after deleting project with subprojects

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2101]
1. Create 2 parent projects with subprojects.
2. Select 2 subproject and one parent project. 
![image](https://user-images.githubusercontent.com/3728712/88662257-6130dd00-d0e2-11ea-821f-b7011304cdfc.png)

3. Click on Delete button and confirm the deleting.
BUG: Selection Toggler remains visible,  one project is still selected.
Expected -  3 selected projects  are removed, so no selections should be in the toggler

![image](https://user-images.githubusercontent.com/3728712/88662700-00ee6b00-d0e3-11ea-92a7-ef48593c9382.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1404](https://github.com/enonic/lib-admin-ui/issues/1404) via [**ZenHub**](https://www.zenhub.com/)
