### ISSUE TITLE
Subproject context - 'Mark as Ready' menu item should be enabled in publish menu

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2119]
1. Create new subproject in Deafult.
2. Add a folder in Default
3. Switch to sub-context
4. Select the just created folder 

**BUG**:  1) Default action should be `Mark as Ready` 
          2) Mark as Ready menu item should be enabled

![image](https://user-images.githubusercontent.com/3728712/88913110-05449080-d269-11ea-91d5-29603362e545.png)

**Open this folder** :   `Mark as ready` is enabled
![image](https://user-images.githubusercontent.com/3728712/88913218-286f4000-d269-11ea-9104-0967a1c6acaf.png)

**Comment by alansemenov** [comment]
Content should be localised first, before it can be marked as ready. If the content is not ready in the parent layer, publishing shouldn't be possible.
