### ISSUE TITLE
Localize button should be displayed in browse toolbar after selecting  a content in subproject 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2144]
Case 1:
1. Create a subproject in `Default` project. Set Norsk(no) language in the subproject
2. Create a folder in `Default`
3. Switch to the subproject-context, select the folder.

BUG: `Localize` button shouldbe present in the browse toolbar: 

![image](https://user-images.githubusercontent.com/3728712/89301674-9f924300-d672-11ea-8750-48d166c9aea3.png)

**===============Case 1 is fixed now.==============**

**Case 2:** 
1. Create a parent project then add subproject (do not select language in the subproject)
2. Add a site in the parent project
3. Open subproject's context, select the site

BUG - Localize button is not displayed on the toolbar

![image](https://user-images.githubusercontent.com/3728712/90237775-7c635280-de2d-11ea-8fec-55476a97282d.png)

**Comment by alansemenov** [comment]
@ashklianko This seems to work correctly for some items but not for others, even within the same layer. For those items where it shows Edit instead of Localise you will also not get a notification about language set from parent when you open the Wizard.

**Comment by sigdestad** [comment]
May be related to missing language in current inheritance implementation?

**Comment by sgauruseu** [comment]
But Localize button appears after adding  the second subproject:

![image](https://user-images.githubusercontent.com/3728712/90000545-f910f800-dc98-11ea-94a6-338a1334ad3b.png)

**Comment by ashklianko** [comment]
Seems to work fine after commit https://github.com/enonic/xp/commit/57e48e329ba8b9ced8cdc5f21c929716250bfb42
@sgauruseu could you please verify?

**Comment by sgauruseu** [comment]
New issue : 
- click on Localize on toolbar - new tab with the wizard is opened

![image](https://user-images.githubusercontent.com/3728712/90024354-70588300-dcbd-11ea-823b-5ab113f0b8d4.png)

Save button is enabled, do nt save the changes - click on close icon - Confirmation dialog does not appear, 
**Expected** -  Confirmation dialog should appear after trying to close the tab

**Comment by alansemenov** [comment]
> Actual behaviour : Save button is enabled, do not save the changes - click on close icon - Confirmation dialog does not appear,
> Expected - Confirmation dialog should appear after trying to close the tab

This behaviour is correct. User hasn't made any changes, so we shouldn't show the confirmation.

The original issue is fixed as well.
