### ISSUE TITLE
Layers widget is not refreshed after selected content was deleted/updated in a descendant project/layer

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2145]
1. Add a subproject(Nors(no) language) in Default project.
2. Create a folder in the parent (Default) project.
3. Switch to subproject's context and select the folder, open `Layers` widget:

![image](https://user-images.githubusercontent.com/3728712/89385966-18dc7500-d709-11ea-9a98-2e55878f4487.png)

4. Click on `Open` button in `Default item-view` - folder from default context is loaded.
5. Click on Delete button in the folder-wizard, confirm the deleting

BUG:   Layers widget  is not updated, default item view should not be displayed after deleting the folder.

Click on `Open` button - blank page with notification message appears : 

![image](https://user-images.githubusercontent.com/3728712/89386433-bb94f380-d709-11ea-8e8e-0807f626acac.png)

**Comment by alansemenov** [comment]
@ashklianko Refresh on update/delete of any item with the same id
