### ISSUE TITLE
Apply button in the Inspect panel shouldn't save content when no changes have been made

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2151]
1. Open a published(ready to publish) site with a text component. Open Page Component View, click on the text component: 
![image](https://user-images.githubusercontent.com/3728712/89524429-3c78eb80-d7ed-11ea-8aa5-28eac39d97ca.png)

2.  InspectionsPanel is opened, click on Apply button:
![image](https://user-images.githubusercontent.com/3728712/89524346-10f60100-d7ed-11ea-8dae-bd5826dd0656.png)

**Bug**: 
1) Incorrect notification message appears after  clicking on Apply  button :`Item is saved`
2) New content version is created.
3) Published content gets `modified` (work in progress)

**Expected**: 
-This message should appear :  `No changes to apply`
- New version should not be created.
- content;s status should not be changed

**Comment by ashklianko** [comment]
Issue not reproduced (we check for changes before saving), I've made only small refactoring. However some improvements could be made: apply button should be enabled only when there are changed in inspected component. That will take time to implement so only refactoring for now. @sgauruseu please confirm that not reproduced
