### ISSUE TITLE
Use layer icon in the Layers widget

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2154]
The logic of displaying icons in the Layers widget is now like this:
1) If content is localised, we show language icon based on content language
2) If content is not localised or if no language is set for the content, we show icon of the content type 
 
Change to this:
1) Always show language icon based on **default language of the layer**
2) If no language is set in the layer, show [default icon of the layer](https://github.com/enonic/app-contentstudio/issues/2153)
3) Language of the content (if set) should be shown in brackets after layer name (where we now show default language of the layer)

**Comment by sigdestad** [comment]
Hmm, not sure about #3 there. It should still show layer lang I think.
