### ISSUE TITLE
Generate release notes automatically

### ISSUE THREAD

**Issue by jsi** [enonic/app-contentstudio#2165]
I have added publishing of builds to Content Studio.  It is working in the basic way for snapshots, but should there be something more?  Please verify my changes: https://github.com/enonic/app-contentstudio/commit/4687a3410949f79c4467fc11cdfaeec0d31186a3

**Comment by jsi** [comment]
I am adding the exact same code to 3.0 branch, so the new 3.0.1 release can be built with Actions.

**Comment by rymsha** [comment]
`PUBLISH=${{ github.ref == 'refs/heads/master' || contains(github.ref, 'refs/heads/7.') }}`
3.x branch won't get published due to this code

**Comment by jsi** [comment]
Will it if I change "7." to "3.", even if I only change it on master?

**Comment by rymsha** [comment]
No. You need to have this code in all branches you want "publish" to work in.

**Comment by jsi** [comment]
I found that out by trial and error on Friday, when I released 3.0.1.
Having the code in master only didn't work, so I added the publishing code on the 3.0 branch also.  This worked.  However, no tags were set by the script, so I set the v3.0.1 tag manually.  Probably my work need a lot more to it.

**Comment by rymsha** [comment]
Publishing and releasing is not the same
Here is how it is done in XP
https://github.com/enonic/xp/blob/master/.github/workflows/gradle.yml#L66
(And a lot more around it to actually generate changelog)
