### ISSUE TITLE
ComboBox input types are very slow/freeze when searching in field

### ISSUE THREAD

**Issue by nerdkid93** [enonic/app-contentstudio#2175]
There's a bug with the `<input type="ComboBox />` form element in Content Studio v3.0.0. When I try searching in the ComboBox search field, the UI freezes for a few seconds, and the drop down shows incorrect search results:
![Screenshot from 2020-08-13 10-18-36](https://user-images.githubusercontent.com/6289786/90145865-63d03b00-dd4e-11ea-9418-fe2f618d5e31.png)

This was the content-type XML schema (there's a copy of this in the ZIP file below):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<content-type xmlns="urn:enonic:xp:model:1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:enonic:xp:model:1.0 https://raw.githubusercontent.com/enonic/xp/master/modules/core/core-api/src/main/resources/META-INF/xsd/model.xsd">
	<display-name>Test</display-name>
	<super-type>base:structured</super-type>
	<form>
		<input type="ComboBox" name="combo">
			<label>ComboBox freezes when searching</label>
			<config>
				<option value="1">1</option>
				<option value="2">2</option>
				<option value="3">3</option>
				<option value="4">4</option>
				<option value="5">5</option>
				<option value="6">6</option>
				<option value="7">7</option>
				<option value="8">8</option>
				<option value="9">9</option>
				<option value="10">10</option>
				<option value="11">11</option>
				<option value="12">12</option>
				<option value="13">13</option>
				<option value="14">14</option>
				<option value="15">15</option>
				<option value="16">16</option>
				<option value="17">17</option>
				<option value="18">18</option>
				<option value="19">19</option>
				<option value="20">20</option>
			</config>
		</input>
	</form>
</content-type>
```

This ZIP contains an MP4 video of the bug in action, as well as the Chrome Performance profile recorded during the screen recording, and a direct copy of the content-type XML schema file for the item I was trying to edit in the recording: [combobox-bug-in-content-studio-v3.0.0.zip](https://github.com/enonic/app-contentstudio/files/5069544/combobox-bug-in-content-studio-v3.0.0.zip)

**Comment by alansemenov** [comment]
Hi @nerdkid93 

This one is tricky. We've had two complaints for the same issue over the last year. Here's the [bug](https://github.com/enonic/app-contentstudio/issues/1760) we registered.

Both times it was very specific to the machines of those reporting the problem, and none of our developers ever managed to reproduce it to be able to fix. Both times the problem disappeared after clearing the browser cache, so apparently something doesn't get cleaned up. It also seems to disappear when you have the caching turned off ("Disable cache" checkbox in the Chrome dev tools).

Could you try opening the same content in a new incognito browser window and see if the problem persists?

I've also tried something here locally, which might solve the problem. Uninstall Content Studio you have now, deploy [this version](https://github.com/enonic/app-contentstudio/files/5075510/contentstudio-3.0.1.jar.zip) to your local XP_HOME/deploy folder and see if it gets better. Ideally, clear the cache before you start testing the new version, to make sure there are no leftovers from the previous one.

**Comment by nerdkid93** [comment]
I'll try the new local version of the Content Studio later today, but I cleared my cache, and opened the app in Chrome Incognito, and the issue persisted:
![Screenshot from 2020-08-18 09-57-14](https://user-images.githubusercontent.com/6289786/90523211-9d33ec80-e13a-11ea-952b-c048d21b9928.png)

**Comment by alansemenov** [comment]
@nerdkid93 I've discovered another issue that might very well be the reason for the recursion. Can you try deploying [this new version](https://github.com/enonic/app-contentstudio/files/5096238/contentstudio-3.0.2-SNAPSHOT.jar.zip) of Content Studio and see if that helps?
