### ISSUE TITLE
Layers widget should always be available

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-contentstudio#2183]
Currently CS only displays the widget if we are in a layer context. NB! If in a project, and the project does not have any layers (child project) just show, "No layers available in this project"

**Comment by alansemenov** [comment]
> NB! If in a project, and the project does not have any layers (child project) just show, "No layers available in this project"

@sigdestad What if it does have layers? As of now we don't show anything below the current level. So if we are to show child layers, then we need to implement that first.

**Comment by alansemenov** [comment]
https://github.com/enonic/app-contentstudio/issues/2197
