### ISSUE TITLE
Show the number of descendant layers in the Layers widget

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2194]
If selected item exists in descendant layers (below the current one), extend the arrow underneath the current layer box, with caption over saying "_More (X)_" where _X_ is the total number of descendant layers where this item exists. The caption should not be clickable.

![image](https://user-images.githubusercontent.com/11612490/90509681-06772800-e15a-11ea-9cb9-3064188e7af6.png)

**Comment by ashklianko** [comment]
Will start after #2195 is merged
