### ISSUE TITLE
Update inherit settings of the content when toggling between inherited and non-inherited sorting options

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2218]
If user switches sorting settings of a content item from "Inherited" to one of the regular options, or the other way around, we should do the following:
1. Toggle header subtitle (see https://github.com/enonic/app-contentstudio/issues/2215)
2. Enable or disable the list of child items
3. Enable the Save button  

Once the Save button is clicked, we should not only save the new sorting but also update inherit settings of the item via [API](https://github.com/enonic/xp/issues/8303) by adding or removing SORT option.

**Comment by ashklianko** [comment]
Pushed into https://github.com/enonic/app-contentstudio/pull/2269
