### ISSUE TITLE
Endless spinner in site-wizard after inserting an image in Live Edit

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#228]
**Case 1:**
1. Open new site-wizard type a name , select Features, select `main region` in controller selector
2. Insert 3-column layout (Page component View)
3. Save and **CLOSE** the site.
4. Open the site and open Page component View . Insert an image in left-region

BUG: Endless spinner appears in live-edit after inserting the image (There are no errors in console)

![image](https://user-images.githubusercontent.com/3728712/53409902-4d57e780-39d3-11e9-8ea9-eb126b4b9c32.png)

**Case 2**

1. Open `SuperHero`, open Page Component View
2. Click on SearchForm and select `insert image` menu item

BUG: Endless spinner appears in live-edit after inserting the image

![image](https://user-images.githubusercontent.com/3728712/53410024-aaec3400-39d3-11e9-9d7f-4b56a6e9512f.png)

**Comment by ashklianko** [comment]
Fixed in https://github.com/enonic/app-contentstudio/issues/222
