### ISSUE TITLE
Broken grid-layout in Settings/Users panel  after deleting/saving a layer

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2285]
**Case 1:**
1. Create 2 layouts in Default project: 
![image](https://user-images.githubusercontent.com/3728712/93218177-97015200-f772-11ea-98fa-941ee537dd49.png)

2. Open  Default context in another browser window.

3. Switch to the first browser window and delete one of the layers
4. Switch to the second browser window and click on `settings` icon

BUG: Broken grid layout in  Settings panel:

![image](https://user-images.githubusercontent.com/3728712/93218740-3a526700-f773-11ea-8eeb-4635a72e4128.png)

**Case 2:**
1. Open new project wizard, fill in the name input , select the access radio and click on Save button
2. Wait for the notification message then click on `Settings` button in the toolbar(Do not close the wizard)

BUG: broken layout in the project grid

![image](https://user-images.githubusercontent.com/3728712/93897173-700ac900-fcfa-11ea-8edb-74578d9eb1b8.png)

**The same issue in Users app:** 

![image](https://user-images.githubusercontent.com/3728712/94244327-60b99480-ff21-11ea-8a32-02c095e6e12e.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1484](https://github.com/enonic/lib-admin-ui/issues/1484) via [**ZenHub**](https://www.zenhub.com/)
