### ISSUE TITLE
Confirmation dialog about unsaved changes does not appear after trying to close a localized content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2307]
1. Create a layer in Default project, select `En` language.
2. Switch to the layer, open a inherited content. (Select the content then click on Localize, or double click on the content)
3. "Language is copied" message appears and Save button gets enabled - OK

![image](https://user-images.githubusercontent.com/3728712/93744437-7f0a5200-fbfa-11ea-809a-a151a0caa589.png)

4. Click on close icon and try to close the wizard.
**Expected**:   Confirmation dialog about unsaved changes should appear.
**Actual**:   Confirmation dialog about unsaved changes does not appear , wizard closes .

**Comment by ashklianko** [comment]
"The beforeunload dialog will only be shown if the frame attempting to display it has received a user gesture or user interaction (or if any embedded frame has received such a gesture)" (https://www.chromestatus.com/feature/5082396709879808)

So it is required to interact with frame first with next events:

- change
- click
- contextmenu
- dblclick
- mouseup
- pointerup
- reset
- submit
- touchend

Thus native dialog won't be shown if immediately closing tab without interaction

**Comment by sgauruseu** [comment]
What if instead of the message : 
![image](https://user-images.githubusercontent.com/3728712/94650891-33ddf680-0300-11eb-8d62-8e3c26f29bba.png)

show a modal dialog with the same message and button `Ok`

**Comment by alansemenov** [comment]
This is required behaviour, we don't need the confirmation if user hasn't made any manual changes.
