### ISSUE TITLE
Layers grid - Inheritance mask is not displayed for readonly items

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2320]
1. Create a project.
2. Add new child layer,( select a language in the layer)
3. Create an user, assign 'Contributor in the layer'  role to user 
4. Add a folder in the parent project
5. Login with the just created user.

BUG:  Inherited content are not displayed as `inherited`

![image](https://user-images.githubusercontent.com/3728712/94260660-3e337580-ff39-11ea-869b-0a9a56d2ffc7.png)

Expected: 

![image](https://user-images.githubusercontent.com/3728712/94260816-7d61c680-ff39-11ea-9e36-b39ac811d0ef.png)

**Comment by ashklianko** [comment]
Was fixed in https://github.com/enonic/app-contentstudio/pull/2348
@sgauruseu please recheck

**Comment by sgauruseu** [comment]
I can not reproduce this issue today - it is fixed
