### ISSUE TITLE
Unpublish dialog - incorrect number of unpublishing items 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2322]
1. Select `Features` and click on `Publish Tree`  menu item.
2. The site is published now. Click on `Unpublish` button in the toolbar, then click on `Unpublish` button in the modal dialog. 

BUG-  Incorrect number of unpublishing items in the modal dialog:  **Expected is 97**
![image](https://user-images.githubusercontent.com/3728712/94424993-cf9e2400-0193-11eb-8396-225efa78e1d1.png)

But correct number  appears in the notification message:

![image](https://user-images.githubusercontent.com/3728712/94425255-4cc99900-0194-11eb-8e1e-d8c9d55059f0.png)

**Comment by alansemenov** [comment]
Fixed in https://github.com/enonic/app-contentstudio/issues/2684
