### ISSUE TITLE
Let readonly content be open in content wizard tab

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2328]
1. Create a layer(select a language), create an user-contributor to this layer.
2. Login with the user  and select a content, open Layers widget

BUG:  `Localize `  button is enabled 

![image](https://user-images.githubusercontent.com/3728712/94561061-2ecf6780-026c-11eb-877c-4aa380202cae.png)

Open this folder: 

Bug - language is updated in the read-only content

![image](https://user-images.githubusercontent.com/3728712/94561356-8c63b400-026c-11eb-8f7a-eb070cf0e669.png)

**Comment by ashklianko** [comment]
-Enabling edit button in toolbar for readonly content
-Replacing 'Edit' text with 'Open' for readonly content both in grid and layers widget
-Not trying to set language for inherited readonly content in wizard, updating url localize->edit in that case
