### ISSUE TITLE
Broken tree in the Settings grid when user does not have access to parent project

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2337]
1. Create a project  then create a child layer.
![image](https://user-images.githubusercontent.com/3728712/94790768-6ad70980-03df-11eb-97de-0671d88b13cc.png)

2. Create an user and add him a role to the layer (Contributor or Owner)
3. Login with the user and navigate to Settings panel: 
**Expected** - Parent project (disabled) and its child should be displayed beneath Project folder.

**Actual**:  Empty `Projects` folder is in Settings panel

![image](https://user-images.githubusercontent.com/3728712/94790965-b1c4ff00-03df-11eb-9959-fdaa27a06ce4.png)

**Comment by ashklianko** [comment]
Pushed into https://github.com/enonic/app-contentstudio/pull/2662
