### ISSUE TITLE
No scrolling and overflow in modal dialogs on mobile resolution 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2339]
1080 x 2280  resolution + chrome browser

1. Select a folder with content and open Sort modal dialog: 

![image](https://user-images.githubusercontent.com/3728712/94899626-50af3100-049c-11eb-83d5-7a23b2f3f746.png)

2. Select the same folder and click on  `Request Publishing` menu item

![image](https://user-images.githubusercontent.com/3728712/94899758-86541a00-049c-11eb-9274-bb7ce13a0ca8.png)

BUG -  No scrolling in modal dialog

**Comment by alansemenov** [comment]
Will be fixed in https://github.com/enonic/app-contentstudio/issues/2470
