### ISSUE TITLE
Lock path field for a published content

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2371]
_NB! Note that this task is only for a published content._

If content is published, path won't dynamically change along with display name. However it's still relatively easy to change the path manually, effectively _moving_ the content with unpredictable consequences.

To make it a bit more tricky to change the path of a published content, we will "lock" the input and warn user about consequences of modifying the field after the content is published.

1. If the content is online (use the current condition that checks whether path should dynamically change along with display name or not), show path as a static text with a lock icon to the right. Show tooltip for the icon: "_Click to modify the path_".

![image](https://user-images.githubusercontent.com/11612490/95871822-665f0900-0d6e-11eb-979b-b9e3dbfbe879.png)

2. We should dynamically toggle between "input + no icon" and "static text + icon" modes on content publish/unpublish via server event listeners.

3. Once the lock icon is clicked, show the new modal dialog with an input having current path as a default value and the "Rename" button disabled. Once the input value changes, verify that new path is available or not (use the same delay as when path is changed directly in the header):

![image](https://user-images.githubusercontent.com/11612490/96174784-1dec4a80-0f2a-11eb-801a-cffdf4add502.png)
![image](https://user-images.githubusercontent.com/11612490/96174830-3492a180-0f2a-11eb-81b7-3d5a4d4fc321.png)

"Rename" button should become enabled only if the path is not empty, different than the current one and available.

4. Once user clicks the "Rename" button, update static path in the header with the new value (don't auto-save the content).

5. If user reopens the dialog, then the input should have the new path as the default value and Rename should be disabled again.

**Comment by sigdestad** [comment]
I would like to discuss this before we start implementation @alansemenov
