### ISSUE TITLE
Selected component  is not displayed in the Inspect Panel 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2381]
This issue can be linked with  https://github.com/enonic/app-contentstudio/issues/2001

**Case 1**:
- Open new site wizard, fill in the name input , select Features in apps selector.
- Select `main region` in the controller selector .
- Open page component and insert a part ,for example 
- Expand the part selector in Inspect Panel and select `Cities List` part , for example 

**BUG**: selected part is not displayed in the Inspect Panel

![image](https://user-images.githubusercontent.com/3728712/96142390-b4a90f00-0f0a-11eb-8c71-8d25360aac63.png)

**This issue does not reproduce** if you select the part in part selector in  `LiveEdit`: 

![image](https://user-images.githubusercontent.com/3728712/96142597-f46ff680-0f0a-11eb-9b00-31a1fe4a64a7.png)

Case 2: Selected option gets  not visible in  Inspect Panel  after several clicking on items in Page Component View 
- Reopen  the site that was created in `case1` 
- Open Page Component View and click on `main` item in the dialog or `main region`
- Click on the part item in   Page Component View

**BUG**:  Selected option is cleared in Inspect Panel: 

![image](https://user-images.githubusercontent.com/3728712/96143439-c212c900-0f0b-11eb-98bb-7ef04885a04d.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1536](https://github.com/enonic/lib-admin-ui/issues/1536) via [**ZenHub**](https://www.zenhub.com/)
