### ISSUE TITLE
Incorrect behaviour of validation in content wizard

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2386]
Case 1 :  - `Not available` message appears after updating a displayName
- Open wizard for new folder , fill in the display name, click on Save button.
- Do not  close the wizard, update the display name, 

BUG: the content gets not valid,  `Not available` message appears, button Saved is disabled
 
![image](https://user-images.githubusercontent.com/3728712/96413179-f8926180-11f3-11eb-8419-0fb755258b28.png)

But the content is valid in the grid:

![image](https://user-images.githubusercontent.com/3728712/96413355-32fbfe80-11f4-11eb-9743-dcb32cb97884.png)

Case 2 :  Unable to save a content without a displayName 

- Open wizard for new folder
- Fill in the path input:

![image](https://user-images.githubusercontent.com/3728712/96413670-a736a200-11f4-11eb-956e-9bde680b877d.png)

BUG- unable to save the content, Save button is disabled

**Comment by ashklianko** [comment]
Pushed into https://github.com/enonic/app-contentstudio/pull/2387 since it has all latest changes
