### ISSUE TITLE
Enable Reset action for inherited, localised content

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2391]
Add new action "_Reset_" to the Content Wizard toolbar, between "_Save_" and "_Delete..._". For now we won't have it in the Content Grid to not have to deal with multiple inheritance checks on bulk select. 

![image](https://user-images.githubusercontent.com/11612490/96604986-fd3f3e80-12f5-11eb-8097-a9fcb5335fe2.png)

Conditions for showing the button (all should be satisfied):
1. Current project is **not** a top level project
2. The item exists in the parent project/layer (use `getbyId` to check)
3. The content doesn't have a **full** set of inheritance flags

Once clicked, we should show the confirmation dialog saying:

"_Resetting this content item will revert all the local changes. This action cannot be undone._" with two buttons Yes and No.

Clicking "Yes" will call the reset API which will restore all the inheritance flags and revert data.

**Comment by sigdestad** [comment]
Where do we place this button in the grid?
