### ISSUE TITLE
Content with Image Selector  - selected options are not displayed in the wizard page

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2437]
Case 1:

- Open new wizard with `Infinite`  image selector and  check 3 images then click on `Apply` button

![image](https://user-images.githubusercontent.com/3728712/97400548-5c0d4500-1900-11eb-8234-93ed634df0bf.png)

BUG:  The options are not selected after clicking on Apply button

Case 2:
- Open new wizard for content with Image Selector 
- click on an image in expanded options and save it.
![image](https://user-images.githubusercontent.com/3728712/97400968-0f763980-1901-11eb-81f2-d84c0debe370.png)

- Reopen the content again

BUG -  Selected image is not present in the form

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1550](https://github.com/enonic/lib-admin-ui/issues/1550) via [**ZenHub**](https://www.zenhub.com/)
