### ISSUE TITLE
Text overflow in Rename published content modal dialog, when the path is more than 80 symbols

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2457]
1. Create a folder with a path more than 80 symbols
2. Publish the folder  and open  `Rename published content` modal dialog

Bug -  Text overflow in the modal dialog.
![image](https://user-images.githubusercontent.com/3728712/97841500-fef60280-1cf6-11eb-96c2-2a4085efff76.png)

**Comment by ashklianko** [comment]
Same for Move dialog
