### ISSUE TITLE
Save button gets enabled and content gets modified after tab navigation to   `Online from` input

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2474]
1. Open `Published` folder.
2. Press Tab key - focus set in `Online from` input

BUG: Save button gets enabled and content is modified after  tab navigation to   `Online from` input

![image](https://user-images.githubusercontent.com/3728712/98095267-65b42100-1e9b-11eb-94e5-96ccebc509af.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/xp #8601](https://github.com/enonic/xp/issues/8601) via [**ZenHub**](https://www.zenhub.com/)

**Comment by alansemenov** [comment]
@ashklianko Reopened - let's cut seconds on the client before comparing publish from/to dates with persisted values. Should probably be in lib-admin-ui?

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1739](https://github.com/enonic/lib-admin-ui/issues/1739) via [**ZenHub**](https://www.zenhub.com/)
