### ISSUE TITLE
Site Wizard - broken layout after selecting a controller 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#250]
1. Open new site wizard, select Features, type a name, select `main region`. save all 
2. Open Page Components View , click on  `main region` and select the `Reset` menu item:

![image](https://user-images.githubusercontent.com/3728712/53635502-63adaf80-3c2e-11e9-8621-17da4170bbac.png)

3. Controller Selector  appears, do close  Context Panel and select `main region` option 
 
**Bug: broken layout after the selecting `main region` option in   controllers**

![image](https://user-images.githubusercontent.com/3728712/53635342-dcf8d280-3c2d-11e9-8f6d-b3b4fe9e33a2.png)

**Comment by edloidas** [comment]
Issue moved to [enonic/lib-admin-ui #947](https://github.com/enonic/lib-admin-ui/issues/947) via [**ZenHub**](https://www.zenhub.com/)
