### ISSUE TITLE
Newly created project splits the tree with layers

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2509]
1. Open Setting , select Default project and create new layer
2. Add new project.

![image](https://user-images.githubusercontent.com/3728712/98934863-c1158d00-24f3-11eb-8a06-50d64fae5340.png)

BUG - newly created project is not correctly inserted into the projects tree.

Click on refresh icon - the tree gets correct.

![image](https://user-images.githubusercontent.com/3728712/98935443-94ae4080-24f4-11eb-8e2b-d47f5398c535.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1577](https://github.com/enonic/lib-admin-ui/issues/1577) via [**ZenHub**](https://www.zenhub.com/)
