### ISSUE TITLE
Need lower-latin numbered list in HtmlArea

### ISSUE THREAD

**Issue by vi-h** [enonic/app-contentstudio#2527]
In some cases, for example when listing law paragraphs, we need to use a numbered list in the lower-latin format, but with a paranthesis behind the character instead of a dot.

At the moment it is only possible to choose between a numbered list (in the decimal format) or a bullet list in the HtmlArea. It would help a lot if it was possible to use the numbered list in the lower-latin format as well.

This functionality exists in CKeditor (https://ckeditor.com/docs/ckeditor5/latest/features/lists.html), and if I have understood correctly you can just activate it.

**Comment by sigdestad** [comment]
Hi. First thing is that we use CK editor 4, not 5 due licensing issues, so it might not be as simple as activating. We'll investigate how this works in CK4 and if so, how it can be applied to Content Studio.

**Comment by vi-h** [comment]
I got a tip that CKeditor 4 got the list style types as an official plugin: https://ckeditor.com/cke4/addon/liststyle 🙂

**Comment by alansemenov** [comment]
To be done together with https://github.com/enonic/app-contentstudio/issues/1518

**Comment by ashklianko** [comment]
Pushed into https://github.com/enonic/app-contentstudio/pull/4257
