### ISSUE TITLE
Enable exclusion of all "in progress" items in the Publishing Wizard

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2528]
Add a link "_Exclude all (X)_" to the "**Work in progress!**" warning on top of the modal dialog. Clicking the link should call `resolvePublishContent` API which will exclude all items that are in "In progress" state and NOT required for publishing. 

After that the dialog should be re-rendered based on new response from the API.

NB! Manually excluded items (if any) should be sent to `resolvePublishContent` API as well, so that they don't come back on the list.

![image](https://user-images.githubusercontent.com/11612490/99281009-51c0d580-2832-11eb-8e86-421a130723a4.png)

**Comment by ashklianko** [comment]
Pushed into https://github.com/enonic/app-contentstudio/pull/2552
