### ISSUE TITLE
Enable exclusion of all invalid items in the Publishing Wizard

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2529]
Similar to https://github.com/enonic/xp/issues/8484, implement exclusion of all invalid items via clicking on the link next to the "**Invalid items!**" warning on the top. Make current text "_Invalid content cannot be published, remove from list or fix this issue_" a tooltip for the "**Invalid items!**" span.

**Comment by ashklianko** [comment]
Pushed into https://github.com/enonic/app-contentstudio/pull/2552
