### ISSUE TITLE
Widget dropdown is missing scrollbar

### ISSUE THREAD

**Issue by poi33** [enonic/app-contentstudio#2535]
The widget dropdown does not have a scrollbar on chome for mac?
Had some users that struggeld to find widgets: 
https://enonic-community.slack.com/archives/C73JLM8E7/p1605554047249800
<img width="298" alt="Skjermbilde 2020-11-16 kl  21 34 17" src="https://user-images.githubusercontent.com/3340349/99371840-b8d89b80-28bf-11eb-876f-d505a63aa129.png">

**Comment by sigdestad** [comment]
Denne kan løses ved å øke lengden på vinduet, slik at man f.eks. ser halvparten av en widget i bunnen av listen

**Comment by poi33** [comment]
Showing half of an item will help make it more clear you can scroll in the window. 👍 
but we are going to need more make it clear its possible to scroll in the window.

**Comment by poi33** [comment]
@alansemenov chrome on windows, and firefox and windows does show a scrollbar so its not missing on some versions of chrome.

**Comment by alansemenov** [comment]
This was caused by scrollbar setting on Mac. Fixing it solved the issue
