### ISSUE TITLE
Page Components View - context menu is cut off after expanding sub-menu

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#254]
**1.**  Open SuperHero, open Page Components View 
**2.**  Click on the bottom-component, menu is opened: 

![image](https://user-images.githubusercontent.com/3728712/53641941-7d0c2700-3c41-11e9-807d-a36b76c27fc9.png)

**3.**  Do expand  `Insert` menu item, 

**Bug**: some menu items are not visible, when menu has been expanded

![image](https://user-images.githubusercontent.com/3728712/53641827-31597d80-3c41-11e9-8fc3-1c1d1157e44e.png)

**Comment by alansemenov** [comment]
We should reposition the context menu on the submenu expand.
