### ISSUE TITLE
Pasting from Word into Enonic doesn't remove formatting

### ISSUE THREAD

**Issue by vot-enonic** [enonic/app-contentstudio#255]
I write articles in Google Docs and Microsoft Word, and copypasting content from these programs into the Enonic text editor leads to several unwanted formatting issues.

For instance: ``<p style="margin-left:0cm; margin-right:0cm">`` when it should only be ``<p>``

**Comment by mortyeriksen** [comment]
Wonder if the paste from word option is enabled?

https://ckeditor.com/docs/ckeditor4/latest/examples/pastefromword.html

**Comment by mortyeriksen** [comment]
@vot-enonic Missing some stuff in your post?

**Comment by alansemenov** [comment]
@ashklianko can we enable the "paste from word" plugin? try to avoid the plugin's button in the toolbar, it won't work anyway.

**Comment by ashklianko** [comment]
Sure, and we can always hide button when needed.

**Comment by ashklianko** [comment]
So, I see that we already have word plugin in editor, it works when you copy-paste Word document's content. However if there is some extra content pasted from Word, we might try to filter pasted content.
@vot-enonic could you please provide word doc that has issues?

Regarding google docs pasting: issue is on google side, they seem to wrap copied content with some extra tags. What I see now is that they wrap text in bold/strong, are there other issues @vot-enonic ? If issue only with bold text pasted then I could also try to filter it.

**Comment by vot-enonic** [comment]
[markup.docx](https://github.com/enonic/app-contentstudio/files/2935120/markup.docx)
Here is an example. The thing is, I write articles in Google Docs, but pasting from Google Docs leads to all the text being in bold and all the italics being removed. So I have to paste the Google Docs text into a Microsoft Word file to maintain the italics, but then the headings are gone. I manually add headers when pasting to Enonic XP, but in the source code we can also see the strange <p> codes.

**Comment by mortyeriksen** [comment]
Both google docs and word should work. Can you send a link to the google doc too?

**Comment by vot-enonic** [comment]
https://docs.google.com/document/d/1-vaxo4MwHipyyO-AIcSNTRjyTJ75yYKWibMHXr1hU34/edit#

**Comment by ashklianko** [comment]
Thanks @vot-enonic , I guess primary issue in Google Docs, and this issue occurs not only for us and not only in CKEditor. I believe I can try to filter out google docs  content on pasted.

**Comment by mortyeriksen** [comment]
@ashklianko It looks like it's the same problem with Word, right? We are answering a lot of requirement specs where they ask for word pasting.

**Comment by ashklianko** [comment]
@mortyeriksen , word pasting plugin is already there, it just also might process pasted content with extra attributes. 
I'd start with fixing google docs pasting so @vot-enonic wouldn't need to copy first to Word and then to editor,  so it would probably solve original problem @vot-enonic found.

**Comment by alansemenov** [comment]
tested
