### ISSUE TITLE
Add indication of item inheritance

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2550]
If a content item is or at some point has been inherited from a project/layer above, we should indicate this with a new icon. This will help separate local content items from those that have been inherited and then localised.

* Use `originProject` field to determine whether the item was inherited. 
* I think we should also fix "Reset" button to check `originProject` field, instead of sending an API request to check it the item exists in other layers
* The icon should be placed in the bottom-left corner of the content type icon
* The icon should be used everywhere, not just in the Content grid: Content Wizard, details panel, modal dialogs etc., just like workflow icons
* Use `cloud-download` icon from the "Material Icons" set on icomoon
* Use blue color for the icon (same as we use for toggle icons)

![image](https://user-images.githubusercontent.com/11612490/99787446-0b17f780-2b20-11eb-88a4-8ae6a5f4b5e4.png)

**Comment by ashklianko** [comment]
Added into https://github.com/enonic/app-contentstudio/pull/2553
