### ISSUE TITLE
Fix indent in LayersContentTreeDialog 

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2575]
![image](https://user-images.githubusercontent.com/11612490/100445370-4892fc80-30ad-11eb-9cb6-64ca6f5d2abd.png)

should be

![image](https://user-images.githubusercontent.com/11612490/100445489-7aa45e80-30ad-11eb-85a5-7f0aeb9d0b45.png)

**Comment by sigdestad** [comment]
Alan, I was also thinking that the cards should have a fixed size? I.e. max width. That will look much better.

**Comment by alansemenov** [comment]
What do you mean? They do have max width, otherwise they wouldn't be aligned by the right border.

**Comment by sigdestad** [comment]
To me, it curently looks like with is 100%, I'm suggesting we set a max width of i.e. 350px. Then the cards would normally have the same size.

But, maybe it is ok like it is currently displayed?

**Comment by alansemenov** [comment]
We have max width for modal dialogs. If the boxes are 350px wide then the dialog will also be 350px wide and that is too narrow, it will not look good.
