### ISSUE TITLE
Inherited icon and Reset button should not be displayed in duplicated content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2576]
1. Create a layer(select En language) in `Default` project
2. Go to the just created layer, select a inherited content and duplicate it . 
3. Open the newly created copy .

**BUG**:  `Reset` button and blue inherited icon should not be displayed in the wizard page , because this content is local 

![image](https://user-images.githubusercontent.com/3728712/100583301-8edd9b00-32fb-11eb-9bbe-fdb32ae20158.png)

**Comment by alansemenov** [comment]
Will be fixed in https://github.com/enonic/xp/issues/8515
