### ISSUE TITLE
Page Editor - Cannot select controller for a page after resetting it (MS Edge)

### ISSUE THREAD

**Issue by jsi** [enonic/app-contentstudio#26]
@sgauruseu commented on [Mon Nov 05 2018](https://github.com/enonic/app-contentstudio-old/issues/530)

**Open XP in Edge browser.**

1. Open new site wizard,  type a name , select Features , select `Attachment function example` (for example)

2. Site is saved, when the controller has been selected  (OK)
3. Open Page Component View and Reset the controller 

4. Select the  `Attachment function example`  in dropdown options again 

**BUG: the option is selected , but the page is not updated and the site is not `Saved`**

![image](https://user-images.githubusercontent.com/3728712/47993573-d6839f80-e100-11e8-9e29-ab461c9b1389.png)

---

@alansemenov commented on [Wed Nov 07 2018](https://github.com/enonic/app-contentstudio-old/issues/530#issuecomment-436626901)

@sgauruseu I don't understand n.3 in your description... After you selected controller, the selector disappears and the page is rendered. How can you select controller again if there's no selector? I tried changing controller from the Inspector panel and it worked fine from there.

**Comment by ashklianko** [comment]
Reproduced; Pushed into https://github.com/enonic/app-contentstudio/pull/259
