### ISSUE TITLE
Add option to display search results as a tree view

### ISSUE THREAD

**Issue by RF0** [enonic/app-contentstudio#2611]
This is a feature request for improved search. 

**Add option to display results in a tree view.**

Content studio search has one drawback when there is many search results, they cannot be filtered, sorted or be displayed in a tree view, thus it can be hard to find the content that we are looking for (see screenshot with search for 'forsikring'). 

I was inspired by how filtering in VS Code editor works (see screenshot with filtering for package.json), where all matching results are displayed in a tree view, and it is possible to perform some actions on multiple files (delete, open..)

https://www.kimsereylam.com/js/2020/05/22/vscode-file-navigation-tips.html#filtering-files

![Skjermbilde 2020-12-02 kl  21 10 39](https://user-images.githubusercontent.com/951293/100925847-de31f000-34e2-11eb-83f1-e9e4551fe619.png)
![Skjermbilde 2020-12-02 kl  21 03 46](https://user-images.githubusercontent.com/951293/100925852-df631d00-34e2-11eb-9db6-8a77f5f55952.png)

**Comment by alansemenov** [comment]
Thank you for the proposal. We are not going to implement this at the moment.
