### ISSUE TITLE
Parent content gets collapsed after adding a child item in filtered grid

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2612]
1. Open filter panel and fill in the filter input.
2. Select the filtered content, expand it .

![image](https://user-images.githubusercontent.com/3728712/101158829-747a2900-363d-11eb-8346-5f429e4b6aa7.png)

3. Add a child content.

BUG: Parent content gets collapsed after adding the child item.

![image](https://user-images.githubusercontent.com/3728712/101158774-5f04ff00-363d-11eb-8a18-1bc4070feac0.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1682](https://github.com/enonic/lib-admin-ui/issues/1682) via [**ZenHub**](https://www.zenhub.com/)
