### ISSUE TITLE
Implement confirmation for unpublishing a site or multiple content items

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2638]
Implement a new confirmation dialog for unpublishing a site or multiple items (same logic as for deletion):

![image](https://user-images.githubusercontent.com/11612490/102100674-04805580-3e2a-11eb-851e-6218c777f746.png)

The number should represent total number of items to be unpublished.

**Comment by ashklianko** [comment]
Will do after #2618 merged as it has confirm dialog prepared
