### ISSUE TITLE
Confirm Value Dialog -  text input is not cleared , the previous value is displayed in the input

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2653]
1. Select a folder with a child and open delete dialog , type number then 2 delete folders
2. Select Features site and open  Confirm Value Dialog again 

BUG: The previous value is displayed

![image](https://user-images.githubusercontent.com/3728712/102459915-50641200-4057-11eb-919f-7a41f3c38b18.png)

**Comment by ashklianko** [comment]
Fixed in https://github.com/enonic/app-contentstudio/pull/2652

**Comment by ashklianko** [comment]
Fixed in https://github.com/enonic/app-contentstudio/pull/2677
