### ISSUE TITLE
"Exclude all" should not exclude main items 

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2654]
"Exclude all" links now count and exclude all items, both the main ones and their dependants. We should fix this behaviour so that they only take into consideration dependant items.

In the case below the "_Work in progress_" warning should be there, but the "_Exclude all (1)_" link should be hidden since there are no dependant items in progress.

![image](https://user-images.githubusercontent.com/11612490/102464486-ada69600-404c-11eb-8486-9a0430aa28e6.png)

**Comment by sigdestad** [comment]
Why not?
