### ISSUE TITLE
Errors in console after inserting images in LiveEdit

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2672]
1. Open  wizard for new site, select Features in app-selctor 
2. Select main controller
3. Open Page component View and insert 2 images from Features
4.

BUG;  error in console after inserting images

![image](https://user-images.githubusercontent.com/3728712/102782800-fe9aef00-43aa-11eb-9856-dbf2e4bacf0d.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1650](https://github.com/enonic/lib-admin-ui/issues/1650) via [**ZenHub**](https://www.zenhub.com/)
