### ISSUE TITLE
Insert Image dialog - broken layout when Custom width checkbox is selected

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2673]
1. Open a content with Html Area and insert an image
2. Click on Custom Width  checkbox 
3. 
Bug -  Broken layout in the modal dialog
![image](https://user-images.githubusercontent.com/3728712/102787332-f6927d80-43b1-11eb-9d2f-ac9e34280fc7.png)

**Comment by alansemenov** [comment]
Duplicate of https://github.com/enonic/app-contentstudio/issues/2743
