### ISSUE TITLE
Broken layout in Content Wizard toolbar for a content with x-data

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2674]
1. Open Features 
2. Create a fragment from the text component
3. .Go to fragment wizard and  add the -x-data  `X-data (all except folders)`
3. Scroll the page 

BUG: Layout gets broken after scrolling a page with x-data

![image](https://user-images.githubusercontent.com/3728712/102862196-c692bb00-4441-11eb-8ea9-342f8b38ed0c.png)

Open Color Picker wizard, add x-data and scroll the page : 

![image](https://user-images.githubusercontent.com/3728712/107771468-db0d7880-6d4b-11eb-92f8-04c6c5af02ab.png)

**Comment by ashklianko** [comment]
Some problems in grid toolbar also:
![image](https://user-images.githubusercontent.com/4255706/102867353-b1218f00-4449-11eb-9685-0d72da7b2fc3.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1793](https://github.com/enonic/lib-admin-ui/issues/1793) via [**ZenHub**](https://www.zenhub.com/)
