### ISSUE TITLE
Incorrect language of a local child item created under inherited non-localised parent

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2681]
When a new child content is created under existing content, we set language of the parent on this child content.
This behaviour should be different when a child content is created under **inherited non-localised** content. In this case we should set language of the current layer on the child content.

**Comment by ashklianko** [comment]
To be done in https://github.com/enonic/xp/issues/8576
We would possibly need to adjust `CreateContentRequest.ts` to let language param be set explicitly (though we don't need it now), but if it is not required then can close this task
