### ISSUE TITLE
Error in console after opening new Option Set wizard

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2686]
**Issue 1**. 

Select Features, open new `Option Set`
![image](https://user-images.githubusercontent.com/3728712/103005998-258c2900-4543-11eb-81ab-0267247dbaa6.png)

BUG- error in console in new wizard page

**Issue 2** 

Expand menu item should be disabled when the option is not selected

![image](https://user-images.githubusercontent.com/3728712/103008031-8452a200-4545-11eb-96c4-d1d6e348b3ed.png)

**Comment by pmi** [comment]
Issue moved to [enonic/lib-admin-ui #1656](https://github.com/enonic/lib-admin-ui/issues/1656) via [**ZenHub**](https://www.zenhub.com/)
