### ISSUE TITLE
Option Set wizard - Esc won't close the delete confirmation mask

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2707]
1. Select Features and open new Option Set wizard
2.  Select `Option 1` in Single selection., then open menu in  Minimum 3 and click on `Add bellow` menu item.
3. Fill in the required Label input and save it.
4.  Expand menu and click on `Delete` menu item.

![image](https://user-images.githubusercontent.com/3728712/103512612-14fc7c80-4e7a-11eb-8c40-229972be6202.png)

5.  **Confirmation dialog is not fully loaded**-

![image](https://user-images.githubusercontent.com/3728712/103654157-920d1c00-4f76-11eb-849f-77f60779872f.png)

**BUG**:  
-  Auto-scroll the page to make room for delete confirmation mask
-  Clicking on `Esc` key does not close the   Confirmation Mask dialog

**Comment by alansemenov** [comment]
@sgauruseu this is by design. the mask has fixed positioning and there's no point in scrolling it together with the form.

but we should fix it so that Esc removes the mask, @pmi

**Comment by pmi** [comment]
Issue moved to [enonic/lib-admin-ui #1693](https://github.com/enonic/lib-admin-ui/issues/1693) via [**ZenHub**](https://www.zenhub.com/)
