### ISSUE TITLE
Browse toolbar - Preview button should be enabled after a controller has been selected

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2728]
1. Create a site (select Features in applications). Close the wizard
2. Click on checkbox and select the site, then click on `Edit` button
3. Select a controller.
  `Preview` button gets enabled in the wizard - **OK**
![image](https://user-images.githubusercontent.com/3728712/103889291-3ae28500-50f7-11eb-8167-25c2e4085ba3.png)

4. Go to grid.
5. 
**BUG**  - `Preview` is disabled in the browse toolbar

![image](https://user-images.githubusercontent.com/3728712/103889434-79783f80-50f7-11eb-96a7-519c547907b8.png)

**Comment by alansemenov** [comment]
This is similar to https://github.com/enonic/app-contentstudio/issues/2646 and is now fixed in that issue
