### ISSUE TITLE
Next button in the Request Publishing wizard not disabled when the item is in progress

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2737]
1. In the Content grid find and select an item that is in progress and has at least one child
2. Select "Request Publishing" from the toolbar's publish button menu

Bug: "Next" button is enabled and there's no notification about items in progress, even though the selected item is in progress
![image](https://user-images.githubusercontent.com/11612490/104004460-0ed10d80-51a4-11eb-9985-7852b8d1fdd3.png)

3. Click the "Include child items" icon to the left of the item

Now both the notification and button state are correct:
![image](https://user-images.githubusercontent.com/11612490/104004665-4b046e00-51a4-11eb-8ecc-bce6b11ed344.png)

Also, there's some blank extra space between the header and the item on the first screenshot, because of incorrectly applied "`has-issues`" style (when there are no issues)

![image](https://user-images.githubusercontent.com/11612490/104004933-ad5d6e80-51a4-11eb-8a8c-02c8a1df3da8.png)

**Comment by ashklianko** [comment]
Done in https://github.com/enonic/app-contentstudio/pull/2744
