### ISSUE TITLE
iframe and script tags should by default not be allowed in HTML Editor

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#274]
1. Disallow `iframe` and ``script`` tags in HTML Editor by default. 

2. Read a property from the **app-contentstudio** config file (`com.enonic.app.contentstudio.cfg`) which will allow `script` tag:

`htmlinput.allowScripts=true`

If it's _true_, allow ``script`` element in the editor.

For `iframe` users can use the iframe macro.

3. Document the new property (separate task)

**Comment by ashklianko** [comment]
Where to document this? https://github.com/enonic/xp-doc ?

**Comment by sigdestad** [comment]
Nope.. 
Strictly speaking it should be documented in app-contentstudio
