### ISSUE TITLE
Change logic for default values in "Insert Image" dialog's "Caption" and "Alt text" fields 

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#275]
Change logic default values in the Caption and Alt Text fields after selecting a new image from the selector.

![image](https://user-images.githubusercontent.com/11612490/53957705-55084200-40df-11e9-9f40-d94211c808a3.png)

**Caption field**: 
Use value from the content's `data.caption` field. If `data.caption` doesn't exist or is empty, use value from `x.media.imageInfo.description`.

**Alt text field**:
Use value from `data.alt_text` field. If `data.alt_text` doesn't exist or is empty, use image file name.

**Comment by ashklianko** [comment]
Pushed into https://github.com/enonic/app-contentstudio/pull/305 because issues closely related
