### ISSUE TITLE
Content marked for deletion still shows status "Publishing Scheduled"

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2780]
1. Select a folder and open Publish Wizard
2. Click on Add Schedule form and  schedule  this folder.
3. Select the folder and open Delete dialog. Click on `Mark as Deleted` menu item

![image](https://user-images.githubusercontent.com/3728712/104708205-7223e800-572e-11eb-9afa-3713bb9b0896.png)

**BUG**:  Publishing Scheduled status remains after the scheduled content has been marked as deleted

![image](https://user-images.githubusercontent.com/3728712/104708451-ca5aea00-572e-11eb-841f-a7e7c1496265.png)

**Comment by alansemenov** [comment]
No longer relevant since we're dropping pending delete
