### ISSUE TITLE
Bulk selection triggers `hasUnpublishedChildren` request for every selected item

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2800]
When user selects multiple items in the grid, CS will send `hasUnpublishedChildren` request for **every** item in the selection. First request will check content id 1, second will check id 1 and 2 and so on... until the last request that checks all of the selected items and THAT is the only request we should check. 

![image](https://user-images.githubusercontent.com/11612490/105153830-2e075d80-5b09-11eb-8793-c36c9af8944f.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1747](https://github.com/enonic/lib-admin-ui/issues/1747) via [**ZenHub**](https://www.zenhub.com/)
