### ISSUE TITLE
Fix issue email layout in Window mail clients

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2801]
We have a problem with layout in mail clients under Windows (Mail, Outlook). Not only it looks ugly but it also strips aways the button that opens the issue details.

![image](https://user-images.githubusercontent.com/11612490/105170637-80527980-5b1d-11eb-8cc5-b22feec2c9e6.png)

![image](https://user-images.githubusercontent.com/11612490/105170573-687af580-5b1d-11eb-98ab-5f497cc269d3.png)

Here's how it looks in Mac's Mail and GMail clients:
![image](https://user-images.githubusercontent.com/11612490/105170469-42edec00-5b1d-11eb-924a-b4dbe22c2312.png)

**Comment by ashklianko** [comment]
Fixed in https://github.com/enonic/xp/issues/8627
