### ISSUE TITLE
Settings grid - duplicate items appear after clicking on Show Selection button

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2839]
**Case 1:**
1. Select a project and several its layers

![image](https://user-images.githubusercontent.com/3728712/106474362-e7751400-64b5-11eb-9364-349bfa3fb826.png)

2. Click on `Show Selection` button
BUG - Items not correctly filtered:  

![image](https://user-images.githubusercontent.com/3728712/106474581-19867600-64b6-11eb-902a-0dacdd4e17d5.png)

**Case 2 :** 
- check the Default project, click on Show selection

![image](https://user-images.githubusercontent.com/3728712/106564332-264eac80-653e-11eb-81dd-f2348f515d55.png)

- add a child layer 
![image](https://user-images.githubusercontent.com/3728712/106564454-4a11f280-653e-11eb-93cf-108eb3647243.png)

**BUG** - child layer should be beneath the parent, Expander icon is not displayed in Default project

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1776](https://github.com/enonic/lib-admin-ui/issues/1776) via [**ZenHub**](https://www.zenhub.com/)
