### ISSUE TITLE
Publishing Wizard is not refreshed after parent and its child content have been marked as ready 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2843]
Publishing Wizard is not refreshed when it was opened in Content Wizard.
This issue does not reproduce if you open Publishing Wizard in Browse Panel
1. Select Features and open new wizard for Selector content, fill in the name input.
2. Select a `work in progress` content in the top selector
3. Click on `Publish....` menu item
4. Expand the button menu and click on `Mark as ready` menu item

BUG - both items are marked as ready , but the modal dialog is not refreshed -  two `work in progress` icons remains in the  dialog

![image](https://user-images.githubusercontent.com/3728712/106596911-b7d21480-6566-11eb-9924-649d79e6ca45.png)

Mark as ready menu item remains clickable after this action.

![image](https://user-images.githubusercontent.com/3728712/106597063-ed76fd80-6566-11eb-9847-c6a7b8555fbc.png)

**BUT this issue does not reproduce in sites**  - the modal dialog is updating after clicking on `Mark as ready` menu item
![image](https://user-images.githubusercontent.com/3728712/106597297-45adff80-6567-11eb-87d4-538f7a229e67.png)

**Comment by ashklianko** [comment]
Fixed in https://github.com/enonic/lib-admin-ui/pull/1784
