### ISSUE TITLE
Save button remains disabled after enabling x-data in the Content Wizard

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#287]
1. Add x-data with Image Selector to Features
2. add in the `site.xml`
`x-data name="image-selector" optional="true" allowContentTypes="base:folder"`
3. Deploy the app
4. Select features and open new folder-wizard, type a name and save the folder
5. Click on `+` and enable  x-data with `image-selector`. 
6. Do not select an image in the x-data, but save the content in the wizard, close the wizard.
7. Open the folder again

**Bug**:
1) x-data with the selector is disabled(Expected is enabled) 
2)  click on '+' and enable the x-data . **Expected** - Save button should appear on the toolbar

![image](https://user-images.githubusercontent.com/3728712/54122405-f8be5e80-440d-11e9-9a1e-ba5b272cded0.png)

**Comment by alansemenov** [comment]
It doesn't work with ImageSelector in the x-data:

```
<x-data xmlns="urn:enonic:xp:model:1.0">
  <display-name>Image Selector</display-name>
  <form>
    <input name="imageSelectorSite" type="ImageSelector">
      <label>allow all on site</label>
      <occurrences minimum="1" maximum="1"/>
    </input>
  </form>
</x-data>
```

**Comment by alansemenov** [comment]
It seems to work fine after all. It's nightly server that wasn't updated with the new version of Content Studio app.
