### ISSUE TITLE
Show Component View is not displayed in wizard toolbar after a page descriptor has been selected

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2876]
1. Open new site wizard, type a name and select Features
2. Select `main region` controller

**BUG**- 
1) Show component View button should appear after selecting a page descriptor
2) Components tab should be loaded
3) Context/widget panel should open in the Docked mode when the browser window is wider than 1850px
4) Emulator menu item should be loaded

![image](https://user-images.githubusercontent.com/3728712/108029259-325a6400-703e-11eb-9db2-c383f78d5d05.png)

**This button appears after refreshing page in browser**

![image](https://user-images.githubusercontent.com/3728712/108029359-57e76d80-703e-11eb-9d92-b466dc762b5e.png)

**Comment by ashklianko** [comment]
Because of IsRenderable cache, will update immediately

**Comment by ashklianko** [comment]
Will be fixed in https://github.com/enonic/app-contentstudio/pull/2877
