### ISSUE TITLE
Content Wizard - Save button remains enabled after creating a content with several text inputs

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2881]
1. Select Feature and open  Article or Blog wizard.
2. Fill in the name input and click on `Save` button (do not fill the  `title`  and `body`)
**BUG**:  Save button remains enabled after the content is saved

![image](https://user-images.githubusercontent.com/3728712/108178153-2ab9be80-7115-11eb-9c17-6227f68e0aee.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1849](https://github.com/enonic/lib-admin-ui/issues/1849) via [**ZenHub**](https://www.zenhub.com/)
