### ISSUE TITLE
Project name field is too small in the Delete Project confirmation dialog

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2882]
1. Go to Settings and open Super Hero project
2. Click on `Delete` button

**Bug**:   the input size is not enough to enter the project name
![image](https://user-images.githubusercontent.com/3728712/108190173-a837fb80-7122-11eb-8de0-b33e53c32c4d.png)

**Comment by ashklianko** [comment]
Will add 'size' attribute or adjust 'min-width'
