### ISSUE TITLE
Item-set inside part config is not properly rendered in the Inspect panel

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#292]
1. Create this new part in the Features app

**test.xml:**
```xml
<part>
  <display-name>Test part</display-name>
  <form>
    <item-set name="news">
      <label>Item set</label>
      <items>
        <input name="image" type="ImageSelector">
          <label>Image</label>
          <occurrences minimum="1" maximum="1"/>
        </input>
      </items>
      <occurrences minimum="1" maximum="1"/>
    </item-set>
  </form>
</part>
```

**test.js:**
```javascript
exports.get = function () {
    return {
        contentType: 'text/html',
        body: '<div></div>'
    };
};
```

2. Build/deploy the app

3. Add the part called "Test part" to the page

4. Everything looks fine in the Inspect panel
![image](https://user-images.githubusercontent.com/11612490/54217813-a011c300-44ec-11e9-91bc-8f98f8252b8a.png)

5. Save the content (doesn't matter if you select anything in the selector or not). Everything is still correct in the Inspect panel

6. Reload the browser page and select the same part

7. Now only the item-set's label is visible, but the contents are empty.

![image](https://user-images.githubusercontent.com/11612490/54217989-f0892080-44ec-11e9-93ab-a351bc4444a5.png)

It works correctly in 6.15.x

**Comment by edloidas** [comment]
Issue moved to [enonic/lib-admin-ui #955](https://github.com/enonic/lib-admin-ui/issues/955) via [**ZenHub**](https://www.zenhub.com/)
