### ISSUE TITLE
Feature request: keyboard shortcut for moving items

### ISSUE THREAD

**Issue by thomasheartman** [enonic/app-contentstudio#2944]
It seems there's no keyboard shortcut for moving content around in the tree view, so the only way to do it with a keyboard is to mark the specific piece of content and then to tab up to the menu and select move. As someone who prefers to use the keyboard as much as possible, I wish that there was a keyboard shortcut for moving content.

**Comment by alansemenov** [comment]
Alt-M is available in all browsers
