### ISSUE TITLE
Inspect Panel - images are not displayed in the Image Component's descriptor selector

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2954]
**Case 1**
1. Open Features site, insert an image/
2. Switch to tree mode in Inspect panel 
**BUG** - images are not displayed in tree mode
![image](https://user-images.githubusercontent.com/3728712/110443764-56edad00-80cd-11eb-9178-318ce1e82036.png)

**This bug does not reproduce in image selector content** 

![image](https://user-images.githubusercontent.com/3728712/110444171-bf3c8e80-80cd-11eb-9cd8-8d769500d578.png)

**Case 2**
1. Insert an image component
2. Expand options in the combobox.
3. Switch to tree mode

![image](https://user-images.githubusercontent.com/3728712/110600232-c1b5eb80-8194-11eb-8851-a9fd928ec58d.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1851](https://github.com/enonic/lib-admin-ui/issues/1851) via [**ZenHub**](https://www.zenhub.com/)
