### ISSUE TITLE
Attachment is removed from content while it's still in use

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2962]
1. Create a part descriptor with AttachmentUploader
2. Add two parts to a page and select this descriptor for both of them
3. Upload the same attachment into both parts

![image](https://user-images.githubusercontent.com/11612490/110635698-ad311d80-81ab-11eb-9de4-b1cda2d90f48.png)

4. Now delete the attachment from one of the parts.

Bug: The attachment is deleted from the content even though it's still in use in the other part.

![image](https://user-images.githubusercontent.com/11612490/110635953-fa14f400-81ab-11eb-86ec-117c2459efef.png)

Part XML:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<part xmlns="urn:enonic:xp:model:1.0">
  <display-name>Attachment in part</display-name>
  <form>
    <input name="attachment" type="AttachmentUploader">
      <label>Single Attachment (required)</label>
      <occurrences minimum="1" maximum="1"/>
    </input>
  </form>
</part>
```

**Comment by ashklianko** [comment]
Same problem for attachments in content types

**Comment by ashklianko** [comment]
One more case when you have both content type with attachment and part with attachment: uploading same item for both leads to a single attachment that will be removed for both content type and part no matter if remove was triggered on part or content type form input
