### ISSUE TITLE
[Firefox] Long content path is not overflown in the Inspection Panel

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2966]
1. Open a site in FF, insert an image.
2. Open Inspect Panel.

**BUG**:  Ellipsis should be displayed in long path in Inspect Panel

![image](https://user-images.githubusercontent.com/3728712/110753834-1e2e0f00-8258-11eb-9f7c-38bf2d5b9235.png)

**Comment by ashklianko** [comment]
Works now:
![image](https://user-images.githubusercontent.com/4255706/197137866-838345f6-7a2a-4c0c-bb61-a8f565482ca4.png)
