### ISSUE TITLE
Handle long path overflow in the Compare versions modal dialog

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2967]
1. Save a content with long name.
2. Open Compare Versions modal dialog.

**BUG** - text overflow in subtitle in the modal dialog
![image](https://user-images.githubusercontent.com/3728712/110755554-2129ff00-825a-11eb-8511-5579ee9087d6.png)

**Comment by alansemenov** [comment]
`.ellipsis()`
