### ISSUE TITLE
Text overflow in Duplicate content modal dialog

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2968]
1. Select a content and open Duplicate dialog.

BUG - ellipsis  should be displayed in the dialog 

![image](https://user-images.githubusercontent.com/3728712/110756144-e2487900-825a-11eb-941e-7d007045252a.png)

![image](https://user-images.githubusercontent.com/3728712/110757913-f7260c00-825c-11eb-904d-6e5120e041ef.png)

EXPECTED:  should be same as in Delete dialog

![image](https://user-images.githubusercontent.com/3728712/110756224-f8eed000-825a-11eb-9987-e30b6ab626d9.png)

**Comment by alansemenov** [comment]
Styling for overflow should be in `dependant-items-dialog.less` so that it's applied to all dialogs displaying content items.
