### ISSUE TITLE
Save button gets enabled after resetting changes in image wizard

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2970]
**Case 1:**
1. Switch to a project context(SuperHero blog for example) and  upload an image .
2. Create a child layer(select a language) and switch to the child context.
3. Open the inherited image - "Language was copied..." message appears.
 
![image](https://user-images.githubusercontent.com/3728712/112455184-8a396880-8d6a-11eb-8137-4ad700e503fa.png)

4.  Do not click on `Save` button, but upload another image
![image](https://user-images.githubusercontent.com/3728712/112455378-b523bc80-8d6a-11eb-9084-16a97aea1e98.png)

**BUG** - Buttons `Reset` and `Save` are enabled at this time
4. Click on `Save` button then click on `Reset` button.

**BUG** - Button Save gets enabled after resetting the changes

![image](https://user-images.githubusercontent.com/3728712/112455950-46932e80-8d6b-11eb-9a90-cee6a0bb2599.png)

**Case 2:**
1. Switch to a project context(SuperHero blog for example) and  upload pdf-file.
2. Create a child layer(select a language) and switch to the child context.
3. Open the inherited document- "Language was copied..." message appears. click on `Save` button.
4. Upload another pdf-file: 
![image](https://user-images.githubusercontent.com/3728712/112453444-be138e80-8d68-11eb-9929-816524d7b159.png)

5. Press `Reset` button
![image](https://user-images.githubusercontent.com/3728712/112453696-ff0ba300-8d68-11eb-8c77-3bd8c9011c59.png)

**BUG** - Media link is not updated after resetting changes in inherited content

**Comment by ashklianko** [comment]
Reproduced maybe once or twice, now unable to reproduce it, will postpone for now
