### ISSUE TITLE
Display Name input doesn't get focus in the Wizard

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2973]
1. Select a project and open new `layer wizard`.
**Expected** - Display Name input in the should get focus.
**Actual** - language option filter input is focused.
![image](https://user-images.githubusercontent.com/3728712/111126700-0ae6b080-8584-11eb-9429-6c579fa175ca.png)

**BUT** - there is correct behavior if you open layer wizard without first selecting a project.

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1859](https://github.com/enonic/lib-admin-ui/issues/1859) via [**ZenHub**](https://www.zenhub.com/)
