### ISSUE TITLE
Version history has several publish events without any content change or compare possibility

### ISSUE THREAD

**Issue by mortyeriksen** [enonic/app-contentstudio#2979]
Published a lot of times without any changes, looks strange. One is a move.

<img width="277" alt="Screenshot 2021-03-12 at 10 48 08" src="https://user-images.githubusercontent.com/702065/111332607-3c3daa00-8672-11eb-904d-e6e4db661b1e.png">

Edit url: https://enonic.com/admin/tool/com.enonic.app.contentstudio/main#/default/edit/544c6a1e-8fb9-43c6-a214-398c820a0bc5

From TSI:
Ja, dette er et problem. Dvs enkelte endringer man publiserer er ikke på innholdet men metadata. (trestruktur) og da blir det kanskje slik? Jeg viste dette til Alan like før vi la ut CS 3.2. I disse tilfellene burde vi kanskje bare ha fjernet listing av de aktuelle publiseringene? Men, må verifisere hvorfor ting er slik i utgangspunktet!

**Comment by alansemenov** [comment]
These dates are in the data coming from the backend, so the order and the look of the versions looks correct. Need to find out what caused these versions if no changes are displayed in comparison.

![image](https://user-images.githubusercontent.com/11612490/111341488-db19d480-8679-11eb-86a6-f975f3ddbb15.png)

**Comment by alansemenov** [comment]
The difference between the 19/10 and the 22/10 versions is that the content was moved:
![image](https://user-images.githubusercontent.com/11612490/111341901-3ea40200-867a-11eb-84d6-5bc961784b0e.png)

**Comment by alansemenov** [comment]
This content was moved on 22/10 by Vegard and then published along with the entire site on 23/10 by Morten. I guess we could fix it to say "_Moved_" instead of "_Published_" when only the path has changed, but this will require some backend job.

**Comment by alansemenov** [comment]
Will be solved in https://github.com/enonic/app-contentstudio/issues/4916
