### ISSUE TITLE
Modal dialogs don't prevent keyboard navigation from interacting with background elements

### ISSUE THREAD

**Issue by thomasheartman** [enonic/app-contentstudio#2984]
# Issue

When a modal dialog is open, it doesn't prevent the user from navigating to the parts of the page that are in the background or from interacting with those elements. In particular this happens when the user navigates from the browser controls, even to modals that otherwise trap focus.

This also allows the user to open multiple modal dialogs.

This appears to affect all modal dialogs.

# Expected behavior

When a modal dialog is open, the user should not be able to focus (or tab to) or interact with elements in the background. 

# Video

This video demonstrates tabbing from the address bar, both forwards and backwards. Notice how the focus moves across the background when tabbing forwards. When tabbing backwards (second half of the video), the focus isn't visible, but the lower part of the screen shows the active url and it changes through a number of addresses.

https://user-images.githubusercontent.com/17786332/111482420-2db7c700-8734-11eb-9a4b-b66f721b2b63.mp4

This video demonstrates opening new modals while already having a modal open. When closing them, you also need to close multiple modals. In this case, I open three and close two. I'm not sure what happened to the third one.

https://user-images.githubusercontent.com/17786332/111483231-e7af3300-8734-11eb-93bf-b171e2ee32a2.mp4

**Comment by reisfmb** [comment]
Fixed in https://github.com/enonic/lib-admin-ui/issues/2321
