### ISSUE TITLE
Component panel not showing components

### ISSUE THREAD

**Issue by mortyeriksen** [enonic/app-contentstudio#299]
Shows them when you first ender the page editor, but if you click something they never come back.

![Screen Shot 2019-03-13 at 15 18 19](https://user-images.githubusercontent.com/702065/54286092-78c9fd00-45a3-11e9-8495-1d189a972d96.png)

![Screen Shot 2019-03-13 at 15 18 26](https://user-images.githubusercontent.com/702065/54286103-7ebfde00-45a3-11e9-80fb-c84195b7dca7.png)

**Comment by alansemenov** [comment]
@mortyeriksen Can you try with the latest version of Superhero from the Market? We cannot reproduce it.

**Comment by mortyeriksen** [comment]
The problem is in Chrome. Have you tested?

**Comment by mortyeriksen** [comment]
Works in Firefox.

**Comment by alansemenov** [comment]
@mortyeriksen let me know if you are still getting this on the release
