### ISSUE TITLE
Select project dialog doesn't trap focus when opened

### ISSUE THREAD

**Issue by thomasheartman** [enonic/app-contentstudio#2990]
# Issue

When opening the 'select project' dialog, it doesn't trap focus. This means that if the user wants to use the keyboard to navigate it, they first need to tab through everything in the background before reaching the dialog.

# Expected behaviour

When the dialog opens, it should steal focus and either focus the first element in the dialog or allow the user to navigate to the first element with a single tab press.

# Video

This video was recorded using Google Chrome on NixOS. The mouse opens the dialog. The keyboard is then used to navigate to it (using only `tab`). 

https://user-images.githubusercontent.com/17786332/111480911-c0576680-8732-11eb-93e0-3a771dc325a9.mp4

**Comment by reisfmb** [comment]
Fixed in https://github.com/enonic/lib-admin-ui/issues/2321
