### ISSUE TITLE
Even when closed, the XP menu items are still reachable via keyboard navigation

### ISSUE THREAD

**Issue by thomasheartman** [enonic/app-contentstudio#2992]
# Issue

Even when the XP menu is closed, the elements are still reachable through keyboard navigation.

# Expected behavior

When a menu is closed, I should not be able to reach the hidden elements.

# Video

This video demonstrates tabbing into the XP menu. It's most easily done by tabbing backwards from the address bar. When on one of the elements, I can also press enter to open this element in a new tab.

https://user-images.githubusercontent.com/17786332/111487038-4aee9480-8738-11eb-81bb-1524ed90fab4.mp4

**Comment by alansemenov** [comment]
Fixed in https://github.com/enonic/app-admin-home/issues/503
