### ISSUE TITLE
Incorrect order of fields resolution in the Display Name expression

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#2993]
There are two fields called "title" in the content type schema below. It's always the first one that should be used, but in this case it's the second one (inside an item-set that takes precedence).

![image](https://user-images.githubusercontent.com/11612490/111495184-690bc300-873f-11eb-9c96-11ec40e859fd.png)

Content type:
```xml
<content-type>
  <display-name>Tjeneste</display-name>
  <description>service</description>
  <super-type>base:structured</super-type>
  <display-name-expression>${title}</display-name-expression>
  <form>
    <input name="title" type="TextLine">
      <label>Title</label>
      <occurrences minimum="1" maximum="1" />
    </input>
    <item-set name="item_set">
      <label>Item set</label>
      <occurrences minimum="1" maximum="1"/>
      <items>
        <input name="title" type="TextLine">
          <label>Title</label>
          <occurrences minimum="1" maximum="1"/>
        </input>
      </items>
    </item-set>
  </form>
</content-type>
```

**Comment by sigdestad** [comment]
If one wants the second one, one should also specify "item_set.title" I suppose?

**Comment by alansemenov** [comment]
Currently not supported, so if we are to support this then it would have to be a separate issue. But yes, good idea.

**Comment by sigdestad** [comment]
Ok
