### ISSUE TITLE
Unsaved invalid value should not affect validity of the content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2994]
1. Select Features and open wizard for new  Double content
2.  Fill in the name input , type a valid value in the `required double` 
3. Type a not valid value in the `not required`  input

![image](https://user-images.githubusercontent.com/3728712/111598246-13d3be00-87e0-11eb-9eff-f32368a8a7f8.png)

**BUG** - this content gets not valid after inserting not valid value in  the top input.

**EXPECTED behaviour**:
1. `Save` button is enabled (because the name was not saved before)
2.  Content should be valid - because the top input is not required.
![image](https://user-images.githubusercontent.com/3728712/111600022-03bcde00-87e2-11eb-848d-d2649f5e0473.png)
3. Incorrect value should be cleared after saving this content: 
![image](https://user-images.githubusercontent.com/3728712/111600159-29e27e00-87e2-11eb-9ae7-72f8c9307b43.png)

4. Open existing valid double-content,  set a not valid value in the not required input.
  Save button gets disabled , but this content remains valid.
![image](https://user-images.githubusercontent.com/3728712/111600747-c3aa2b00-87e2-11eb-81af-a0810309e02b.png)

**Comment by ashklianko** [comment]
Will be fixed in https://github.com/enonic/lib-admin-ui/issues/1821
