### ISSUE TITLE
Empty details panel opens after tabbing through the elements in wizard

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#2999]
**This issue is reproducing on laptop resolution:**

1. Open wizard for new folder.
2. Press `Tab` and move focus to the next tab-able elements inside the wizard.
3. When `remove principal` icon get the focus, click again on the Tab key

BUG:   Empty details panel opens after pressing Tab key

![image](https://user-images.githubusercontent.com/3728712/111634801-e864c980-8807-11eb-903c-ebf0e125ca54.png)

**Comment by reisfmb** [comment]
@sgauruseu couldn't reproduce this one too. Maybe it was fixed by another task?!

**Comment by sgauruseu** [comment]
This bug does not reproduce in the latest version 4.2.0
