### ISSUE TITLE
 Template info in the content's info widget is not updated after the template is removed

### ISSUE THREAD

**Issue by jsi** [enonic/app-contentstudio#30]
@sgauruseu commented on [Tue Nov 20 2018](https://github.com/enonic/app-contentstudio-old/issues/550)

1. Create a site , 
2. expand the site and add a template for folder
3. Open wizard for new folder , type a name and save it , open in the wizard details panel for the folder .
4. Go to the grid and delete the template 
5.  Go to the folder wizard again 

**BUG**:  link for the deleted  template still present in  `Details Panel`, 

![image](https://user-images.githubusercontent.com/3728712/48768088-55640500-ecc9-11e8-8523-e1c1f49e2b21.png)

**if click on the link, error in console and notification will appear**

![image](https://user-images.githubusercontent.com/3728712/48768025-2483d000-ecc9-11e8-86cb-7e5b465c0812.png)

**Components  widget should not be present in folder-wizard after deleting the page-template**

![image](https://user-images.githubusercontent.com/3728712/54522702-e51b7680-497e-11e9-923d-bfe400e85e01.png)

**Comment by ashklianko** [comment]
Occurs in browse panel, not in wizard
