### ISSUE TITLE
Selected attachment(s) inside an option-set not cleared after resetting the selected option

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3001]
1. Go to `oprionset.xml` and add attachment input in Single Selection/option 1
```

        <input name="attachment1_1" type="AttachmentUploader">
           <label>Single Attachment (required)</label>
           <custom-text/>
          <help-text/>
          <occurrences minimum="1" maximum="1"/>
         </input>

```
2. Open new wizard for optionset , select the Option 1 and upload an image and save the content:
![image](https://user-images.githubusercontent.com/3728712/111780209-232e3680-88c8-11eb-9ae8-735e6c0e2d60.png)

3. Expand menu and reset the `Option 1` . Save the content
![image](https://user-images.githubusercontent.com/3728712/111780722-d139e080-88c8-11eb-81c5-bfe9eb8d1b52.png)

4.  Select `Option 1`  again  in `single selection`

![image](https://user-images.githubusercontent.com/3728712/111780877-0c3c1400-88c9-11eb-9fe4-81ced5ec1c31.png)

**BUG - Attachment input is not cleared  after resetting the option in Single Selection**

**Comment by alansemenov** [comment]
Similar to https://github.com/enonic/lib-admin-ui/issues/1758. All property values inside an unselected option should be cleared before save in [ContentWizardPanel.cleanFormOptionSetsRedundantData](https://github.com/enonic/app-contentstudio/blob/6a5359f75a0f451d51374b9ee8bc651360a32ae0/modules/lib/src/main/resources/assets/js/app/wizard/ContentWizardPanel.ts#L2165).

**Comment by ashklianko** [comment]
That one is more tricky - we also need to handle content attachment after reset and save
