### ISSUE TITLE
Added x-data with blank required input fields should make the content invalid

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3018]
1.  Specify the required text area in `x-data`
```
<?xml version="1.0" encoding="UTF-8"?>
<x-data xmlns="urn:enonic:xp:model:1.0">
  <display-name>Text Area x-data</display-name>
  <form>
     <input name="textarea" type="TextArea">
      <label>Text Area</label>
      <occurrences minimum="1" maximum="1"/>
    </input>
  </form>
</x-data>
```
2.  Specify this x-data in `site.xml`  for double content, for example

3. Open new wizard with this x-data
4. Fill in the display name input - this content gets valid - OK
5. Click on  `enable x-data`
![image](https://user-images.githubusercontent.com/3728712/112622941-c3420d80-8e3c-11eb-8337-65a7042d152b.png)

BUG: This content should be not valid after enabled x-data with required input

**Comment by alansemenov** [comment]
@ashklianko most likely after https://github.com/enonic/app-contentstudio/issues/2928. the content should get validated after adding x-data but invalid fields inside x-data form should not get invalid highlighting until the content is saved or reopened.
