### ISSUE TITLE
Option Set wizard - Save button is not enabled on change of an input with multiple occurrences

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3025]
### Case 1
1. Insert   htmlarea 2-4 in `Option 4` of Option Set (features)
```
            <items>
            <input name="htmlarea_2_4" type="HtmlArea">
              <label>HTML content 2:4</label>
              <occurrences minimum="2" maximum="4"/>
            </input>
          </items>
```
2. Open wizard for new content, fill in the name input and insert a text in the first html area
3. Click on Save button
4. Insert a text in the second html area 

**BUG - Save button must become enabled after inserting a text in the htmlarea**

![image](https://user-images.githubusercontent.com/3728712/113115682-5a301080-9215-11eb-99c2-9cb464470a3d.png)

**BUT Save button gets enabled after updating the htmlarea in reopened content** 

Reopen just created optionset and update a text in the second htmlarea 

![image](https://user-images.githubusercontent.com/3728712/113116996-b6dffb00-9216-11eb-93c4-acbff7b183f7.png)

**Save button gets enabled in this case** 

### Case 2:
**This bug is reproducing  in occurrences of double input** 
**Save** button remains disabled in new content after updating a number in the second  long-input

![image](https://user-images.githubusercontent.com/3728712/113123914-a8491200-921d-11eb-9d7f-8ead0708e2a0.png)

**Comment by ashklianko** [comment]
Not reproducing now

**Comment by sgauruseu** [comment]
I did not reproduce it in the latest version
