### ISSUE TITLE
Option Set - incorrect validation styling for multiple input occurrences inside an option-set

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3026]
1. open `optionset.xml` and   update the `option 4`:  set ` <occurrences minimum="2" maximum="4"/> in long and double inputs
2. Open wizard for new optionset, click on `Option 4`
`
BUG: Incorrect styles for required input: 

 
![image](https://user-images.githubusercontent.com/3728712/113123212-0a554780-921d-11eb-84e7-be886ca660fd.png)

**Comment by ashklianko** [comment]
Fixed in https://github.com/enonic/lib-admin-ui/issues/1888
