### ISSUE TITLE
Option Set - text is not cleared in areas after resetting options 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3027]
1. Insert htmlarea 2-4 in  `Option 1` in `Single selection`
```
    <input name="htmlarea_2_4" type="HtmlArea">
      <label>HTML content 2:4</label>
      <occurrences minimum="2" maximum="4"/>
    </input>
```
2. Open wizard for new option set , fill in the name input and select `Option 1` in `Single Selection`
3. Insert text in both htmlAreas then save the content 

![image](https://user-images.githubusercontent.com/3728712/113135018-3d520800-922a-11eb-87a1-56b5fba65899.png)

4. Reset `Option` 1 in  `Single selection` and save the content again 
5. Select `Option 1`

**BUG- text in htmlArea is not cleared after resetting the option + saving the content**  

![image](https://user-images.githubusercontent.com/3728712/113135356-b5203280-922a-11eb-86a2-bce9df5cd0fe.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1888](https://github.com/enonic/lib-admin-ui/issues/1888) via [**ZenHub**](https://www.zenhub.com/)
