### ISSUE TITLE
Lazy rendering doesn't work for Item/option sets inside site config modal window

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#3052]
When using this [site.xml](https://drive.google.com/file/d/1JUwPHZ3oMEQGEySP_ykEqgf_3Un61kKY/view?usp=sharing), the two bottom item-sets ("URLs for...") won't be rendered and nothing inside selected options of the "footer" option-set.

![image](https://user-images.githubusercontent.com/11612490/114699544-bc623880-9d20-11eb-8138-90caccde7d4d.png)

**Comment by ashklianko** [comment]
Issue with lazy render, investigating

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1898](https://github.com/enonic/lib-admin-ui/issues/1898) via [**ZenHub**](https://www.zenhub.com/)
