### ISSUE TITLE
`display-name-expression` breaks when content type has a Content Selector

### ISSUE THREAD

**Issue by thomasheartman** [enonic/app-contentstudio#3070]
Generated display names using `display-name-expression` seem to break if content type also has an ImageSelector input type. When I add the ImageSelector, the display name is no longer auto-generated (as if the expression is ignored). However, if I manually edit the display name, the path is not updated. The focus is also correctly trapped on the first input element when I load the page.

With this markup, the display name is generated as expected:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<content-type>
  <display-name>Test</display-name>
  <display-name-expression>${input}</display-name-expression>
  <super-type>base:structured</super-type>
  <form>

    <input name="input" type="TextLine">
      <label>input</label>
    </input>

  </form>
</content-type>
```

However, if I add an ImageSelector (as below), it stops working:
``` xml
<?xml version="1.0" encoding="utf-8"?>
<content-type>
  <display-name>Test</display-name>
  <display-name-expression>${input}</display-name-expression>
  <super-type>base:structured</super-type>
  <form>

    <input name="input" type="TextLine">
      <label>input</label>
    </input>

    <input name="image" type="ImageSelector" >
      <label >image</label>
    </input>

  </form>
</content-type>
```

## Versions
- *Content Studio*: 3.2.3
- *XP*: 7.6.1
- *Firefox*:  87

**Comment by thomasheartman** [comment]
Little update: It seems that ContentSelectors cause the same issue, which suggests that they're the real source of the problem.

**Comment by alansemenov** [comment]
Also https://discuss.enonic.com/t/error-when-using-display-name-expression/2488/

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1902](https://github.com/enonic/lib-admin-ui/issues/1902) via [**ZenHub**](https://www.zenhub.com/)
