### ISSUE TITLE
Error after deleting moved content in wizard 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3090]
1. Open new folder wizard and save new folder.
2. Do not close the wizard, go to browse panel , select and move tis folder to another location
3. Switch to the folder wizard again and click on Delete button in the wizard toolbar

BUG: Folder is not deleted, error message appears after  confirm the deleting 
![image](https://user-images.githubusercontent.com/3728712/116368711-4aeeb380-a811-11eb-9dca-3f10391cc387.png)

**Comment by ashklianko** [comment]
Not reproduced neither locally or on nightly, closing
