### ISSUE TITLE
HtmlArea: unable to select tools with keyboard

### ISSUE THREAD

**Issue by thomasheartman** [enonic/app-contentstudio#3095]
This may be an issue or it may just be me not being aware of how it works, but I can't seem to select tools from the HtmlArea toolbar with the keyboard. Tab takes me out of the field and there are no obvious keyboard shortcuts. Hovering over the tools reveals that some of them (such as image) have shortcuts, but others (such as macros) do not. How can I reach these using the keyboard?

**Comment by alansemenov** [comment]
We are using a 3rd party Rich Text Editor called CKEditor which doesn't support keyboard navigation in the toolbar, so there's nothing we can do about it unfortunately. You can see their demo [here](https://ckeditor.com/ckeditor-4/demo/).

**Comment by alansemenov** [comment]
Not feasible at the moment

**Comment by thomasheartman** [comment]
Thanks for the link to their website. I had a little look through their docs and their issues and it turns out that you _can_ reach the toolbar with just the keyboard. When focused within an editor area Alt+f10 moves focus to the toolbar, where tab and the arrow keys move you around. To return to the editor, press esc.

So it turns out, it _is_ accessible, it's just not very clear how to use it 😅
