### ISSUE TITLE
Build config optimisation

### ISSUE THREAD

**Issue by edloidas** [enonic/app-contentstudio#3102]
The problem is present only for the `-Penv=dev` builds.
For some reason, `lib-admin-ui` resources are processed before the actual `lib-admin-ui` is build, therefore the first clean dev build will fail. All other builds will unpack and use not the latest sources, but the sources before from the previous builds. It was fixed before by setting the dependencies of the `app-contentstudio` tasks on `lib-admin-ui` tasks. This code is probably missing or broken now.

**Comment by edloidas** [comment]
@alansemenov Just reminding you of this problem.

**Comment by alansemenov** [comment]
Yes, we need to look at this. Another issue I noticed is that running 

`./gradlew clean deploy pTML -Penv=dev`

no longer deploys `lib-contentstudio` jar to the local maven. This used to work and is needed to test Content Studio Plus locally.
