### ISSUE TITLE
Site wizard is not refreshed after reverting a version

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3128]
1. Open new wizard for site.
2. Fill the name input, select Features in app-selector. Site is automatically saved (OK)
3.  Select a controller 
4. Open Versions Panel in the wizard and revert the previous version
**BUG: Wizard page is not refreshed after reverting the version.** 
- Controller is not selected in this version
- Save button gets enabled after reverting this version
![image](https://user-images.githubusercontent.com/3728712/117278805-c1229400-ae69-11eb-9156-0f442fe1ef8e.png)

**Expected** wizard page after the reverting

![image](https://user-images.githubusercontent.com/3728712/117279359-50c84280-ae6a-11eb-820b-310258bb61c2.png)

**Comment by ashklianko** [comment]
Not reproduced, @sgauruseu please confirm

**Comment by sgauruseu** [comment]
I did not reproduce it
