### ISSUE TITLE
Tooltip for workflow state should not be shown when content is not valid

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3143]
1. Click on a valid content(Ready for publish) and open Details Panel  
1. Click on a not valid content .
2. Move cursor to the content name in Details Panel 

**BUG** - `Ready for publish` state remains visible  in Details Panel, but the content is not valid

![image](https://user-images.githubusercontent.com/3728712/117649549-525e7700-b198-11eb-9c3c-149113bcac3e.png)

**Comment by alansemenov** [comment]
Same issue in the grid (see https://github.com/enonic/app-contentstudio/issues/3708). Fix in both places.
