### ISSUE TITLE
Translate new phrases to Swedish

### ISSUE THREAD

**Issue by jsi** [enonic/app-contentstudio#317]
The following keys are missing in 'phrases_sv.properties': [dialog.table.notanumber, dialog.table.formitem.border, dialog.table.headers.col, text.noDescription, dialog.table.notawholenumber, dialog.table.formitem.rows, dialog.new.searchTypesOrDrop, dialog.table.title, dialog.permissions.applying, dialog.table.formitem.columns, field.contextPanel.noDescription, notify.dependencies.absent, dialog.table.formitem.cellSpacing, dialog.table.headers.both, dialog.table.headers.none, field.contextPanel.dependencies.description, dialog.table.alignment.right, dialog.table.formitem.alignment, dialog.table.formitem.headers, field.contextPanel.pageEditor.description, widget.useraccess.restricted, widget.pagetemplate.notused, field.contextPanel.details.description, dialog.table.alignment.none, dialog.image.style.apply, field.contextPanel.versionHistory.description, dialog.template.change, dialog.table.alignment.center, dialog.table.alignment.left, field.contextPanel.pageEditor, dialog.controller.change, dialog.table.headers.row, dialog.table.formitem.cellPadding]

**Comment by Bellfalasch** [comment]
The following keys are missing in 'phrases_sv.properties':

dialog.table.notanumber = 
dialog.table.formitem.border = 
dialog.table.headers.col = 
text.noDescription = 
dialog.table.notawholenumber = 
dialog.table.formitem.rows = 
dialog.new.searchTypesOrDrop = 
dialog.table.title = 
dialog.permissions.applying = 
dialog.table.formitem.columns = 
field.contextPanel.noDescription = 
notify.dependencies.absent = 
dialog.table.formitem.cellSpacing = 
dialog.table.headers.both = 
dialog.table.headers.none = 
field.contextPanel.dependencies.description = 
dialog.table.alignment.right = 
dialog.table.formitem.alignment = 
dialog.table.formitem.headers = 
field.contextPanel.pageEditor.description = 
widget.useraccess.restricted = 
widget.pagetemplate.notused = 
field.contextPanel.details.description = 
dialog.table.alignment.none = 
dialog.image.style.apply = 
field.contextPanel.versionHistory.description = 
dialog.template.change = 
dialog.table.alignment.center = 
dialog.table.alignment.left = 
field.contextPanel.pageEditor = 
dialog.controller.change = 
dialog.table.headers.row = 
dialog.table.formitem.cellPadding =

**Comment by Bellfalasch** [comment]
Done, but perhaps I shouldn't close it myself. Will let it sit here open and you'll take care of it. Changes are merged into master.

**Comment by jsi** [comment]
Was everything merged?  Or maybe some new phrases have arrived?  When I test the new output format of the verification tool, I get this:

```
The following keys are missing in 'phrases_sv.properties': 
 - dialog.duplicate.progressMessage
 - dialog.new.searchTypesOrDrop
 - dialog.permissions.applying
 - field.contextPanel.dependencies.description
 - field.contextPanel.details.description
 - field.contextPanel.emulator
 - field.contextPanel.noDescription
 - field.contextPanel.pageEditor
 - field.contextPanel.pageEditor.description
 - field.contextPanel.versionHistory.description
```

**Comment by jsi** [comment]
Still 3 phrases missing in Swedish : 
 - dialog.duplicate.progressMessage
 - dialog.new.searchTypesOrDrop
 - dialog.permissions.applying

**Comment by Bellfalasch** [comment]
New PR sent

**Comment by jsi** [comment]
Looks good!  ;)
