### ISSUE TITLE
Invalid Option Set is not highlighted when saved in a new content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3183]
Case 1: 
- select Features , open Option Set wizard.
-  fill in the name input and select `Option 1` in `Single Selection`
-  save the content 

**BUG**: Red borders should be displayed  in Single Selection  after saving the content

![image](https://user-images.githubusercontent.com/3728712/118966171-1d111080-b972-11eb-8daa-f5d22fc397b6.png)

**Expected:** 

![image](https://user-images.githubusercontent.com/3728712/118966308-46ca3780-b972-11eb-8e26-afd78b4141b1.png)

Case 2
- Reset the selected `option 1`  
- Save the content

**BUG**: Red border should be displayed after resetting options:
![image](https://user-images.githubusercontent.com/3728712/118966769-97419500-b972-11eb-9704-0e4bb7f91a62.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1952](https://github.com/enonic/lib-admin-ui/issues/1952) via [**ZenHub**](https://www.zenhub.com/)
