### ISSUE TITLE
Save button remains enabled after attachment is updated in a content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3189]
https://github.com/enonic/app-contentstudio/issues/1203

[pack.zip](https://github.com/enonic/app-contentstudio/files/6539557/pack.zip)
1. Upload renault.jpg
2. Open renault.jpg
3. Upload Dictyophorus_spumans01.jpg in the wizard

**BUG** - Save is enabled

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1988](https://github.com/enonic/lib-admin-ui/issues/1988) via [**ZenHub**](https://www.zenhub.com/)
