### ISSUE TITLE
Wizard does not load for text line with regexp in config

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3190]
1. Add `regexp` in textline.xml
```
 <input name="textline" type="TextLine">
      <label>Regexp IP address</label>
      <occurrences minimum="0" maximum="1"/>
      <config>
        <regexp>\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b</regexp>
      </config>
    </input>
    <input name="textline2" type="TextLine">
      <label>Regexp Email</label>
      <occurrences minimum="0" maximum="1"/>
      <config>
        <regexp>^([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})$</regexp>
      </config>
    </input>
```
2. Open new wizard for this content 

**BUG**: error in console, wizard does not load

![image](https://user-images.githubusercontent.com/3728712/119510474-37842900-bd7a-11eb-98fa-ecb91d0cb6ab.png)

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #1955](https://github.com/enonic/lib-admin-ui/issues/1955) via [**ZenHub**](https://www.zenhub.com/)
