### ISSUE TITLE
Wizard step forms are not displayed in mobile resolution

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3204]
**Case 1:**  Open existing shortcut (target is selected and single parameter added)

**BUG**: **Target and parameters are not displayed in the wizard in mobile resolution**

![image](https://user-images.githubusercontent.com/3728712/120201207-db178280-c22d-11eb-9ac1-ddb1f83da824.png)

**Case 2:** Open a site with x-data(html-area)
 Click on Add button and add x-data form

****BUG** - Html Area is not displayed in the page wizard**

![image](https://user-images.githubusercontent.com/3728712/120201405-13b75c00-c22e-11eb-8c9b-9d1a66b852b8.png)

### 4. **Click on  Html Area x-data menu item:**

![image](https://user-images.githubusercontent.com/3728712/120201753-76105c80-c22e-11eb-8ab5-1bdecafaee2d.png)

X-data gets visible

**Case 3 :  Date Time content:**

![image](https://user-images.githubusercontent.com/3728712/120203509-76a9f280-c230-11eb-80ce-ef68afb60db2.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1983](https://github.com/enonic/lib-admin-ui/issues/1983) via [**ZenHub**](https://www.zenhub.com/)
