### ISSUE TITLE
Broken layout in Site Configurator Selected Option View

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3237]
1. Open a site, Enonic for example

**BUG**:  Broken layout in all site config view.

![image](https://user-images.githubusercontent.com/3728712/122741358-8ba4ff00-d28d-11eb-875c-0f00898d67ef.png)

**### The same issue in a simple site** 

![image](https://user-images.githubusercontent.com/3728712/122741294-7c25b600-d28d-11eb-849f-6825fe2d51fc.png)

**The same issue  in Users app**

![image](https://user-images.githubusercontent.com/3728712/122782557-7e9e0500-d2b9-11eb-8c97-7ebddb82293b.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2013](https://github.com/enonic/lib-admin-ui/issues/2013) via [**ZenHub**](https://www.zenhub.com/)
