### ISSUE TITLE
Insert Panel - missed localization resource for  Rich Text Editor

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3238]
1. Open a site and drag the `Rich Text Editor`  item on the Insert panel

BUG - missed resource for  `Rich Text Editor` 
![image](https://user-images.githubusercontent.com/3728712/122742003-34ebf500-d28e-11eb-9c79-0232cd76e51d.png)

**Comment by alansemenov** [comment]
@ashklianko Let's put `field.text` back, it's ok that it's used only for D'n'D.

**Comment by ashklianko** [comment]
Seems to be some uncleaned caching issue, works OK loacally for me
![image](https://user-images.githubusercontent.com/4255706/123232041-6f999b80-d4e1-11eb-8d58-de08bcbdb78d.png)

**Comment by alansemenov** [comment]
@ashklianko Yes, because we removed `field.text` only from `phrases.properties` and your browser is not in English.

**Comment by ashklianko** [comment]
We also removed field.text from the code using it, but will recheck then

**Comment by alansemenov** [comment]
We dynamically generate and use it [here](https://github.com/enonic/app-contentstudio/blob/master/modules/lib/src/main/resources/assets/js/page-editor/DragAndDrop.ts#L563). So we can keep `field.text` only for DnD, that's fine.
