### ISSUE TITLE
Content Wizard - Show Context Panel button is not displayed for content  without Page Editor 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3267]
1. Select Features and open wizard for new Article or ItemSet

**BUG** - Show Context Panel button should be visible in the wizard page
               ( Show Context Panel  gets visible after clicking on Show Page Editor button)

![image](https://user-images.githubusercontent.com/3728712/123842717-c35d1800-d919-11eb-8845-cefc624d9285.png)

Expected: wizard page :
 
![image](https://user-images.githubusercontent.com/3728712/123643293-e8c02800-d82c-11eb-9a0a-d36dc2a0cff2.png)

**Comment by alansemenov** [comment]
I don't understand what the problem is here. The title says that the button is NOT displayed, but on the screenshot it IS displayed (and I see it as well when I create a new article)

![image](https://user-images.githubusercontent.com/11612490/123789809-d94ce780-d8dd-11eb-8b14-0bf4c55b648d.png)

**Comment by sgauruseu** [comment]
@alansemenov  sorry ,
1)  I added `Expected: wizard page :`  for this attached image 
2) Issue is reproducing when  browser.width=1970
ui-tests run on browser width =1970

And this issue is reproducing on  Chrome in full screen mode on my  monitor  23.8"

**Comment by sgauruseu** [comment]
**And there are no problems with the icon on the laptop resolution:**
![image](https://user-images.githubusercontent.com/3728712/123802897-731f8f00-d8f4-11eb-9db6-32c4846cfdaa.png)
