### ISSUE TITLE
Incorrect layout in some of the selectors' dropdown

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#3273]
It's only input types' (Content Selectors, Custom Selectors, Combobox etc.) dropdowns that should have displayed more data. Now it seems that the changes done in https://github.com/enonic/app-contentstudio/issues/3229 have affected all of the dropdowns, for example see part descriptor selector below.

Try to fix it so that the new change affects only dropdowns of the input type selectors.

![image](https://user-images.githubusercontent.com/11612490/123928548-4cae3200-d98e-11eb-8f8f-e3690dbba1ef.png)

**Comment by sigdestad** [comment]
Why would we not want bigger lists for these comboboxes? I guess there can be quite a lot of parts as well?
