### ISSUE TITLE
Text Inspection Panel - Apply button should not be displayed in the panel

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3287]
1. Insert new text component in a site
2. Type a text(insert an image) in the component and save.
3. Open `Page Component View` and click on the component

**BUG** - `Apply`  button is present on the panel, clicking on the button opens Insert tab 

![image](https://user-images.githubusercontent.com/3728712/125050185-6ba57600-e0aa-11eb-8b37-7e14f34e8891.png)

**Comment by pmi** [comment]
This is expected bahavior: when you click on text component in page components view it gets selected and text tab is activated in inspection panel. 
After clicking Apply text component is deselected and insert tab is active again.

**Comment by pmi** [comment]
After discussion with @alansemenov decided to show/hide Apply button based on descriptor form presence for all components.
