### ISSUE TITLE
Sanitize binary names

### ISSUE THREAD

**Issue by jsi** [enonic/app-contentstudio#33]
@GlennRicaud commented on [Fri Nov 23 2018](https://github.com/enonic/app-contentstudio-old/issues/569)

Binary names should be sanitized by Content Studio when uploaded
The list of illegal characters is: '/', '\', '*', '?', '|', ':'

![screen shot 2018-11-23 at 14 04 48](https://user-images.githubusercontent.com/12030113/48944966-fc92a780-ef28-11e8-83d8-390e0c1421d6.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1010](https://github.com/enonic/lib-admin-ui/issues/1010) via [**ZenHub**](https://www.zenhub.com/)
