### ISSUE TITLE
Page Component View - context menu won't close on a click outside 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3308]
1. Open new site wizard, select Features, select main region controller.
2. Open Page Component View click on `main region` then expand the menu 
![image](https://user-images.githubusercontent.com/3728712/125795239-d0368e18-ec0f-4ba9-8522-9655f5780405.png)

3. Click outside the menu 
BUG:  `main region` item gets unhighlighted, Context Menu does not close after clicking outside the menu .

![image](https://user-images.githubusercontent.com/3728712/125794446-3cfdc2f3-35fe-4091-8135-a107edf4a24f.png)

4. Click on Publish menu item
**BUG** - Context Menu and modal dialog are opened at the same time 

![image](https://user-images.githubusercontent.com/3728712/125795646-0f61eb81-29eb-45d2-a4a2-089cd0b816cc.png)

**Comment by pmi** [comment]
- Added outside click listener
- It does not work when clicking on Page Editor though because it's an iframe which swallows all events like a black hole
