### ISSUE TITLE
Publish with child items > 10000

### ISSUE THREAD

**Issue by Garlov** [enonic/app-contentstudio#334]
I've recently upgraded to enonic 7.0.0-B3, and I'm having problems with publishing.

The site is quite large, and when I try to publish with child items it doesn't show anything in the content studio publishing wizard, but I do get an error in the server log:

`Caused by: org.elasticsearch.search.query.QueryPhaseExecutionException: Result window is too large, from + size must be less than or equal to: [10000] but was [15405]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.
`

If I try to take it in smaller chunks and only publish one and one sub-folder, where the total amount of items and refs are less than 10000, it seems fine. 

I've tried with 0.9.1, 0.9.3 and at commit: 2c08e07b74edcc9b3760bb77d1e420de6d20dcbb

**Comment by alansemenov** [comment]
Hi,

You can try to increase the page size in the elastic config, as [described here](https://xp.readthedocs.io/en/stable/operations/configuration.html). Let us know if it worked :)

**Comment by GlennRicaud** [comment]
In the 'com.enonic.xp.elasticsearch.cfg'.

But we will look at it anyway.
Thank you for reporting the problem

**Comment by Garlov** [comment]
It looks like it works to set index.max_result_window = 20000, but the ui still doesn't show anything. 

When press the "with child items" button, it loads for a bit, but doesn't show the child/ref count when it's done (just like before). Then if I press the publish button, it seems to work, but it just says that it's publishing 1 item. Then the green loading bar is progressing for a while, and then everything is published.

So it works as intended, but there's a few visual bugs.

**Comment by alansemenov** [comment]
We have added error handling to resolution of dependant items here https://github.com/enonic/app-contentstudio/issues/70. It's coming in 0.9.4 release (most likely tomorrow).
