### ISSUE TITLE
Component's name is duplicated after dragging text components in Page Component View

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3349]
1. Open a site , open Page Component View , insert  several text components and save it.
2.  Swap text components several times.
3. BUG - the display name of one of the components gets duplicated (this bug does not reproduce with part, layout  components)

![image](https://user-images.githubusercontent.com/3728712/127494129-b0f2c51f-300e-436a-92d2-ecbbe82a886e.png)

**Comment by alansemenov** [comment]
@sgauruseu check if this one is still relevant
