### ISSUE TITLE
Add e-mail notification to failed tests on master/7.x branches

### ISSUE THREAD

**Issue by jsi** [enonic/app-contentstudio#3383]
This issue must be solved for lib-admin-ui, app-admin-home, app-applications and app-users in addition to app-contentstudio:

When UI tests run by GitHub Actions fail on commits, the developer is notified.  This is good, but there may be situations where everything looks good on the PR, but then fails when it is merged to a "main branch", i.e. master or a release branch, like 7.x.  These failures must be notified to the Team Core leader, @alansemenov and the Team Quality leader, @jsi

**Comment by rymsha** [comment]
I think #3394 covers it
