### ISSUE TITLE
Browse panel gets empty after clicking on Show/Hide Search Panel

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3386]
1. Click on  `Show  Search Panel` icon

 BUG: Grid gets empty after the clicking 

![image](https://user-images.githubusercontent.com/3728712/128470149-1d083419-ce38-4ef0-a603-f1414f49d3c6.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2083](https://github.com/enonic/lib-admin-ui/issues/2083) via [**ZenHub**](https://www.zenhub.com/)
