### ISSUE TITLE
Changing a part config bypass "Mark as ready"

### ISSUE THREAD

**Issue by mortyeriksen** [enonic/app-contentstudio#3387]
Change a field on the part config for a published item:
<img width="1679" alt="Screenshot 2021-08-06 at 09 48 31" src="https://user-images.githubusercontent.com/702065/128476202-b2c072b7-d7e0-47e5-abdb-aef9fedc5a09.png">

Click apply and get the publish button, but should be "Mark as ready":
<img width="1680" alt="Screenshot 2021-08-06 at 09 48 47" src="https://user-images.githubusercontent.com/702065/128476227-55c0192a-eb88-4389-b10a-f8c7b84cdee1.png">

**Comment by alansemenov** [comment]
This is fixed
