### ISSUE TITLE
Menu items are not fully shown in Access Selector

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3388]
1. Open project wizard select a role then expand the menu in Access Selector 
![image](https://user-images.githubusercontent.com/3728712/128478202-701f7e93-328a-4f7e-b3a7-063da8bb95ee.png)

2. The same issue in  Edit permissions dialog 

![image](https://user-images.githubusercontent.com/3728712/128478461-f8a521d4-c259-49f2-9843-8828dc91dd08.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2079](https://github.com/enonic/lib-admin-ui/issues/2079) via [**ZenHub**](https://www.zenhub.com/)
