### ISSUE TITLE
Workflow icon is not displayed in content browse panel

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3389]
1. Open CS :

**BUG**  - workflow icon is not displayed: 
![image](https://user-images.githubusercontent.com/3728712/128487441-e7347650-f30b-487e-b619-c1caa6b256fe.png)

**But it is displayed in the wizard**

![image](https://user-images.githubusercontent.com/3728712/128487581-5cf6eb44-d611-4d93-b356-fc97cdbfd9f8.png)

**Comment by alansemenov** [comment]
@ashklianko caused by https://github.com/enonic/app-contentstudio/pull/3376
