### ISSUE TITLE
Html Area content - broken layout after version rollback

### ISSUE THREAD

**Issue by jsi** [enonic/app-contentstudio#34]
@sgauruseu commented on [Mon Dec 03 2018](https://github.com/enonic/app-contentstudio-old/issues/591)

1. Select `Features` and open HtmlArea wizard
2. Type a name in the wizard, save it 
3. Go to `Second HTML content ` . Click on `Add` button and add one more html area. 
4. Insert an  image (see the screenshot) and save all

![image](https://user-images.githubusercontent.com/3728712/49379271-c4a51480-f71f-11e8-84cf-8081b335ace1.png)

5. Open `Versions` in the wizard and restore the previous  version 
6. Click on the htmlara that is below the area with the image 
7. Restore the version with the image again 

**Bug: Layout is broken** .   _Layout is getting normal after refresh the page in browser_

![scr1](https://user-images.githubusercontent.com/3728712/49379518-5745b380-f720-11e8-8649-64ad24c493b3.png)

**Comment by ashklianko** [comment]
@sgauruseu please run tests on HtmlArea after this is done to be sure nothing is broken, thanks!
