### ISSUE TITLE
Duplicate of a content is inherited in layer without child elements

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3400]
1. Create a layer in Default project
2. Switch to Default context and duplicate `Features` and `Large Tree` folder
3. Switch to the layer's context

BUG - Inherited duplicated content  have no children 
![image](https://user-images.githubusercontent.com/3728712/128887186-91cd66d5-51a5-4c93-a20f-687008fd6bc5.png)

**Comment by vbradnitski** [comment]
Issue moved to [enonic/xp #9239](https://github.com/enonic/xp/issues/9239) via [**ZenHub**](https://www.zenhub.com/)
