### ISSUE TITLE
Item Set, Occurrence View -  tooltip for 'Add' button is not shown after saving a new added set

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3437]
**Case 1:**
1. Open Shortcut Wizard and fill in the name input, select a target.
2. Move the cursor to the `Add Parameters` button. Tooltip for the button gets visible (OK)

![image](https://user-images.githubusercontent.com/3728712/130421740-6da06a3a-74d9-41fc-bb6d-a14e0821659d.png)

3. Click on `Add Parameters`  type a data and click on Save button

**BUG** - The tooltip is not  shown after saving a parameter

![image](https://user-images.githubusercontent.com/3728712/130422203-27ed1381-d836-4178-a076-61751f0b8c34.png)

**Case 2:**
1 Open Nested Forms Item Set in  `Features`
2. Fill in the name input, click on Add button and click on Save 
3. Move the cursor to the Add button in the bottom
**BUG**:   Expected tooltip `Add Level 1` should be displayed

![image](https://user-images.githubusercontent.com/3728712/130424605-b39f86a2-3965-4674-a3a2-8b52f58060ec.png)

EXPECTED tooltip:

![image](https://user-images.githubusercontent.com/3728712/130424771-498a0f68-af9a-42bf-88e5-d2c03c86fd56.png)

**Comment by alansemenov** [comment]
Tooltips on toggle icons stopped working after first click
