### ISSUE TITLE
Details panel does not load when opening Templates folder

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3439]
1. Switch  a browser to the full screen mode.
2. Expand Features and double click on `Templates` (_templates) folder 

**BUG**: 
- Details Panel is not loaded 

![image](https://user-images.githubusercontent.com/3728712/130453328-6a831bf7-c495-4443-ac9d-bff19f47c9f5.png)

Click on `Show Context Panel`

**BUG** - Details Panel is in `Floating` mode

**Comment by ashklianko** [comment]
Fixed in https://github.com/enonic/app-contentstudio/pull/3848
