### ISSUE TITLE
Inconsistent threshold of switching between the Details Panel modes

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3440]
**Case 1**
1. Set width of a browser window to  about 1700- 1800
2. Select `Features` in the grid - `Details Panel` is loading in `Docked` mode

![image](https://user-images.githubusercontent.com/3728712/130459569-c2766c4e-a764-41fe-a933-d59afddf54fe.png)

3. Open `Features` in wizard  - The panel's mode is floating

![image](https://user-images.githubusercontent.com/3728712/130459670-aaab6213-5596-4184-af78-41eb3aa03548.png)

BUG  - The mode of Details Panel should be the same  

**Case 2:** 

1. Navigate to `https://dev-branch-nightly.enonic.net/admin/tool`
2. Set browser to `Full screen` mode
3. Open filter Panel 
4. Type `Cape_Agulhas_P1040396` and do double click on  the filtered image
5. The image is opened in wizard

**BUG: Details Panel should be loaded automatically after opening an image content**

**Comment by alansemenov** [comment]
See also https://github.com/enonic/app-contentstudio/issues/2563

**Comment by alansemenov** [comment]
Fixed earlier
