### ISSUE TITLE
`allowContentType` config doesn't work in site's x-data

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#3464]
```xml
  <form>
    <input name="allowArticle" type="ContentSelector">
      <label>Allow articles from this site</label>
      <occurrences minimum="0" maximum="0"/>
      <config>
        <allowContentType>article</allowContentType>
      </config>
    </input>
  </form>
```

This config (filtering of content by content type inside a selector) will work as intended in a content type form or x-data or a part in any content below a site, but not on a site itself. There filtering doesn't work.

To reproduce:
1. Install the Features app locally
2. Change `resource/site/x-data/menu-item/menu-item.xml` by replacing its form with the form above.
3. Deploy the app

In Content Studio open any content inside the Features site and expand the selector inside the "Menu" x-data.

Sorting is correct:
![image](https://user-images.githubusercontent.com/11612490/130959321-89971c9e-499d-4017-9fb4-25acac1c776e.png)

Now open the Features site itself, expand the same selector inside the same x-data:

![image](https://user-images.githubusercontent.com/11612490/130959407-b0397c31-3285-45ec-bac3-879d3b0dfa12.png)

**Comment by rymsha** [comment]
X-Data, Part and Layout forms, when presented on a Site, get a Site content Id. ContentId is used to resolve ContentType, that is portal:site.
So, app name is `portal`. And partial, or wildcard names don't work correctly assuming "article" to be "portal:article"
There is no content type "portal:article".

There is another issue: when filter finds no match, query returns ALL content types.
