### ISSUE TITLE
When creating template in Content Studio the page controller does not show up in the dropdown

### ISSUE THREAD

**Issue by ComLock** [enonic/app-contentstudio#3466]
If you try to type some letters in the search box, it might how up after a while.

<img width="553" alt="Screenshot 2021-08-27 at 10 08 58" src="https://user-images.githubusercontent.com/118847/131094936-b95c9437-0d77-4cbf-b663-cded978684a0.png">

**Comment by ComLock** [comment]
The request and response looks fine

![Screenshot 2021-08-27 at 12 46 59](https://user-images.githubusercontent.com/118847/131116889-58fc8a05-0b4a-459b-b778-2233cba32b71.png)


![Screenshot 2021-08-27 at 12 42 22](https://user-images.githubusercontent.com/118847/131116884-98bffa0e-252c-46b2-9f99-0b804c7c8bef.png)

Might have something to do with using Promises?


![Screenshot 2021-08-27 at 12 47 51](https://user-images.githubusercontent.com/118847/131116875-68583313-be54-4c5a-814b-fa7e7d7e5195.png)


Using this browser

![Screenshot 2021-08-27 at 12 48 35](https://user-images.githubusercontent.com/118847/131116870-66896748-9d79-498c-8a1b-6ee305f1ccaa.png)

**Comment by alansemenov** [comment]
@ComLock any news on this one? still reproducing for you?

**Comment by ComLock** [comment]
Well unless anyone has fixed it, and released a new version of XP or Content Studio... This was discovered during training courses and witnessed by many, and I tried many times.

**Comment by ComLock** [comment]
The only possible idea I could come up with is my Mod-Header plugin in the browser being enabled with a Authorization header (and not locked to a specific browser tab). But I don't think that's the case. However I could try again (when I'm not deep in something else).

**Comment by alansemenov** [comment]
No longer seem relevant
