### ISSUE TITLE
500 Error after deleting a child folder 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#352]
1. Add the parent folder : "folder1"
2. Open Filter panel , type "folder1", select the folder, open new wizard and save the child folder  "folder2". Do not close the wizard 

3. Click on `Delete` button and delete the child
4. Wizard closes and tab with grid is loaded :

![image](https://user-images.githubusercontent.com/3728712/54922169-aa828280-4f18-11e9-8120-3a5b70f0bd9c.png)

5. Press `Delete ` button on the grid-toolbar

**BUG**: 
`null` **appears in notification message**

![image](https://user-images.githubusercontent.com/3728712/54922299-e584b600-4f18-11e9-88a6-a932020017f0.png)

**Click on Clear link.  this message appears again** 

![image](https://user-images.githubusercontent.com/3728712/54922376-0baa5600-4f19-11e9-937e-de2e66fa529b.png)

`Failed to load resource: the server responded with a status of 500 (Server Error)
_all.js:1 null
DefaultErrorHandler.handle @ _all.js:1
`

**Click on refresh-icon:** 

![image](https://user-images.githubusercontent.com/3728712/54922635-a2771280-4f19-11e9-8031-ad376e2ba550.png)

**Comment by pmi** [comment]
Issue moved to [enonic/lib-admin-ui #973](https://github.com/enonic/lib-admin-ui/issues/973) via [**ZenHub**](https://www.zenhub.com/)
