### ISSUE TITLE
Display name field no longer gets focus in the new content wizard

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#353]
After the fix of https://github.com/enonic/app-contentstudio/issues/325 the display name field no longer gets focus when creating a new content. Now the cog icon gets focus.

**Comment by edloidas** [comment]
Issue moved to [enonic/lib-admin-ui #969](https://github.com/enonic/lib-admin-ui/issues/969) via [**ZenHub**](https://www.zenhub.com/)
