### ISSUE TITLE
Fix spacing in the Content grid

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#3592]
Now:
![image](https://user-images.githubusercontent.com/11612490/134678770-79568073-756c-4a40-ae8c-4a37121141c6.png)

Was:
![image](https://user-images.githubusercontent.com/11612490/134678283-4d37747f-eb5f-4f1d-bb40-6971d8b4a7fa.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2150](https://github.com/enonic/lib-admin-ui/issues/2150) via [**ZenHub**](https://www.zenhub.com/)
