### ISSUE TITLE
Changes to the sidebar menu

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#3593]
* Expand the sidebar by default
* Change the Content Studio tree icon to the pencil icon as it was
* Replace the Archive button with this one (`drawer` in the "IcoMoon - Free" set):

![image](https://user-images.githubusercontent.com/11612490/134679243-e46605d5-1067-4b78-ad58-6612df38fc36.png)

**Comment by ashklianko** [comment]
Both studio and studio-plus to be updated
