### ISSUE TITLE
Fix duplicate icons

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#3636]
https://github.com/enonic/app-contentstudio/blob/epic-archive-new/modules/app/src/main/resources/assets/icons/icons.less
https://github.com/enonic/app-contentstudio/blob/epic-archive-new/modules/lib/src/main/resources/assets/icons/icons.less

**Comment by ashklianko** [comment]
I've also noticed that lots of icons in contentstudio lib also overlapping with icons in lib-admin-ui, so will try to remove duplicated also from contentstudio lib
