### ISSUE TITLE
Trigger default preview after controller handled request

### ISSUE THREAD

**Issue by espen42** [enonic/app-contentstudio#3654]
Sometimes we have a mapping that handles all requests, but decide (during controller handling) that it's better to use the default preview rendering in content studio. We want to be able to return some signal in the response for this (e.g. a partifcular status code or just `null`) that will cause content studio to fall back to the default rendering.

**Comment by alansemenov** [comment]
@espen42 Why don't you use a filter for this and either return "next" (if you want default rendering) or custom response for custom rendering?

**Comment by sigdestad** [comment]
That sounds like a plan :-)
