### ISSUE TITLE
Incorrect validation for checkbox input type

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3665]
1. Configure a required checkbox
```
<input name="checkbox1_1" type="Checkbox">
      <label>Requred CheckBox</label>
      <indexed>true</indexed>
      <custom-text>Custom text</custom-text>
      <occurrences minimum="1" maximum="1"/>
      <help-text>checkbox</help-text>
    </input>
```
2. Open new wizard for this content, fill in the name input and save it 

**BUG: this content should be invalid and the validation recording  `'This field is required'` should appear after saving this content, because the checkbox is required** 

3. Update the checkbox configuration
```
<input name="checkbox2_4" type="Checkbox">
      <label>To Check</label>
      <indexed>true</indexed>
      <custom-text>Custom text</custom-text>
      <occurrences minimum="2" maximum="4"/>
      <help-text>checkbox</help-text>
    </input>
```
4. Open new wizard , fill in the name input and save it 

**BUG:  Incorrect validation recording appears - `Min 2 valid occurrence(s) required`**
**Expected: Checkbox input doesn't support occurrences. So in case of minimum>1 the validation message should be the same as for minimum=1: `'This field is required'`**

![image](https://user-images.githubusercontent.com/3728712/137134361-687485ff-d12d-4c63-b276-ed28ce364876.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2344](https://github.com/enonic/lib-admin-ui/issues/2344) via [**ZenHub**](https://www.zenhub.com/)
