### ISSUE TITLE
Combo Box incorrectly loads options after selecting an option with Enter key

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3673]
https://user-images.githubusercontent.com/3728712/150769668-635be27f-3fcb-4b48-814d-57acc9c69f1b.mp4

1. Select Features and open wizard for new `Combo box` content
2. go to `Required 2, max 4` combobox,  type the `111` text in the filter option input

![image](https://user-images.githubusercontent.com/3728712/137500200-47cd198b-5cb1-4054-a32b-21b5b07fdfe1.png)

3. Press the `arrow down key` then press `Enter` key - the option is selected.

![image](https://user-images.githubusercontent.com/3728712/137499399-606df27d-905d-4674-b7ec-65ccd3372a18.png)

4. Click on `Remove` icon and remove the selected option
5.  Click on the dropdown handler and expand options in the combobox

**BUG:  Only one option is loaded in the dropdown list,**

![image](https://user-images.githubusercontent.com/3728712/137500026-7643e2e0-aea6-4ca3-a849-fd27693b2cfb.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2515](https://github.com/enonic/lib-admin-ui/issues/2515) via [**ZenHub**](https://www.zenhub.com/)
