### ISSUE TITLE
Tooltip for workflow state should not be shown for invalid content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3708]
1. Create a ready for publishing shortcut, for example
2. Click on remove icon and remove the selected target option in the shortcut
3. Go to grid, move the cursor to the shortcut

**BUG**:  `Ready for publishing` tooltip appears

![image](https://user-images.githubusercontent.com/3728712/138079316-4d92bfdb-62bf-4c97-aa18-0708eec12827.png)
 
**Expected** - the tooltip should be hidden for invalid content

**Comment by alansemenov** [comment]
See also https://github.com/enonic/app-contentstudio/issues/3143

**Comment by alansemenov** [comment]
Duplicate of https://github.com/enonic/app-contentstudio/issues/3143
