### ISSUE TITLE
Launcher Panel does not load in MS Edge

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#375]
Type a correct name and password and log in.
Bug: Launcher  Panel is not loaded .

![image](https://user-images.githubusercontent.com/3728712/55237059-4fb39880-5242-11e9-8274-b81cf3d529bd.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #975](https://github.com/enonic/lib-admin-ui/issues/975) via [**ZenHub**](https://www.zenhub.com/)
