### ISSUE TITLE
Invalid grid layout

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#3761]
Clicking the refresh icon fixes it.

![image](https://user-images.githubusercontent.com/11612490/139701966-9e3e87f4-0fc4-40f5-be94-2f37d816ba38.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2238](https://github.com/enonic/lib-admin-ui/issues/2238) via [**ZenHub**](https://www.zenhub.com/)
