### ISSUE TITLE
Nested Form Item Sets - incorrect behaviour of validation when 2 levels added

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3773]
1. Select Features and open wizard for new `Nested Form Item Sets` content
2. Fill in the name input
3. Click on `Add level` button twice - two levels are present in the wizard
4. Fill in the required input in the first Level

![image](https://user-images.githubusercontent.com/3728712/139868924-e0de6971-9236-4c13-8ac1-6e724d6d546e.png)

**BUG** - The content gets valid after filling required input in the first Level, but required inputs are empty in the second added level,  `Mark as Ready` button appears on in the wizard toolbar  

**The content gets invalid after clicking on `Save` button.**

![image](https://user-images.githubusercontent.com/3728712/139869081-2bba8ddb-ded0-411f-bdec-c1ab512fffcd.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2518](https://github.com/enonic/lib-admin-ui/issues/2518) via [**ZenHub**](https://www.zenhub.com/)
