### ISSUE TITLE
Revert button should be hidden in the Version History widget inside Archive

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3777]
1. Archive a folder.
2. Go to Archive app , select the folder and open `Versions Widget` 
3. click on `Revert` button - error message appears 

**BUG** - `Revert` button should be hidden in the version items
![image](https://user-images.githubusercontent.com/3728712/140061256-fe70e354-6940-4f4e-b832-db35d820328e.png)

**Comment by alansemenov** [comment]
Issue moved to [enonic/app-contentstudio-plus #271](https://github.com/enonic/app-contentstudio-plus/issues/271) via [**ZenHub**](https://www.zenhub.com/)
