### ISSUE TITLE
Archive app - confirmation dialog should not appear when deleting single content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3778]
1. Go to Archive app select a single content and click on Delete
2. Click on `Delete now` button

**BUG** - Confirm delete dialog should not be loaded for single content

![image](https://user-images.githubusercontent.com/3728712/140064442-d5ff7a05-0e2b-4426-a817-e99d2d12ea62.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/app-contentstudio-plus #287](https://github.com/enonic/app-contentstudio-plus/issues/287) via [**ZenHub**](https://www.zenhub.com/)
