### ISSUE TITLE
Image Wizard - incorrect height of the Image Editor toolbar

### ISSUE THREAD

**Issue by jsi** [enonic/app-contentstudio#38]
@sgauruseu commented on [Mon Dec 17 2018](https://github.com/enonic/app-contentstudio-old/issues/622)

1. Open an existing image 
2. Do scroll the page 
Bug: height of the toolbar  is more then height of the 'wizard step'-  toolbar 

![image](https://user-images.githubusercontent.com/3728712/50078056-04c3c700-01f7-11e9-882d-6b3699301b3d.png)

**Comment by pmi** [comment]
Problem was not in the height of the editor toolbar, but in the incorrect positioning above the wizard toolbar, instead of underneath it. Should be this way:
![annotation 2019-01-28 161955](https://user-images.githubusercontent.com/754221/51838876-a2db9e80-2318-11e9-8c49-9417520ae067.jpg)
