### ISSUE TITLE
Docked Details Panel remains empty after a content is selected

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3811]
**Case 1:**
1. Set a browser to full screen mode 
2. Select a content 

BUG : Details panel remains empty after selecting a content

![image](https://user-images.githubusercontent.com/3728712/140898541-2894e039-0a52-4ee9-b84b-d1554e32668f.png)

**Case 2:** 
1. Set a browser to full screen mode 
2. Open an existing folder

**BUG 
- Details panel should be loaded  when there is enough space in the browser
- clicking on `Show context panel` button does not open the panel the first time**

![image](https://user-images.githubusercontent.com/3728712/140899547-a5b49b23-e3b9-4b9d-921f-c23652a4dac8.png)

**Comment by alansemenov** [comment]
@ashklianko this is currently a cause of failure of UI tests. please look at it when you have a chance.
