### ISSUE TITLE
Changing order of selected options of a Content Selector makes the browser freeze

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/app-contentstudio#382]
Happened during training at NAV. Using beta-3 of XP7.

They have this ContentStype with only one ContentSelector with infinite amount of items added. The one example I used contained roughly 200 added items.

When adding new items, they will appear at the very bottom of that list (which itself is annoying) so I scrolled all the way down. I then tried to drag it upwards (which also was very difficult to pull off without a mouse and scroll wheel btw). Roughly half-way up through the list I gave up, but when I released/dropped the item the Chrome browser stalled completely and had to be restarted.

**Comment by alansemenov** [comment]
I reproduced it on 20 selected items in one of the Content Selector inside the Features's Selector content type. The more items selected in the selector, the more CPU load increases inside the browser thread after an item is DnD'ed.
