### ISSUE TITLE
Details panel does not load when opening new wizard in a non-root directory

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3824]
1. Set a browser in full screen mode, open new folder wizard in the root directory, Details Panel loads automatically (OK)  
2. Select `Large tree` folder and open new wizard for folder 

BUG -  Details panel does not load when  new wizard is opened for a child content

**Comment by alansemenov** [comment]
See also https://github.com/enonic/app-contentstudio/issues/3439

**Comment by sgauruseu** [comment]
the bug is not reproduced in the latest version of CS
