### ISSUE TITLE
Restore from Archive dialog  is missing scrollbar

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3825]
1.  Open Archive Brose Panel , select more than 25 items(items should be without child)
2. Click on Restore or Delete button in the toolbar 

BUG -  scrollbar is missing in the modal dialog 

![image](https://user-images.githubusercontent.com/3728712/141451249-9a79225c-0fa4-44ae-b01b-577d36530201.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/app-contentstudio-plus #289](https://github.com/enonic/app-contentstudio-plus/issues/289) via [**ZenHub**](https://www.zenhub.com/)
