### ISSUE TITLE
Confirm clearing the form on deselecting an option in an OptionSet

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/app-contentstudio#383]
During NAV training in beta-3 of XP7 multiple persons worked with a ContentType containing an OptionSet. What they thought was after an option is selected and filled in, you could use the checkbox again to just hide the form of that option. They tried, and it disapear, and clicking it again opened the form showing the previous filled in data. Happy days. So they hide it by unchecking and then save. Now the data is lost.

It would be nice to be made aware as a user that deselecting options will remove that data on save. Even better, "hide/expand"-toggles of their own, much like how ItemSets work.

I believe that with ItemSets if you close them (using "x" icon) in XP7 you are warned that it will delete the data. This should also be the case with OptionSets.

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1022](https://github.com/enonic/lib-admin-ui/issues/1022) via [**ZenHub**](https://www.zenhub.com/)
