### ISSUE TITLE
"Restore content" dialog is missing progress bar

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#3830]
Should be exactly the same behaviour as in the Archive dialog - progress bar inside the dialog, then one refresh of the grid. See also https://github.com/enonic/app-contentstudio/issues/3826

**Comment by ashklianko** [comment]
Issue moved to [enonic/app-contentstudio-plus #298](https://github.com/enonic/app-contentstudio-plus/issues/298) via [**ZenHub**](https://www.zenhub.com/)
