### ISSUE TITLE
Input with a mix of valid and invalid occurrences is considered valid

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#3834]
When there's a mix of valid and invalid occurrences in the same input view, the input is considered valid:

![image](https://user-images.githubusercontent.com/11612490/141769812-416e0325-04a4-443a-a9c8-59017d0089c1.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2275](https://github.com/enonic/lib-admin-ui/issues/2275) via [**ZenHub**](https://www.zenhub.com/)
