### ISSUE TITLE
Inconsistent behaviour of the Page Editor & Context panel layout

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3852]
1. Set a browser in full screen mode, Open new `Article` or double wizard
2. Click `Show Page Editor` 
3. Click on `Hide Page Editor` 

BUG - Splitter and scrollbar gets not visible after click on  `Hide Page Editor` 

![image](https://user-images.githubusercontent.com/3728712/142435485-f63c9cf4-1296-4c15-adea-0d8f1bf39c08.png)

**Comment by alansemenov** [comment]
Current issues with Context panel:
* No splitter/scrollbar between the Content form and the Context panel, but only when there's no Page Editor panel. When Page Editor is present, the splitter is there.
* Context panel stopped being responsive, but only when Page Editor IS present. When there's no Editor, the Context panel is responsive.
