### ISSUE TITLE
Content wizard - Incorrect position of 'Show help texts' button when Live Edit is not loaded

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3857]
1. Set a browser to laptop resolution , select `Features` and open  article wizard
![image](https://user-images.githubusercontent.com/3728712/142600962-1da6868e-9ac3-4e3d-98b0-78922e202bad.png)

**BUG** - Incorrect position of 'Show help texts' button

**Expected** : 

![image](https://user-images.githubusercontent.com/3728712/142601745-0c0c8259-c47d-4cb9-b967-be2d81dfa933.png)

**Comment by alansemenov** [comment]
No longer relevant
