### ISSUE TITLE
Content Wizard - error in console after opening a content with Preview Panel

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3887]
1. Set a browser to full screen mode. 
2. Select Features , and open new wizard for content with Live Edit, `Option Set` ,  for example 

BUG - error in console appears 

![image](https://user-images.githubusercontent.com/3728712/143441408-6fa582e4-59ed-4d8d-9fdb-e2ab0964a344.png)

**Comment by ashklianko** [comment]
Сan't reproduce, @sgauruseu can you please verify it is still there also?
