### ISSUE TITLE
Can't replace a deleted image in the HML Area's Image dialog

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#392]
1. Open new wizard with html  area.
2. Click on `Insert image` button and upload an image(Child content will be added )
3. Save and close the wizard,
4. Expand the content in the grid and delete image that was uploaded
5. Open content with Html Area again 

Bug:   Caption and icon remains in html area. Do double click on the icon and try to upload another image. **Error in console and endless spinner appear**   .

![image](https://user-images.githubusercontent.com/3728712/55549897-9fc9a980-56df-11e9-904c-a452b2320202.png)

![image](https://user-images.githubusercontent.com/3728712/55549876-904a6080-56df-11e9-9981-3e915aef8491.png)

`Endless spinner`:

![image](https://user-images.githubusercontent.com/3728712/55549940-b8d25a80-56df-11e9-915a-af58286a1d2e.png)

**Comment by alansemenov** [comment]
It's correct that there are errors in console when opening content, because the image referred by image tag inside the HTML Area is missing. But it should of course be possible to replace the image in the dialog, without the spinner etc.
