### ISSUE TITLE
Details panel stays responsive in floating mode

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#3945]
See video. After switching from docked to floating mode the panel remains responsive and finally gets correct "fixed" width when the browser window is narrowed down even more. This happens only in the Content Wizard. When the panel switches modes it should not change its width, as in docked mode min width of the panel is 280px and in floating mode the width is always 280px.

https://user-images.githubusercontent.com/11612490/145843612-4a818c12-b072-4191-bdf6-f6310383e715.mov

**Comment by ashklianko** [comment]
Done in https://github.com/enonic/app-contentstudio/pull/3990
