### ISSUE TITLE
[MS Edge] Controller Selector  is not displayed in the site wizard after selecting an application 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#396]
1. Open new site-wizard in MS Edge, type a name , save it.
2. Select Features in applications. Press the Save 

BUG:  page controller selector does not appear after selecting the application (the selector appears after refreshing the page )

![image](https://user-images.githubusercontent.com/3728712/55638051-01b50c80-57cf-11e9-867f-6328111930cc.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #977](https://github.com/enonic/lib-admin-ui/issues/977) via [**ZenHub**](https://www.zenhub.com/)
