### ISSUE TITLE
Drag'n'Drop of inputs(occurrences block)  in Option Set is not working

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#3982]
1. Update the `optionset.xml`  - insert `Double input 2:4`  in  `Single Selection` and `Multi Selection` 
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<content-type xmlns="urn:enonic:xp:model:1.0">
  <display-name>OptionSet</display-name>
  <super-type>base:structured</super-type>
  <form>
    <option-set name="radioOptionSet">
      <label>Single selection</label>
      <expanded>false</expanded>
      <help-text>Single selection radio option set</help-text>
      <occurrences minimum="1" maximum="1"/>
      <options minimum="1" maximum="1">
        <option name="option_1">
          <label>Option 1</label>
          <help-text>Help text for Option 1</help-text>
          <items>
            <input name="name" type="TextLine">
              <label>Name</label>
              <help-text>Text input</help-text>
              <occurrences minimum="1" maximum="1"/>
            </input>
            <item-set name="minimum3">
              <label>Minimum 3</label>
              <occurrences minimum="3" maximum="0"/>
              <items>
                <input name="double1" type="Double">
                  <label>Double</label>
                  <indexed>true</indexed>
                  <occurrences minimum="2" maximum="4"/>
                </input>
                <input name="label" type="TextLine">
                  <label>Label</label>
                  <occurrences minimum="0" maximum="1"/>
                </input>
                <input name="value" type="TextLine">
                  <label>Value</label>
                  <occurrences minimum="0" maximum="1"/>
                </input>
              </items>
            </item-set>
          </items>
        </option>
        <option name="option_2">
          <label>Option 2</label>
          <help-text>Help text for Option 2</help-text>
        </option>
      </options>
    </option-set>
    <option-set name="checkOptionSet">
      <label>Multi selection</label>
      <expanded>true</expanded>
      <help-text>Multi selection checkbox option set</help-text>
      <occurrences minimum="1" maximum="1"/>
      <options minimum="1" maximum="3">
        <option name="option_1">
          <label>Option 1</label>
          <help-text>Help text for Option 1</help-text>
        </option>
        <option name="option_2">

          <label>Option 2</label>
          <default>true</default>
          <help-text>Help text for Option 2</help-text>
        </option>
        <option name="option_3">
          <label>Option 3</label>
          <help-text>Help text for Option 3</help-text>
          <items>
            <input name="double2" type="Double">
              <label>Double</label>
              <indexed>true</indexed>
              <occurrences minimum="2" maximum="4"/>
            </input>
            <input name="imageselector" type="ImageSelector">
              <label>Image selector</label>
              <indexed>true</indexed>
              <occurrences minimum="1" maximum="1"/>
              <config/>
            </input>
          </items>
        </option>
        <option name="option_4">
          <label>Option 4</label>
          <help-text>Help text for Option 4</help-text>
          <items>
            <input name="double" type="Double">
              <label>Double</label>
              <indexed>true</indexed>
              <occurrences minimum="2" maximum="4"/>
            </input>
            <input name="long" type="Long">
              <label>Long</label>
              <indexed>true</indexed>
              <occurrences minimum="2" maximum="4"/>
            </input>
          </items>
        </option>
      </options>
    </option-set>
  </form>
</content-type>


```

2. Open new wizard for Option Set , 
3.  Fill in both double inputs in any selection 
4. Try to swap these inputs  

![image](https://user-images.githubusercontent.com/3728712/146372455-51a891ec-a4f8-42b5-b671-c90e2d759a29.png)

BUG - Drag'n'Drop of inputs  in Option Set is not working

**Comment by reisfmb** [comment]
@ashklianko [PR](https://github.com/enonic/lib-admin-ui/pull/2511) fixing it in lib-admin-ui.

**Comment by ashklianko** [comment]
Hi Bruno! Your fix seems to break drag'n'drop in other place: try Nested Form Item Set under Features site - drag and drop for items not working:
![image](https://user-images.githubusercontent.com/4255706/163342559-eee1a087-ade3-4e7a-8b88-9694c4aed68d.png)
Also me and @sgauruseu have totally different problem with drag'n'drop in the case mentioned in issue description, @sgauruseu will give video

**Comment by sgauruseu** [comment]
I have rechecked this issue in `optionset`  in `Features`
It is still not possible to swap two long inputs in `Option 1` in  multiselect


https://user-images.githubusercontent.com/3728712/163342869-b06df554-f132-4d8b-9d2e-260eeeffb9ea.mp4

**Comment by sgauruseu** [comment]
but there are no problems with dragging htmlarea in option 3

https://user-images.githubusercontent.com/3728712/163343413-ec73c0b5-ed45-4b92-8310-e631b6860411.mp4

**Comment by sgauruseu** [comment]
This issue is reproducing with  `Date`, `Long`, `Double` inputs in  option items
There are no problems with dragging  of Content Selector selected options and htmlArea




https://user-images.githubusercontent.com/3728712/163349270-5383d64c-e57e-4e79-95cb-aacf665c1779.mp4

**Comment by reisfmb** [comment]
@ashklianko @sgauruseu I'll take a look in those cases. Thanks.

**Comment by reisfmb** [comment]
@ashklianko @sgauruseu 

Made an adjustment and tested with the cases that were mentioned above. All working right now.

Can you take a look again after [this](https://github.com/enonic/lib-admin-ui/pull/2511/commits/90cdb0a5234dbb893d18004ed9482da8259259c2) commit?

**Comment by ashklianko** [comment]
Are any commits to be done in this repo regarding issue?

**Comment by reisfmb** [comment]
> Are any commits to be done in this repo regarding issue?

@ashklianko no, only to lib-admin-ui

**Comment by sgauruseu** [comment]
There are no problems with  Drag'n'Drop of inputs in the latest build in master. Probably, this issue was fixed in lib-admin-ui

**Comment by reisfmb** [comment]
@ashklianko shouldn't we close this since this [PR](https://github.com/enonic/lib-admin-ui/pull/2511/) is already merged to master in lib-admin-ui?

**Comment by ashklianko** [comment]
Done in https://github.com/enonic/lib-admin-ui/issues/2510
