### ISSUE TITLE
Archive item(s) wizard includes outdated text

### ISSUE THREAD

**Issue by vot-enonic** [enonic/app-contentstudio#4000]
When pushing the triangle button next to the red "Archive" button, the text says "Delete now".
![Screenshot 2021-12-20 204515](https://user-images.githubusercontent.com/43465080/146823977-545114c2-ef82-490e-aee4-5708b2fb3ce1.png)

**Comment by alansemenov** [comment]
@vot-enonic why is it outdated? this button will instantly delete content as opposed to the main action ("Archive") which moves content to the archive.

**Comment by vot-enonic** [comment]
I thought it was a mistake. Could it be improved, UX-wise? Instead of "Delete Now", maybe only "Delete"? I am not sure. In any case I was confused by it, as an editor.

**Comment by alansemenov** [comment]
Ok, will change to "Delete".
