### ISSUE TITLE
[Regression] Content Wizard form is missing left padding on higher resolutions

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#4015]
We used to have two layout modes in the Content Wizard. When Wizard panel was more than 960px wide we applied left padding of 110px to `.wizard-steps-panel`. After some changes done to the wizard header, the padding is gone and the form is always left-aligned.

Last version where it worked correctly was XP 7.6.1 + CS 3.2.4:
![image](https://user-images.githubusercontent.com/11612490/146933697-b2c99834-e2bc-4ed6-abce-14c577a7275f.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2376](https://github.com/enonic/lib-admin-ui/issues/2376) via [**ZenHub**](https://www.zenhub.com/)
