### ISSUE TITLE
Content status is not fully shown in selectors

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4019]
1. Select Features and open new wizard for `Custom Relationship` , for example
2 Expand the selector 

**BUG:   status is not fully shown in the selector**
![image](https://user-images.githubusercontent.com/3728712/146949564-36f66fe0-64c9-48e3-8655-90de9395eb55.png)

###  **The same  issue in `Selector` content**

![image](https://user-images.githubusercontent.com/3728712/146949758-097c7863-c95a-4d09-bea5-3e4710d4d763.png)

**Comment by ashklianko** [comment]
Fixed in https://github.com/enonic/app-contentstudio/pull/5304
