### ISSUE TITLE
Content Selector - error appears after collapsing an option in tree mode

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4021]
https://user-images.githubusercontent.com/3728712/147087764-17fd1483-060b-40a5-9dd8-cd40b3078257.mp4

1. Open wizard for new Custom Relationship content
2. Select 2 options

![image](https://user-images.githubusercontent.com/3728712/147084619-7d8c8628-c4fc-479e-913b-e924de599a79.png)

**3. Click on mode toggler and switch to tree mode , expand  `Features`  in the options:**  

![image](https://user-images.githubusercontent.com/3728712/147084688-f723c88b-a85f-4999-9ad4-17c196cbaf9e.png)

**4. Collapse the `Features` in the options**

**BUG: error appears in console,** 
![image](https://user-images.githubusercontent.com/3728712/147084747-85e7412d-f19a-4d53-8a0d-02971d83eabe.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2437](https://github.com/enonic/lib-admin-ui/issues/2437) via [**ZenHub**](https://www.zenhub.com/)
