### ISSUE TITLE
Site Wizard in MS Edge - Unable to type a search text in filter input  in Component View

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#405]
1. Open Features , Insert an image-component (fragment, layout)
2. Try to type a text in the search input

![image](https://user-images.githubusercontent.com/3728712/55787964-20adea00-5ac0-11e9-9cf9-eb01dd186a20.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #985](https://github.com/enonic/lib-admin-ui/issues/985) via [**ZenHub**](https://www.zenhub.com/)
