### ISSUE TITLE
Content Wizard with Image Selector - Save button  gets enabled in the wizard after deleting the image in grid

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#407]
1. Open new content wizard (Image Selector) type a name and select an image, save it . Do not close the wizard
2. Go to the grid and delete just selected image.
3. Go to the wizard again.

BUG: Save button is enabled in the wizard 

![image](https://user-images.githubusercontent.com/3728712/55791702-c6b12280-5ac7-11e9-9fa9-636ea16be37d.png)

**Comment by alansemenov** [comment]
This is not a bug. We store a reference to selected image in the image selector content. When the image is selected, the reference is deleted (and the image disappears from the list of selected options under the selector), the content changes and that's why the Save button gets enabled.
