### ISSUE TITLE
Do not use `eval`

### ISSUE THREAD

**Issue by rymsha** [enonic/app-contentstudio#4072]
`eval()` is used by DisplayNameResolver to calculate display-name expressions. It's unsafe and should be replaced.

**Comment by alansemenov** [comment]
Research a library which can help us here

**Comment by alansemenov** [comment]
This one looks legit and super-secure: https://www.npmjs.com/package/vm2. Running it might be an overkill, so check how much memory it consumes.

**Comment by rymsha** [comment]
Wow, I did not know it would work in browsers, or does it?

Anyway, we seem to support only very limited expression syntax https://developer.enonic.com/docs/content-studio/stable/content-types#display_name_expression . It is possible to support via RegExp
