### ISSUE TITLE
Archive items dialog - inbound references are  not filtered in new browser tab after 'Show inbound' button is clicked

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4074]
1. Create a shortcut , select an image in the target selector 
2. Select the image and open `Archive item` dialog.
3. Click on  `show the inbound references` button

**BUG - Not filtered grid is loaded in the new browser tab**. (This issue does not reproduce in  Details widget)

![image](https://user-images.githubusercontent.com/3728712/148354680-239e27cc-1f1e-4a16-b8b5-bbdd6d6fdaa6.png)

**Comment by alansemenov** [comment]
Most likely caused by https://github.com/enonic/app-contentstudio/commit/72125fbaf32b3d1d989a0fbdb502df4edab774c2
