### ISSUE TITLE
Site Configurator dialog -Html area lost the focus after clicking in the area, toolbar blinks 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4075]
1. Open a site with html area in config
2. Open Site configurator and try to insert a link in the area 

**Bug**  - Html area lost the focus

https://user-images.githubusercontent.com/3728712/148356624-c836ba03-a2ab-4988-8cde-5d9c9ad4cfbe.mp4

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2364](https://github.com/enonic/lib-admin-ui/issues/2364) via [**ZenHub**](https://www.zenhub.com/)
