### ISSUE TITLE
File upload dropdown stops working due to new security headers

### ISSUE THREAD

**Issue by rymsha** [enonic/app-contentstudio#4089]
Probably After this https://github.com/enonic/xp/issues/8642#issuecomment-1008811981

File upload dropdown functionality just does not upliad the file without any error message in console

**Comment by alansemenov** [comment]
Upload works, but it takes a while before the uploaded item appears in the grid (unless you refresh the page). It also seems to only happen the first time, subsequent uploads appear right away.
