### ISSUE TITLE
Translate "pending" and "expired" to Norwegian

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/app-contentstudio#410]
In Content Studio the statuses "Published (pending)" and "Published (expired)" is not translated to Norwegian other than "Published" being translated to "Publisert". Could we also translate "expired" to "utløpt" and "pending" to "venter" or something better?

![93ec9045-6e91-4bcc-b4ec-ab9ebd7f069d](https://user-images.githubusercontent.com/1465598/55793052-505df180-5ac2-11e9-9e4f-7e40c565b1e0.png)

**Comment by alansemenov** [comment]
Translations added in https://github.com/enonic/lib-admin-ui/issues/978 (only english and russian for now)
