### ISSUE TITLE
Incorrect behavior of validation in modal dialogs containing inputs with config

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4102]
1. Add the next input in `site configurator`  or  `macros.xml`
```
<input name="textarea" type="TextArea">
      <label>Text Area</label>
      <occurrences minimum="0" maximum="0"/>
      <config>
        <max-length>41</max-length>
      </config>
    </input>
```
2. Open `Site Config Dialog` and insert more than 41 chars

BUG - `Apply` button should be disabled when any input contains invalid data

![image](https://user-images.githubusercontent.com/3728712/148933801-b4a21c83-3acc-43ef-bdad-04028d4f7ca6.png)

**The same issue** in `Insert Macro` dialog:

![image](https://user-images.githubusercontent.com/3728712/148933983-26c6c8fa-3bad-49eb-af8f-b7063f1b559e.png)

**Comment by ashklianko** [comment]
This is a perfectly VALID form on your picture since you have min=0 occurrences and input is not required to be valid to make entire form valid.
