### ISSUE TITLE
Limit available languages per project

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-contentstudio#4106]
We need to support a mechanism that will limit the "locales" aka languages a user may select when working with content.

This should be implemented as a configuration via the "project settings" edit form.
NB! Design for this needs to be created before this task can be implemented:

NB! If content with a "non allowed" language already exits in the project, this must continue working seamlessly, even if the list of allowed languages are changed (also when copying the item etc).

**Comment by poi33** [comment]
Wont fix
