### ISSUE TITLE
ContentSelector inside HtmlArea link-dialog should show content status

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/app-contentstudio#411]
The ContentSelector inside the "Create Link" dialog inside a HtmlArea is not possible to configure (which is troublesome in itself). When linking to items here you'll struggle with not knowing what item is the correct one if you have multiple items with the same name in multiple locations. Trying to search for "Dagpenger" on NAV will give me 100s of results in this list, impossible to know which one is the correct. At least showing status ("Published", "Deleted", "Edited", would help alot). Could we have that?

(bonus would be to also on hover on these items show full URL/path since this is usually cut and not useful)

![Screenshot 2019-04-09 at 12 31 48](https://user-images.githubusercontent.com/1465598/55793597-99627580-5ac3-11e9-800d-61899b0e1d04.png)

**Comment by alansemenov** [comment]
@Bellfalasch you remember that you can use the folder icon in the selector to switch to the tree mode, right? it will still switch to the flat list when you use search but if you know exactly where the item is located then the tree mode is a way to go.

**Comment by alansemenov** [comment]
Done in https://github.com/enonic/app-contentstudio/issues/2887
