### ISSUE TITLE
Embed macro should not allow preview

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4115]
1. Open Features site, insert a text component 
2. Insert `Embed IFrame` in the component 
3.  insert ``` <iframe src='http://www.enonic.com'> enonic</iframe>``` in the config tab
4. Click on Insert then click on `Preview`  in the wizard toolbar

BUG : Error appears in the console -  Refused to display 'https://enonic.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'. 

![image](https://user-images.githubusercontent.com/3728712/149754106-cc6698bd-1cd4-4f36-ae3c-5af8b40cede2.png)

![image](https://user-images.githubusercontent.com/3728712/149754165-847c2188-35da-45f1-a65b-bd6bb4392769.png)

**Comment by alansemenov** [comment]
Change the Preview tab of the Embed macro to show "`Preview of this macro is not allowed`".

![image](https://user-images.githubusercontent.com/11612490/162433152-aa296834-470d-4bc8-9643-fdcd5236a522.png)

**Comment by sgauruseu** [comment]
One test is failing because the area remains empty after pressing the Insert button and Preview tab is activated:

https://user-images.githubusercontent.com/3728712/163159398-33b0795b-7702-4a93-84a1-ae5779648ff2.mp4

**Comment by sigdestad** [comment]
Hmm.. Are we saying that preview of embeds should not be allowed any more? How will editors be able to verify if they are working then?

**Comment by alansemenov** [comment]
Preview content containing the macro.
