### ISSUE TITLE
Image Wizard - Save button gets enabled after uploading an image

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#413]
1. Open an image,  and upload another image

BUG:
- Notification Message - 'image saved' appears but button Save gets enabled 
- icon is not updated in the wizard 

![image](https://user-images.githubusercontent.com/3728712/55801297-6aa5c880-5ade-11e9-92e6-0201f171516e.png)

**Comment by sgauruseu** [comment]
This bug still reproducing on Windows (but  does not reproduce on Nightly server )

**Comment by sgauruseu** [comment]
[IMG.ZIP](https://github.com/enonic/app-contentstudio/files/3406162/IMG.ZIP)

**Comment by vbradnitski** [comment]
Issue moved to [enonic/lib-admin-ui #1094](https://github.com/enonic/lib-admin-ui/issues/1094) via [**ZenHub**](https://www.zenhub.com/)
