### ISSUE TITLE
Incorrect selection behavior after filtering items via aggregation view

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4146]
1. Open  Features context 
2. Open `Filter Panel`
3. Click on `Landing page (27)` checkbox
4.  Click on `Select all rows` checkbox

![image](https://user-images.githubusercontent.com/3728712/150786824-3e58fa70-e060-4e49-b4a9-11462e714c86.png)

5. The number of items in Selection Panel Toggler  (circle) is 27 - OK

6. Click on  `Image aggregation checkbox`

![image](https://user-images.githubusercontent.com/3728712/150787383-e5abd9f3-c317-4cd1-8ee9-05af5a8941a9.png)

**BUG**:   Images should not be selected in the filtered  grid

7. Click on `Archive` button  
8. Click on Archive button in the modal dialog 
 Filtered  images remain in the grid 

![image](https://user-images.githubusercontent.com/3728712/150789314-2053df22-0aa1-4c2d-8a16-6da273100a6e.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2442](https://github.com/enonic/lib-admin-ui/issues/2442) via [**ZenHub**](https://www.zenhub.com/)
