### ISSUE TITLE
Cannot update part config on qa.enonic.com

### ISSUE THREAD

**Issue by mortyeriksen** [enonic/app-contentstudio#415]
I'm getting these exceptions:
<img width="1680" alt="Screenshot 2019-04-09 at 18 04 31" src="https://user-images.githubusercontent.com/702065/55816207-0e4ca400-5af2-11e9-804a-86ec2a63ff25.png">

<img width="1673" alt="Screenshot 2019-04-09 at 18 04 15" src="https://user-images.githubusercontent.com/702065/55816209-11479480-5af2-11e9-8a52-00d5a07e53da.png">

**Comment by alansemenov** [comment]
1. In the Features app find a part called "city-map".
2. Open city-map.xml and replace the contents with this:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<part xmlns="urn:enonic:xp:model:1.0">
  <display-name>City Map</display-name>
  <form>
    <input name="count" type="Long">
      <label>Number of blog posts to show</label>
      <default>10</default>
      <occurrences minimum="1" maximum="1"/>
      <config>
        <min>0</min>
        <max>100</max>
      </config>
    </input>
  </form>
</part>
```
3. Open Content Studio, open the Features site for edit
4. Build page structure as shown on the screenshot below (layout with two columns and City Map part inside both columns)
5. Now select the first part, change value inside the input in the Inspect panel, then select the second part and do the same. No need to save anything, just change the value inside the input. Keep switching between the parts and changing values - usually happens after 3-4 times - until you get errors in the console.

![image](https://user-images.githubusercontent.com/11612490/55914261-fefb5280-5be6-11e9-9eb6-f802a50a8f23.png)

**Comment by vbradnitski** [comment]
Issue moved to [enonic/lib-admin-ui #980](https://github.com/enonic/lib-admin-ui/issues/980) via [**ZenHub**](https://www.zenhub.com/)
