### ISSUE TITLE
Direct issue link should automatically set correct project

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#4162]
When clicking "Show details" button in the issue email, user gets a dialog for selecting a project/layer. After selecting the project, user ends up in that project's Content Browse view (instead of opening the issue details dialog).

How it should be: we should either determine project by issueId (if issueId is unique across the projects) or pass projectId as a part of the issue link. In any case, user should not be asked to select a project.

**Comment by sigdestad** [comment]
Issue id's are unique p.t., but we should probably also include the project name in the mail link

**Comment by ashklianko** [comment]
Project name is already included in the email's issue link, I am having issue link correctly open in whatever project
