### ISSUE TITLE
Previewing newly uploaded video (mp4) in CS never starts/loads

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/app-contentstudio#419]
When uploading this video (2-3 MB, found here: https://drive.google.com/file/d/1S5IGOS4bpxwhoFWIhQztUr-G1egAPQ94/view?usp=sharing) to XP7 and latest CS will not work in Firefox Dev Edition. The previewing "mode" looks like it starts to load inside the grid, the loading "snake" with dots starts spinning but it spins forever and the video never starts to play and I never see the length in seconds of the video either. Basically previewing/playing the video is not possible from CS.

![Screenshot 2019-04-10 at 10 56 48](https://user-images.githubusercontent.com/1465598/55866002-bd838c80-5b7f-11e9-9236-6ee5417e89f7.png)

**Comment by Bellfalasch** [comment]
I pulled latest commits from Content Studio app, built it, and ran it on RC1 of XP7 - video now actually works. It plays instantly.

**Comment by alansemenov** [comment]
Yep, works fine on Nightly
