### ISSUE TITLE
Inline preview won't show custom error 500 from XP

### ISSUE THREAD

**Issue by pmi** [enonic/app-contentstudio#4190]
Currently CS shows failed to render when 500 response is returned,
but XP can render custom error pages with status 500 that need to be displayed
Start looking at ContentItemPreviewPanel:370

Possibly send a custom header from XP along with 500 status to tell CS to show it

**Comment by alansemenov** [comment]
We need to discuss what we want to do in this case:
1. Keep it like now: output error message in CS' inline preview, disable Preview button
2. Have XP add some kind of header to the HEAD response, which will help CS understand that this is a custom error page and make another request (this time GET) to output the custom error page body.

**Comment by sigdestad** [comment]
Lets consider 500 a real error and get the 418 fixed now. If we get a 500, lets show the while thing to the editor. It will likely be more informative for them than "contact someone"

**Comment by rymsha** [comment]
Does not seem to worth spending time on this edge case, IMO

**Comment by rymsha** [comment]
Live view can solve it, if needed
