### ISSUE TITLE
Apply 'unsafe-eval' in CSP when doing LiveEdit injection

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#4221]
Instead of doing it in [XP](https://github.com/enonic/xp/commit/e553325829b89c13f5fa0b3328a2edb403357cad), do it when injecting [LiveEdit](https://github.com/enonic/app-contentstudio/blob/master/modules/app/src/main/java/com/enonic/xp/app/contentstudio/LiveEditInjection.java) in Content Studio

**Comment by alansemenov** [comment]
Will be done in XP

**Comment by rymsha** [comment]
After a few trials we ended up specifying meta SCP tag injected by CS.
A few more details can be found [here](https://github.com/enonic/xp/issues/9360)
