### ISSUE TITLE
Normalise file name before upload

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#4222]
If filename contains Norwegian letters (ÅØÆ) and the filename was set in MacOS, then uploading such a file to Content Studio will result in "Unsafe attachment name" error message and the file won't be uploaded. Run filename through `normalise('NFC')` which will make it Linux-compatible.

**Comment by rymsha** [comment]
info about normalization https://unicode.org/reports/tr15/

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #2494](https://github.com/enonic/lib-admin-ui/issues/2494) via [**ZenHub**](https://www.zenhub.com/)
