### ISSUE TITLE
Page component loses selection in the Page Components view after descriptor is selected

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#424]
1. Open a site / Page Editor
2. Open the Page Components view
3. Add a part inside the Page Components view (via context menu)
4. Select descriptor for this part (inside the Inspect panel)

The page auto-saves, the part remains selected on the page and inside the Inspect panel but it's no longer selected inside the Page Components view

**Comment by vbradnitski** [comment]
Issue moved to [enonic/xp #7085](https://github.com/enonic/xp/issues/7085) via [**ZenHub**](https://www.zenhub.com/)
