### ISSUE TITLE
Issue Details dialog -  'No comments yet' placeholder remains visible after adding a comment

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4247]
1. Open Issues list dialog
2. Click on  a task, Issue Details dialog is loaded.
3. Add a comment and click on `Comment` button

BUG:  'No comments yet' is visible after adding a comment

![image](https://user-images.githubusercontent.com/3728712/154254789-04f0208b-ad9f-4bee-816e-5452a0cdac6e.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2431](https://github.com/enonic/lib-admin-ui/issues/2431) via [**ZenHub**](https://www.zenhub.com/)
