### ISSUE TITLE
Thumbnail URLs are hardcoded to `/admin`

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#4250]
URLs of image thumbnails in the Content grid and Content Wizard seem to be hardcoded to `/admin` and stop working if admin is mapped differently in the vhost config.

![image](https://user-images.githubusercontent.com/11612490/154308149-42affc18-483b-470b-a3f6-7514ae53f58c.png)

![Screenshot 2022-02-16 at 17 16 46](https://user-images.githubusercontent.com/11612490/154308567-c0bf860f-2b32-45cc-b5f2-d34740545a10.png)

**Comment by rymsha** [comment]
They are not hardcoded, but have an extra leading `/` that makes them protocol-relative, and no url-rewrite happens.
