### ISSUE TITLE
Table editing in rich text editor uses old legacy format of styling

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/app-contentstudio#426]
In XP7 and new CS the table editor will add table properties like padding, spacing, and such in the old legacy format (as attributes on the table element itself). This works in the editor, but when saving and watching a part/website trying to show this in modern browsers, it usually doesn't work. This should be added as style attributes (this is proper way to style tables) as this will not be overwritten by

Using the table editor setting padding and spacing gives this format, something we haven't seen since when XHTML was hot and new:

`<table border="1" cellpadding="3" cellspacing="5" style="width:100%">`

Most modern websites set some type of reset code on tables in their CSS, and the way styling is applied on websites, attributes like this will always loose, making sure this feature is useless for the end-users.

Video of me trying this out on Superhero: https://drive.google.com/file/d/1aTNDYvRJP_G4T2IV060zmcqMCFK3b_e_/view?usp=sharing

**Comment by alansemenov** [comment]
@Bellfalasch This is CKE plugin that does it, we cannot configure this.

@ashklianko Check if you can make changes to the plugin code to wrap the properties inside the style attribute.
