### ISSUE TITLE
`<allowContentType>media:svg</allowContentType>` allowing more than svgs

### ISSUE THREAD

**Issue by reisfmb** [enonic/app-contentstudio#4261]
The expected behavior for `<allowContentType>media:svg</allowContentType>` inside a MediaSelector input type is to restrict the medias to .svg files only, but it seems that this isn't what is happening as can be seen:
![image](https://user-images.githubusercontent.com/67838246/154961995-5ddd39fd-4931-43db-94d2-1cedf9f985d5.png)
That field has the following schema:
```
<input type="MediaSelector" name="icon">
    <label>Svg icon to use</label>
    <occurrences minimum="1" maximum="1"/>
    <config>
        <allowContentType>media:svg</allowContentType>
    </config>
</input>
```
and it's allowing the selection of images with different extensions (such as .png in the first image for example)

**Comment by alansemenov** [comment]
Proper content type for SVG (and other vector graphics) is "`media:vector`".

Here's a media selector with proper config allowing me only one SVG file:

![image](https://user-images.githubusercontent.com/11612490/154964735-d396ba3e-1583-4c27-9f43-f17b5ca9ed1c.png)

**Comment by sigdestad** [comment]
Yea, we don't have a special media type for SVG right now - maybe we could even just do stupid filtering on extension one day :-)
