### ISSUE TITLE
Hide "Settings" and "Access" sections for non-admins

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/app-contentstudio#428]
Only show these parts of the content form for admins, CMS experts, and CMS admins? It is something that confuses us all during training and demonstration "What are those fields for..." etc. It would be really nice to make the interface even less poluted by removing things like this that most editors will not need to use. When we introduce localization they might need the language-setting, but the others could still be hidden (fully or behind a button/toggle to show them). Main point is don't show all these fields by default for users with limited capabilites.

![Screenshot 2019-04-12 at 11 44 56](https://user-images.githubusercontent.com/1465598/56028464-711f8480-5d18-11e9-89c4-0ca65f6a107a.png)

**Comment by sigdestad** [comment]
Yes, we will restrict this to:
CMS Admin (role)
CMS Experts (role)
System admin (role)
Users with "full access" permission for the item
