### ISSUE TITLE
[Regression] Preview of a shortcut shows target content

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#4294]
When preview request for a selected content returns 3xx code, show our standard "Preview not unavailable" message instead of showing the redirect target content as now.

**Comment by sigdestad** [comment]
IMHO It should use the same panel as was used in CS 4.0.2 - basically saying it will redirect, and a link to go there?

**Comment by alansemenov** [comment]
No idea what you mean. We never had anything like that.

**Comment by sigdestad** [comment]
Try clicking a shortcut item i current version

**Comment by alansemenov** [comment]
What should I be looking at?

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/11612490/156628488-5bcd9d77-47cd-4bb3-8902-3b5a4878dbf9.png">

**Comment by sigdestad** [comment]
Hmm.. What does this look like in 4.0 (or even the latest 3.x)?

**Comment by alansemenov** [comment]
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/11612490/156722678-471bbc00-7667-4ecb-95b1-e894f77a4946.png">
