### ISSUE TITLE
Save button gets enabled after content has  been unpublished in the wizard page

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4296]
1. Open wizard for new folder , fill in the name input and save it ,
2. Expand the publish menu and click on `Publish....` menu item .
3. Click on `Mark as ready` menu item in the modal dialog 

![image](https://user-images.githubusercontent.com/3728712/156758029-1509da6f-5b98-4c3b-8491-696b603c7a2e.png)

4.  `Publish Now` button gets enabled, click on it.
5.  `Unpublish` gets visible in the default action
6.  Unpublish this folder.

BUG - Save button gets enabled after this content has been unpablished, workflow state gets `Work in progress`

![image](https://user-images.githubusercontent.com/3728712/156758557-bfa6d804-fbe2-4661-9702-0ceb44e2b7b2.png)

**Comment by alansemenov** [comment]
Most likely caused by https://github.com/enonic/lib-admin-ui/commit/28264d725b8b6bff0dccada2529c3d2123210752 - publish from/to fields in the Schedule form modify property values. Probably belongs in lib-admin-ui.

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2450](https://github.com/enonic/lib-admin-ui/issues/2450) via [**ZenHub**](https://www.zenhub.com/)
