### ISSUE TITLE
Publishing Wizard - Cancel button should be enabled, when a site has invalid items

### ISSUE THREAD

**Issue by jsi** [enonic/app-contentstudio#43]
@sgauruseu commented on [Tue Dec 18 2018](https://github.com/enonic/app-contentstudio-old/issues/632)

1. Add an invalid child content to Features
2. Select Features and press "Publish tree"

**Issue 1:  Cancel button is disabled** 
![image](https://user-images.githubusercontent.com/3728712/50158516-5e0a2400-02e5-11e9-84b2-444cec533e4c.png)

**Issue 2:**
- add a child site to Features. Do not type a name of the site and close the wizard
- select Features and press Publish Tree
 **Item for the  Invalid   child site is not removable** :
![image](https://user-images.githubusercontent.com/3728712/50159018-ae35b600-02e6-11e9-994f-4476a6b36e04.png)

**Comment by ashklianko** [comment]
Regarding part 2 of issue: item is not removable when it has child items; New site has template folder created inside of it, thus when you delete it Site will become removable.
