### ISSUE TITLE
ImageSelector does not display images in gallery mode and loads forever in form

### ISSUE THREAD

**Issue by vot-enonic** [enonic/app-contentstudio#4311]
In my Cloud (XP 7.8.3 and Content Studio 4.0.2) the ImageSelector is behaving strangely. The gallery mode displays empty placeholders, while the form in e.g. a post on the Superhero Blog just keeps loading (see lower left corner on the second screenshot).
![ImageSelector Gallery](https://user-images.githubusercontent.com/43465080/157446908-777a3d3a-80a0-469a-9fbb-294d137951fc.png)
![ImageSelector in form panel](https://user-images.githubusercontent.com/43465080/157446916-fb715b33-00c6-463e-9494-2a8e0c86953b.png)

**Comment by vot-enonic** [comment]
This is still an issue and makes it difficult to create explainer videos.

**Comment by alansemenov** [comment]
Not a CS issue. Solved by recreating the cloud solution.
