### ISSUE TITLE
Ckeditor scaling an image in fullscreen mode does not trigger a new save state

### ISSUE THREAD

**Issue by poi33** [enonic/app-contentstudio#4315]
The ckeditor does not save image scaling when they are done in the fullscreen mode. 
Any text change does trigger a new "save" state.

**Comment by ashklianko** [comment]
Hi, @poi33, could you please explain more what is wrong, my changes of image scaling of the image in the fullscreen mode enable Save button after fullscreen dialog is closed

**Comment by poi33** [comment]
@ashklianko tried to recreate it in the newest version. 
I could not, so might have bin a bug in earlier versions 🤷 feel free to close

**Comment by ashklianko** [comment]
Thank you @poi33, closing it then!
