### ISSUE TITLE
Help text overflow in occurrences block

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4335]
1. Open optionset.xml  and insert a long help text for an input
2. Open wizard for new option set and click on Show Help text toggler

BUG ; Help text overflow in the form

![image](https://user-images.githubusercontent.com/3728712/158837757-2c676ba1-aba1-4b84-9db4-f402e82980f2.png)

**Comment by alansemenov** [comment]
Apply `.ellipsis()` mixin in CSS

**Comment by sgauruseu** [comment]
I can not reproduce this bug in the lates version, probably this issue was fixed in another task
![image](https://user-images.githubusercontent.com/3728712/162782490-25101add-4412-4928-84e5-33d2d1b73cc7.png)


![image](https://user-images.githubusercontent.com/3728712/162784506-9552b6b1-2d95-443e-8129-30a7538d83c9.png)
