### ISSUE TITLE
Option form is not displayed after rollback a version

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#434]
1. Select Features, open wizard for new `Option Set`.
2. Type a name, save it
3. Click on Option 1 radio and fill the form, save it
4. Click on Option 2 radio , save it
5. Open versions widget and rollback the version with filled `Option 1`

**BUG**: `Option 1` form restored incorrectly:
 
![image](https://user-images.githubusercontent.com/3728712/56138853-65de8a00-5fa0-11e9-9050-5bfb42246def.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #989](https://github.com/enonic/lib-admin-ui/issues/989) via [**ZenHub**](https://www.zenhub.com/)
