### ISSUE TITLE
Multi-select option-set allows selecting more than maximum options

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4354]
1.  Select `Features`, open wizard for new  `OptionSet`
2.  Select  3 options in the `Multi selection`, the fourth checkbox gets disabled - OK

![image](https://user-images.githubusercontent.com/3728712/159925630-500a9671-9c80-4d6a-8e0e-cc31972c5a98.png)

3. Save the  content, then close and then reopen it  or just refresh the page in browser

**BUG**: The fourth checkbox is enabled after reopening the content. Click on the option - validation message gets visible

![image](https://user-images.githubusercontent.com/3728712/159926348-da4883b8-90fd-46a6-9f85-ff0e3be43c3a.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2513](https://github.com/enonic/lib-admin-ui/issues/2513) via [**ZenHub**](https://www.zenhub.com/)
