### ISSUE TITLE
CKEditor: Newly opened Link dialog shows old values

### ISSUE THREAD

**Issue by jsi** [enonic/app-contentstudio#44]
To reproduce in SiteConfigurator dialog:
1. Open SiteConfigurator dialog with CKEditor, click on any image in editor
2. Open link dialog and enter some tooltip and enter link data (any type of link), close dialog (no matter if you insert link or just cancel it)
3. Close SiteConfigurator dialog
4. Open SiteConfigurator dialog and try to insert link anywhere in Editor 

To reproduce in Features.HtmlArea content:
1. Add image in one editor, click on it
2. Open link dialog and enter some tooltip and enter link data (any type of link), close dialog (no matter if you insert link or just cancel it)
3. Click inside any other editor and open Link Dialog

Result: old values present

**Comment by ashklianko** [comment]
Here is correct way to reproduce this:
1. Open SiteConfigurator dialog with CKEditor, click on any image in editor
2. Open link dialog and enter some tooltip and enter link data (any type of link), close dialog (no matter if you insert link or just cancel it)
3. Close SiteConfigurator dialog
4. Open SiteConfigurator dialog and try to insert link anywhere in Editor 

Result:  first of all when you open Link dialog you'll see that old data is already typed in, and if you try to insert link it will throw this exception
