### ISSUE TITLE
Image wizard laptop resolution -  image toolbar is overlapping options in the wizard's toolbar dropdown

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4405]
1. Create a site, then add new page-template and select Image in the support
2. Upload an image to the site.
3. Select the image and click on `Edit` button.
4. Click on `Show Page Editor` button.
5. Click on the wizard toolbar menu

BUG:  image toolbar is overlapping options in the expanded menu

![image](https://user-images.githubusercontent.com/3728712/161981440-be05e7aa-077b-46cb-a73f-994e0725fd5c.png)

**Comment by alansemenov** [comment]
Most likely a simple z-index fix
