### ISSUE TITLE
Image Editor: move action buttons to the bottom toolbar

### ISSUE THREAD

**Issue by ashklianko** [enonic/app-contentstudio#4435]
On small screens action buttons in the editor's toolbar might be wrapped on next line, overlapping active working zone of the editor tools. This problem will evolve when new editor tools added. See a picture below:

![image](https://user-images.githubusercontent.com/4255706/162973900-fb0e515a-ac55-424c-b1a5-43238f657934.png)

To fix:
Add a bottom toolbar with action buttons moved into it:

![image](https://user-images.githubusercontent.com/4255706/162976157-b52e7c2b-b86b-418c-b1c2-c6a359fe650b.png)

**Comment by alansemenov** [comment]
If we do that, Apply and Cancel buttons must swap places and Reset should be left-aligned.

**Comment by sgauruseu** [comment]
Image Editor Tollbar  should not move when the image is cropping 


https://user-images.githubusercontent.com/3728712/163144413-1a4a0caf-4e2b-4111-813c-b081d99687a2.mp4

**Comment by sgauruseu** [comment]
I updated ui-tests, but one test is still failing due to the next issue:
`Reset Mask` should not be visible when the edit mode is closed.

![image](https://user-images.githubusercontent.com/3728712/163144562-6291bdc0-0e12-456a-80e9-5355f1d8aa75.png)

**Comment by reisfmb** [comment]
@sgauruseu 

> Image Editor Tollbar should not move when the image is cropping

Still discussing with Sasha the expected behavior of the bottom toolbar in crop mode.

> I updated ui-tests, but one test is still failing due to the next issue: `Reset Mask` should not be visible when the edit mode is closed.

This was fixed [here](https://github.com/enonic/app-contentstudio/commit/5252ae050c19b56f2345c0b84296193bd2e3ef75)

**Comment by alansemenov** [comment]
Will be solved by https://github.com/enonic/app-contentstudio/issues/4557
