### ISSUE TITLE
UI controls must be disabled during the check for name availability and rename

### ISSUE THREAD

**Issue by ashklianko** [enonic/app-contentstudio#4437]
When typing/changing content name in the content wizard we run background check for name is not occupied, however this check progress is not reflected in ui and we only see result when it is finished. It is especially dangerous when renaming parent content with multiple children and when update may take some time

1. Update wizard header to show small spinner when name is being changed
2. Disable save action while the check is in progress
3. Update RenameContentDialog to show spinner in place of Available/Not available text when name check is on
4. Block rename action in RenameContentDialog while check is on
5. Make sure no error is shown during content rename(update) like there's now:
![image.png](https://images.zenhubusercontent.com/58a588dc51aa2c3057749dad/bc691980-e577-49f7-a8e4-9766ddc8d7b0)

**Comment by sgauruseu** [comment]
1. Content remains `published` after rename the content
2. Notification message should appear after the renaming

https://user-images.githubusercontent.com/3728712/163361143-79883c54-8a2d-411f-ab12-03afc3ab4fc1.mp4
