### ISSUE TITLE
Websocket connection fails with current CSP

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#4479]
For some reason only in Safari

**Comment by alansemenov** [comment]
Reason: https://csplite.com/csp/test15/#Safari_ws_wss

**Comment by ashklianko** [comment]
Works fine in IPhone Safari:
![File](https://user-images.githubusercontent.com/4255706/164707484-73a54f65-65f6-4fbe-9ea6-71a0a3dd414d.jpg)
