### ISSUE TITLE
Missing apps are incorrectly sequenced in the applications selector

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-contentstudio#453]
In the latest version of Content Studio (tested on XPQA), and while Editing the Enonic site (which has a lot of apps). The app called "attachmentviewer" has been stopped, and appears as "red".

This is fine, the problem however is that when trying to remove the app, and saving - the change is actually not stored. So UI will show it as removed, but it will be in the data. Same goes for restoring versions, the applications list is not correctly reflecting the actual underlying data (UI is actually blinking after restoring version, so it appears to reload, but not so for the applications list at least).

Also, on some rare occations, you may be lucky and actually be able to remove the app!..

Here is a screenshot of what tings look like from the UI.

![Screenshot 2019-04-26 at 12 11 44](https://user-images.githubusercontent.com/482228/56800906-7c94a480-681c-11e9-8673-e7ea7b72e160.png)

**Comment by vbradnitski** [comment]
Issue moved to [enonic/lib-admin-ui #993](https://github.com/enonic/lib-admin-ui/issues/993) via [**ZenHub**](https://www.zenhub.com/)
