### ISSUE TITLE
Published/Unpublished statuses in the Version History should not show user name

### ISSUE THREAD

**Issue by llabaj-gj** [enonic/app-contentstudio#4572]
It seems that "Published by" status shows name of the user who marked content as "Ready" not the person who actually published it afterwards. See screenshot below, where it is conflicting with what is shown in version history widget.

The issues is in Content Studio 4.0.4, could not check if it also exists in 4.1.0

![image](https://user-images.githubusercontent.com/81151513/169005956-6418a00d-aa88-443b-bb53-9a33709a099b.png)

**Comment by sigdestad** [comment]
In order to make room for new stuff in header. 
I propose we simply remove the "by user" and only keep the state e.g. "Published" here

**Comment by alansemenov** [comment]
Places to remove "`by UserName`" after Published & Unpublished:
* Version History widget
* Content preview panel
* Content Wizard toolbar
