### ISSUE TITLE
Insert Link dialog  -  target is not shown in Content/Download tabs , when modal dialog has been reopened

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4581]
1. Open a content with html area
2. Open `Insert Link` dialog and insert link to Content or Download

![image](https://user-images.githubusercontent.com/3728712/169762526-2105a442-d210-465f-be63-523b3b51f3f4.png)

3. Click on Insert button
4. Double click on the just inserted link

**BUG**:  Target is not selected in the Download tab

![image](https://user-images.githubusercontent.com/3728712/169762894-ef73f156-b71b-450f-b182-a658940ef8ec.png)

**Comment by alansemenov** [comment]
Same as https://github.com/enonic/lib-admin-ui/issues/2574
