### ISSUE TITLE
Shortcut- selected options are not refreshed after reverting versions

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4582]
1. Open wizard for new shortcut, fill in the name input and select an option in target selector, save 
2. Open Versions Panel and revert the previous version.
3. Revert the verdion with selected target.

BUG  - selected options not refreshed after revertiong versions 

https://user-images.githubusercontent.com/3728712/169778088-bd261c7d-c469-4d23-a3fe-50c379d66534.mp4

**Comment by ashklianko** [comment]
That's probably because of latest changesin Combobox

**Comment by alansemenov** [comment]
Same as https://github.com/enonic/lib-admin-ui/issues/2574
