### ISSUE TITLE
Html area - expanded menu moves on page scroll

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4601]
1. Open a content with HtmlArea, 
2. Click on `Insert Table` menu button , then scroll the wizard page.

https://user-images.githubusercontent.com/3728712/170278190-900249d9-1232-4cfb-9421-b755e6c5faca.mp4

**Comment by ashklianko** [comment]
This appears to be a known CKEditor 4 issue:
[issue](https://github.com/ckeditor/ckeditor4/issues/4419)
[same issue](https://github.com/ckeditor/ckeditor4/issues/1139)
However it is not yet resolved and the fix proposed by a community is not suitable for us

**Comment by ashklianko** [comment]
Setting _**won't fix**_ state and closing
