### ISSUE TITLE
Actions Docs with errors

### ISSUE THREAD

**Issue by felipestanzani** [enonic/app-contentstudio#4607]
* The "Duplicate" section mentions "Delete" instead of "Duplicate" at the second paragraph.
* The last paragraph of "Sort" section mentions an image that should contains "/folder-copy", "/folder-copy-2", and "/folder-copy-3".

---
#### Document Details

⚠ *Please do not edit this section. It helps us track and organize our issues.*

* Commit: 2e902fcbe4ae98036ba5016b0f4e4e0309945ef1
* Document: Actions
* Document path: /developer/docs/content-studio/stable/actions

**Comment by alansemenov** [comment]
@felipestanzani Thank you for reporting, this should be fixed now.
