### ISSUE TITLE
Default options in option-set don't get selected in site configurator

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#4629]
With this form inside a content type schema, options with `<default>true</default>` will be selected by default. However, with the same form inside `site.xml` preselection will not work.

```XML
  <form>
    <option-set name="checkOptionSet">
      <label i18n="checkOptionSet.label">Multi-selection OptionSet</label>
      <expanded>true</expanded>
      <occurrences minimum="1" maximum="1"/>
      <help-text>You can select up to 2 options</help-text>
      <options minimum="0" maximum="2">
        <option name="option_1">
          <label i18n="checkOptionSet.option_1.label">Option 1</label>
          <help-text i18n="checkOptionSet.option_1.help-text">Help text for Option 1</help-text>
        </option>
        <option name="option_2">
          <label i18n="checkOptionSet.option_2.label">Option 2</label>
          <default>true</default>
          <items>
            <input name="contentSelector" type="ContentSelector">
              <label>Content selector</label>
              <occurrences minimum="0" maximum="0"/>
              <config/>
            </input>
          </items>
        </option>
        <option name="option_3">
          <label>Option 3</label>
          <help-text>Help text for Option 3</help-text>
          <items>
            <input name="textarea" type="TextArea">
              <label>Text Area</label>
              <occurrences minimum="0" maximum="1"/>
            </input>
            <input name="long" type="Long">
              <label>Long</label>
              <indexed>true</indexed>
              <occurrences minimum="0" maximum="1"/>
            </input>
          </items>
        </option>
      </options>
    </option-set>
  </form>
```

**Comment by alansemenov** [comment]
Not only the introduced fix didn't help, but it actually caused [another bug](https://github.com/enonic/app-contentstudio/issues/5217).

The reason seems to be that once an application is selected/assigned to a site, the site config's PropertySet not getting the `_selected` property set to the default option before the site gets auto-saved.

To test this:
1. Use the form above in the Features's app's site.xml
2. Create a new site
3. Open the Network tab, filter it by "_update_" keyword to intercept auto-save of the site.
4. Assign the Features app to the site.
5. The site gets auto-saved.

Now examine the update request and note that `_selected` property is empty:
![image](https://user-images.githubusercontent.com/11612490/193273646-88217d06-29c8-467e-ba9e-d533d31ae857.png)

This is how it should have been for the config above:
![image](https://user-images.githubusercontent.com/11612490/193274138-4cc9a3b0-9486-431b-a26d-72d59b11888b.png)

**Comment by reisfmb** [comment]
@alansemenov I'll take a look at this right after finishing the visualization for model studio 1.0
