### ISSUE TITLE
Implement prefix selector for external url

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#4666]
![image](https://user-images.githubusercontent.com/11612490/173100887-82ed8935-32f9-4754-8b78-7fbc955b2f8e.png)

Implement prefix selector for the input field on the "Url" tab, using MenuButton.
* The main action should say "Type" and should act like a dropdown expander
* The options inside are:
  * 'https://'
  * 'http://'
  * 'ftp://'
  * 'Relative'
* When user selects an option in the dropdown, it should
  * For 'Relative":
    * if the field is empty, simply set cursor inside the field
    * if the field is not empty, clear the input 
  * For the prefixes:
    * if the field is empty, copy selected prefix into the field, then set cursor in the last position
    * if the field is not empty, check if current value starts with any of the other prefixes. If it does, replace it with the selected one. If it doesn't, prepend selected prefix to the value (f.ex., if it was "`blabla`" in the field and I selected "https://" then the value will change to "`https://blabla`"). Then set cursor in the last position.
* Prefix currently used in the url value should be marked as selected inside the dropdown
* For a new link, "https://" should be set as default (marked inside the dropdown and be set inside the input)
* For an existing link we should parse the value to determine what prefix the URL starts with, and mark this prefix as selected inside the dropdown.
* We should also perform the same parsing when URL is pasted inside the field.
* Each of the prefixes should have a corresponding regular expression that input's value will be verified against (see https://github.com/enonic/app-contentstudio/issues/4688).

**Comment by reisfmb** [comment]
@alansemenov 

1) Validation is not implemented yet. Will be done in #4688.

2) What should be the color of the menu button and the selected option in the menu button dropdown?

3) I've currently used css "order" to properly place the label of the input as the first thing in the fieldset, and the up/down dropdown arrow of the menu button to the right. I don't think that this is the best approach. What would you recommend? I can only see a private getter of the dropdown arrow position [here](https://github.com/enonic/lib-admin-ui/blob/master/src/main/resources/assets/admin/common/js/ui/button/MenuButton.ts#L154).
