### ISSUE TITLE
Assignees in the Issue dialog are incorrectly loaded

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#4691]
Assignees dropdown In `CreateIssueDialog` and `IssueDetailsDialog` is now filtered to show only users with Publish permissions. This filtering only makes sense for publish requests, but not for regular issues which don't necessary involve publishing of content.

**Comment by ashklianko** [comment]
@alansemenov  neither me nor @sgauruseu could reproduce it, maybe some special conditions required?

**Comment by alansemenov** [comment]
@ashklianko It seems that confusion is caused by a totally different bug in the Principal selector.

Here how it looks on the first open:
![image](https://user-images.githubusercontent.com/11612490/174590858-2d846cc8-3d83-486c-880d-b975b5e7e784.png)

As you can see, it only shows 9 users and no scrollbar. In reality there are more than 20 users, but they are not lazy-loaded. If you search for something and then clear the filter, then the list will be displayed correctly:

![image](https://user-images.githubusercontent.com/11612490/174592836-5523712c-352c-48bf-8150-6675ae65e49f.png)

I checked the Principal selector in the Role wizard and it's correct there (there's scrollbar right away):

![image](https://user-images.githubusercontent.com/11612490/174592583-76f0a0e4-aad0-49b7-8386-da424c376351.png)

**Comment by alansemenov** [comment]
Updated issue title
