### ISSUE TITLE
Insert Image Dialog - styles filtering does not work in some cases

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4697]
1. Open new wizard for  htmarea n in Features
2. Insert an image
3. Type an existing option in the styles options filter input

BUG - filtering does not work in some cases:

https://user-images.githubusercontent.com/3728712/174260360-5c4f0694-56d3-491b-b585-9cf51526b516.mp4

**Comment by ashklianko** [comment]
@sgauruseu is there a stable way to reproduce? I couldn't reproduce at all

**Comment by sgauruseu** [comment]
this issue was fixed in https://github.com/enonic/xp/issues/9497
