### ISSUE TITLE
Feature request: Replacing a content with a specific ID with another content, but keeping the ID

### ISSUE THREAD

**Issue by vot-enonic** [enonic/app-contentstudio#4770]
Sometimes when you run a website with thousands of assets being reused on hundreds of pages, it would be nice to simply swap e.g. an outdated image with a new one, but keeping the content ID and thus automatically replacing the image wherever it is being used on the website. Possible?

**Comment by sigdestad** [comment]
Just edit image, upload a new file - and you're done
