### ISSUE TITLE
Custom Selector - requests use content's path instead of content id

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4778]
1. Select Features and open wizard for new Custom Selector content
2. Click on the dropdown handle and expand the selector

Bug - 404 error appears in the custom selector 

![image](https://user-images.githubusercontent.com/3728712/176673253-bcd1ab1b-e3d8-46a2-8756-db6a0fd6ced6.png)

**Comment by ashklianko** [comment]
`CustomSelector ` uses content's path `/admin/site/edit/features/draft/features/1111/` instead of  content's id, `/admin/site/edit/features/draft/<CONTENT_ID>/`, that leads to an IllegalArgumentException
