### ISSUE TITLE
Cannot upload new image in HtmlArea

### ISSUE THREAD

**Issue by vot-enonic** [enonic/app-contentstudio#4790]
When I try to upload a new image in the input field HtmlArea, the button for "uploading from local drive" is not present in the wizard, and drag & drop does not work either.
![Cannot upload new image](https://user-images.githubusercontent.com/43465080/177111093-0ff79b32-1993-43cb-b7dc-411143edb11e.gif)

**Comment by alansemenov** [comment]
@vot-enonic did you know that you can drag an image directly inside the editor?
