### ISSUE TITLE
Issues with copy/pasting into HTML Editor from Google Docs

### ISSUE THREAD

**Issue by mortyeriksen** [enonic/app-contentstudio#485]
Hi, 

I tried this today and it would be great to fix a few more problems:

1. Syle must be removed: `<a href="content://acd6d47e-919f-4e0f-bbc8-203a455e1650" style="text-decoration:none;">`

2. Also, underline is added in all link texts: `<a href="content://acd6d47e-919f-4e0f-bbc8-203a455e1650" style="text-decoration:none;"><u>content management systems</u></a>`

3. Paragraphs must be removed in lists:

```
<ul>
	<p><li>Self service</li></p>
	<p><li>Corporate web</li></p>
	<p><li>Social intranet</li></p>
</ul>
```

Here's a test document:
https://docs.google.com/document/d/1m62J8fVr9s3zpkmPj9KmX1_V-1ITb2fpxHylm3QeIeM/edit#

**Comment by alansemenov** [comment]
@ashklianko check if this can be fixed without changing the plugin code... otherwise maybe we can contribute the fix to the plugin code if it's an open source project?

**Comment by ashklianko** [comment]
Ok!

**Comment by alansemenov** [comment]
1. Either set `style="text-decoration: none;"` on the `<u>` element inside `<a>`, or remove `<u></u>` element (but not the text inside, of course), whatever is the easiest.
2. Remove `<p></p>` when inside `<li></li>`
