### ISSUE TITLE
Update/add tests for the Version History widget

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#4850]
What has changed:
1. Actions for publish (including scheduled publishing) and unpublish now correctly display name of the user who published/unpublished. Before the changes we showed name of last modifier, not the one who actually did the publish/unpublish.
2. After sorting has been changed, a new version will be displayed in the list of versions.
3. After user permissions have been changed, a new version will be displayed in the list of versions.
4. Actions for archive and restore are no longer clickable

To do:
1. Manually test all of the changes mentioned above
2. Update existing Selenium tests
3. Add Selenium tests for new functionality (sorting and permission changes, correct publisher name etc.)

**Comment by sgauruseu** [comment]
I split this task into several tasks
