### ISSUE TITLE
Project wizard step (1/5): Parent Project

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#4859]
First step of the New project wizard: selection of a parent project. This will determine whether we are creating an ordinary project or a layer.

It's important that we automatically skip this step if the list in project selector is empty.

Note that the button to go to the next step says "Skip" and not "Next". This should be a part of general Wizard functionality if none of the properties on the current step are mandatory. Once a parent project is selected, the button caption should change to "Next".

![new-project-wizard-1](https://user-images.githubusercontent.com/11612490/179509523-ee6296e1-7c68-4f49-adb9-dce859ec31b4.png)

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/pull/4934
