### ISSUE TITLE
Project wizard step (2/5): Language

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#4860]
Optional selection of project language.

Note Skip/Next captions on the button depending on if Language is selected.

![new-project-wizard-2-1](https://user-images.githubusercontent.com/11612490/179509836-f22df80f-4292-4903-96b4-c34f5306bc64.png)

![new-project-wizard-2-2](https://user-images.githubusercontent.com/11612490/179509847-e65ccdb4-bb03-4349-a9e2-27285e5651f7.png)

**Comment by ashklianko** [comment]
@alansemenov do we need "Copy from parent" buttons here, for the access mode and Permissions?

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/pull/4934
