### ISSUE TITLE
Project wizard step (3/5): Access mode

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#4863]
Same as in the existing project wizard. As selection is mandatory, the Next button is disabled until something is selected.

![new-project-wizard-3-1](https://user-images.githubusercontent.com/11612490/179510156-dba00f1a-2402-4dbb-b881-a5721c6ca5a3.png)

![new-project-wizard-3-2](https://user-images.githubusercontent.com/11612490/179510147-0c9aa1e4-2149-455a-b1ca-1f68c273df31.png)

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/pull/4934
