### ISSUE TITLE
Project wizard step (4/5): Permissions

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#4864]
Same as in the existing project wizard. As selection is optional, the button will say "Skip" unless something is selected.

![new-project-wizard-4-1](https://user-images.githubusercontent.com/11612490/179514147-b4e87d79-42d5-40eb-87b2-282cc992f630.png)
![new-project-wizard-4-2](https://user-images.githubusercontent.com/11612490/179513831-f71259ba-7977-4f48-939d-81ed3e3242a3.png)

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/pull/4934
