### ISSUE TITLE
Project wizard: Summary

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#4865]
Important: don't show optional properties without values.

If there was an error creating the project: stay on this step and show error toast with error message.
If the project was successfully created: redirect to the Settings module, open a new AppBar tab with wizard for the created project and show success toast with the same message we now show upon project creation.

![new-project-wizard-summary](https://user-images.githubusercontent.com/11612490/179515233-eea12174-cc42-4f39-9028-b53c9cd296e4.png)

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/pull/4934
