### ISSUE TITLE
Project wizard step (5/5): Project name/id/description

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#4866]
When user comes to this step:
* if no parent project is selected: set focus inside the Display name field.
* if parent project is selected:
  * auto-generate values in the "Display name" and "Identifier" fields as `<Parent project Id>-<New project's language code>`
  * if Parent project's description is not empty, auto-generate value in the Description field as `<Description of the parent project (Display name of the new project's language)>`

Value in the Identifier should be auto-generated on change of the Display name field, like now. 

When the Next button is clicked, we should check whether a project with provided id already exists. If it does, we should show a validation error under the input and disable the "Next" button. The button should become enabled again once the value in the Id field has been changed.

Initial state of the step (no parent project):
![new-project-wizard-5-1](https://user-images.githubusercontent.com/11612490/179520537-b39e296c-610c-431d-9e84-83fd85427f4e.png)

User has typed in "My project" into the Display name field:
![new-project-wizard-5-2](https://user-images.githubusercontent.com/11612490/179520533-fc69c7fc-11ca-472b-9e7a-8caf045b517f.png)

Initial state of the step (parent project with Id "market" and language code "no" is selected):
![new-project-wizard-5-3](https://user-images.githubusercontent.com/11612490/179520532-ce604c94-0536-4e98-965b-f7de7de9d7c1.png)

User clicked the "Next" button but project with such Id already exists:
![new-project-wizard-5-4](https://user-images.githubusercontent.com/11612490/179522508-4f082566-9137-4e86-b292-4b733763844a.png)

**Comment by ashklianko** [comment]
https://github.com/enonic/app-contentstudio/pull/4934
