### ISSUE TITLE
Incorrect header in versions item after moving a content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4892]
1. Select a child folder and open versions widget.

![image](https://user-images.githubusercontent.com/3728712/180747150-ab751c6b-78e1-4d3f-8328-7d7c559ce71c.png)

3. Move the selected folder to root directory .

![image](https://user-images.githubusercontent.com/3728712/180747282-83a105c7-fd1b-4d0c-b651-63be5fee9964.png)

**BUG**  - `Permissions updated` version item appears in the widget after moving a content

**Comment by ashklianko** [comment]
Until we change XP api for ContentVersion we can't detect what exactly was changed in a ContentVersion (permissions or move), thus showing 'Changed' text for this type of version and using checkmark icon
