### ISSUE TITLE
Page Editor is not working in MS Edge

### ISSUE THREAD

**Issue by jsi** [enonic/app-contentstudio#49]
@sgauruseu commented on [Fri Jan 04 2019](https://github.com/enonic/app-contentstudio-old/issues/664)

1. Open new site-wizard
2. Type a name , select an application....

BUG: 
- Save button is always disabled  
- auto saving  is not working.
-  Page Editor is not loaded 
- unable to open Page Component View and Inspection Panel
The same issue when open existing site , Features or Superhero
 
![image](https://user-images.githubusercontent.com/3728712/50683709-104f2480-1024-11e9-82b4-e723152788ea.png)

Error in console:

`SCRIPT438: SCRIPT438: Object doesn't support property or method 'getRootNode'
ab2eeb0e-e6b6-48c3-8838-132208992237 (21445,35)

 Editor with id 'api.ui.text.TextArea-3' not found`

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #945](https://github.com/enonic/lib-admin-ui/issues/945) via [**ZenHub**](https://www.zenhub.com/)
