### ISSUE TITLE
Permissions prevent tree node expansion in the Move dialog's content selector

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4910]
Allow an user with limited permissions to expand a content in read only mode, see the issue :

https://discuss.enonic.com/t/content-studio-permissions-preventing-tree-node-expansion-in-move-modal/2823

Steps to reproduce : 
1. Create an user with roles `Admin Console Login, Content Manager App`
2. Create a folder with name `test` in the root and set `Read only` permissions for just created user.
3. Create a child folder  and set `Full Access` for just created user
4. Do login with the new userName/password
5. Select a content and click on `Move` button. Try to move the content to the child folder with `Full Access` permissions

BUG:  The user can not move an item to the folder with Full Access  permissions , because   it’s not possible to expand the root `test` folder in move selector

![image](https://user-images.githubusercontent.com/3728712/181523779-759524af-8410-4d39-b1d6-cd8859f58731.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2839](https://github.com/enonic/lib-admin-ui/issues/2839) via [**Zenhub**](https://www.zenhub.com/)
