### ISSUE TITLE
Pasted Url with query params is not correctly recognised by the Insert Link dialog

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#4938]
If I paste the URL below into the Link text field of the Insert Link dialog, it won't be correctly recognised as an https link. Instead, Link type is set to "Relative" and validation won't allow creating the link.

`https://myurl.mysite.net/ApplicationForm/SinglePageApplicationForm.aspx?cid=139&departmentId=21678&ProjectId=183198`

It works correctly when pasting `https://myurl.mysite.net/ApplicationForm/SinglePageApplicationForm.aspx`

**Comment by reisfmb** [comment]
@alansemenov 

Couldn't reproduce it:

[video-10421492-8b8440b950bf0a10000f2c46b1ee8ae5.webm](https://user-images.githubusercontent.com/67838246/183713384-51173d14-8856-4783-b1a7-f150394c08ea.webm)
