### ISSUE TITLE
Workflow state is incorrect after pressing Mark as Ready

### ISSUE THREAD

**Issue by ashklianko** [enonic/app-contentstudio#4964]
Add a new `TextComponent` in Page Editor and press `Mark as Ready` - content is being saved, however status remains to be _In Progress_

**Comment by espen42** [comment]
Possibly related, from https://enonic.zendesk.com/agent/tickets/5667:

> _I am testing 7.10.0 and experiencing trouble when I want to mark a content as ready. When I click the “Mark as ready” button, the version history says it marked the content as ready. But the button didn’t change to “publish”. If I continue to click the “mark as ready” button, the version history adds “edited”.
> This error also occurs in the “mark as ready” button in the downarrow-dropdown menu.
> If I choose “publish” in the downarrow-dropdown menu, and choose “mark as ready”, content-studio will properly mark the content as ready._

https://user-images.githubusercontent.com/5279775/184154958-d19ccbac-0169-45fb-bf82-09d7d67ec633.mov

**Comment by ashklianko** [comment]
There are also additional issues after latest backend adjustments regarding rich text processors
