### ISSUE TITLE
Layer Wizard - project selector should open in the tree mode by default

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#4966]
1. Go to Settings panel
2. Click on New button then click on Layer
3. Expand the project selector - this selector in the flat mode  

![image](https://user-images.githubusercontent.com/3728712/183895692-27052c6b-7234-4304-992d-1034d8349636.png)

4. Type 'Deafult' in the options filter input

**BUG: the selector switches to tree mode after a filtering**

![image](https://user-images.githubusercontent.com/3728712/183896010-658b62ab-2fc1-4df7-a9b0-70be076fa98e.png)

**The same issue is in new Project Wizard modal dialog** 

 
![image](https://user-images.githubusercontent.com/3728712/183896562-d27086b4-752c-4549-88bb-baa81a645abd.png)

**Comment by alansemenov** [comment]
There's also a problem with the layout - too much indent on the left.

**Comment by ashklianko** [comment]
For a new dialog: of https://github.com/enonic/app-contentstudio/issues/5008

**Comment by ashklianko** [comment]
Done in https://github.com/enonic/app-contentstudio/issues/5024
