### ISSUE TITLE
Critical: Uploading media with Drag'n drop through new dialog gives wrong permissions

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-contentstudio#499]
I just uploaded an svg icon below the start/ page on developer portal.
For unknown reasons, the "everyone" row in permissions was missing, and the icon was not available.

This might be an error in the back-end, but should be investigated top down.

**Comment by GlennRicaud** [comment]
Tried to reproduce on my machine and on prod with Tsi without success.
Closing it for now
