### ISSUE TITLE
Inputs with custom validation are shown as invalid before content is saved

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#4997]
When creating a content with an input that has custom server-side validation, the input with incorrect value will be highlighted (albeit without error message, which is good) **before** a new content is saved. Note the red border:

![image](https://user-images.githubusercontent.com/11612490/185571808-9addc019-27fa-47fe-96b7-6fe2eea2a2e5.png)

Here's example of a content with a mandatory input value (here it's correct):
![image](https://user-images.githubusercontent.com/11612490/185572483-75879734-6e2f-4be0-bd80-fcc5f7fcb815.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2721](https://github.com/enonic/lib-admin-ui/issues/2721) via [**ZenHub**](https://www.zenhub.com/)
