### ISSUE TITLE
Preview no longer saves content

### ISSUE THREAD

**Issue by mortyeriksen** [enonic/app-contentstudio#500]
Create the content without saving:
![Screenshot 2019-05-29 at 09 36 20](https://user-images.githubusercontent.com/702065/58538426-6ef48500-81f5-11e9-9654-13e092e5ea6a.png)
Click preview:
![Screenshot 2019-05-29 at 09 36 13](https://user-images.githubusercontent.com/702065/58538430-71ef7580-81f5-11e9-8c8f-e7384cf650ae.png)

**Comment by alansemenov** [comment]
We did use to save content before previewing (tested in 6.15.6)
