### ISSUE TITLE
Errors in  Insert Macro and Request Publishing modal dialog

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#5006]
**Case 1**. Select a folder (Ready for publishing) then click on Request Publishing... menu item

![image](https://user-images.githubusercontent.com/3728712/185856888-d1b08cc8-aee4-48ea-b4bd-2e6eeccdcef8.png)

BUG: Modal dialog does not appear, errors appear in console 

**Case 2**: The similar issue in `Insert Macro` dialog 

Just click on the `Insert` button: 

![image](https://user-images.githubusercontent.com/3728712/185857313-b8880634-e3ee-471f-ac14-712d3321fdce.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2723](https://github.com/enonic/lib-admin-ui/issues/2723) via [**ZenHub**](https://www.zenhub.com/)
