### ISSUE TITLE
Missing documentation: how to hide the default project

### ISSUE THREAD

**Issue by espen42** [enonic/app-contentstudio#5072]
The config `settings.hideDefaultProject` isn't documented anywhere, should probably have an entry in [config.adoc](https://github.com/enonic/app-contentstudio/blob/6ba607b8e39104d7852d5b04bafd6e5e66323a1a/docs/config.adoc).

**Comment by alansemenov** [comment]
This was not supposed to be a public feature, so it wasn't documented on purpose. The setting was implemented to enable hiding the default project in Cloud projects (but it was never taken in use there).

**Comment by alansemenov** [comment]
Done in https://github.com/enonic/app-contentstudio/issues/5259
