### ISSUE TITLE
Context menu stays open when menu button's dropdown is expanded

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#5075]
**Case 1:**
1. Right-click a content in the Content Grid. Context menu of the content item pops up
2. Expand the dropdown of the Publish menu button in the top right corner.

Bug: context menu didn't close on the click outside

![image](https://user-images.githubusercontent.com/11612490/188395608-7e6fc8ba-f428-434b-85f9-bc409febbb1d.png)

**Case 2 (case 1 the other around):**
1. Select a content in the grid, so that Publish menu item gets a dropdown toggler
2. Expand the dropdown
3. Right-click anywhere in the grid

Bug: dropdown didn't close on the click outside.

**Comment by sgauruseu** [comment]
The similar issue in Live Edit 

![image](https://user-images.githubusercontent.com/3728712/189309620-ead96502-c378-4d3e-b069-0a96db9682e6.png)



![image](https://user-images.githubusercontent.com/3728712/189309323-d93b8317-2a97-4da1-b7d2-6228625b9f5f.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2832](https://github.com/enonic/lib-admin-ui/issues/2832) via [**Zenhub**](https://www.zenhub.com/)
