### ISSUE TITLE
OptionSet performance: do not create option inputs until option is selected

### ISSUE THREAD

**Issue by ashklianko** [enonic/app-contentstudio#5097]
Having an option set makes all inputs, including unselected ones (especially with  `<expanded>false</expanded>` ), be created immediately when opening wizard. That may potentially lead to performance issues, thus need to instantiate items only when option is selected and items become visible.
This issue will have impact on content's property tree layout and comparing it with saved property tree.

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #2780](https://github.com/enonic/lib-admin-ui/issues/2780) via [**Zenhub**](https://www.zenhub.com/)
