### ISSUE TITLE
Not possible to tab to the form in edit view

### ISSUE THREAD

**Issue by poi33** [enonic/app-contentstudio#5101]
![image](https://user-images.githubusercontent.com/3340349/188888940-640eee74-3279-4597-86e7-b307cf260de2.png)

Its not possible to reach the form with keyboard naviation. 
It looks like the toolbar kees focus and loop over the same items.

**Comment by alansemenov** [comment]
Regression after [#4589](https://github.com/enonic/app-contentstudio/issues/3377)
