### ISSUE TITLE
X-data is not returned for a content-type outside of site

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#5117]
1. Create new project (select `Features` app in the wizard step) 
![image](https://user-images.githubusercontent.com/3728712/189612909-7e5ff07c-942c-4b02-bb1a-9e11ca17b246.png)

2. Go to the just created context and click on New button, then select `Folder` type

**BUG**:  x-data is not displayed in the wizard for folders in root directory 

**EXPECTED**: X-data (folders only ) should be present in folder wizard

![image](https://user-images.githubusercontent.com/3728712/189612471-67cfdab3-4813-46c5-a38b-12f0afc1c83b.png)

**Comment by alansemenov** [comment]
@vbradnitski `schema/getContentXData` API in Content Studio returns nothing for the same content-type outside of site.
