### ISSUE TITLE
Implement action flow for IN_PROGRESS state

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#514]
For content state IN_PROGRESS:

* If current user **does not have** publish permissions for selected content item(s):

  * “MARK AS READY” will be the default action in the “PUBLISH” button menu in the toolbar 
  * "PUBLISH" will be present in the Publish menu dropdown and disabled
  * "MARK AS READY" will be disabled if content is invalid

* If current user **has** publish permissions for selected content item(s):

  * "PUBLISH" will be the default action
  * "MARK AS READY" will be present in the Publish menu dropdown
  * "MARK AS READY" will be disabled if content is invalid

NB! If selection in the Content grid contains items in both IN_PROGRESS and READY states, both PUBLISH (if user has permissions) and MARK AS READY actions should be enabled.

**Comment by ashklianko** [comment]
This will work as described automatically if Mark as Ready https://github.com/enonic/app-contentstudio/issues/515 is done
