### ISSUE TITLE
References to archived content causes publish action to fail

### ISSUE THREAD

**Issue by anders-nom** [enonic/app-contentstudio#5182]
If a live content contains a reference to an archived content, publishing fails for any user who is **not an admin**.

This also occurs if a reference to archived content exists anywhere in the dependencies graph of the content, ie: `LiveContent1 -> LiveContent2 -> ArchivedContent`
In this case, publishing `LiveContent1` will fail.

The cause seems to be the `resolvePublishContent` service returning a 404 error for the archived content, possibly triggered by an exception from this predicate: https://github.com/enonic/app-contentstudio/blob/a869f8b99908592f9b874ca4750a63ee82d1d14d/modules/rest/src/main/java/com/enonic/xp/app/contentstudio/rest/resource/content/ContentResource.java#L648 

Reproduced on XP v7.10.3 and CS v4.2.3

![publish-error](https://user-images.githubusercontent.com/18137669/191910397-5ce42f5e-7256-4098-ad67-4b677d5ca6d1.png)

**Comment by alansemenov** [comment]
@anders-nom This is correct behaviour. You can achieve the same result by deleting a referenced content, and then trying to publish the content that has the reference to the deleted content. And we cannot allow publishing a content which is referencing something that does not exist, so Content Studio is correct to not allow publish in this case. You should click the content you are about to publish and remove the reference to the archived content. Then you'll be able to publish.
