### ISSUE TITLE
Versions Widget - A version created after content rename should say "Renamed", not "Moved"

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#5289]
1. Open a published content.
2. Click on `Click to modify the path` icon and update the name, click on Rename button
   
![image](https://user-images.githubusercontent.com/3728712/195546540-2609e682-eedb-46af-b6bc-7c37ad136ed9.png)

**BUG**   
 - `Edited` version item should appear in the widget after updating a name. But Actual is `Moved`
 -  **tolltip**  `Click to modify the path` should be changed to  `Click to modify the name`
                 
![image](https://user-images.githubusercontent.com/3728712/195547545-a97b5363-9541-49df-b16e-f42538e8b073.png)

**Comment by alansemenov** [comment]
Now it says "Moved" both for move and rename operations:
<img width="277" alt="image" src="https://user-images.githubusercontent.com/11612490/196230475-049ba83d-5ce5-4119-a1a9-d009370eb166.png">

1) Use "_Moved_" + icon for move if only `_path` (but not `_name`) has changed:
<img width="891" alt="image" src="https://user-images.githubusercontent.com/11612490/196230048-333d9f89-a5c3-40fd-b579-abfb5507c3ad.png">

2) Use "_Renamed_" + icon for edit if both `_path` and `_name` have changed:
<img width="893" alt="image" src="https://user-images.githubusercontent.com/11612490/196230313-571869bc-50c4-43ef-89b3-cb82ad6998eb.png">
