### ISSUE TITLE
Content path is not updated after reverting a moved version item

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#5291]
1. Create a folder then do Move this folder to a parent folder
2. Move the folder to another parent folder , two `Moved` version items are created - OK

![image](https://user-images.githubusercontent.com/3728712/195550516-2f873272-a247-43ef-b628-4419686c8841.png)

3. Open this folder, open versions widget and revert the previous moved version .

![image](https://user-images.githubusercontent.com/3728712/195550757-2d064f63-5ccc-41cf-95b5-076d3d13f450.png)

**BUG** - `No changes to revert.` message appears after reverting the moved version and path is not updated

**Comment by alansemenov** [comment]
It's no longer possible to revert a move operation, so this bug is not relevant.
