### ISSUE TITLE
Compare Content Versions Dialog - left Revert menu button should be disabled for moved version item 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#5313]
1. Create a folder then move this one to another location
2. Open the moved folder, open Versions Widget
3. Click on `Compare with current version` button in the Moved version item
![image](https://user-images.githubusercontent.com/3728712/196375414-2d8e511c-dcf6-4a9c-ae8f-43c4138fa12e.png)

4. Compare Versions dialog is opened

**BUG**: Left Revert menu button should be disabled

![image](https://user-images.githubusercontent.com/3728712/196375121-e5cb5f20-7c5d-45cc-988d-967503cbb70f.png)

**Comment by ashklianko** [comment]
Totally correct behavior since version on the left is revertable: only when dropdown version is non-revertable (published, moved, permissions, archived, restored etc.) then revert button of the dropdown to be disabled, no matter if it is left or right one
