### ISSUE TITLE
Modified display name is rolled back after renaming a published content

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#5403]
1. Publish a content
2. Modify its display name. Don't save.
3. Click the pencil icon and modify path. 
4. Click "Rename" button

Bug: Instead of saving both updated path and updated display name, only the path is changed and display name is rolled back to its original value.

**Comment by ashklianko** [comment]
It was made intentionally to perform only rename operation and to not update other fields in the wizard panel, however it is a bug that displayName's value is overwritten after rename
