### ISSUE TITLE
Unpublish button interrupts my flow between "Mark as ready" and "Publish"

### ISSUE THREAD

**Issue by vot-enonic** [enonic/app-contentstudio#5405]
When I am ready to publish a content item, I push "Mark as ready", and when the button changes, I push it again, expecting "Publish". But instead "Unpublish" sneaks in the middle, which brings forth an annoying interruption of my editing flow. See video for a demonstration.

https://user-images.githubusercontent.com/43465080/200571197-7f8471a5-5d68-4458-b100-e94beb1bc283.mp4

**Comment by alansemenov** [comment]
@vot-enonic not saying this is not a bug, but if you are intending to publish right after marking as ready, why don't you go directly to publishing? you can mark as ready directly from the dialog.

**Comment by vot-enonic** [comment]
@alansemenov That means 5 steps instead of 2, which is equally annoying. (5 steps = I. click the triangle, II. click "publish",  III. click triangle, IV. click "mark as ready", V. click "publish) (2 steps = I. click "mark as ready", II. click "publish").

**Comment by sigdestad** [comment]
This will be fixed by new workflow in CS5. Clicking mark as ready will instantly open publishing wizard

**Comment by alansemenov** [comment]
Fixed by https://github.com/enonic/app-contentstudio/issues/5413
