### ISSUE TITLE
Path is cleared after updating permissions in new unsaved content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#5407]
1. Open wizard for new folder
2. Fill in the name input.
3. Open `Edit Permissions`  dialog and add one more acl entry or just uncheck Inherit permissions checkbox then click on `Apply` button

**Bug**; Applying new permissions clears Path input.

![image](https://user-images.githubusercontent.com/3728712/200821313-641e37e7-572a-4299-bc3a-78e1be9bd6cc.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2907](https://github.com/enonic/lib-admin-ui/issues/2907) via [**Zenhub**](https://www.zenhub.com/)
