### ISSUE TITLE
Focus jumps to disabled elements after tab navigation

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#5444]
1. Open  new wizard for `Option Set` content (Features)
2. Press to `Tab` key several times 

**BUG** - disabled elements get focus after tab navigation 

https://user-images.githubusercontent.com/3728712/202696539-8655fbe1-6716-4191-9e4f-2dfead77ccee.mp4

**Comment by alansemenov** [comment]
Moved to https://github.com/enonic/lib-admin-ui/issues/2951
