### ISSUE TITLE
Selecting content items with a checkbox no longer enables toolbar actions

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#545]
1. Open the Content studio content grid
2. Select one or few items using the checkbox

Bug 1: buttons in the toolbar are supposed to change based on the selected items but nothing happens. 

![image](https://user-images.githubusercontent.com/11612490/59677801-03398280-91cb-11e9-983e-4652f33c3adb.png)

3. Unselect all items
4. Select more than one item using keyboard 

Bug 2: several items are selected, and the toolbar actions have now changed, but in the toolbar it says "1 selected"

![image](https://user-images.githubusercontent.com/11612490/59677871-4136a680-91cb-11e9-97ac-8c7d6d71427a.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1016](https://github.com/enonic/lib-admin-ui/issues/1016) via [**ZenHub**](https://www.zenhub.com/)
