### ISSUE TITLE
Application that creates content on init causes console errors

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#546]
1. Make sure you **don't** have Superhero app installed
2. Open the Content Studio grid
3. Open dev tools panel
4. Open "Applications" module in **another** tab
5. Install Superhero app from the Market
6. Switch to the dev tools panel of the first page

There are errors in console:

![image](https://user-images.githubusercontent.com/11612490/59678437-ba82c900-91cc-11e9-8423-84ffa1dc38fb.png)

Content seems to be created fine though, so I'm not sure what are the consequences of this error.

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1018](https://github.com/enonic/lib-admin-ui/issues/1018) via [**ZenHub**](https://www.zenhub.com/)
