### ISSUE TITLE
Issues in option set with nested mixin 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#5472]
There is a option set with nested mixins.
[mixins.zip](https://github.com/enonic/app-contentstudio/files/10083509/mixins.zip)

1. Open wizard for new `Freeform` content
2. Select `Input` option in the nested `freeform-input-types` mixin

![image](https://user-images.githubusercontent.com/3728712/203761762-78d467f1-46dc-4325-af71-743bfa5ddba0.png)

3. Select `Image` option in the `input type` selector

![image](https://user-images.githubusercontent.com/3728712/203762139-f4218288-ebf2-4db7-98c4-d1ef01f515a2.png)

4. Click on `Save` button

Issues;
- default value is not set in `scale` input
- Incorrect behaviour of validation - `scale` input is required, so the content should be invalid after saving,
- validation recording should be displayed for `scale` input
```
<input type="TextLine" name="scale">
              <label>scale</label>
              <help-text>See http://xp.readthedocs.io/en/stable/reference/image-processor/scaling.html</help-text>
              <occurrences minimum="1" maximum="1"/>
              <default>height(30)</default>
            </input>
```

![image](https://user-images.githubusercontent.com/3728712/203763032-5bfa5aa5-6bbf-4eea-85bd-ca95432a676e.png)

**Comment by ashklianko** [comment]
Problem is that we layout entire form items tree, including items that are yet to be selected. Thus when content form is being created and layout is on we set all those default values, but if we save content after layout before selecting options that contain these inputs, then those inputs are being cleared on save

**Comment by alansemenov** [comment]
Moved to https://github.com/enonic/lib-admin-ui/issues/2947
