### ISSUE TITLE
Controller of a Fragment gets reset after its parent site is renamed

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#5473]
1. Open `Features` site, insert a layout, then save it as fragment.
![image](https://user-images.githubusercontent.com/3728712/203765538-8a754498-3c2e-4839-90fb-03a9104ccdeb.png)

2. Update the name in path  input 

![image](https://user-images.githubusercontent.com/3728712/203767205-df0d5078-59fc-493b-9163-e49241049035.png)

3. Switch to the tab with  site's fragment

**BUG**  - controller has been reset in the wizard, button `Save` is enabled

![image](https://user-images.githubusercontent.com/3728712/203767950-2589f0bb-b7c4-40e6-b846-f745f71a6c6a.png)

**Comment by alansemenov** [comment]
Check if it's still relevant

**Comment by sgauruseu** [comment]
Can not reproduce this bug in the lates version

**Comment by ashklianko** [comment]
I'm having another issue when reproducing these steps, investigating

**Comment by ashklianko** [comment]
Also HtmlArea links are not processed
