### ISSUE TITLE
Replace icon for invalid content

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#549]
Use [this icon](https://drive.google.com/open?id=19n9Izr5IaRXicMDlSyOUOPsP8Har4MBj) instead of the one we are using now. Keep the same size of the icon as now.

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1027](https://github.com/enonic/lib-admin-ui/issues/1027) via [**ZenHub**](https://www.zenhub.com/)
