### ISSUE TITLE
Console errors for browser locales unknown to CKEditor

### ISSUE THREAD

**Issue by ashklianko** [enonic/app-contentstudio#552]
Based on https://discuss.enonic.com/t/ckeditor-missing-locale-in-content-stuido/1912:
1. Switch browser locale to Ukrainian and reopen browser
2. Open any content with html area instance in

Result: HtmlArea instances are not fully loaded, errors in dev tools console present complaining regarding lang pack not found:

> http://localhost:8080/admin/tool/com.enonic.app.contentstudio/main/_/asset/com.enonic.app.contentstudio:1560949524/lib/ckeditor/plugins/image2/lang/uk.js?t=IA8F net::ERR_ABORTED 404 (Not Found)

**Comment by alansemenov** [comment]
Let's add all CKE locale files matching languages that we support in admin UI (f.ex. for Norwegian add no, nb and nn). For all others fall back to english locale.
