### ISSUE TITLE
Implement action flow for READY state

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#553]
For content state READY:

* “MARK AS READY” should always be disabled in the dropdown 
* If current user **does not have** publish permissions for the content item:
  * “REQUEST PUBLISHING” will be the default action in the “Publish” button menu in the toolbar 
* If current user **has** publish permissions for the content item:
  * "PUBLISH" will be the default action

**Comment by ashklianko** [comment]
This will work as described automatically if Mark as Ready https://github.com/enonic/app-contentstudio/issues/515 and https://github.com/enonic/app-contentstudio/issues/556 is done
