### ISSUE TITLE
Layers widget won't correctly display multi-inheritance hierarchy

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#5540]
Introduction of multi-inheritance seems to have broken the Layers widget. In the Settings tree we show a layer only under its main parent. This might be temporary, until we find a better way to represent the structure, but for now we need the same logic in the widget.

As of now, it seems to show incorrect structure both in the widget and the widget's "Show all" overlay.

Current structure (note the `sample-blog/ sample-blog-de/ sample-blog-de-ch` chain):
![image](https://user-images.githubusercontent.com/11612490/206131847-c6b3a5d7-4b63-4a8b-aaeb-c5c0920cab2f.png)

Layers widget for a content item in the `sample-blog-de-ch` layer (note that incorrect parent is shown for `sample-blog-de-ch`:
![image](https://user-images.githubusercontent.com/11612490/206132163-3b563fc5-bac0-4b71-a856-401d133634fb.png)

Overlay (only the top parent is shown):
![image](https://user-images.githubusercontent.com/11612490/206132555-4737ad7e-4989-4558-89a7-b273439476af.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/app-contentstudio-plus #752](https://github.com/enonic/app-contentstudio-plus/issues/752) via [**Zenhub**](https://www.zenhub.com/)
