### ISSUE TITLE
Multi-select option-set allows selecting more than maximum options

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#5593]
**Case 1 :**
1. Select `Features` open wizard for new `OptionSet` content
2. Select oaal 4 options in the wizard

![image](https://user-images.githubusercontent.com/3728712/208408681-85ccd2a3-4c7c-4f92-a9f9-ae2e000e645a.png)

**BUG** -   `Option 4`  input should be disabled

**Case 2**   
This case is the similar to the issue -  https://github.com/enonic/app-contentstudio/issues/4354

1. Open new wizard for the next optionSet:

````
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<content-type xmlns="urn:enonic:xp:model:1.0">
  <display-name>optionset0_2</display-name>
  <super-type>base:structured</super-type>
  <form>
     <option-set name="checkOptionSet1">
      <label>Multi selection</label>
      <expanded>true</expanded>
      <help-text>Multi selection checkbox option set</help-text>
      <occurrences minimum="1" maximum="1"/>
      <options minimum="0" maximum="2">
        <option name="option_1">
          <label>Option 1</label>
        </option>
        <option name="option_2">
          <label>Option 2</label>
        </option>
        <option name="option_3">
          <label>Option 3</label>
        </option>
      </options>
    </option-set>
  </form>
</content-type>
````

2. Select the first and the second options , the  third option is disabled - OK
3. Save , close the wizard and reoprn the content again 

**BUG**: - The third option should be disabled 

![image](https://user-images.githubusercontent.com/3728712/208409615-d231a592-96ec-4fdb-9577-9ffdf45bd9a9.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2942](https://github.com/enonic/lib-admin-ui/issues/2942) via [**Zenhub**](https://www.zenhub.com/)
