### ISSUE TITLE
Disable "+" icon in Content Selector when no child content types are allowed

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#5647]
"+" icon should be disabled for Content Selector if regex in `allowContentType` config doesn't return any results _or_ current content's content type doesn't allow children (via `allow-new-content` config).

**Comment by alansemenov** [comment]
Ok, so we decided not to do this. The "+" icon will always be there for a Content Selector, but "New Content" dialog may in some cases show that no content types are available.

**Comment by ashklianko** [comment]
Still need to adjust things a bit to show dialog with no items properly

**Comment by alansemenov** [comment]
Let's do these changes here: https://github.com/enonic/app-contentstudio/pull/5649
