### ISSUE TITLE
Widgets request optimization: don't update widgets until widget panel is open

### ISSUE THREAD

**Issue by ashklianko** [enonic/app-contentstudio#5648]
Multiple requests are sent even though widget panel is not open. 
Adjust widget workflow so that it loads data only when widget panel is open.
![image](https://user-images.githubusercontent.com/4255706/210223570-59614de2-ef03-48e5-a1d6-087c6eb0c2eb.png)

**Comment by alansemenov** [comment]
This is a duplicate of https://github.com/enonic/app-contentstudio/issues/5543

**Comment by ashklianko** [comment]
Closing then
