### ISSUE TITLE
Bulk select is not triggering "publish button"

### ISSUE THREAD

**Issue by mortyeriksen** [enonic/app-contentstudio#576]
If I select one by one the "publish button" updates:

![Screenshot 2019-06-26 at 09 25 08](https://user-images.githubusercontent.com/702065/60159976-a8b8ab80-97f4-11e9-8c08-6b4da1cf9dc4.png)

If I check the bulk select checkbox, the "publish button" is not changed:

![Screenshot 2019-06-26 at 09 24 55](https://user-images.githubusercontent.com/702065/60159977-a8b8ab80-97f4-11e9-850e-1444538d19bb.png)

**Comment by alansemenov** [comment]
This is fixed in master but will have to wait for 7.1.0 release since the fix is a part of big refactoring which we don't want to release in a bugfix version
