### ISSUE TITLE
Focus jumps to the next disabled input after saving a content with option set

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#5787]
1. Select Features and open new wizard for `OptionSet`
2. Fill in the name input and save the content

**BUG** - Focus jumps to the disabled `Image Selector`

![image](https://user-images.githubusercontent.com/3728712/214322009-73907008-29d9-4f09-b460-f7a999be0d4f.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2986](https://github.com/enonic/lib-admin-ui/issues/2986) via [**Zenhub**](https://www.zenhub.com/)
