### ISSUE TITLE
App config with a default checked checkbox makes site invalid

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#5795]
1. Add the form below to site.xml of an app
2. Assign the app to a site.

Bug: The app will instantly be marked as invalid which will make the site itself be invalid as well (only client-side).

3. Open the app config

Bug: Even though the checkbox has default value and is checked off, it's marked as required and invalid in the form (which is the reason for the first bug as well).

![image](https://user-images.githubusercontent.com/11612490/215118930-d1046650-9260-44e4-9382-a1313fb6c936.png)

```XML
  <form>
    <field-set>
      <label>App settings</label>
      <items>
        <input name="allowViewOnSite" type="CheckBox">
          <label>Allow viewing on site</label>
          <occurrences minimum="1" maximum="1"/>
          <default>checked</default>
          <help-text>If enabled on site, links of type "content" can be used to view attachments instead of downloading them.</help-text>
        </input>
      </items>
    </field-set>
  </form>
```

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #2988](https://github.com/enonic/lib-admin-ui/issues/2988) via [**Zenhub**](https://www.zenhub.com/)
