### ISSUE TITLE
Issues in app config, project apps

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#5819]
**Case 1**
1.  Open new wizard for project, go to Applications step wizard then select an application with HtmlArea in its configurator 
2. Create the project.
3. Select the just created project and click on Edit button
4. Open app config in the project wizard.
5. Insert an image in HtmlArea
6. Do double click on the inserted image

**Issue** - Eception thrown after opening Insert Image modal dialog 

![image](https://user-images.githubusercontent.com/3728712/216003769-b302f9c0-b2c5-4886-9f14-cd4195d8089a.png)

**Case 2**
1. App config contains Image Selector 
```
 <input type="ImageSelector" name="backgroundImage">
      <label>Background image</label>
      <occurrences minimum="0" maximum="1"/>
      <config/>
    </input>
```
2. Open the app config in Project Wizard

**Issue** :  Image selector does not contain Upload button 

![image](https://user-images.githubusercontent.com/3728712/216007505-eff4dda8-7b71-46f5-8b3c-c05b566c7f28.png)

**Case 3**

Issue : Content Selector does not contain ' +'  icon for adding new content directly from the Content Selector

**Case 4**
 Issue  - Multi-select option-set allows selecting more than maximum options

```
<site xmlns="urn:enonic:xp:model:1.0">
  <form>
    <option-set name="checkOptionSet">
      <label i18n="checkOptionSet.label">Multi-selection OptionSet</label>
      <expanded>true</expanded>
      <occurrences minimum="1" maximum="1"/>
      <help-text>You can select up to 2 options</help-text>
      <options minimum="0" maximum="2">
        <option name="option_1">
          <label i18n="checkOptionSet.option_1.label">Option 1</label>
          <help-text i18n="checkOptionSet.option_1.help-text">Help text for Option 1</help-text>
        </option>
        <option name="option_2">
          <label i18n="checkOptionSet.option_2.label">Option 2</label>
          <default>true</default>
          <items>
            <input name="contentSelector" type="ContentSelector">
              <label>Content selector</label>
              <occurrences minimum="0" maximum="0"/>
              <config/>
            </input>
          </items>
        </option>
        <option name="option_3">
          <label>Option 3</label>
          <help-text>Help text for Option 3</help-text>
          <items>
            <input name="textarea" type="TextArea">
              <label>Text Area</label>
              <occurrences minimum="0" maximum="1"/>
            </input>
            <input name="long" type="Long">
              <label>Long</label>
              <indexed>true</indexed>
              <occurrences minimum="0" maximum="1"/>
            </input>
          </items>
        </option>
      </options>
    </option-set>
  </form>
</site>

```

![image](https://user-images.githubusercontent.com/3728712/216074418-93891292-87cb-4467-9fd4-9950be772566.png)

https://user-images.githubusercontent.com/3728712/216074508-adb2c5aa-9ad1-4d2e-b1c7-eb04be325fd4.mp4

**Case 5**   Selected Options in `Custom acces mode` are not cleared after saving switching to  another  mode

![image](https://user-images.githubusercontent.com/3728712/216950665-8bb61353-1bba-4e6c-b59d-95480961d40e.png)

**Comment by ashklianko** [comment]
#1 - Can't reproduce,
#2,3,5 - In a PR
#4 - Need a separate issue
