### ISSUE TITLE
Always expand the list of dependencies in the Publishing Wizard

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#5847]
The list of dependencies should be expanded by default to avoid accidental publishing.

![image](https://user-images.githubusercontent.com/11612490/217261861-6de5615b-1748-4b82-8a4a-f59206087f31.png)

**Comment by edloidas** [comment]
@alansemenov not relevant anymore?

**Comment by edloidas** [comment]
Was done in another issue.
