### ISSUE TITLE
Remove Schedule, Settings and Access icons

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#5892]

**Comment by ashklianko** [comment]
@alansemenov we used to set current project language into language input when localizing content (opening content wizard with 'localized' keyword in path), do we just skip this behavior entirely now?

**Comment by alansemenov** [comment]
@ashklianko We don't change any behaviour related to data mutations. We will still set language etc. The only thing we change is that we move parts of the form displaying language and owner to a different UI control.

It's the same we did with Permissions - we used to have that inlined in the Content Wizard form, then we moved it to the separate modal dialog. We are now doing the exact same thing with Owner, Language and Online From/To.
