### ISSUE TITLE
Edit Properties dialog  - DateTime Picker Popup blinks after opening the dialog

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#5928]
**Case 1**
1. Select a pblished content , open details panel 
2. Click on `Edit Properties` button

https://user-images.githubusercontent.com/3728712/221166488-f51d5176-0b79-4436-98c1-648719214cf0.mp4

**Bug** -   DateTime Picker Popup blinks after opening the dialog

**Case 2**:  Click on any place in the modal  dialog -   DateTime Picker Popup opens after it

**Comment by ashklianko** [comment]
Pushed into [#5447](https://github.com/enonic/app-contentstudio/pull/5923)
