### ISSUE TITLE
Publishing wizard is not refreshed after content updated in dialog

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#5934]
Case 1:
1. Select a parent folder, child item should be 'Work inprogress'
2. Click on  'Publish Tree' menu item.

![image](https://user-images.githubusercontent.com/3728712/221586194-88b7f4f2-ea81-4855-9b50-7076121af367.png)

3. Click on  Work inprogress' dependent item, child item is opened in the new browser tab (OK)
4. Click on Mark as Ready button , child item gets 'ready for publishing'
5. Switch to Publishing Wizard

BUG - 'Publish Now` button remains disabled after updating the dependant item 

Case 2:  Endless spinner is displayed in the modal dialog after clicking on  `Mark as ready` button

- Select a child content , its parent should be `work in progress`
- Open Publish wizard then click on Mark as ready butoon

 

https://user-images.githubusercontent.com/3728712/221810901-eea0654a-09de-4a3c-bf5b-84f523be41be.mp4

**Comment by edloidas** [comment]
Must be fixed in https://github.com/enonic/app-contentstudio/pull/5931
