### ISSUE TITLE
Scrollbar in the content grid is not taking full available height

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#596]
Open Content Studio, grid should be scrollable.

![image](https://user-images.githubusercontent.com/3728712/60440418-76a4b080-9c1d-11e9-82f6-1f07bf59ab7a.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1043](https://github.com/enonic/lib-admin-ui/issues/1043) via [**ZenHub**](https://www.zenhub.com/)
