### ISSUE TITLE
Incorrect behaviour of Page template link in the Details widget

### ISSUE THREAD

**Issue by poi33** [enonic/app-contentstudio#5964]
![image](https://user-images.githubusercontent.com/3340349/222082770-07d65949-2d3a-475a-b8f2-7400cf0d669e.png)

Expected behavior:
When right clicking the page template link and opening in a new tab I expect the page template content to be opened in a new page

Current behavior:
Right clicking the page template link and opening in a new tab opens the current content you are on. Not the page template.

**Comment by alansemenov** [comment]
@poi33 I don't understand neither title nor description. "different behaviour" from what? Please describe what you expect to happen. As far as I see, everything works as it should - template opens in a new browser tab.
