### ISSUE TITLE
Remove button in issue dialogs main list must never be disabled

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#5970]
1. Select a folder and create new issue.
2. Open `Issue details` dialog

![image](https://user-images.githubusercontent.com/3728712/222411804-9b24a2fb-4562-46aa-a459-37499a3ab213.png)

**BUG** - Icon remove should be enabled in the  `Items tab`

**Comment by edloidas** [comment]
Must be fixed in PR https://github.com/enonic/app-contentstudio/pull/5931
