### ISSUE TITLE
Notification message does not appear after resetting content in layer

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#6007]
1. Create a layer (No) in `Default`  propject 
2. Go  to the layer's context , select a folder then click on `Localize` button.
3. The folder is localized, OK. 
4. Click on `Reset` button , confirm the action.

![image](https://user-images.githubusercontent.com/3728712/223374268-772d1c5e-f942-48b9-b06e-73888794fcfa.png)

**Bug** - Notification message does not appear after resetting content in wizard

**Comment by ashklianko** [comment]
Can't find tracks that we had this notification before, thus it is not a bug but improvement
