### ISSUE TITLE
Localize button is missing in the Content Wizard toolbar for a non-localised content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#6009]
1. Create a layer (No) in `Default` propject
2. Go to the layer's context , then do double click on a content.
3. Content wizard is opened 

**Bug** -  Localize button should be present in the wizard toolbar

![image](https://user-images.githubusercontent.com/3728712/223375420-3a7891f6-9904-412c-82cb-a68dd90a361a.png)

**Comment by ashklianko** [comment]
This button was never there before, so we are not _missing_ it, we must add a new one
