### ISSUE TITLE
Handle unresolvable selected items in Content Selector

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#6026]
We handle selected images that cannot be resolved in Image Selector:
![image](https://user-images.githubusercontent.com/11612490/223750134-ae16cf60-2710-484b-aa29-7a0af195304b.png)

But we don't handle selected content items that cannot be resolved in Content & Media Selectors - missing items simply won't be shown as if nothing was selected. We should display placeholders for content items that cannot be resolved (note that this may also happen because of the lack of permissions). 

Verify that the fix also works for content selector inside "Insert Link" dialog in HtmlArea.

![image](https://user-images.githubusercontent.com/11612490/223750597-3e1b73bb-7863-421b-9bef-a7d06eaba212.png)

**Comment by sigdestad** [comment]
It would be really great if we can show some more details than "not found" i.e. there are multiplereasons why this may happen:

1. Content has been deleted/missing (404 style)
2. User cannot read content (401)

AFAIK Today, we also show a "yellow warning" when editing a page/item with broken links and we automatically break missing references. I think this new approach is a much better solution - where user must decided to remove the refs, but then user needs to know if link is broken - or he/she does not have access.


Error message could be

1. Not found
2. Access denied
