### ISSUE TITLE
DateTime picker opens on any click inside the Schedule Publish dialog

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#6069]
1. Select a published content 
2. Click on `Edit Schedule` button in `Details Panel`
3. `Edit Schedule` dialog  is opened - OK 

**BUG** -  click in any place opens Date Time Picker dialog

![image](https://user-images.githubusercontent.com/3728712/225002743-209da537-389f-4ff0-8c32-d39d90db651e.png)

**Comment by ashklianko** [comment]
This is how modal dialog behaves when focus moves out of a dialog - it brings it back to the dialog and focuses first focusable element, in this case it is a date time picker that always shows calendar on focus. @alansemenov not sure if there's anything to do
