### ISSUE TITLE
Page Editor displays rendering error for content with valid preview 

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#6077]
If page controller responds with simple text in `response.body`, Content Studio will show preview error message inside the Editor panel. In the Grid preview is correct (as it should be inside the Editor as well). Preview button is also enabled in the Editor (as it should be), and in the case of enabled preview we should always show preview in the Editor panel.

```
exports.get = function(req) {
    return {
        body: 'Hello World'
    };
}
```

![image](https://user-images.githubusercontent.com/11612490/225655621-5c916267-116d-4c9f-ad11-863bdb5b60d4.png)

![image](https://user-images.githubusercontent.com/11612490/225656391-3a925770-0853-45f2-966a-ff0a69391b67.png)

**Comment by ashklianko** [comment]
Fixed in other tasks, not reproduced now
