### ISSUE TITLE
Show Changes button should be displayed for renamed published content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#6085]
1. Open a published content
2. Open ` Rename published content` modal dialog then rename it content.

![image](https://user-images.githubusercontent.com/3728712/226391358-10b5f8c8-b734-4782-9915-66f12c46045c.png)

**Issue** - `Show changes` button  should appear in the PreviewItem toolbar and in content wizard

![image](https://user-images.githubusercontent.com/3728712/226391959-3017a219-0a8b-42f6-ab0d-99de2e2b4299.png)

**Comment by alansemenov** [comment]
Done in https://github.com/enonic/app-contentstudio/issues/6912
