### ISSUE TITLE
Page Editor panel for child content is not correctly refreshed when a page template was added or removed

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#610]
This bug is similar to  https://github.com/enonic/xp-apps/issues/738
And this bug does not reproduce in site-wizard now. This bug reproducing only in child content

1. Open new site-wizard, select Superhero in apps
2. Select the site and open new wizard for Landing Page, for example.
  
![image](https://user-images.githubusercontent.com/3728712/60709879-1b730680-9f1a-11e9-831f-11cc104736b2.png)

Do not close this landing page .

3. Expand the site, select _templates and open new wizard,  select  `Landing page` in supports and save the template:

![image](https://user-images.githubusercontent.com/3728712/60710073-87ee0580-9f1a-11e9-9ba4-50f9eb807ce7.png)

4. Go to Landing Page content again 

BUG: wizard for  Landing Page content  should be updated and Live Editor should  appear.

**Comment by pmi** [comment]
Either was fixed by other changes or Enonic XP is able to regenerate ;)
