### ISSUE TITLE
Dependent items in the Publishing Wizard disappear after parent item update

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#6123]
1. Select a `ready for publishing` parent folder (child itmes are `work in progress`)
2. Click on Publish Tree menu item: 

![image](https://user-images.githubusercontent.com/3728712/227891488-9242c9ff-17dd-4149-8897-03fb9dd9d1fd.png)

3. Click on the parent item in the dialog then update it and close the content wizard.

**BUG** -   Dependent items get not visible and `All` checkbox gets disabled

![image](https://user-images.githubusercontent.com/3728712/227892010-bcd3a3dc-dab5-483e-9c53-1242cb56ffed.png)

**Comment by edloidas** [comment]
Fixed in another issue.
