### ISSUE TITLE
Table incorrectly inserted in a text component

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#614]
**Case 1**
1. Install SuperHero app
2. Open SuperHero  site , open Page Component View and insert a table (5x7 for example)

BUG: The table is inserted incorrectly  :

![image](https://user-images.githubusercontent.com/3728712/60725776-98b27180-9f42-11e9-9a4d-de6991737393.png)

Case 2
1. Open new site wizard, select Superhero in apps
2. Select  Page in controllers, insert new text component and then insert any table 

![image](https://user-images.githubusercontent.com/3728712/60725895-e16a2a80-9f42-11e9-9a4e-c2d060d3167f.png)
  

Error : `VM390 _all.js:1 Uncaught TypeError: Cannot read property 'getElementsByTag' of  undefined`

![image](https://user-images.githubusercontent.com/3728712/60802413-7d817500-a181-11e9-8af8-cb23bcd05817.png)

**Click on Preview button. The table incorrectly displayed on the page:**

![image](https://user-images.githubusercontent.com/3728712/60805986-76ab3000-a18a-11e9-8678-63fead69dc78.png)

**Comment by ashklianko** [comment]
Not an issue, just a css styles used by app-superhero-blog.
