### ISSUE TITLE
Live Editor - two scrollbar appear after inserting 2 components.

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#615]
This bug reproducing in Chrome browser(Windows). It does not reproduce in FF browser
Case 1.
1. Open new site wizard, select SupeHero in apps, select Page controller.
2. Open Page Component View and insert an image with pretty large height .`Adansonia_grandidieri_02.jpg` for example (in superhero ).
3. Insert  new text component.
Bug- Two scrollbars appear in the wizard after inserting the second component

![image](https://user-images.githubusercontent.com/3728712/60727382-6f93e000-9f46-11e9-8c97-181d7b1cb13e.png)

Case 2; 
1. Open just created site and  do double click on the text component (switch ti Edit Mode)

BUG- 2 scrollbars appear after starting edit the component

**Comment by ashklianko** [comment]
Superhero app styles to be updated, not an app-contentstudio issue.
