### ISSUE TITLE
Image Wizard , Photo Form -  field values are not updated and Save button gets enabled after version rollback

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#618]
This issue is similar to the fixed bug https://github.com/enonic/app-contentstudio/issues/388
But it is reproducing when Photo properties are empty.

Steps to reproduce:
1. Download any image in internet (Photo  properties are empty in this case)
2. Open this image in wizard.
3. Go to Photo wizard-step and select a date in the input, save the image
4. Open Versions panel and rollback the previous version 

BUG: ` Date` input should be cleared and `Save` button should be disabled:

![image](https://user-images.githubusercontent.com/3728712/60808525-326f5e00-a191-11e9-98c7-e28fec0c3e71.png)

**Comment by vbradnitski** [comment]
fixed in #638
