### ISSUE TITLE
Endless spinner after duplicating text components

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#6258]
THis bug is reproduced only if the component is duplicated several times:

1. Open `Features`, 
2. Duplicate the text component **several  times**.

![image](https://user-images.githubusercontent.com/3728712/235640217-635f9ef3-0e3e-4f39-9f36-a6f446bab81f.png)

**BUG** - Error notification message and endless spinner appear after duplicating a text component several times
![duplicate](https://user-images.githubusercontent.com/3728712/235640981-20cc0da7-4bfd-4dee-8680-3e1b0b3da510.png)

**Comment by sgauruseu** [comment]
I reproduced this issue in new version of PCV

**Comment by sgauruseu** [comment]
can not reproduce in the latest version

**Comment by ashklianko** [comment]
Checked together with @sgauruseu, the issue is not reproduced anymore
