### ISSUE TITLE
Сontent selector switches to flat mode after text input

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#6355]
1. Select `Features` site then open new wizard for `Selector` content
2. Click on `mode toggler` in  `Allow all content items` combobox - Tree mode is switched on

![image](https://github.com/enonic/app-contentstudio/assets/3728712/6b4701f5-2834-4ebe-9eae-4d5d74922040)

3. Insert `features` text in options filter input:  

![image](https://github.com/enonic/app-contentstudio/assets/3728712/b2e6b6ec-7a84-4852-babd-425bbf8c2008)

**BUG** - The combobox switches to flat mode after inserting a text in the filter input

**Expected behaviour:** 

![image](https://github.com/enonic/app-contentstudio/assets/3728712/63c36962-be94-4179-88d0-71ee43e8ddda)

**Comment by alansemenov** [comment]
No, this is not the expected behaviour. Pasting text into an input is the same as typing text into an input, and in this case we switch the dropdown to flat mode.
