### ISSUE TITLE
Adding a new component triggers refresh of the editor page

### ISSUE THREAD

**Issue by poi33** [enonic/app-contentstudio#6390]
Content studio can refresh the entire page if a new part is inserted into a region. 

We have setup content studio to use the nextjs to render the frontend. 

If you add a new part to a page controller it will refresh the entire page you are on.
This gives a really bad user experience.

**Comment by ashklianko** [comment]
Reproduced it on QA and locally, investigating

**Comment by alansemenov** [comment]
Reopening this since it still happens (albeit less often than before the fix)
