### ISSUE TITLE
Don't collapse a newly added layout after selecting controller for it

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#6392]
From https://github.com/enonic/app-contentstudio/issues/6382

When a new layout is added to a page and layout controller is selected the Page Component tree is reloaded and the new layout is collapsed (since we collapse layouts by default). We should keep it expanded since user will most likely start adding components to the new layout.

**Comment by ashklianko** [comment]
@sgauruseu , please check if it is reproduced now

**Comment by sgauruseu** [comment]
The behaviour is correct now, Layout component remains expanded in PCV after selecting a layout controller

![image](https://github.com/enonic/app-contentstudio/assets/3728712/31b6dcc3-6599-4895-b284-ce0fd6fdeadf)
