### ISSUE TITLE
New fragment should be created in the same workflow state as the content it was created from

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#642]
1. Open new site wizard, select Features, select Page-controller.
2. Insert new text component(for example) then select `Save as Fragment` menu item:

![image](https://user-images.githubusercontent.com/3728712/61215572-fe0d1c00-a713-11e9-9fb3-b78a95cfeba4.png)

3. New fragment wizard is opened.

BUG: Workflow state of the fragment should `In Progress`, because parent site is 'In Progress'

![image](https://user-images.githubusercontent.com/3728712/61215739-59d7a500-a714-11e9-99b8-0bb224570165.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/xp #7244](https://github.com/enonic/xp/issues/7244) via [**ZenHub**](https://www.zenhub.com/)
