### ISSUE TITLE
Save button remains enabled after switching templates

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#6484]
1. Create a site, select Features in app-selector. (do not select a controller).
2. Create 2 templates, select `site` in support, select `main region` in controller selector 

![image](https://github.com/enonic/app-contentstudio/assets/3728712/dc661cc4-d0e3-4a2c-a6e8-b493e1062273)

3. Reopen the site, Do not click on `Customize` menu item , but open Inspect Panel and  select  `template1` then `template2` in the dropdown,

**BUG** - `Save` button remains enabled after switching the template, Click on the `Save` button, the button still enabled after clicking.

![image](https://github.com/enonic/app-contentstudio/assets/3728712/7e447809-f57d-4c84-9964-ab71b6720405)

**Comment by ashklianko** [comment]
@sgauruseu , I didn't manage to reproduce

**Comment by sgauruseu** [comment]
@ashklianko I reproduced this bug in master, I updated the description of this bug.

**Comment by sgauruseu** [comment]
can not reproduce in 6492 branch
