### ISSUE TITLE
Excluded non-required dependency aren't added in Issue Details

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#6545]
This issue is reproducing when a non-required dependency item is child of a content to publish.
Excluded non-required dependency should be added after clicking on Include child icon.

1. Create a site , insert a text component then upload an image, so  **this site has one non-required dependency (the image)** .
    or Insert a link to a child content.
3. Open `Create Issue` modal dialog and create new issue (Do not include children, do not include the dependency).

![image](https://github.com/enonic/app-contentstudio/assets/3728712/eccf931d-284c-4142-bd64-df66553a4019)

4. Click on `Include children` toggler in `Items` tab.

**BUG** - The excluded dependency should be added after clicking on `Include children` toggler.

![image](https://github.com/enonic/app-contentstudio/assets/3728712/8f7cec90-0a30-4b6e-a905-d3d337972b60)

**Expected behaviour** - all child items should be visible after clicking on `Include child items` toggler:

![image](https://github.com/enonic/app-contentstudio/assets/3728712/dca041e3-b860-4efc-97c3-1a0baa2f4d81)

But the correct behaviour of the `including child items` is present in the `Create Issue` dialog : 

![image](https://github.com/enonic/app-contentstudio/assets/3728712/99927b33-6f67-4213-a710-cddec9a20793)

**Comment by edloidas** [comment]
This is the correct behavior for Issue Details: if the item was previously excluded and that item became listed in the dependencies list, we must keep it excluded.
