### ISSUE TITLE
Creating a long description wraps incorrectly 

### ISSUE THREAD

**Issue by poi33** [enonic/app-contentstudio#657]
![image](https://user-images.githubusercontent.com/3340349/61439209-612fc600-a941-11e9-9829-74fb5a9c1c7d.png)

The class `.xp-admin-common-sub-name` allready has `text-overflow: ellipsis;` 
but its not triggered because `white-space` need to be `nowrap`.

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1119](https://github.com/enonic/lib-admin-ui/issues/1119) via [**ZenHub**](https://www.zenhub.com/)
