### ISSUE TITLE
Publishing Wizard - Handle resolvePublishContent errors

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/app-contentstudio#658]
On an installation with 6.15.6, we got the following error message in the publishing wizard
![Screen Shot 2019-07-17 at 16 55 51](https://user-images.githubusercontent.com/12030113/61445034-d94fb900-a94c-11e9-8c5c-d6318aafc6b9.png)

But I was logged in as Admin, so definitely not a permission error.
When looking at the network tab, we saw the following error.
![Screenshot 2019-07-18 at 11 10 21](https://user-images.githubusercontent.com/12030113/61445092-f7b5b480-a94c-11e9-8601-ded66d3e4c29.png)

Could you check if we are not somehow hiding the real error message.

In my local 6.15.6 installation I do not reproduce exactly this error, but I get another problem.
If the resolvePublishContent fails, the wizard still proposes to publish. Is that on purpose?

![Screenshot 2019-07-18 at 11 20 17](https://user-images.githubusercontent.com/12030113/61445775-516aae80-a94e-11e9-8abd-10f69177b7e7.png)
![Screenshot 2019-07-18 at 11 20 25](https://user-images.githubusercontent.com/12030113/61445792-54fe3580-a94e-11e9-829d-fb4acf16036a.png)

**Comment by alansemenov** [comment]
Fixed in branch **epic-workflow** (since it has a lot of changes related to displaying messages inside the Publishing Wizard). Will be merged to master once the epic is finished.
