### ISSUE TITLE
Issue Details Dialog - 'Publish & Close' button should be disabled when  items to publish are "Work in progress"

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#659]
1. Open an issue that contains item in 'Work in progress'
2. 'Publish & Close' is enabled, click on the button:
![image](https://user-images.githubusercontent.com/3728712/61456715-6d327c80-a96f-11e9-9155-337ec3746d28.png)

BUG: Error message appears after clicking on `Publish & close` button
![image](https://user-images.githubusercontent.com/3728712/61456938-f34ec300-a96f-11e9-8450-c51421957484.png)

**Comment by alansemenov** [comment]
We are rebuilding the entire issue handling, so let's not add any bugs for this until it's finished. Especially not inside the unfinished epic...
