### ISSUE TITLE
Create Issue Dialog - incorrect number of items in 'Create Issue' button

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#660]
1. Install Features, open Filter Panel,  click on `Selectors` checkbox.
2. Select both content.
3. Press on Publish button. 
4. Click on drop down handle and click on `Create Issue` menu item
   2 items is displayed in the button (OK).

![image](https://user-images.githubusercontent.com/3728712/61459408-52fb9d00-a975-11e9-8a3d-75470d297a54.png)

![image](https://user-images.githubusercontent.com/3728712/61461032-9b688a00-a978-11e9-947d-cebcd508cb0c.png)

5. Click on Back button, return to the first wizard-page.
6. Click on `Create Issue` menu button again.

**Bug** - Incorrect number of items  **5**  is displayed in the `Create Issue` button
![image](https://user-images.githubusercontent.com/3728712/61459231-f5675080-a974-11e9-996a-fcedcd2095cd.png)

**Comment by alansemenov** [comment]
No, this is wrong. Only 2 issues will actually be saved with the issue, dependant items are not included.  2 is correct number.
