### ISSUE TITLE
Shortcut wizard - Page Editor is not shown after adding page template for the content type

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#6625]
1. Create a site, select a controller
2. Add a child shortcut.
3. Add new template, select `shortcut` in the support selector.
4. Reopen the shortcut content.

**BUG** -  `Page Editor` is not shown in Shortcut wizard

![image](https://github.com/enonic/app-contentstudio/assets/3728712/1305c84e-c10a-4b71-b35b-30d49f03f179)

**Comment by alansemenov** [comment]
Page templates have never worked for shortcuts. We will remove "Shortcut" content type from the "Supports" dropdown of the page template wizard to make sure people don't create page templates for shortcuts.
