### ISSUE TITLE
New Find/Replace dialog for Rich Editor

### ISSUE THREAD

**Issue by edloidas** [enonic/app-contentstudio#6675]
Find&Replace dialog is now shown above the editor. It also blures the bsckground. These effects make it partly unusable. Moving it to toolbar must fix this problem.

**Comment by alansemenov** [comment]
https://ckeditor.com/ckeditor-5/demo/feature-rich/

<img width="1068" alt="image" src="https://github.com/enonic/app-contentstudio/assets/11612490/ee4cfbfd-d9ae-4263-91fe-7ed142f50443">
