### ISSUE TITLE
Inherited content in layers - popup dialog appears after resetting changes in wizard

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#6684]
**Case 1** 

1. Create a layer, set a language different from the language in the parent project.
2. Create a site in Parent Project
3. Go to the layer and select the inherited site and clcik on Localize button
4. Select a page controller in the ingherited site.
5. Click on Reset button in the wizard toolbar.

**BUG** - Popup dialog appears after resetting changes in the layer

![image](https://github.com/enonic/app-contentstudio/assets/3728712/332528bb-5d0f-4660-aec5-b4397b7cbf8f)

**Case 2**

1. Create a new layer, select Superhero as parent project.
2. Go to the layer, select `Supehero` site, click on `Localize` button. 
3. Click on `Reset` button
4. Click on `Localize` button in the wizard toolbar.

**BUG** - `Save`  button is enabled and PCV remains disabled after clicking on `Localize` button in the second time

![image](https://github.com/enonic/app-contentstudio/assets/3728712/b88dc0cd-b9c5-4f65-8e34-32d8f162cc2a)

**Comment by ashklianko** [comment]
Checked, part 2 is not related to part 1, will create a separate issue
