### ISSUE TITLE
Implement New Layer modal dialog

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#669]
"New Layer" dialog can be opened either from the Layers widget (when there's only base layer) or from the modal dialog with the list of layers.

**Required fields** (should be checked by validation when trying to submit the form):
1) _Display name_
2) _Parent layer_ - selector, will always be preset
3) _Default language_ - language selector, will be preset with language of the parent layer
4) _Identifier_ - text input, value is based on language code, will change every time default language is selected. Can also be edited manually. Allow value format according to the following regex: `[A-Za-z0-9\-_]`

**Optional fields:**
4) Icon - media uploader allowing SVG format
5) Description

![image](https://user-images.githubusercontent.com/11612490/61628768-809d5a80-ac83-11e9-9949-dd18dcd353fd.png)

When a new layer is successfuly created, give a notification "_New layer created successfuly_".  If there's an error, show error notification with the message sent from the backend.

**Comment by ashklianko** [comment]
@alansemenov Do we close the dialog after successful creation (can also close new layer dialog and open layer list dialog), or just keeping new layer dialog open to continue layers creation?

**Comment by alansemenov** [comment]
@ashklianko we should switch to the details dialog for the newly created layer. visually it will look as if we stayed in the same dialog. same behaviour as when we create a new issue.
