### ISSUE TITLE
Implement Layer Details modal dialog

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#670]
Modal dialog with layer details will be similar to New Layer except for the following changes:
1) the button in the footer will say "Update layer"
2) the "back" icon in the header to go to the list of layers (like we have in the Issue dialogs)
3) _Parent layer_ and _Identifier_ are readonly (changing default language should not change the identifier)
4) Different message on successful save ("_The layer has been updated_")

This dialog can be opened either from the list of layers, or from the "Layers" widget

![image](https://user-images.githubusercontent.com/11612490/61629228-92cbc880-ac84-11e9-9257-1ac2b14bb6f9.png)

**Comment by ashklianko** [comment]
Pushed into https://github.com/enonic/app-contentstudio/pull/691
