### ISSUE TITLE
Apply styling to content items in the Grid based on inherited property

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#672]
Content object now has a new boolean property: `inherited`.

![image](https://user-images.githubusercontent.com/11612490/61632425-1ab5d080-ac8d-11e9-8cf8-fd28db8626f2.png)

If `inherited` is **true**, the content item in the grid should be styled in the same way we style readonly items. Also, for inherited items we shouldn't allow _Delete, Duplicate, Move_ and _Sort_ operations.

![image](https://user-images.githubusercontent.com/11612490/61632719-d4ad3c80-ac8d-11e9-9923-6e5cbcd393d1.png)

**Comment by ashklianko** [comment]
Pushed into https://github.com/enonic/app-contentstudio/pull/730 so it could be tested
