### ISSUE TITLE
Error appears after publishing 'Work in progress'-content in grid

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#675]
1. Add a folder in root. (State is 'work in progress')
2. Select the folder , open Publish Menu and click on Publish menu item.
3. Click on Publish Now button:

![image](https://user-images.githubusercontent.com/3728712/61637275-e7307180-ac9f-11e9-8b49-4b2c8b3f3a7e.png)

BUG: Notification Error appears:

![image](https://user-images.githubusercontent.com/3728712/61637347-062f0380-aca0-11e9-993a-f561178f16c0.png)

**Comment by alansemenov** [comment]
It was a bug that Publish button was enabled when there were items in progress in the list. This is fixed now.
