### ISSUE TITLE
Macroes in rich text field are not shown in edit

### ISSUE THREAD

**Issue by poi33** [enonic/app-contentstudio#6802]
Next.adapter: 2.0.0-B3
Content studio: 5.1.0-SNAPSHOT

The macroes are not rendering insdide the component. 

Expected to have a [form <attrtibutes here>] inside the editor field

![Screenshot 2023-09-11 131605](https://github.com/enonic/app-contentstudio/assets/3340349/08d38b1b-62d8-41d8-9634-b531efc2b10f)

**Comment by alansemenov** [comment]
Seems to not be reproduced any longer
