### ISSUE TITLE
Newly created item is not added to the filtered grid

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#6818]
**Case 1:** 
1. Select a checkbox in Filter Panel (work in progress for example )
2. Open a wizard add  new content, close the wizard

**BUG** - New added content is not displayed in the filtered grid

![image](https://github.com/enonic/app-contentstudio/assets/3728712/456eed6c-86ca-4773-9361-2f057654b747)

**Case 2:**
1. Add a site , expand the site.
2. Select `Last modified - 1day` checkbox

![image](https://github.com/enonic/app-contentstudio/assets/3728712/d8ba81f8-c457-42a9-99ae-6dca2f1b21ea)
3. Delete `templates` folder
![image](https://github.com/enonic/app-contentstudio/assets/3728712/51b96af4-5d17-46ff-bfd2-20fa4f026ab9)

**BUG** - Deleted  `Templates` folder remains visible in the grid after deleting 

![image](https://github.com/enonic/app-contentstudio/assets/3728712/a32bc117-60db-4077-931b-9b54e10887cc)

**Comment by ashklianko** [comment]
Update: 
Part 1 is not reproduced now , however an other problem showed up - now newly created item is duplicated in the grid.
