### ISSUE TITLE
Content Layer - Adapt resource requests

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/app-contentstudio#684]
Adapt resource requests to use
* "/admin/rest/cms/default/[layer]/page" instead of "/admin/rest/content/page"
* "/admin/rest/cms/default/[layer]/page/template" instead of "/admin/rest/content/page/template"
* "/admin/rest/cms/default/[layer]/page/fragment" instead of "/admin/rest/content/page/fragment"
* "/admin/rest/cms/default/[layer]/icon" instead of "/admin/rest/content/icon"
* "/admin/rest/cms/default/[layer]/media" instead of "/admin/rest/content/media"
* "/admin/rest/cms/default/[layer]/image" instead of "/admin/rest/content/image"

**Comment by ashklianko** [comment]
XP and lib-admin-ui are also updated for this to work
