### ISSUE TITLE
Content Wizard - validation message disappears after saving the content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#689]
1. Select Features, open Attachments-wizard
2. Type a name and save the content.

BUG: Validation record should be displayed for required inputs:

![image](https://user-images.githubusercontent.com/3728712/61874024-fc9bda80-aeef-11e9-895a-3a8c960dcbeb.png)

**Comment by pmi** [comment]
Issue moved to [enonic/lib-admin-ui #1055](https://github.com/enonic/lib-admin-ui/issues/1055) via [**ZenHub**](https://www.zenhub.com/)
