### ISSUE TITLE
Browse toolbar is not refreshed when selected contents have been deleted 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#69]
The same bug was in :  https://github.com/enonic/xp-apps/issues/398
Case 1:
1. Create 2 folders - Folder1 and Folder2
2. Click on checkboxes and select both folders
3. Click on Delete button and confirm the deleting.
![image](https://user-images.githubusercontent.com/3728712/51183822-76209380-18e3-11e9-9765-61188d521421.png)

Bug: Delete dialog is closed, folders are deleted but 
 - buttons on toolbar have incorrect state (Enabled)
 - SelectionPanelToggler is not refreshed - 2 is present in the circle . Endless spinner appears when click on it

![image](https://user-images.githubusercontent.com/3728712/51183657-f266a700-18e2-11e9-9923-06dc21e621e9.png)

**ContentItemStatisticsPanel** is not refreshed as well. Deleted image is displayed on the panel,  when images were selected and deleted

![image](https://user-images.githubusercontent.com/3728712/51244843-26030900-1997-11e9-93f0-fd135448782d.png)

**Case 2:**
1. Create a folder.
2. Type the name of the folder in Filter Panel
3. Select the folder and delete it 
BUG: Selection circle  remains when the content has been deleted

**Comment by edloidas** [comment]
Issue moved to [enonic/lib-admin-ui #911](https://github.com/enonic/lib-admin-ui/issues/911) via [**ZenHub**](https://www.zenhub.com/)
