### ISSUE TITLE
'Publish...' should be the default action for content in Deleted state

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#692]
1. Add a folder and publish it.
2. Open the folder and change a language, for example, The folder gets Modified.

![image](https://user-images.githubusercontent.com/3728712/62040425-4a6f5600-b202-11e9-976d-88b239a8a171.png)

3. Select the folder in the grid and  delete it.

**BUG**: The folder is `Deleted` now , but `MARK AS READY`  is present on the toolbar:
![image](https://user-images.githubusercontent.com/3728712/62040768-e26d3f80-b202-11e9-9263-55262ac52fd6.png)

**Expected**:  `Publish...` button should be present in the toolbar.

**Comment by alansemenov** [comment]
"Mark As Ready" should be disabled in the dropdown for Deleted content
