### ISSUE TITLE
Content in the Publishing Wizard is not updated after it has been changed on the server

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#697]
1. Select `Work in progress` content, then click on `Publish...` menu item.
2. One item to publish is displayed on the modal dialog, click on the `item-link` and switch to the opened content wizard.
3. Update `displayName` of the content  and click on   `Mark as ready` or "Publish" menu items in the wizard-publish menu. 
4. State of the content is changed. Close the content wizard.

**Issue**:  Wizard is closed but modal dialog is not updated after changing the state of the content in wizard.

![image](https://user-images.githubusercontent.com/3728712/62113491-608e1c80-b2bd-11e9-8f95-5e8823c32bbf.png)

**Comment by alansemenov** [comment]
Item status is updated correctly now but we should also update a) the section above the items that shows that there are invalid/in progress items, b) state of the Publish button. Here on the screenshot I marked the main item as ready, but the dialog still says that there are items in progress and Publish button is still disabled.

![image](https://user-images.githubusercontent.com/11612490/62412972-d372fc80-b609-11e9-96ce-0df6f999c02c.png)
