### ISSUE TITLE
Content Wizard - Schedule form is cleared after this content has been modified

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#699]
1. Open Large Tree content and publish it:

![image](https://user-images.githubusercontent.com/3728712/62123516-c46e1080-b2d0-11e9-983f-ae6985cc5a30.png)

2. Modify this content - select a language, for example.

BUG: Schedule form is cleared after this content has been updated:

![image](https://user-images.githubusercontent.com/3728712/62123663-0f882380-b2d1-11e9-8ca7-bf6e2782b389.png)

**Comment by pmi** [comment]
Issue moved to [enonic/lib-admin-ui #1056](https://github.com/enonic/lib-admin-ui/issues/1056) via [**ZenHub**](https://www.zenhub.com/)
