### ISSUE TITLE
Content changes are not saved along with meta data updates

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#7128]
To reproduce:
1. Open a published content
2. Make some changes inside the content form. "Save" button becomes enabled.
3. Open the Details widget
4. Click "Edit schedule" in the Details widget
5. Change Published From date to something else
6. Click Update button
7. Content gets saved, "Save" button becomes disabled.

Bug: Content changes are not saved (can be verified with a page refresh), only the new Online From. Same problem with meta-data ("Edit settings" link above).

**Comment by ashklianko** [comment]
Issue is reproduced on 7.11, didn't check earlier versions
