### ISSUE TITLE
Default action is not updated after creation of a new Publish Request

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#717]
1. Open a folder. Do it 'Mark as ready'
2. Open publish menu and select `Request Publishing...`
3. Click on Next, then type a changes and  click on `Create request `

BUG: 
1) `Open Request` button should appear  on the toolbar and `Open Request...` menu item should appear in the menu-items: 
2) `Open Request` should end with dots.

![image](https://user-images.githubusercontent.com/3728712/62473015-9a24c300-b7a8-11e9-9f64-7e2c6caf17ea.png)

**Comment by alansemenov** [comment]
We should also update the default action for an item when an active publish request containing that item is closed
