### ISSUE TITLE
SettingsItemsTreeGrid: replace slickgrid classes 

### ISSUE THREAD

**Issue by ashklianko** [enonic/app-contentstudio#7172]
Refactor to use new non-slickgrid classes

- [x] Replace TreeGrid with TreeListBox
- [x] Add Expand/Collapse funcs
- [x] Expand on load
- [x] Add locale code after display name 
- [x] Add context menu
- [x] Bind actions
- [x] Add double click handler
- [x] Add Highlight/Select functionality
- [x] Adjust styling to look the same as TreeGrid version
- [x] Add selection toggler toolbar
- [x] Maintain context-like list of all projects 
- [x] Handle server events
- [ ] Keyboard navigation

**Comment by alansemenov** [comment]
Keyboard navigation should be moved to a separate issue
