### ISSUE TITLE
HTML Editor: Fix shortcuts for heading and tab cycle

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#72]
https://xp.readthedocs.io/en/stable/admin/contentstudio/shortcuts.html

All of these used to work in TinyMCE.
* Ctrl-Shift-numeric won't convert text to a header (Cmd-Alt-numeric works on Mac)
* Alt-Tab is used for switching between windows in Win, it should tab out of editor (or find another "X-tab" shortcut that will work on Windows). Works fine on Mac.
* Copy-pasting text from Google Docs document with Ctrl-V (formatted paste) always makes text bold, even when original text is not bold (also on Mac)
* When copy/pasting text from the Word file below (for example, a couple of paragraphs from the "Forord" section), it gets pasted with inline styling on ``<p>`` elements, for example ``<p style="margin-left:28.85pt; margin-right:10cm">`` 

[Eksempel på innrykkskode.docx](https://github.com/enonic/app-contentstudio/files/2767757/Eksempel.pa.innrykkskode.docx)

**Comment by ashklianko** [comment]
- Made formatting shortcuts work
- ALT+TAB is a native shortcut on Windows for switching between open windows; No way to catch and replace it's behaviour in browser;  Disabled indent/outdent shortcuts to make TAB key focus on next element on windows; now indent/outdent commands executed only via buttons on toolbar
- Copy-pasting text from Google Docs and seeing it as bold is a known issue for Google Docs, as webkit browsers wrap it's data with own tags that are translated into bold; Same behaviour in Tinymce; There's issue open in CKE: https://github.com/ckeditor/ckeditor-dev/issues/835
- When Copy/Pasting form word editor tries to preserve formatting text had in word, thus it results in text having styling with margin in editor
