### ISSUE TITLE
Project Wizard - improve project/layer selection step

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#7289]
On the first step of the Project Wizard user has to specify whether he/she creates a project or layer. If "Layer" radio is selected, then we show the dropdown with projects for selecting parent for the new layer. 

1. The radio group should be removed. If user will select a parent project in the dropdown then we'll create a layer, otherwise a new project.

2. Change label of the dropdown to make it obvious what "parent project" actually means.

If multi-inheritance is disabled (default):
_Should data be inherited from another project? Select it here:_

If multi-inheritance is enabled:
_Should data be inherited from other projects? Select them here:_

3. Make sure "Next" button is replaced with "Skip".

![image](https://github.com/enonic/app-contentstudio/assets/11612490/b5362570-226d-464a-bec3-6612c210df35)
![image](https://github.com/enonic/app-contentstudio/assets/11612490/f78133c6-9ec9-4872-a9d7-7f120f8b1df9)

**Comment by vot-enonic** [comment]
Other suggestions for improvement, @alansemenov 

- When creating a new layer, and you have already selected a layer/project in the grid, the latter should be populated as the parent in the wizard
- Apps should be possible to copy, including configuration, from parent (PLZ)

**Comment by alansemenov** [comment]
> When creating a new layer, and you have already selected a layer/project in the grid, the latter should be populated as the parent in the wizard

We had this originally but removed as people were seemingly confused. Do you remember why exactly @sigdestad? I also think it was convenient.

> Apps should be possible to copy, including configuration, from parent (PLZ)

👍

**Comment by sigdestad** [comment]
The UI was a bit different at the time, with the refactoring, I agree we should set the selected project as parent by default. Now this can easily be removed anyway.

**Comment by alansemenov** [comment]
> Apps should be possible to copy, including configuration, from parent (PLZ)

https://github.com/enonic/app-contentstudio/issues/7418
