### ISSUE TITLE
Duplicated items in Issue Details Dialog

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#733]
1. Select `Features` and open `Create Issue` dialog.
2. type  a name and click on `Create issue` button .
3. Open `Items-tab` Switch the selector to Tree-mode , then expand options and add `Large Tree`
   Click on Apply button

![image](https://user-images.githubusercontent.com/3728712/62610891-38ca3480-b90d-11e9-9484-00beab3ee9ce.png)

4. Close the modal dialog.
5. Click on the issue menu-item(ItemPreviewToolbar) and open this modal dialog again.
6. Expand  options in the content selector: 

![image](https://user-images.githubusercontent.com/3728712/62611158-bbeb8a80-b90d-11e9-8516-7b5a4087e25b.png)

**BUG - Large Tree is not checked in options**
Select this option again. Two Large Tree items appears on the dialog
 
![image](https://user-images.githubusercontent.com/3728712/62611073-965e8100-b90d-11e9-8149-c7e94a3b58d0.png)

**Comment by alansemenov** [comment]
I don't reproduce it on master. Publish requests are not yet merged to master, and for regular issues I'm not getting this behaviour.
