### ISSUE TITLE
Issue Detail Dialog - cannot replace a single selection on the Items tab

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#734]
This issue can be linked to  https://github.com/enonic/app-contentstudio/issues/725
1. Select Features and create new issue.
2. Issue details dialog is loaded (OK).
3. Open Items tab , click on drop down handle then uncheck `Features` and check `Large Tree`

![image](https://user-images.githubusercontent.com/3728712/62613623-7bdad680-b912-11e9-8eeb-19ac234cbede.png)

4. Close the dialog.
5. Click on the issue name in the ItemPreview toolbar and open the dialog again, go to Items tab:

BUG: Features site is in selected options in the tab:

![image](https://user-images.githubusercontent.com/3728712/62613747-bc3a5480-b912-11e9-8cde-e98aa532fca7.png)

**Comment by alansemenov** [comment]
Will be obsolete when https://github.com/enonic/app-contentstudio/issues/725 is fixed
