### ISSUE TITLE
Issues in new version of selectors

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#7362]
**### Image Selector** 

1.  **FIXED**  Incorrect styles for Edit/Remove button .        
    **Steps** 
    - open a content with ImageSelector,
    -  click on a selected option

![image](https://github.com/enonic/app-contentstudio/assets/3728712/c70a2c6c-39c0-4ae1-b39c-d3ab67bb99f4)

2.   **FIXED**  Content with image selector is not correctly saved after selecting more than Max images in the selector 
    **Steps** 
    - Open new wizard for content with image-selector 2-4,   
    - Select 5 images in the dropdown-list and click on `Save` button, 
    -  Reopen or refresh the page in browser
        Issue - `Save` button is enabled, this content is invalid in the `Browse Panel`

3. **FIXED** Instead of one item, an infinite number of items are shown in the filtered dropdown
    **Steps** 
   - open a content with image selector
   - Insert a name of existing image in the Options Filter Input
   
![image](https://github.com/enonic/app-contentstudio/assets/3728712/3223b047-3086-41a0-9cce-9d574a606064)
 
4. `No matching items` message should appear after inserting a non-existing name of image

![image](https://github.com/enonic/app-contentstudio/assets/3728712/d4591982-bcc2-44c4-9821-6093e554709a)

5. **FIXED**  Content selector in `Insert Link` dialog - 
      - content are not filtered in the dialog:
      - tree mode should be by default in the content selector

![image](https://github.com/enonic/app-contentstudio/assets/3728712/fa9c4d4a-c498-42a3-bad9-f87967102f57)

6.  **FIXED**  CombobBox ;  Option filter input is not displayed after removing options 

**Steps** - 
  - open new wizard for Combobobox (2:4)
  - select 5  option 
    Save the content then remove one of the selected option

![image](https://github.com/user-attachments/assets/d3576cd8-387f-4fb4-ae70-2c3bbde0caec)

**BUG - Options filter input should be displayed in the form**

7.  **FIXED**   **BUG** -  **Validation message should not be displayed:**
![image](https://github.com/user-attachments/assets/e4df5766-f409-409c-8ea7-c508e7cff47e)

 **FIXED**    **8.  Options always selected in Custom Selector content**

  **Steps** -  Select Features site , then open new wizard for `Custom Selector` 
  **BUG** - both options are selected in the new wizard 

![image](https://github.com/user-attachments/assets/7b175493-2c8a-4652-8ffe-f1e311030ffe)

  **FIXED**   **9  Duplicated items in `Content Selector` in `InsertLink` modal dialog**
 - Open  the dialog, switch  the selector to `Flat mode`
 -  Insert Templates-text in the options filter input
 
![image](https://github.com/user-attachments/assets/e0440c7c-5591-4844-8185-80a71ee00199)

**Comment by ashklianko** [comment]
Issue N8 can be checked again
