### ISSUE TITLE
Content Selector - options loose selection after switching a mode

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#7387]
**FIXED** 1. Open a content with selector , expand the dropdown and select a content 
![image](https://github.com/enonic/app-contentstudio/assets/3728712/8b27e1d9-9f4e-431e-b339-fdf2a3d23175)

2. Click on `Mode-toggler` button and switch to `tree mode`

**BUG** - the selected option gets unselected but `OK` button remains visible:

![image](https://github.com/enonic/app-contentstudio/assets/3728712/cd040848-c689-45d5-91a1-42fcbf9c11c7)

**Comment by ashklianko** [comment]
Commited into epic branch, hiding the button on tree/flat mode switch
