### ISSUE TITLE
Save button remains enabled after image is replaced and saved inside a fragment

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#74]
Create an image-fragment
1. Open new site wizard, select Features, select default page controller
2. Open Page Component View and insert an mage , save it as fragment

Go to Fragment wizard, 
- Open Page Component View and click on the image
- open Inspection Panel.
- click on remove-icon and select another image.

Bug: Notifiaction message "Item ..... is saved"
But  Save button is still enabled. Click on close-tab icon,  'Live site' alert appears

![image](https://user-images.githubusercontent.com/3728712/51249344-0c1bf300-19a4-11e9-9be1-bc682bd4b68a.png)

**Comment by ashklianko** [comment]
@sgauruseu , this was fixed in https://github.com/enonic/app-contentstudio/issues/104.
Please check that this issue is not actual anymore.

**Comment by sgauruseu** [comment]
Bug is fixed now. I verified it on the latest build . I will add ui-test for the bug
