### ISSUE TITLE
Project Applications step is not correctly updated after pressing on Copy from parent button

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#7430]
**Case 1**
1. Create a project with 2 selected applications 
2. Select the project and open new wizard for a layer.
3. Go to `Applications Step`
4. Click on 'Copy from parent' button

**BUG:**
-  Skip button remains visible after copying application from its parent.
-  `Copy from` button should be disabled.

![image](https://github.com/enonic/app-contentstudio/assets/3728712/69f772fb-564c-494c-9b8c-d2b320648246)

**Case 2**

5. Click on `Back` button - `Roles step` is loaded - OK
6. Go to `Applications step` again  -   `Copy from parent` is disabled now - OK.
7. Remove one of the Applications 

**BUG** - `Copy from parent` button remains disabled after removing an application.

![image](https://github.com/enonic/app-contentstudio/assets/3728712/62adbeb2-34c8-4293-8158-403b0617cb65)

**Case 3**
 - Open project wizard, Select `Deafult` project in `Parents step`
 - Go to `Applications step` select an application 

**BUG** -  `Copy from default` remains disabled after selecting an application

![image](https://github.com/enonic/app-contentstudio/assets/3728712/ec75c99a-f8fb-4776-b40b-52cbffd241ad)

**Comment by alansemenov** [comment]
There won't be "Copy from parent" on the Applications step. Read about the new behaviour here: https://github.com/enonic/app-contentstudio/issues/7441.
