### ISSUE TITLE
Add 'Copy Applications from parent' button in wizard-page for layers

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#7431]
1. Create a layer , (select apps in `Applications step`) 
2. Open the just created layer.

**Expected** : `Copy from parent` button should be present in `Applications form` on the page  

![image](https://github.com/enonic/app-contentstudio/assets/3728712/8d9fcaf3-4938-4ad1-ae54-cfe56c7eb3c3)

**Comment by alansemenov** [comment]
There won't be "Copy from parent" button for applications (for neither new or existing layer). Layers automatically inherit applications from their parent, so they should always be displayed (for both new and existing layer) with no option to remove them. Here's the task: https://github.com/enonic/app-contentstudio/issues/7418.
