### ISSUE TITLE
Display apps from parent project in the Layer Settings form

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#7441]
Same as https://github.com/enonic/app-contentstudio/issues/7418, but for an existing layer it should be possible to edit site configs for apps inherited from the parent.

**Comment by vot-enonic** [comment]
I am testing the "Parent project apps" improvement from Content Studio 5.2. As far as I can tell, the project wizard does not list the existing apps from the parent project in the manner that the documentation asserts. In the below test, I am on QA and am testing a new layer based on the main Enonic project. You would believe it has a sizeable list of apps, but it doesn't.

See my test to the left and the documentation screenshot to the right.
![image](https://github.com/enonic/app-contentstudio/assets/43465080/22705a18-8bc6-49c1-add5-0d80c39a803f)

I can't tell which apps are included or not based on the current project wizard.

**Comment by alansemenov** [comment]
Well, it means you don't have any apps on the parent project (or you haven't selected parent project at all)
