### ISSUE TITLE
Customize page is not working

### ISSUE THREAD

**Issue by pmi** [enonic/app-contentstudio#7470]
IMPORTANT: Use next.xp for rendering. 
Edit "Carrie Ann Moss" and and try to customize page. 
It will simply "freeze" with an overlay.

**Comment by ashklianko** [comment]
Reproduced without next, using custom controllers mapping that returns some html for a content that has no page obj and no page template rendering, thus custom controller renders it and 'Customize' action becomes available with no reason.
