### ISSUE TITLE
Go back to the Layer List after closing the Create/Update Layer dialog

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#748]
If the Layer dialog was opened from the layers list, there's no way to go back to the list (there's no "back" icon as in the update layer dialog). If we cancel or close the dialog, the list dialog is no longer visible and has to be reopened. 

So, **if the Layer dialog was opened from the layers list** and closed (with either Cancel button or X icon) then we need to go back/reopen/make visible the list dialog again. But if the Layer dialog was opened from the Layers widget, then we will simply close it.

**Comment by alansemenov** [comment]
Good, but we need the same behaviour for the Details dialog as well (should've mentioned that). Again, only when it was opened from the list and then closed/canceled.

**Comment by ashklianko** [comment]
Will do
