### ISSUE TITLE
Controller returning null breaks part/layout placeholder

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#7497]
1. Create a part with a controller that returns `null`
2. Add a part to a page and select the controller from the previous step in the part dropdown

Bug: The result will be a part placeholder which still looks like no controller is selected, although it is and is correctly shown in the Inspect panel on the right. There's the same problem with layouts.

![image](https://github.com/enonic/app-contentstudio/assets/11612490/ba1206d0-4b89-4326-9cae-9caed3ee4c4c)

We should fix it so that:
1. Controller dropdown is not shown
2. A text is shown over the placeholder saying that the part (or layout) is empty

Suggestion:
![image](https://github.com/enonic/app-contentstudio/assets/11612490/cf469a2a-6131-40bb-b11d-1aeee9b36401)

**Comment by sigdestad** [comment]
How avout rolling back to XP 7.11 + older CS, and see how this was handled before? AFAIK, there was a fallback for empty components then?

**Comment by alansemenov** [comment]
No, we never had a fallback. In earlier versions such a component was simply not shown inside Page editor.

Here's XP 7.10.3 + Content Studio 4.2.5 (note the narrow blue line where the "empty" part is):
![image](https://github.com/enonic/app-contentstudio/assets/11612490/562c152c-18d5-4c7f-a17c-ce7ffaade581)

**Comment by sigdestad** [comment]
Let's have a 10 min session to conclude the design!
