### ISSUE TITLE
Content Preview Toolbar is not updated after item is added to a publish request

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#752]
Select Features in the grid and create a new Publish Request with it.

![image](https://user-images.githubusercontent.com/11612490/62706742-6cca5600-b9f0-11e9-9034-90dcaf55689c.png)

BUG: new request menu item should appear on the ItemPreviewToolbar

It works for issues, but not for publish requests.

**Comment by edloidas** [comment]
Related to the #717. Should be fixed, after the PR #762 is merged.
