### ISSUE TITLE
Esc will not close the Publishing Wizard when it was opened from the Issue Details dialog

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#754]
Case 1:
-Select a folder in the grid and click `Request Publishing...`, press `Next` button , type changes.
- Click on `Create Request`  button.
- Issue Details Page is loaded.
- press ESC key.
BUG: the dialog is not closed:  
![image](https://user-images.githubusercontent.com/3728712/63264775-91e28280-c294-11e9-93ec-f24cd2b0c3f9.png)

The same issue when the modal dialog is opened in a wizard.

Case 2:
1. Select a folder and create new issue.
2. Issue Details dialog is opened. Go to items tab and click on Publish... button.
3. Publishing wizard is opened. 
4. Press `Esc`  - Publishing Wizard is not closed. Click `Esc` in the second time.

**BUG** Issue details dialog is closed , but Publishing Wizard remains in Browse Panel 
![image](https://user-images.githubusercontent.com/3728712/62710338-c5551f80-b9ff-11e9-94c7-bbe0c64d8dd2.png)

**Comment by alansemenov** [comment]
I still reproduce this after the fixes.
Case 1 reproduces exactly like described above.
In case 2 it's now different - Esc will clear the publish message in the header which was originally set from the issue title. Upon second press Esc it closes the dialog as it should.
