### ISSUE TITLE
Caption text remains visible in html-area after archiving its image

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#7558]
1. Open a content with Html-area or a site with text component
2. Open Insert Image dialog , select `Decorative image` radio button
3. Fill in the caption input , click on `Insert/Update` button
![image](https://github.com/enonic/app-contentstudio/assets/3728712/ac483275-e47a-45ef-b8a6-5c8d6eea9530)

4. Go to Browse panel and archve the image (click on `Ignore inbound references`)
5.  Switch to the content wizard then refresh it in browser or reopen  the content.

**BUG**:  Caption text is displayed in the html-area

![image](https://github.com/enonic/app-contentstudio/assets/3728712/8c3dfc56-3743-48fb-95c6-e942cb429b8d)

**Comment by alansemenov** [comment]
Why is this a bug? Caption is stored in this content, not in the archived one. So there's no reason to why it should be hidden if the image is archived. We should fix [this bug](https://github.com/enonic/app-contentstudio/issues/7559) to show some kind of placeholder for an image that is no longer accessible, but caption doesn't have anything to do with that.

**Comment by sigdestad** [comment]
I guess there are two approaches when considering this in the front-end, and we should conclude what is the right approach - as some of this may occur within the API

a) The whole figure element is removed when image is missing
b) Front-end (or backend?) uses a nice fallback image if image is missing

**Comment by alansemenov** [comment]
a) We cannot modify the original content if an image is gone missing, in any case. And we won't have any magic that "hides" the figure element inside the editor if the image is not available.
b) This is another bug registered here: https://github.com/enonic/app-contentstudio/issues/7559.
