### ISSUE TITLE
Adding author in content type "blog post" leads to wrong field

### ISSUE THREAD

**Issue by vot-enonic** [enonic/app-contentstudio#76]
When adding an author in a blog post type (with keyboard) and pushing enter, you get transported to the "Topics" field, instead of the "Teaser text" field.
![5jxag2gtko](https://user-images.githubusercontent.com/43465080/51250786-d3761c80-1997-11e9-88ed-fb3a42e5653d.gif)

**Comment by alansemenov** [comment]
Issue moved to [enonic/lib-admin-ui #899](https://github.com/enonic/lib-admin-ui/issues/899) via [**ZenHub**](https://www.zenhub.com/)
