### ISSUE TITLE
Content in the Publish Request Wizard is not updated after it has been changed on the server

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#760]
1. Add new folder , select it and open Request Publishing dialog:

![image](https://user-images.githubusercontent.com/3728712/62769442-a909bf00-baa1-11e9-900f-6e6aca43bdd6.png)

2. Click on the item in the dialog, do Marked as ready in the opened wizard, then close the wizard.

BUG: The workflow state is updated in the modal dialog but Next button is disabled and warning is still displayed:

![image](https://user-images.githubusercontent.com/3728712/62769593-fab24980-baa1-11e9-836b-6528ee473cb4.png)

**Comment by alansemenov** [comment]
Thought this was fixed?

**Comment by sgauruseu** [comment]
This issue is fixed in Published Wizard , not in Request publishing dialog!

**Comment by pmi** [comment]
Has already been fixed by publish dialogs refactoring
