### ISSUE TITLE
Broken  layout in modal dailogs

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#765]
**This issue does not reproduce in master**
Case 1:
1. Open a content with HtmlArea, (or SiteConfigurator with htmlarea).
2. Open Insert Image dialog and select the `elephant` image (in Features).

**BUG: Broken layout after the image is uploaded**
![image](https://user-images.githubusercontent.com/3728712/62784421-1d0a8e00-bac7-11e9-881d-e5041760cd47.png)

Case 2:
1. Select `Features`  and `Large Tree` 
2. Click on `Delete` button 

![image](https://user-images.githubusercontent.com/3728712/62785017-614a5e00-bac8-11e9-8f97-fe1244a13155.png)

Case 3:

![image](https://user-images.githubusercontent.com/3728712/62936031-5eee4980-bdd1-11e9-93a0-d48109cf3261.png)

**Comment by sgauruseu** [comment]
![image](https://user-images.githubusercontent.com/3728712/63412145-c32b9180-c3ff-11e9-86e1-5d8657c2c49a.png)

 The same issue in DeleteContent dialog

**Comment by sgauruseu** [comment]
![image](https://user-images.githubusercontent.com/3728712/63413436-5f569800-c402-11e9-9c8f-31f8d2ae3ea7.png)

**Comment by alansemenov** [comment]
@sgauruseu  @edloidas I have the same issue with the Insert Image dialog, but Delete dialog and New Issue look fine to me.

![image](https://user-images.githubusercontent.com/11612490/63415097-7b0b6f80-c3fd-11e9-9e4e-701afa24f9cf.png)

![image](https://user-images.githubusercontent.com/11612490/63415125-85c60480-c3fd-11e9-9503-45f0457343d7.png)

**Comment by edloidas** [comment]
Related PR in the [lib-admin-ui](https://github.com/enonic/lib-admin-ui/pull/1073) repo was not merged. Will reopen it, merge and test again.
