### ISSUE TITLE
Incorrect behavior after applying changes in Inspection Panel

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#77]
**Case 1**
1. Open Features, open Page Component View and insert an image. Press the `Save` on wizard-toolbar
2. Click on the inserted component and open Inspection Panel
3. Type a text in caption input  "test caption" click on Apply
4. Clear the text in caption and type "may caption" click on Apply

**Bug: the previous text appears in the caption-input, when Apply has been pressed.** 

![stepp1](https://user-images.githubusercontent.com/3728712/51257067-de40a980-19b7-11e9-9dc7-34bff1b2b411.png)

**Case 2**
 1. Open SuperHero, open Page Component View click on Post List part.
2. Select a post folder for the part(Comments for example) , press Apply button
3. Remove just selected post folder and select another - "Categories" for example

 **BUG: Browser hangs after selecting "Categories"  folder,** 
![step-superh](https://user-images.githubusercontent.com/3728712/51674573-0f396380-1fe2-11e9-9dcb-44a41858021f.png)

Page is getting unresponsive. Alert appears in the browser : 

![unresp](https://user-images.githubusercontent.com/3728712/51674600-211b0680-1fe2-11e9-884f-01279b84e304.png)

**Case 2** is reproducing in Features as well.  (select the part "Image Filters test" and change a folder in Inspect panel)

![image](https://user-images.githubusercontent.com/3728712/51680067-d0130e80-1ff1-11e9-8db7-49177054fd31.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #918](https://github.com/enonic/lib-admin-ui/issues/918) via [**ZenHub**](https://www.zenhub.com/)
