### ISSUE TITLE
Set language when turning inherited content into a local copy

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#775]
We now correctly set language of a new local content when implicitly creating it in the layer. We should do the same when we turn an inherited content into local by editing it. 

When user clicks "Edit" (or opens the Wizard directly) for an item that has `inherited` property set to `true`, update `language` property with language of the current layer and save content. After such an update, give user a notification (similar to "_Item is created_" which we give for a new item) saying "_A local item is created with language "en"_"

Test that if the item is already local then none of this happens.

**Comment by ashklianko** [comment]
One thing: Save button becomes active on languge update, but that is ContentWizardPanel issue, probably should leave it to fix later

**Comment by alansemenov** [comment]
It works correctly for folders in the root, but for site and child items inside it won't show selected language in the selector (although language is correctly updated in the content)

**Comment by ashklianko** [comment]
Updated
