### ISSUE TITLE
Change the Norwegian translation of "Issues"

### ISSUE THREAD

**Issue by vot-enonic** [enonic/app-contentstudio#7759]
We should change the Norwegian translation of "Issues" from "Saker" to "Oppgaver".

![image](https://github.com/user-attachments/assets/bc108a75-5659-48cb-8ebb-611a13fb3300)

**Comment by alansemenov** [comment]
Done (coming in the next release:
https://github.com/enonic/app-contentstudio/pull/7760/files
https://github.com/enonic/app-contentstudio/pull/7761/files
