### ISSUE TITLE
Publish Request doesn't get closed after publishing

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#778]
After a **publish request** gets published, the notification says "Issue ... is closed", but the publish request remains open.

Also see https://github.com/enonic/app-contentstudio/issues/781 for a different behaviour when an issue gets published.

**Comment by sigdestad** [comment]
I think the checkbox and text should be right-aligned to be associated with the button?

**Comment by sigdestad** [comment]
Or maybe we should simply change the button text to "Publish and close request"?

**Comment by sigdestad** [comment]
Conclusion: We should simply close the request when publishing, and the user should then see the closed issue after request is completed, and he can "re-open" it.. I think :-)

Anyway, lets discuss before implementing.

**Comment by alansemenov** [comment]
This is a wrong issue for these comments. This is a bug that the publish request doesn't get closed after publishing even though the notification says so. Here's the checkbox task: https://github.com/enonic/app-contentstudio/issues/781.
