### ISSUE TITLE
Issue Details Dialog - Items-tab should be activated after closing the Publishing wizard.

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#779]
1. Select an issue and open  `Issue Details` dialog.

![image](https://user-images.githubusercontent.com/3728712/62925837-e761ef80-bdbb-11e9-9ba8-121e1ce4de6b.png)

2. Go to Items-tab, click on `Publish..` button. Publishing wizard is opened (OK).

![image](https://user-images.githubusercontent.com/3728712/62925993-314ad580-bdbc-11e9-8bb1-87c2efc6b19a.png)

3. Do close the publishing  wizard , Issue details dialog is loaded again.

Issue : 
Items tab should be opened after closing Publishing wizard.  
Actual - `Comments` tab is active

**Comment by alansemenov** [comment]
I cannot reproduce this. The "Items" tab remains selected after the Publish dialog is closed.

**Comment by sgauruseu** [comment]
Probably this issue  is already fixed in another task
