### ISSUE TITLE
Misc issues in non-slickgrid classes

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#7801]
**FIXED**   **Case 1**  error after expanding combobog in `Move content` dialog

![image](https://github.com/user-attachments/assets/5b5fa28c-e749-4556-aec9-5cfbd362e37f)

**FIXED**   **Case 2**   Site wizard - app-selector does not allow to select multiple applications

Step - open wizard for new site, select an application
**BUG**  - Options filter gets not visible after selecting an application

![image](https://github.com/user-attachments/assets/c3bdd2da-ad93-4d08-9537-303567d39c3e)

**FIXED**  **Case 3**  -  Incorrect behaviour of content-filtering( grid is not refreshed after adding a content)

Steps:  1) create a folder, 2) open filter panel and insert  name of  the folder in Filter Text Input 3) Add one more folder in filterd grid

**BUG** - only one folder should be displayed in the filterd grid.  (the second folder disappears after clicking on refresh icon)

![image](https://github.com/user-attachments/assets/cecd3e39-7059-459f-863d-7b6707b05632)

**FIXED**   **Case 4**  - Incorrect behaviour of validation 

Steps -  open wizard for content with `ImageSelector 2:4`,  select 5 options 

**BUG**  - Validation error message apppears after selecting more than max items

![image](https://github.com/user-attachments/assets/21936fb8-1964-41df-9f6e-780fae326bf6)

**Comment by ashklianko** [comment]
Regarding Case 3: not adding items into filtered grid at all, otherwise need to make an additional requests to find out if the item to be added into the filtered list root
