### ISSUE TITLE
Issue Details Dialog  - Publish... button should be disabled when invalid child items are present  

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#782]
1. Select a folder with invalid child.
2. Open `Create Issue` dialog menu item, then click on Include children link, type a name and click on Create.
3. Go to Items tab.

Bug:
 Publish button should be disabled, because invalid items are present in the dependent list:

![image](https://user-images.githubusercontent.com/3728712/62944833-30c73480-bde6-11e9-9a94-248e86e2d195.png)

**Comment by alansemenov** [comment]
Nice refactoring!
