### ISSUE TITLE
Publish menu is not updated after filtered content marked as ready

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#7846]
**FIXED VERIFIED**

Steps:  
-  filter two folders then click on checkbox (select 2 folders)
  -  Click on `Mark as ready` button in browse-toolbar
  -  Close `Publish Content` modal dialog

BUG - `Mark as ready` button remains visible in the toolbar , but both folders are ready to publish

![image](https://github.com/user-attachments/assets/ef4fa3aa-16c7-4275-8396-7cb67ccf86ab)

![image](https://github.com/user-attachments/assets/59be83c0-9102-4078-bbb8-59c8fa49a554)

**Comment by ashklianko** [comment]
Need to filter and select and then filter again and select one more item so the first one does not appear in the list
