### ISSUE TITLE
Console errors in the Content grid inside layers with id XX-YY

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#785]
![image](https://user-images.githubusercontent.com/11612490/63027457-48b5bb80-bead-11e9-8b07-fbed6dc8e449.png)

See the screenshot above. The first and the last layers work fine. But switching to the 2nd or the 3rd will produce errors.
  
![image](https://user-images.githubusercontent.com/11612490/63027313-02605c80-bead-11e9-8159-a53cf9772a98.png)

**Comment by ashklianko** [comment]
Elastic search query transforms uppercase branch name to lower case thus no results;
Prohibited using upper case in layer identifier
