### ISSUE TITLE
Incorrect styles in selectors

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#7877]
Case 1
1. Open Insert Image dialog in htnlArea
2. Insert an image 

**BUG**  - incorrect styles for style selector

![image](https://github.com/user-attachments/assets/33fcc654-70e6-42ec-8117-ef177a9641b9)

Case 2  C**ontent Wizard** - incorrect styles in Widgetselector

![image](https://github.com/user-attachments/assets/df2c85b7-23a8-46d8-9573-c9ac5240588b)

**Comment by alansemenov** [comment]
Fixed
