### ISSUE TITLE
Incorrect styles for buttons

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#7901]
**Case 1 -  Inspect Panel**

![image](https://github.com/user-attachments/assets/749e0538-29e3-44cb-b284-60096452189e)

**Case 2 -  Project Wizard**

![image](https://github.com/user-attachments/assets/448879ec-8642-40f0-a4ac-0e49b1e9ac89)

**Case 3 -  Create Issue dialog** 

![image](https://github.com/user-attachments/assets/f08fc840-b70d-4e60-9c4f-1e6b5175bc09)

**Comment by ashklianko** [comment]
The issue is from master, will fix after slick removal issues are gone

**Comment by sgauruseu** [comment]
Fixed
