### ISSUE TITLE
Incorrect behaviour of image selector

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#7944]
**Case 1**
- filter and click on an option (do not click on the checkbox)

**Expected** - the option should be selected

**Actual**  -  the option is checked and `Apply` button appears

![image](https://github.com/user-attachments/assets/89741626-20ab-4a32-bd2b-72e84f391a50)

**Case 2** 
- Do filter and clcick on the first checkbox in the option
- Do filter and click on another one checkbox-option 
- Click on `Apply` button  

**BUG**  - Error in console after clickin on Apply button for 2 checked options 
![image](https://github.com/user-attachments/assets/89ab13ce-9614-4002-89ca-9ae04b033cb5)

**Comment by ashklianko** [comment]
Discussed this behavior with @alansemenov, agreed that current behavior in slickless branches is correct, clicking on items in multi-selection lists should do the same as clicking on the selection checkbox, thus issue is not an issue but a feature
