### ISSUE TITLE
Incorrect notification message when content gets marked as ready automatically 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#795]
1. Open new folder wizard , type a name , save it.
2. Open `Request Publishing` dialog. The folder gets `Marked as ready `

![image](https://user-images.githubusercontent.com/3728712/63091028-c6d59900-bf65-11e9-8b9e-b92d7e26ee9d.png)

**Issue - Notification message 'Item is marked as ready' should appear when  the modal  is opened**

**Comment by alansemenov** [comment]
If it's possible to track that it's not a usual save but a save that also marks the item as ready, change the message to "_Item "..." is saved and marked as ready_". For a usual save the notification should remain as is.
