### ISSUE TITLE
Version items are not cleared after a site has been reimported

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#796]
1. Open Features site and insert an image, text-component . save these changes. (Create some new versions).

2. Delete Features site.

3. Go to Applications and Stop then Start `Features`-app
4. Features site is imported again, open Versions panel.

Issue:  Version Items are not cleared after the site is re-imported 

![image](https://user-images.githubusercontent.com/3728712/63092941-115a1400-bf6c-11e9-957f-87cf9df5c860.png)

**Comment by alansemenov** [comment]
This is by design. Versions of deleted content are supposed to be cleaned up by Vacuum Cleaner. Also, when we implement Archive feature we'll need versions of deleted content to be kept.
