### ISSUE TITLE
Issue Details tab - Incorrect order of tabs when request is created after creating of an issue.

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#810]
1. Select a content  and create new publish request. Issue details dialog is loaded. 
   Publish Request - tab is the first.
![image](https://user-images.githubusercontent.com/3728712/63268614-3e286700-c29d-11e9-9840-e95ad741ce51.png)

2. Select this content and create an issue,  Issue details dialog is loaded and the second tab is active:

![image](https://user-images.githubusercontent.com/3728712/63268722-7f207b80-c29d-11e9-9534-8d828a0661d1.png)
 3. Close the modal dialog and create  a publish request again.

**BUG: Publish Requests is the second tab now**

![image](https://user-images.githubusercontent.com/3728712/63268889-e0e0e580-c29d-11e9-9435-55022d8e5376.png)

**Comment by edloidas** [comment]
Probably fixed in another issue.
