### ISSUE TITLE
Preview button should be disabled when  404 error is displayed

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#8107]
1. Select an image
2. Select `Site engine`  - 404 error appearars in the `Preview Panel` - OK 

**BUG** - Preview button should be disabled when 404 error in Preview Panel 

![image](https://github.com/user-attachments/assets/63ed689d-f55f-4b6c-8552-fe007643fdc9)

**Comment by pmi** [comment]
Duplicate of https://github.com/enonic/app-contentstudio/issues/8091
