### ISSUE TITLE
Incorrect message in Preview Panel when a site and Media option are selected

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#8108]
1. Select `Features` site.
2. Select `Media` in the preview dropdown

**BUG** -   `Unable to render  No template or page configured` is displayed but controller is selected in this site

![image](https://github.com/user-attachments/assets/5f22273b-c506-450b-94fd-75016b1937de)

**Comment by pmi** [comment]
@alansemenov 

Do we need to customize message depending on the selected widget ?

Or should the message just say that widget was unable to render ?

**Comment by pmi** [comment]
Agreed to make widgets able to return clarifying message with a default fall back by content studio.
