### ISSUE TITLE
Preview button is disabled after selecting a site in the second time

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#8117]
1. Select a site with a controller(Features)  - Preview button is enabled - OK
2. Click on the same row and unhighlit the site
3. Click on the row again .

**BUG**  - `Preview` button is disabled : 

![image](https://github.com/user-attachments/assets/b745fe6c-f54a-45b2-9b64-22ee8226a89d)

**Comment by pmi** [comment]
Fixed by https://github.com/enonic/app-contentstudio/pull/8126
