### ISSUE TITLE
Incorrect page title is shown when previewing media content

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#8145]
1. Select a document (txt) or an image
2. Select `Media` then click on `Preview` button

**BUG** - Incorrect page title is shown
**Expected** - The display name of the content should be displayed

![image](https://github.com/user-attachments/assets/25e1939f-e4e0-431a-8b55-1eaf239e9ac3)

![image](https://github.com/user-attachments/assets/cc714e29-2bd5-4e8b-bf34-e96831dc059f)

**Comment by pmi** [comment]
Unfortunately there is no easy way of setting tab title when serving binary content from the server directly 😒 
Browser decided that itself based on the content type.
