### ISSUE TITLE
Сalendar icon and log message should be hidden in the Publishing Wizard if all content is going to be deleted

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#824]
1. Select a Deleted content and open Publishing Wizard

![image](https://user-images.githubusercontent.com/3728712/63421660-a9934580-c411-11e9-93f0-e6bc5b0fb0a6.png)

Issue : calendar icon should be hidden in the dialog., because this content will be deleted with any date

**Comment by alansemenov** [comment]
NB! The icon should be hidden only if ALL of the items to be published are in Deleted state. Also, we should do the same in the Publish Request.

**Comment by sgauruseu** [comment]
`Start typing or click here to add a change log message`  -  change log should be hidden as well.
