### ISSUE TITLE
[Feature request]: Let page controller configure "Context Panel"

### ISSUE THREAD

**Issue by abdavid** [enonic/app-contentstudio#833]
Not sure how easy this would be, but for more advanced application development it would be nice to be able to take more control over the context panel.

By default you include [these components](https://xp.readthedocs.io/en/stable/admin/contentstudio/components.html#cs-components).

What I am thinking is that being able to configure the page controller with a sub-set of the default types or add parts directly to the context path without having to use the dropdown. If the latter is not feasible being able to hide a sub-set of the default components would be really nice, since in advanced cases using parts and fragments are most convenient. 

Some pseudo xml that would be added to the xml configuration of the page controller. 

```xml 
<config>
        <component>com.enonic.app.contentstudio.parts.Text</component>
        <component>com.enonic.app.contentstudio.parts.Image</component>
        <component>com.enonic.app.contentstudio.parts.Fragment</component>
        <component>no.my.application.namespace.parts.MyPart</component>
</config>
```

-- David

**Comment by sigdestad** [comment]
This is an interesting Idea, but what if you have multiple page controllers?
Wouldn't it be more natural to handle this on site or application level somehow?

BTW: We recommend placing questions and feature requests in our forum (https://discuss.enonic.com). Use github for pull requests and bughs
