### ISSUE TITLE
Issue Details Dialog - Issue title must be mandatory

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#861]
Preconditions : 
changes input is required:

![image](https://user-images.githubusercontent.com/3728712/63867759-12ecf880-c9be-11e9-8d04-89f90b802193.png)

1. Open existing Publish Request and remove the title

![image](https://user-images.githubusercontent.com/3728712/63867552-bdb0e700-c9bd-11e9-8068-cab075d3f88f.png)

2. Close the modal dialog and expand menu with issues: 

![image](https://user-images.githubusercontent.com/3728712/63867845-3adc5c00-c9be-11e9-8af9-e1f20f58333d.png)

**BUG: Publish Requests with empty names are in menu items**

**Comment by alansemenov** [comment]
In 7.0 we reset input value on blur if it's empty, we should do the same here
