### ISSUE TITLE
Content Wizard - Incorrect state icon after unpublished content was modified

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#863]
1. Open content in "ready" state in the editor
2. Publish it (state icon disappears)
3. Unpublish it ("ready" icon appears - wrong, but ok)
4. Make some changes to the content. "ready" changes to "in progress" - correct.
5. Save content.

Bug: Icon changes back to "ready". In Content grid it's correct ("in progress")

**Comment by sigdestad** [comment]
Hmm this is no bug Alan, after unpublishing the content should be in ready starte, possible to publish direcly again...

**Comment by sigdestad** [comment]
Unpublish does not modify the content, so it should be ready..

**Comment by alansemenov** [comment]
Of course it's a bug - state icon changes after save. You probably read up to 3rd point, but it's the last sentence where the bug is described.
