### ISSUE TITLE
Selection checkbox in the Content Grid toolbar becomes irresponsive when content is filtered

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#864]
**Case 1 is fixed.**
1. Click a checkbox and select a content in the root.
2. Open filter panel and type a name of another not selected content.
3. Click on the Selection Controller checkbox.
BUG: the check box is not clickable, then error appears in the console after clicking on `Selection Panel Toggler` (click on Show Selection)

![image](https://user-images.githubusercontent.com/3728712/63931781-99591700-ca5e-11e9-81af-0502ee2d0b73.png)

**Case 2:**

1. Open Filter Panel.
2. Click on Posts checkbox  and click on `Selection Controller`

![image](https://user-images.githubusercontent.com/3728712/64343486-4ac6f200-cff5-11e9-9eab-5de28a3faacb.png)

3. Click on `Clear`
4. Click on Selection Controller
**BUG - Checkbox becomes irresponsive** 

![image](https://user-images.githubusercontent.com/3728712/64343642-94174180-cff5-11e9-9782-b12c931f8c56.png)

**Comment by edloidas** [comment]
Issue moved to [enonic/lib-admin-ui #1086](https://github.com/enonic/lib-admin-ui/issues/1086) via [**ZenHub**](https://www.zenhub.com/)
