### ISSUE TITLE
List of issues/publish requests in Content Preview toolbar is displayed with a noticeable delay

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-contentstudio#866]
When selecting an item in Content Studio, if there is a request or issue - this will be displayed in the top right corner.

There are two problems:
1. When selecting an item, "issue info" is very delayed before it is displayed
2. When selecting another item, the issue for the old item will "hang around" for a long time before it disappears.

These might both be the same problem.
We basically need to make this info appear faster (preferably instantly) when an item is selected.

**Comment by alansemenov** [comment]
The challenge here is that the user might use keyboard to navigate up and down the grid and it would be wrong to send requests instantly, so we implemented a delay to send a request when item selection remains on the row for a while. But we should decrease this delay, yes.
