### ISSUE TITLE
Request Content Publish Dialog - Create request button should be disabled when required input is empty

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#867]
1. This issue reproducing just after the `log in` action
2. Select a folder (New) and click on `Request Publishing...` menu item.
3. Click on Next button.
4. Request Content Publish Dialog is loaded.

BUG:  Create request button is enabled and clickable.

![image](https://user-images.githubusercontent.com/3728712/63936162-d4ac1380-ca67-11e9-93ab-bcc8f92407fa.png)

**Comment by pmi** [comment]
Not reproducible any more, most likely has been fixed by some other issue.

**Comment by pmi** [comment]
Fixed by https://github.com/enonic/app-contentstudio/issues/860
