### ISSUE TITLE
Console errors after switching to layer where selected content doesn't exist

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#873]
1. Create a child layer under the base layer
2. Switch to that layer
3. Create a new content
4. Select it in the grid
5. Switch back to the base layer

We try to select the same item in the new layer and it fails because it's not there. We should reset selection if item is not found. If it's difficult to achieve, always reset selection after switching the layer.

**Comment by vbradnitski** [comment]
Issue moved to [enonic/lib-admin-ui #1081](https://github.com/enonic/lib-admin-ui/issues/1081) via [**ZenHub**](https://www.zenhub.com/)
