### ISSUE TITLE
Publishing Wizard - Dependent items toggler clears publish message

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#887]
1. Select a new or unpublished item that has child items
2. Open Publishing Wizard
3. Fill in publish message
4. Click the toggler icon to show dependencies

Bug: the publish message is removed

**Comment by pmi** [comment]
According to https://github.com/enonic/app-contentstudio/issues/696 schedule form and calendar icon are hidden if there are any issues with child content, otherwise schedule form and calendar icon remain visible.
Are you sure this should this be changed ? (y/n)

**Comment by pmi** [comment]
Publish message disappears indeed.

**Comment by alansemenov** [comment]
True, no problem with scheduling form
