### ISSUE TITLE
Roll back the changes in "Select parent" context menu

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#897]
In https://github.com/enonic/app-contentstudio/issues/541 we improved "Select parent" action in Page Editor by showing the list of parent components in the context menu. However, this list doesn't look very good:
![image](https://user-images.githubusercontent.com/11612490/64179625-cabd5280-ce63-11e9-8b41-38db84972db4.png)

Make the following changes:
1. Reverse the order (from root down to the direct parent)
2. Remove component type in brackets
3. Set padding based on level (so that the list is tree structured)
4. Decrease font size (but only under "Select parent")
5. Fix context menu width so that it's not fixed and increases for subitems with long names

![image](https://user-images.githubusercontent.com/11612490/64181256-68b21c80-ce66-11e9-9701-f8fe045bc18d.png)

**Comment by sigdestad** [comment]
Alan, i suggest we remove this functionality alltogether, and revert to the simple "select parent" instead.

**Comment by alansemenov** [comment]
Removing is always easy but what is wrong with the new approach?

**Comment by sigdestad** [comment]
I find it too "complicated". Random menu items is a tricky thing. 
If you want this stuff you can always open the page components view?

**Comment by sigdestad** [comment]
Good old "select parent" is simple

**Comment by alansemenov** [comment]
Ok
