### ISSUE TITLE
"Publish Tree" action causes two batches of identical requests

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#921]
1. Select Features site in the grid
2. Open Chrome dev tools, switch to the Network panel
3. Click "Publish Tree" button in the toolbar

There will be two batches of 5 identical requests in the list.

![image](https://user-images.githubusercontent.com/11612490/64340697-0fbdc200-cfe7-11e9-978b-a1b319a7812e.png)

**Comment by alansemenov** [comment]
@pmi Had to roll back this fix since it caused the Publish button to always be disabled and have incorrect caption in the Publish dialog. Please review the fix.

**Comment by pmi** [comment]
Created a brand new PR https://github.com/enonic/app-contentstudio/pull/1010
