### ISSUE TITLE
Publishing Wizard-  arrows are closing date time picker  

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#943]
1. Open Publishing dialog.
2. Click on calendar-button .
3. Open "Online from" dropdown
4. Try to twice click on hours arrow.  

![image](https://user-images.githubusercontent.com/3728712/64617398-11bcc200-d3e7-11e9-981f-70a079e4d4f6.png)

Actual - popup closes after a clicking on the hours arrow
Expected  clicking on  hours arrow multiple times and not close the datetime picker.

**Comment by pmi** [comment]
Issue moved to [enonic/lib-admin-ui #1117](https://github.com/enonic/lib-admin-ui/issues/1117) via [**ZenHub**](https://www.zenhub.com/)
