### ISSUE TITLE
HTML Areas are included in display name expression calculation

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#953]
Contents of the HTML Areas are unpredictable and must therefore be excluded from display name expression calculation.

**Comment by sigdestad** [comment]
Do we want it to trigger when editing htmlarea at all?

**Comment by sigdestad** [comment]
It is omportant to get the instant update when typing in textline inputs

**Comment by alansemenov** [comment]
Why should there be a difference? It either has to be consistent or not work for html areas at all.

**Comment by sigdestad** [comment]
Why on earth should this work for html-areas, imho this should only work for the simplest inputs like textline, and maybe "number" and "date"

**Comment by alansemenov** [comment]
That's what they are trying to do [here](https://discuss.enonic.com/t/display-name-expression-for-some-norwegian-symbols/1973) at least... But I agree, let's exclude html area from the expression.
