### ISSUE TITLE
Translate and clean up Swedish phrases file

### ISSUE THREAD

**Issue by jsi** [enonic/app-contentstudio#956]
The following keys are missing in 'phrases_sv.properties': 
 - action.clickToEdit
 - action.closeRequest
 - action.commentAndCloseIssue
 - action.commentAndCloseRequest
 - action.commentIssue
 - action.createRequest
 - action.markAsReady
 - action.openRequest
 - action.publishNow
 - action.reopenRequest
 - action.requestPublishMore
 - dialog.issue.noIssues
 - dialog.issue.noIssuesAndPublishRequests
 - dialog.issue.noPublishRequests
 - dialog.markAsReady.question
 - dialog.publish.addSchedule
 - dialog.publish.in-progress.part1
 - dialog.publish.in-progress.part2
 - dialog.publish.invalidError.part1
 - dialog.publish.invalidError.part2
 - dialog.publish.messageHint
 - dialog.publish.messagePlaceholder
 - dialog.publish.notPublishable
 - dialog.requestPublish
 - dialog.requestPublish.assignees
 - dialog.requestPublish.changes
 - dialog.requestPublish.error.loadFailed
 - dialog.requestPublish.noItems
 - dialog.requestPublish.subname1
 - dialog.requestPublish.subname2
 - field.all
 - field.assignedByMe
 - field.issue.hideClosedIssues
 - field.issues
 - field.publishRequest
 - field.publishRequests
 - field.rowselector.title
 - field.scheduledPublishing
 - field.scheduledPublishing.helptext
 - notify.item.markedAsReady
 - notify.item.markedAsReady.multiple
 - notify.item.savedAndMarkedAsReady
 - notify.publishRequest.closeError
 - notify.publishRequest.closed
 - notify.publishRequest.commentAdded
 - notify.publishRequest.commentDeleted
 - notify.publishRequest.commentUpdated
 - notify.publishRequest.created
 - notify.publishRequest.status
 - notify.publishRequest.updated
 - tooltip.state.in_progress
 - tooltip.state.modified
 - tooltip.state.published
 - tooltip.state.ready
The following keys are in 'phrases_sv.properties' but not in source file: 
 -action.publishAndCloseIssue
 -dialog.publish.readOnlyError
 -dialog.schedule.subname

**Comment by Bellfalasch** [comment]
Believe this one is ready. Really hard to get good overview, trying to diff `en` and `sv` files doesn't properly show me missing rows.
