### ISSUE TITLE
Translate and cleanup Portuguese phrases file

### ISSUE THREAD

**Issue by jsi** [enonic/app-contentstudio#957]
The following keys are missing in 'phrases_pt.properties': 
 - action.clickToEdit
 - action.closeRequest
 - action.commentAndCloseIssue
 - action.commentAndCloseRequest
 - action.commentIssue
 - action.createRequest
 - action.markAsReady
 - action.openRequest
 - action.publishNow
 - action.reopenRequest
 - action.requestPublishMore
 - dialog.issue.noIssues
 - dialog.issue.noIssuesAndPublishRequests
 - dialog.issue.noPublishRequests
 - dialog.markAsReady.question
 - dialog.publish.addSchedule
 - dialog.publish.in-progress.part1
 - dialog.publish.in-progress.part2
 - dialog.publish.invalidError.part1
 - dialog.publish.invalidError.part2
 - dialog.publish.messageHint
 - dialog.publish.messagePlaceholder
 - dialog.publish.notPublishable
 - dialog.requestPublish
 - dialog.requestPublish.assignees
 - dialog.requestPublish.changes
 - dialog.requestPublish.error.loadFailed
 - dialog.requestPublish.noItems
 - dialog.requestPublish.subname1
 - dialog.requestPublish.subname2
 - field.all
 - field.assignedByMe
 - field.issue.hideClosedIssues
 - field.issues
 - field.publishRequest
 - field.publishRequests
 - field.rowselector.title
 - field.scheduledPublishing
 - field.scheduledPublishing.helptext
 - notify.item.markedAsReady
 - notify.item.markedAsReady.multiple
 - notify.item.savedAndMarkedAsReady
 - notify.publishRequest.closeError
 - notify.publishRequest.closed
 - notify.publishRequest.commentAdded
 - notify.publishRequest.commentDeleted
 - notify.publishRequest.commentUpdated
 - notify.publishRequest.created
 - notify.publishRequest.status
 - notify.publishRequest.updated
 - tooltip.state.in_progress
 - tooltip.state.modified
 - tooltip.state.published
 - tooltip.state.ready
The following keys are in 'phrases_pt.properties' but not in source file: 
 -action.publishAndCloseIssue
 -dialog.schedule.subname

**Comment by bzmelotti** [comment]
- action.clickToEdit = Editar 
- action.closeRequest = Fechar solicitação
- action.commentAndCloseIssue = Comentar e fechar a tarefa 
- action.commentAndCloseRequest = Comentar e fechar a solicitação 
- action.commentIssue = Comentar 
- action.createRequest = Criar solicitação 
- action.markAsReady = Marcar como pronto
- action.openRequest = Abrir uma solicitação... 
- action.publishNow = Publicar agora
- action.reopenRequest = Reabrir a solicitação
- action.requestPublishMore = Publicando a solicitação... 
- dialog.issue.noIssues = Não existem tarefas
- dialog.issue.noIssuesAndPublishRequests = Não exitem tarefas ou solicitações 
- dialog.issue.noPublishRequests = Não existem solicitações
- dialog.markAsReady.question = Você tem certeza que deseja marcar os itens como prontos? 
- dialog.publish.addSchedule = Adicionar à agenda 
- dialog.publish.in-progress.part1 = Em progresso! 
- dialog.publish.in-progress.part2 = Um ou mais itens estão em progresso
- dialog.publish.invalidError.part1 = Itens inválidos
- dialog.publish.invalidError.part2 = Conteúdo inválido não pode ser publicado. Remova da lista ou corrija esta tarefa 
- dialog.publish.messageHint = Digite ou clique aqui para adicionar uma mensagem ao log
- dialog.publish.messagePlaceholder = Mudanças que serão publicadas
- dialog.publish.notPublishable = Alguns dos itens selecionados impedem a publicação. Verifique as mensagens de erro
- dialog.requestPublish = Solicitação de publicação 
- dialog.requestPublish.assignees = Atribuídos
- dialog.requestPublish.changes = Descreva as mudanças
- dialog.requestPublish.error.loadFailed = Ocorreu algum erro durante a publicação das dependências
- dialog.requestPublish.noItems = Nenhum item para publicar
- dialog.requestPublish.subname1 = Solicitação de publicação de outro usuário
- dialog.requestPublish.subname2 = Completar os detalhes da solicitação
- field.all = Todos 
- field.assignedByMe = Atribuídos por mim 
- field.issue.hideClosedIssues = Esconder as tarefas finalizadas
- field.issues = Tarefas
- field.publishRequest = Publicar solicitação
- field.publishRequests = Publicar solicitações 
- field.rowselector.title = Mostrar 
- field.scheduledPublishing = Publicação agendada 
- field.scheduledPublishing.helptext = Nota: Somente itens offline serão agendados. Todas as outras mudanças serão publicadas imediatamente. 
- notify.item.markedAsReady = Item "{0}" está marcado como pronto
- notify.item.markedAsReady.multiple = {0} itens estão marcados como prontos
- notify.item.savedAndMarkedAsReady = Item "{0}" está salvo e marcado como pronto
- notify.publishRequest.closeError = Falha ao finalizar a solicitação de publicação "{0}".
- notify.publishRequest.closed = A solicitação de publicação "{0}" está fechada.
- notify.publishRequest.commentAdded = O seu comentário está adicionado a solicitação de publicação.
- notify.publishRequest.commentDeleted = O comentário foi removido da solicitação de publicação.
- notify.publishRequest.commentUpdated = A solicitação de publicação foi atualizada.
- notify.publishRequest.created = A solicitação de publicação foi criada com sucesso.
- notify.publishRequest.status = A solicitação de publicação está {0}.
- notify.publishRequest.updated = A solicitação de publicação foi atualizada.
- tooltip.state.in_progress = Em progresso 
- tooltip.state.modified = Modificado {0} por {1}
- tooltip.state.published = Publicado {0} por {1} 
- tooltip.state.ready = Pronto para publicação
