### ISSUE TITLE
Image Selector content - error appears after selecting an option.

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#971]
**Case 1:**
1. Select Features and open Images Selector wizard.
2. Type `spumans` in the  `One required` image selector.
3. Press arrow down key , the image is focused
4. Press Enter key.
5. Click on Save button
BUG:   Error message   `Service error: Maximum call stack size exceeded`

![image](https://user-images.githubusercontent.com/3728712/65035741-9ca33c80-d952-11e9-967e-a549b1e89612.png)

**Case 2:** - Does not always reproduce.
1. Open new wizard for Image Selector content (Features).
2. Use `Min2 , Max 4`  selector - type a name of image in the filter options input, and click on the 
 filtered image.
3. Press `Backspace` key and clear the input.

Bug: Error appears after the input has been cleared. 

![image](https://user-images.githubusercontent.com/3728712/64848742-94799300-d61a-11e9-908b-62da96368e87.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/lib-admin-ui #1129](https://github.com/enonic/lib-admin-ui/issues/1129) via [**ZenHub**](https://www.zenhub.com/)
