### ISSUE TITLE
Incorrect default action in the Publish button menu after a site has been published

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-contentstudio#991]
Case 1:
1. Maximize the browser page. Select SuperHero, open Publish Wizard.
2. Click on  `Include child items`.
3. Click on remove icons and exclude 3-4 items, then click on `Publish Now` button

**Issue** the site is published , but default action is "Publish..." and it is disabled.

![image](https://user-images.githubusercontent.com/3728712/65227323-195c2500-dad1-11e9-86c6-fc3068b94dfd.png)

Expected: "Publish Tree" action should be displayed

Case 2: 
Unpublish Features: 

![image](https://user-images.githubusercontent.com/3728712/66112556-c6579700-e5d3-11e9-9ad8-63f4e6469282.png)

`UNPUBLISH` default action is expected

**Comment by ashklianko** [comment]
Unable to reproduce locally
