### ISSUE TITLE
Document implementation of custom widgets

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-contentstudio#993]
[This page](https://developer.enonic.com/docs/content-studio/master/widgets) describes internal widgets, but we need description on how to create custom widgets like [here](https://xp.readthedocs.io/en/stable/developer/admin/widgets/index.html). I suggest splitting "Widgets" menu item in two subitems - "Internal" and "Custom".

**Comment by poi33** [comment]
https://github.com/enonic/doc-xp/pull/115 
Pull request add widget documentation
